unpackaged/objects/Account_Plan__c.object
<CustomObject>
  <description>Account planning is the process of mapping out important details about your customer, including information about their decision-making process, the companies you're competing with to close them, and the overall strategy to win them over, retain and grow them.

An Account plan is yearly-based as it's typically something you create at the beginning of the year and you keep track of your progress throughout the months.

This account plan is based on the "OGSM" strategic planning methodology: an OGSM is a written and easily communicated statement of an organization’s Objective, Goals, Strategies and Measures. OGSM brings alignment, transparency of priorities and metrics that define success.</description>
  <fields>
    <fullName>BusinessUnits__c</fullName>
    <description>Select the business units that apply to this account in order to mass generate financial records per Business Unit</description>
    <inlineHelpText>Select the business units that apply to this account in order to mass generate financial records per Business Unit</inlineHelpText>
    <label>Business Unit(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Imaging</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Lab (Prosthetics)</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(Today()))</defaultValue>
    <label>Calendar Year</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>2019</fullName>
        </value>
        <value>
          <fullName>2020</fullName>
        </value>
        <value>
          <fullName>2021</fullName>
        </value>
        <value>
          <fullName>2022</fullName>
        </value>
        <value>
          <fullName>2023</fullName>
        </value>
        <value>
          <fullName>2024</fullName>
        </value>
        <value>
          <fullName>2025</fullName>
        </value>
        <value>
          <fullName>TEXT(Year(22 November 2021))</fullName>
          <isActive>false</isActive>
          <label>TEXT(Year(22 November 2021))</label>
        </value>
        <value>
          <fullName>Year(22 November 2021)</fullName>
          <isActive>false</isActive>
          <label>Year(22 November 2021)</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Account Plan</label>
  <nameField>
    <label>Account Plan #</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Account Plans</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/AccountPlanTriggerHandler.cls
/**
 * @description       : AccountPlan2__c trigger handler
 * @author            : kdoruibin@salesforce.com
 * @group             : 
 * @last modified on  : 11-12-2021
 * @last modified by  : naoussar@salesforce.com
**/
public with sharing class AccountPlanTriggerHandler extends TriggerHandler {
	private List<Account_Plan__c> oldAccountPlanList, newAccountPlanList;
    private Map<Id, Account_Plan__c> oldAccountPlanMap, newAccountPlanMap;

    public AccountPlanTriggerHandler() {
        oldAccountPlanList = (List<Account_Plan__c>) Trigger.old;
        newAccountPlanList = (List<Account_Plan__c>) Trigger.new;
        oldAccountPlanMap = (Map<Id, Account_Plan__c>) Trigger.oldMap;
        newAccountPlanMap = (Map<Id, Account_Plan__c>) Trigger.newMap;
    }

    protected override void beforeInsert() {
        AccountPlanTriggerHelper.setAccountPlanName(newAccountPlanList);
        AccountPlanTriggerHelper.setOffices(newAccountPlanList);
        AccountPlanTriggerHelper.checkUniquePerYear(newAccountPlanList);
    }
    
    protected override void afterUpdate() {
        List<Account_Plan__c> updatedAccountPlan = new List<Account_Plan__c>();
        for( Id accountPlanId : newAccountPlanMap.keySet() ){
  			if( oldAccountPlanMap.get(accountPlanId).BusinessUnits__c != newAccountPlanMap.get(accountPlanId).BusinessUnits__c){
     	    	updatedAccountPlan.add(newAccountPlanMap.get(accountPlanId));
    		}
        }
        AccountPlanTriggerHelper.createAccountPlanEstimates(updatedAccountPlan);
		
    }
    
    protected override void beforeUpdate() {
        List<Account_Plan__c> updatedAccountPlan = new List<Account_Plan__c>();
        for( Id accountPlanId : newAccountPlanMap.keySet() ){
  			if( oldAccountPlanMap.get(accountPlanId).Year__c != newAccountPlanMap.get(accountPlanId).Year__c){
     	    	updatedAccountPlan.add(newAccountPlanMap.get(accountPlanId));
    		}
        }
        AccountPlanTriggerHelper.checkUniquePerYear(updatedAccountPlan);
        AccountPlanTriggerHelper.setAccountPlanName(updatedAccountPlan);
		
    }


}