unpackaged/objects/Account_Plan__c.object
<CustomObject>
  <description>Account planning is the process of mapping out important details about your customer, including information about their decision-making process, the companies you're competing with to close them, and the overall strategy to win them over, retain and grow them.

An Account plan is yearly-based as it's typically something you create at the beginning of the year and you keep track of your progress throughout the months.

This account plan is based on the "OGSM" strategic planning methodology: an OGSM is a written and easily communicated statement of an organization’s Objective, Goals, Strategies and Measures. OGSM brings alignment, transparency of priorities and metrics that define success.</description>
  <fields>
    <fullName>AccountPlanOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_Plans</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(Today()))</defaultValue>
    <label>Calendar Year</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>2019</fullName>
        </value>
        <value>
          <fullName>2020</fullName>
        </value>
        <value>
          <fullName>2021</fullName>
        </value>
        <value>
          <fullName>2022</fullName>
        </value>
        <value>
          <fullName>2023</fullName>
        </value>
        <value>
          <fullName>2024</fullName>
        </value>
        <value>
          <fullName>2025</fullName>
        </value>
        <value>
          <fullName>TEXT(Year(22 November 2021))</fullName>
          <isActive>false</isActive>
          <label>TEXT(Year(22 November 2021))</label>
        </value>
        <value>
          <fullName>Year(22 November 2021)</fullName>
          <isActive>false</isActive>
          <label>Year(22 November 2021)</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Account Plan</label>
  <nameField>
    <label>Account Plan #</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Account Plans</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Objective__c.object
<CustomObject>
  <description>This account plan is based on the "OGSM" strategic planning methodology: an OGSM is a written and easily communicated statement of an organization’s Objective, Goals, Strategies and Measures. OGSM brings alignment, transparency of priorities and metrics that define success.</description>
  <fields>
    <fullName>AccountPlan__c</fullName>
    <inlineHelpText>Account planning is the process of mapping out important details about your customer, including information about their decision-making process, the companies you're competing with to close them, and the overall strategy to win them over, retain and grow them.</inlineHelpText>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Account Plan Objectives</relationshipLabel>
    <relationshipName>Account_Plan_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Initiatives__c</fullName>
    <inlineHelpText>"What are the choices that we have ?"
Strategies are words that provide explanations and descriptions of specific choices that focus an organization’s plans toward accomplishing the desired Objective and Goals</inlineHelpText>
    <label>Strategies &amp; Initiatives</label>
    <length>300</length>
    <type>LongTextArea</type>
  </fields>
  <fields>
    <fullName>Objective__c</fullName>
    <inlineHelpText>"What are we trying to achieve?"
 The Objective should define the playing field and the rules for winning. An Objective is a constant and meaningful reminder to the organization about what success looks like in the future. An effective Objective statement is not generic; it is a customized, business-specific view of where the business is headed.</inlineHelpText>
    <label>Objective</label>
    <length>300</length>
    <type>LongTextArea</type>
  </fields>
  <label>Account Plan Objective</label>
  <nameField>
    <displayFormat>OB-{000}</displayFormat>
    <label>Objective #</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Account Plan Objectives</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Test_ObjectivesController_OGSM.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Nihad Aoussar (Salesforce) 20211020
Description:    test class for the ObjectivesController_OGSM class
History:        
20211025        create fetchObjectives, updateObjectives, deleteObjective
----------------------------------------------------------------------------------------*/
@isTest
public with sharing class Test_ObjectivesController_OGSM {
    @testSetup
    public static void setup() {
        User user = TestDataFactory.createUsers(1, '#System: System Administrator')[0]; 
        System.runas(user) {
            Account currentAccount = TestDataFactory.createAccounts(1, 'CIM_Account', user.Id)[0];
            
    		Account_Plan__c accountPlan = new Account_Plan__c (AccountPlanOwner__c = user.Id ,
                                                       Year__c  = '2019',
                                                       Account__c = currentAccount.Id);
    		insert accountPlan;
        }
    }
    @isTest
    public static void fetchObjectivesByAccountPlanIdTest() {
    User testUser = [SELECT Id FROM User WHERE Alias = 'test1'][0];
    System.runas(testUser) {
        Account_Plan__c accountPlan = [SELECT Id FROM Account_Plan__c WHERE AccountPlanOwner__c=:testUser.Id];
        Objective__c objective = TestDataFactory.createObjective(1,accountPlan.Id)[0];
        Test.startTest();
        	List<Objective__c> objectives = ObjectivesController_OGSM.fetchObjectives(accountPlan.Id);
        Test.stopTest();
        System.assertEquals(objectives.size(), 1, 'one objective exist for this account plan');
    
    }    
    }

    @isTest
    public static void updateObjectivesTest() {
    User testUser = [SELECT Id FROM User WHERE Alias = 'test1'][0];
    System.runas(testUser) {
        Account_Plan__c accountPlan = [SELECT Id FROM Account_Plan__c WHERE AccountPlanOwner__c=:testUser.Id];
		List<Objective__c> objective = TestDataFactory.createObjective(1,accountPlan.Id);
  		objective[0].Initiatives__c = 'initiative updated';
        Test.startTest();
            ObjectivesController_OGSM.updateObjectives(objective);
            List<Objective__c> objectives = [ SELECT id, Name , Initiatives__c from Objective__c where AccountPlan__c=:accountPlan.Id]; 
        Test.stopTest();
    	System.assertEquals(objectives[0].Initiatives__c,'initiative updated', 'initiative value has been updated');
    }
    }

    @isTest
    public static void updateEmptyObjectivesTest() {
    User testUser = [SELECT Id FROM User WHERE Alias = 'test1'][0];
    System.runas(testUser) {
        Test.startTest();
        try{
            ObjectivesController_OGSM.updateObjectives(null);
            } 
        catch (AuraHandledException ex) {
            System.assertEquals('Script-thrown exception', ex.getMessage());
        } 
        Test.stopTest();
    }
    }

    @isTest
    public static void deleteObjectivesTest() {
    User testUser = [SELECT Id FROM User WHERE Alias = 'test1'][0];
    System.runas(testUser) {
        Account_Plan__c accountPlan = [SELECT Id FROM Account_Plan__c WHERE AccountPlanOwner__c=:testUser.Id];
		List<Objective__c> objective = TestDataFactory.createObjective(2,accountPlan.Id);
  		
        Test.startTest();
            ObjectivesController_OGSM.deleteObjective(objective[0].Id);
            List<Objective__c> objectives = [ SELECT id, Name FROM Objective__c WHERE AccountPlan__c=:accountPlan.Id]; 
        Test.stopTest();
    System.assertEquals(objectives.size(), 1, 'only one objective exist for this account plan After deletion');
    }
    }

    @isTest
    public static void deleteEmptyObjectiveTest() {
    User testUser = [SELECT Id FROM User WHERE Alias = 'test1'][0];
    System.runas(testUser) {
    	Test.startTest();
        try{
            ObjectivesController_OGSM.deleteObjective(Id.valueOf('a6Y8Y000000odO4UAI'));
        } catch (AuraHandledException ex) {
            System.assertEquals('Script-thrown exception', ex.getMessage());
        } 
        Test.stopTest();
    }
    }
}