unpackaged/objects/Account_Plan__c.object
<CustomObject>
  <description>Account planning is the process of mapping out important details about your customer, including information about their decision-making process, the companies you're competing with to close them, and the overall strategy to win them over, retain and grow them.

An Account plan is yearly-based as it's typically something you create at the beginning of the year and you keep track of your progress throughout the months.

This account plan is based on the "OGSM" strategic planning methodology: an OGSM is a written and easily communicated statement of an organization’s Objective, Goals, Strategies and Measures. OGSM brings alignment, transparency of priorities and metrics that define success.</description>
  <fields>
    <fullName>AccountPlanOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_Plans</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>BusinessUnits__c</fullName>
    <description>Select the business units that apply to this account in order to mass generate financial records per Business Unit</description>
    <inlineHelpText>Select the business units that apply to this account in order to mass generate financial records per Business Unit</inlineHelpText>
    <label>Business Unit(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Imaging</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Lab (Prosthetics)</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Offices__c</fullName>
    <inlineHelpText>Automatically calculated upon creation of the Account Plan (Based on the # of Accounts related to this account in the hierarchy)</inlineHelpText>
    <label>Offices</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(Today()))</defaultValue>
    <label>Calendar Year</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>2019</fullName>
        </value>
        <value>
          <fullName>2020</fullName>
        </value>
        <value>
          <fullName>2021</fullName>
        </value>
        <value>
          <fullName>2022</fullName>
        </value>
        <value>
          <fullName>2023</fullName>
        </value>
        <value>
          <fullName>2024</fullName>
        </value>
        <value>
          <fullName>2025</fullName>
        </value>
        <value>
          <fullName>TEXT(Year(22 November 2021))</fullName>
          <isActive>false</isActive>
          <label>TEXT(Year(22 November 2021))</label>
        </value>
        <value>
          <fullName>Year(22 November 2021)</fullName>
          <isActive>false</isActive>
          <label>Year(22 November 2021)</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Account Plan</label>
  <nameField>
    <label>Account Plan #</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Account Plans</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/AccountPlanEstimates__c.object
<CustomObject>
  <description>Account Plan Financials Numbers (Targets, Estimates, Budget, ....)</description>
  <fields>
    <fullName>AccountPlan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipName>Account_Plan_Target_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Imaging</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Lab (Prosthetics)</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Year__c</fullName>
    <formula>TEXT(AccountPlan__r.Year__c)</formula>
    <label>Calendar Year</label>
    <type>Text</type>
  </fields>
  <label>Sales Quota Line</label>
  <nameField>
    <displayFormat>SQL{0000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Sales Quota Lines</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Test_AccountPlanTriggerHelper.cls
/*----------------------------------------------------------------------------------------
Author:         Nihad Aoussar (Salesforce) 20211020
Description:    test class for the AccountPlanTriggerHelper class
History:        
20211111        create setOfficesTest, setAccountPlanNameTest, checkUniquePerYearTest,createAccountPlanEstimatesTest
----------------------------------------------------------------------------------------*/
@isTest
public class Test_AccountPlanTriggerHelper {
    
    @testSetup
    public static void setup() {
        User user = TestDataFactory.createUsers(1, '#System: System Administrator')[0]; 
        System.runas(user) {
            Account currentAccount = TestDataFactory.createAccounts(1, 'CIM_Account', user.Id)[0];
            
    		Account_Plan__c accountPlan = new Account_Plan__c (AccountPlanOwner__c = user.Id ,
                                                       Year__c  = '2019',
                                                       Account__c = currentAccount.Id);
    		insert accountPlan;
            Account_Plan__c accountPlan2 = new Account_Plan__c (AccountPlanOwner__c = user.Id ,
                                                       Year__c  = '2019',
                                                       Account__c = currentAccount.Id,
                                                       BusinessUnits__c = 'Endodontics');
    		insert accountPlan2;
            
            AccountPlanEstimates__c newAccountEstimates = new AccountPlanEstimates__c ( AccountPlan__c = accountPlan2.Id , 
                                                                                         BusinessUnit__c  = 'Imaging');
            insert newAccountEstimates;
        }
    }
    
    @isTest
    public static void setOfficesTest(){
    User testUser = [SELECT Id FROM User WHERE Alias = 'test1'][0];
    System.runas(testUser) {
        List<Account_Plan__c> accountPlans = [SELECT Id,Account__c,Offices__c FROM Account_Plan__c WHERE AccountPlanOwner__c=:testUser.Id];
        Test.startTest();
        	AccountPlanTriggerHelper.setOffices(accountPlans);
        Test.stopTest();
        
        System.assertEquals(0, accountPlans[0].Offices__c, 'Account has no offices');
    
    } 
    }
   
    
    @isTest
    public static void setAccountPlanNameTest(){
    User testUser = [SELECT Id FROM User WHERE Alias = 'test1'][0];
    System.runas(testUser) {
        List<Account_Plan__c> accountPlans = [SELECT Id,Year__c,Account__c,Name FROM Account_Plan__c WHERE AccountPlanOwner__c=:testUser.Id];
        Test.startTest();
        	AccountPlanTriggerHelper.setAccountPlanName(accountPlans);
        Test.stopTest();
       
        System.assertEquals('2019 Plan - TestAccount0', accountPlans[0].Name, 'Account name has changed');
    
    } 
    }
    
    
    @isTest
    public static void checkUniquePerYearTest(){
    User testUser = [SELECT Id FROM User WHERE Alias = 'test1'][0];
    System.runas(testUser) {
        List<Account_Plan__c> accountPlans = [SELECT Id,Year__c,Account__c,Name FROM Account_Plan__c WHERE AccountPlanOwner__c=:testUser.Id];
        Test.startTest();
        try{
        	AccountPlanTriggerHelper.checkUniquePerYear(accountPlans);
        }catch(Exception ex){
            Boolean expectedExceptionThrown =  ex.getMessage().contains('There can only be one Account Plan per year') ? true : false;

            System.assertEquals(expectedExceptionThrown, true);
        }
        Test.stopTest();
    }   
    }

    @isTest
    public static void createAccountPlanEstimatesTest(){
    User testUser = [SELECT Id FROM User WHERE Alias = 'test1'][0];
    System.runas(testUser) {
        List<Account_Plan__c> accountPlans = [SELECT Id,BusinessUnits__c FROM Account_Plan__c WHERE AccountPlanOwner__c=:testUser.Id];
        Test.startTest();
        	AccountPlanTriggerHelper.createAccountPlanEstimates(accountPlans);
        Test.stopTest();
        set<Id> accountPlanIds = new set<Id>();
        for(Account_Plan__c accplan : accountPlans){
            accountPlanIds.add(accplan.Id);
        }
        
        List<AccountPlanEstimates__c> accEstimates = [ SELECT Id,AccountPlan__c 
                                                  FROM AccountPlanEstimates__c 
                                                  WHERE  AccountPlan__c IN: accountPlanIds];
        System.assertEquals(2, accEstimates.size(), 'Only one target line will be added');
    
    } 
    }
}