unpackaged/objects/Account_Create_Change_Request__c.object
<CustomObject>
  <fields>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <type>TextArea</type>
  </fields>
  <fields>
    <fullName>Existing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Create_Change_Requests</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <controllingField>Request__c</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Account Info Change</fullName>
        </value>
        <value>
          <fullName>Account Linking CIM360</fullName>
        </value>
        <value>
          <fullName>All Stop</fullName>
        </value>
        <value>
          <fullName>Create New Account</fullName>
        </value>
        <value>
          <fullName>Parent/Child Grouping</fullName>
        </value>
        <value>
          <fullName>Pending Order</fullName>
        </value>
        <value>
          <fullName>Reopen Account</fullName>
        </value>
        <value>
          <fullName>Sales Issue</fullName>
        </value>
        <value>
          <fullName>Account Linking</fullName>
          <isActive>false</isActive>
          <label>Account Linking</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Account Change Request</fullName>
        </value>
        <value>
          <fullName>Account Creation Request</fullName>
          <default>true</default>
          <label>Account Creation Request</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Created</fullName>
          <default>true</default>
          <label>Created</label>
        </value>
        <value>
          <fullName>Submitted</fullName>
        </value>
        <value>
          <fullName>Processing</fullName>
        </value>
        <value>
          <fullName>Completed</fullName>
        </value>
        <value>
          <fullName>Rejected</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Account Request</label>
  <nameField>
    <displayFormat>ACCR - {000000}</displayFormat>
    <label>Account Create/Change Request Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Account Requests</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/AccountChangeRequestTest.cls
/*Version History
 * Date: 20-Nov-2018
 * Class Name: AccountChangeRequestTest
 * Created By:Sanjay Pandey/Amit Pandey
 * Related to: TFUS-000000149 : "Account Change Request" button
 * Related Class: AccountChangeRequest.cls
 */
@isTest
private class AccountChangeRequestTest {
    @isTest
    static void getAccountDetailsMethod() {
        Account a = new Account(name = 'Testdta', Phone = '9866763002', billingstate = 'California', billingcity = 'anah', billingcountry = 'United States', billingpostalcode = '92801', billingstreet = 'ls');
        insert a;

        AccountChangeRequest.getAccountDetails(a.id);
        System.assertNotEquals(Null, a);

        Account_Create_Change_Request__c ac = new Account_Create_Change_Request__c(
			Comments__c = 'Test',
			Status__c = 'Created', 
			CurrencyIsoCode = 'USD', 
			Existing_Account__c = a.Id,
			Request__c = 'Account Change Request',
			Request_Type__c = 'Account Info Change');
        insert ac;
        try{
            AccountChangeRequest.createRecord(ac);
        }
        catch(Exception e){
            System.debug('Script-thrown exception : '+e.getMessage());
        }
        System.assertNotEquals(Null, ac);
    }
     @isTest
    static void getselectOptionsTest() {
        AccountChangeRequest.getselectOptions();
    }
}