unpackaged/objects/AccountContactRelation.object
<CustomObject>
  <fields>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Consumables</fullName>
          <isActive>false</isActive>
          <label>Consumables</label>
        </value>
        <value>
          <fullName>Dealer Sales Rep (CEREC)</fullName>
        </value>
        <value>
          <fullName>Digital</fullName>
          <isActive>false</isActive>
          <label>Digital</label>
        </value>
        <value>
          <fullName>Digital Group</fullName>
          <isActive>false</isActive>
          <label>Digital Group</label>
        </value>
        <value>
          <fullName>Endodontics</fullName>
          <isActive>false</isActive>
          <label>Endodontics</label>
        </value>
        <value>
          <fullName>Equipment</fullName>
          <isActive>false</isActive>
          <label>Equipment</label>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
          <isActive>false</isActive>
          <label>Equipment &amp; Imaging</label>
        </value>
        <value>
          <fullName>Implants</fullName>
          <isActive>false</isActive>
          <label>Implants</label>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
          <isActive>false</isActive>
          <label>Orthodontics</label>
        </value>
        <value>
          <fullName>Partner Sales Rep Imaging</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
          <isActive>false</isActive>
          <label>Prosthetics</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
</CustomObject>

unpackaged/objects/Campaign.object
<CustomObject>
  <fields>
    <fullName>CampaignMemberAccountIdList__c</fullName>
    <description>A comma-separated list of account IDs for all campaign members.</description>
    <inlineHelpText>A comma-separated list of account IDs for all campaign members.</inlineHelpText>
    <label>Campaign Member Account ID List</label>
    <length>65535</length>
    <type>LongTextArea</type>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Organizing Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>ALL</fullName>
        </value>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>BEX</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Distributor Markets</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ: DE</fullName>
        </value>
        <value>
          <fullName>HQ: NL</fullName>
        </value>
        <value>
          <fullName>HQ: SE</fullName>
        </value>
        <value>
          <fullName>INDIA</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Korea</fullName>
        </value>
        <value>
          <fullName>Luxembourg</fullName>
        </value>
        <value>
          <fullName>Malaysia</fullName>
        </value>
        <value>
          <fullName>New Zealand</fullName>
        </value>
        <value>
          <fullName>Norway</fullName>
        </value>
        <value>
          <fullName>Philippines</fullName>
        </value>
        <value>
          <fullName>Poland</fullName>
        </value>
        <value>
          <fullName>Portugal</fullName>
        </value>
        <value>
          <fullName>Russia</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>SBU_Focus__c</fullName>
    <description>Used to track which SBU the Campaigns target for promotion/training.</description>
    <inlineHelpText>Pick the SBU(s) that this Campaign targets for promotion/training.</inlineHelpText>
    <label>SBU</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
        <value>
          <fullName>Imaging Systems</fullName>
        </value>
        <value>
          <fullName>Instruments</fullName>
        </value>
        <value>
          <fullName>US Consumables</fullName>
        </value>
        <value>
          <fullName>Maillefer</fullName>
        </value>
        <value>
          <fullName>Midwest</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN.</description>
    <fullName>DI_Campaign</fullName>
    <label>Course/Event/Exhibition</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>First Draft of DNA Campaign setup</description>
    <fullName>DNA_Campaign</fullName>
    <label>DNA Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Used in Lightning for the Eloqua integration</description>
    <fullName>Digital_Marketing_Campaign</fullName>
    <label>Digital Marketing Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CampaignMember.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</description>
    <inlineHelpText>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members (Account)</relationshipLabel>
    <relationshipName>Campaign_Members2</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>International_Speaker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mirrors the International Speaker field on the Contact. Referenced in roll-up summary field to the Campaign, that is in turn used for sharing to international speaker group</description>
    <label>International Speaker</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Specialty__c</fullName>
    <formula>IF(ISBLANK(ContactId),TEXT(Lead.Specialty__c),TEXT(Contact.Specialty__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Specialty</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Distributor</fullName>
        </value>
        <value>
          <fullName>Interpreter</fullName>
        </value>
        <value>
          <fullName>Moderator</fullName>
        </value>
        <value>
          <fullName>Other</fullName>
        </value>
        <value>
          <fullName>Participant</fullName>
          <default>true</default>
          <label>Participant</label>
        </value>
        <value>
          <fullName>Sales Staff</fullName>
        </value>
        <value>
          <fullName>Speaker</fullName>
        </value>
        <value>
          <fullName>Speaker &amp; Moderator</fullName>
        </value>
        <value>
          <fullName>Spouse</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>of_Guests_including_participant__c</fullName>
    <label>Room Type</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Single Room</fullName>
        </value>
        <value>
          <fullName>Double Room</fullName>
        </value>
        <value>
          <fullName>Suite</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Albania</fullName>
        </value>
        <value>
          <fullName>Algeria</fullName>
        </value>
        <value>
          <fullName>Argentina</fullName>
        </value>
        <value>
          <fullName>Armenia</fullName>
        </value>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Azerbaijan</fullName>
        </value>
        <value>
          <fullName>Bahrain</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Bosnia and Herzegovina</fullName>
        </value>
        <value>
          <fullName>Botswana</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Bulgaria</fullName>
        </value>
        <value>
          <fullName>Cambodia</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Chile</fullName>
        </value>
        <value>
          <fullName>China</fullName>
        </value>
        <value>
          <fullName>Colombia</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Ecuador</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>InsertEmailMarketingConsentCollected__c</fullName>
    <inlineHelpText>Please fill the information if the Email Marketing Consent was collected or not</inlineHelpText>
    <label>Insert Email Marketing Consent Collected</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Yes</fullName>
        </value>
        <value>
          <fullName>No</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>International_Speaker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Only some HQ Users should have edit access</description>
    <label>International Speaker</label>
    <type>Checkbox</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>In use for all countries</description>
    <fullName>ContactGlobal</fullName>
    <label>Contact Global</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <fullName>Contact_D</fullName>
    <label>Contact</label>
  </recordTypes>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/Test_CampaignMemberTrigger.cls
/*------------------------------------------------------------
Author: 		Ahmed LOUDRASSI (Salesforce) 2019-10-22
Description:   	Test Class for all CampaignMemberHelper methods.
History
20191022   Ahmed LOUDRASSI   Migrated CampMgmtCampaignMemberTrigger and CampMgmtCampaignMemberTrigger2 triggers. (#)
20191022   Ahmed LOUDRASSI   Migrated CampaignMember Workflows. (#)
------------------------------------------------------------*/
@isTest(seeAllData=false)
public class Test_CampaignMemberTrigger {

    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
    }

    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();
        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }
    
    @isTest
    public static void testUpdateCampaignMemberAccount() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> accountsList = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
        List<Contact> contactList = TestDataFactory.returnContacts(1, 'Contact_D', testUser.Id);
        contactList.get(0).AccountId = accountsList.get(0).Id;
        insert contactList;
        List<Campaign> campaignList = TestDataFactory.createCampaigns(1, 'DNA_Campaign', testUser.Id);
        List<CampaignMember> campaignMembertList = TestDataFactory.returnCampaignMembers(1);

        campaignMembertList.get(0).ContactId = contactList.get(0).Id;
        campaignMembertList.get(0).CampaignId = campaignList.get(0).Id;

        Test.startTest();
        insert campaignMembertList;
        Test.stopTest();
        System.assertEquals(accountsList.get(0).Id, [SELECT ID, Account__c FROM  CampaignMember LIMIT 1].Account__c);
    }

    @isTest
    public static void testUpdateCampaignAndAccountIdCMList() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> accountsList = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);

        List<Contact> contactList = TestDataFactory.returnContacts(1, 'Contact_D', testUser.Id);
        contactList.get(0).AccountId = accountsList.get(0).Id;
        insert contactList;

        accountsList.get(0).ContactCampaignIdList__c = contactList.get(0).Id;
        update accountsList;

        List<Campaign> campaignList = TestDataFactory.returnCampaigns(1, 'DNA_Campaign', testUser.Id);
        campaignList.get(0).CampaignMemberAccountIdList__c = accountsList.get(0).Id;
		insert campaignList;

        List<CampaignMember> campaignMembertList = TestDataFactory.returnCampaignMembers(1);
        campaignMembertList.get(0).ContactId = contactList.get(0).Id;
        campaignMembertList.get(0).CampaignId = campaignList.get(0).Id;
		campaignMembertList.get(0).Status = 'Confirmed';
        campaignMembertList.get(0).Type__c = 'Participant';

        Test.startTest();
        insert campaignMembertList;
        Test.stopTest();
    }

    @isTest
    public static void testUpdateCampaignMembersInfo() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> accountsList = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
        List<Contact> contactList = TestDataFactory.returnContacts(4, 'Contact_D', testUser.Id);
        contactList.get(0).AccountId = accountsList.get(0).Id;
        insert contactList;
        List<Campaign> campaignList = TestDataFactory.returnCampaigns(4, 'DI_Campaign', testUser.Id);
        for(Campaign cm : campaignList) {
            cm.SBU_Focus__c = 'Implants';
        }
        insert campaignList;
        List<CampaignMember> campaignMembertList = TestDataFactory.returnCampaignMembers(4);

        // WF-CAMM-01 : 'Set Account Strategy and W/L status'
		campaignMembertList.get(0).ContactId = contactList.get(0).Id;
        campaignMembertList.get(0).CampaignId = campaignList.get(0).Id;

        // WF-CAMM-02 : 'Set DI Campaign Member Info Based On Campaign'
        campaignMembertList.get(1).ContactId = contactList.get(1).Id;
        campaignMembertList.get(1).CampaignId = campaignList.get(1).Id;
        campaignMembertList.get(1).Type__c = 'Participant';

        campaignMembertList.get(2).ContactId = contactList.get(2).Id;
        campaignMembertList.get(2).CampaignId = campaignList.get(2).Id;
        campaignMembertList.get(2).Type__c = 'Participant';
        campaignMembertList.get(2).of_Guests_including_participant__c = 'Single Room';

        campaignMembertList.get(3).ContactId = contactList.get(3).Id;
        campaignMembertList.get(3).CampaignId = campaignList.get(3).Id;
        campaignMembertList.get(3).Type__c = 'Participant';
        campaignMembertList.get(3).of_Guests_including_participant__c = 'Double Room';

        Test.startTest();
        insert campaignMembertList;
        Test.stopTest();
    }

    @isTest
    public static void testetInternationalSpeaker() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> accountsList = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
        List<Contact> contactList = TestDataFactory.returnContacts(1, 'Contact_D', testUser.Id);
        contactList.get(0).AccountId = accountsList.get(0).Id;
        contactList.get(0).International_Speaker__c = true;
        insert contactList;
        List<Campaign> campaignList = TestDataFactory.createCampaigns(1, 'DNA_Campaign', testUser.Id);
        List<CampaignMember> campaignMembertList = TestDataFactory.returnCampaignMembers(1);

        campaignMembertList.get(0).ContactId = contactList.get(0).Id;
        campaignMembertList.get(0).CampaignId = campaignList.get(0).Id;

        Test.startTest();
        insert campaignMembertList;
        Test.stopTest();

        System.assertEquals(true, [SELECT Id, International_Speaker__c FROM CampaignMember LIMIT 1].International_Speaker__c);
    }
    
    @isTest
    public static void testCreateOpportunities(){
               
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> accountsList = TestDataFactory.createAccounts(2, 'CIM_Account', testUser.Id);
        accountsList.get(1).OneAccount_Type__c = 'Distributor';
        accountsList.get(0).Country__c = 'DE';
        update accountsList;
        
        List<Contact> contactList = TestDataFactory.returnContacts(2, 'ContactGlobal', testUser.Id);
        contactList.get(0).AccountId = accountsList.get(0).Id;
        contactList.get(0).Email = 'test1.test@dentsplysirona.com.invalid';
        contactList.get(0).InsertEmailMarketingConsentCollected__c = 'No';
        contactList.get(1).AccountId = accountsList.get(1).Id;
        contactList.get(1).Email = 'test2.test@dentsplysirona.com.invalid';
        contactList.get(1).InsertEmailMarketingConsentCollected__c = 'No';
        insert contactList;
        
        List<AccountContactRelation> relations = [SELECT AccountId, ContactId, Specialty__c FROM AccountContactRelation WHERE AccountId =: accountsList.get(1).Id];
        
        for(AccountContactRelation rel : relations){
            rel.Specialty__c = 'Dealer Sales Rep (CEREC)';
        }
        update relations;
        
        List<Campaign> campaignList = TestDataFactory.returnCampaigns(1, 'Digital_Marketing_Campaign', testUser.Id);
        campaignList.get(0).Brands__c = 'Sinius';
        campaignList.get(0).Convert_To__c = 'Opportunity';
        campaignList.get(0).Include_In_Dealer_Community__c = 'Yes';
        insert campaignList;
        List<CampaignMember> campaignMembertList = TestDataFactory.returnCampaignMembers(1);

        campaignMembertList.get(0).ContactId = contactList.get(0).Id;
        campaignMembertList.get(0).CampaignId = campaignList.get(0).Id;
        campaignMembertList.get(0).Dealer__c = accountsList.get(1).Id;
        campaignMembertList.get(0).Status = 'Registered';
        
		Test.startTest();
        insert campaignMembertList;
        campaignMembertList.get(0).Status = 'Responded';
        update campaignMembertList;
        	
        Test.stopTest();        
        
    }
    
    @isTest
    public static void testCreateSalesLead(){
               
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> accountsList = TestDataFactory.createAccounts(2, 'CIM_Account', testUser.Id);
        accountsList.get(1).OneAccount_Type__c = 'Distributor';
        accountsList.get(0).Country__c = 'US';
        update accountsList;
        
        List<Contact> contactList = TestDataFactory.returnContacts(2, 'ContactGlobal', testUser.Id);
        contactList.get(0).AccountId = accountsList.get(0).Id;
        contactList.get(0).Email = 'test1.test@dentsplysirona.com.invalid';
        contactList.get(0).InsertEmailMarketingConsentCollected__c = 'No';
        contactList.get(1).AccountId = accountsList.get(1).Id;
        contactList.get(1).Email = 'test2.test@dentsplysirona.com.invalid';
        contactList.get(1).InsertEmailMarketingConsentCollected__c = 'No';
        insert contactList;
        
        List<AccountContactRelation> relations = [SELECT AccountId, ContactId, Specialty__c FROM AccountContactRelation WHERE AccountId =: accountsList.get(1).Id];
        
        for(AccountContactRelation rel : relations){
            rel.Specialty__c = 'Dealer Sales Rep (CEREC)';
        }
        update relations;
        
        List<Campaign> campaignList = TestDataFactory.returnCampaigns(1, 'Digital_Marketing_Campaign', testUser.Id);
        campaignList.get(0).Brands__c = 'Sinius';
        campaignList.get(0).Convert_To__c = 'Sales Lead';
        insert campaignList;
        List<CampaignMember> campaignMembertList = TestDataFactory.returnCampaignMembers(1);

        campaignMembertList.get(0).ContactId = contactList.get(0).Id;
        campaignMembertList.get(0).CampaignId = campaignList.get(0).Id;
        campaignMembertList.get(0).Dealer__c = accountsList.get(1).Id;
        campaignMembertList.get(0).Status = 'Registered';
        
		Test.startTest();
        insert campaignMembertList;
        campaignMembertList.get(0).Status = 'Responded';
        update campaignMembertList;
        	
        Test.stopTest();        
        
    }
}