unpackaged/objects/Article__c.object
<CustomObject>
  <description>Used to add multiple articles to a Case</description>
  <label>Article Number</label>
  <nameField>
    <displayFormat>A-{000000}</displayFormat>
    <label>Article Id</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Article Numbers</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Status__c</fullName>
    <description>TFUS-000002053</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Inactive</fullName>
        </value>
        <value>
          <fullName>GDPR – Forget</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>In use for all countries</description>
    <fullName>ContactGlobal</fullName>
    <label>Contact Global</label>
  </recordTypes>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Contract.object
<CustomObject>
  <fields>
    <fullName>SourceRecord__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Record</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>$Source.AccountId</field>
        <operation>equals</operation>
        <valueField>Source_Record__c.CIM_Account__r.Id</valueField>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Source_Record__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
    <fullName>Contract</fullName>
    <label>Contract</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Field_Sales_Project_Members__c.object
<CustomObject>
  <description>Used to track targets for sales for specified initiatives based on target lists, regional initiatives, or customer interactions.</description>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Field_Sales_Project_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>UserCountry__c</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>3D Imaging</fullName>
          <isActive>false</isActive>
          <label>3D Imaging</label>
        </value>
        <value>
          <fullName>ATLANTIS</fullName>
          <isActive>false</isActive>
          <label>ATLANTIS</label>
        </value>
        <value>
          <fullName>CEREC Equipment</fullName>
          <isActive>false</isActive>
          <label>CEREC Equipment</label>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Consumables</fullName>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Digital Solutions</fullName>
          <isActive>false</isActive>
          <label>Digital Solutions</label>
        </value>
        <value>
          <fullName>Endentulous</fullName>
          <isActive>false</isActive>
          <label>Endentulous</label>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Extra Oral Imaging</fullName>
          <isActive>false</isActive>
          <label>Extra Oral Imaging</label>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>InLab</fullName>
          <isActive>false</isActive>
          <label>InLab</label>
        </value>
        <value>
          <fullName>Intra Oral Imaging</fullName>
          <isActive>false</isActive>
          <label>Intra Oral Imaging</label>
        </value>
        <value>
          <fullName>Midwest Equipment</fullName>
          <isActive>false</isActive>
          <label>Midwest Equipment</label>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
          <isActive>false</isActive>
          <label>Preventive</label>
        </value>
        <value>
          <fullName>Procedures</fullName>
          <isActive>false</isActive>
          <label>Procedures</label>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Regenerative</fullName>
          <isActive>false</isActive>
          <label>Regenerative</label>
        </value>
        <value>
          <fullName>Restorative</fullName>
          <isActive>false</isActive>
          <label>Restorative</label>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
          <isActive>false</isActive>
          <label>Treatment Centers</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>New</fullName>
          <default>true</default>
          <label>New</label>
        </value>
        <value>
          <fullName>In progress</fullName>
        </value>
        <value>
          <fullName>Parked/OnHold</fullName>
          <label>Parked/On Hold</label>
        </value>
        <value>
          <fullName>Completed</fullName>
        </value>
        <value>
          <fullName>Cancelled</fullName>
        </value>
        <value>
          <fullName>To Call</fullName>
        </value>
        <value>
          <fullName>Answered - Call Back Later</fullName>
        </value>
        <value>
          <fullName>No Answer - Call Back Later</fullName>
        </value>
        <value>
          <fullName>Left Message</fullName>
        </value>
        <value>
          <fullName>Call Completed</fullName>
        </value>
        <value>
          <fullName>Expired</fullName>
        </value>
        <value>
          <fullName>Active</fullName>
          <isActive>false</isActive>
          <label>Active</label>
        </value>
        <value>
          <fullName>Declined</fullName>
          <isActive>false</isActive>
          <label>Declined</label>
        </value>
        <value>
          <fullName>Parked</fullName>
          <isActive>false</isActive>
          <label>Parked</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Sales Lead</label>
  <nameField>
    <displayFormat>Ld-{0000000}</displayFormat>
    <label>LD ID</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Sales Leads</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET Restorative - D</businessProcess>
    <description>Quick Account Plan that can be used by all the sbus (IT, MEA)</description>
    <fullName>Account_Plan</fullName>
    <label>Account Plan</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET</businessProcess>
    <fullName>GET</fullName>
    <label>X DO NOT USE 2t</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>SourceRecord__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#1674</description>
    <label>Source Record</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>$Source.AccountId</field>
        <operation>equals</operation>
        <valueField>Source_Record__c.CIM_Account__c</valueField>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Source_Record__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <fullName>Direct_global_order</fullName>
    <label>Direct global order</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <fullName>Free_Good_Order</fullName>
    <label>Free Good Order</label>
  </recordTypes>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Pricebook2.object
<CustomObject>
  <fields>
    <fullName>CompanyCode__c</fullName>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Contract_Discount_types__c</fullName>
    <label>Contract Discount types</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Contract_Discount_Type</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>Pricebook_Channel__c</fullName>
    <label>Pricebook Channel</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Direct</fullName>
        </value>
        <value>
          <fullName>Indirect</fullName>
        </value>
        <value>
          <fullName>Generic</fullName>
        </value>
        <value>
          <fullName>Free Good Order</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>ShowPricingfromMicroServiceOM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Pricing from Micro-Service (OM)</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>SourceId__c</fullName>
    <label>Source Id</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>1</fullName>
          <label>M3</label>
        </value>
        <value>
          <fullName>2</fullName>
          <label>AX</label>
        </value>
        <value>
          <fullName>7</fullName>
          <label>BPCS</label>
        </value>
        <value>
          <fullName>31</fullName>
          <label>SAP</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Product2.object
<CustomObject>
  <fields>
    <fullName>Article__c</fullName>
    <externalId>true</externalId>
    <label>Article (SKU)</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Company_Code__c</fullName>
    <description>The Company Code as written in the GDW</description>
    <inlineHelpText>The Company Code as written in the GDW</inlineHelpText>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>ERP_Source__c</fullName>
    <description>The ERP Source. 1= M3, 2=AX</description>
    <inlineHelpText>The ERP Source. 1= M3, 2=AX</inlineHelpText>
    <label>ERP Source</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>GlobalSKUMapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GlobalSKU Mapping</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Mapped LocalSKUs</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>PG1_Desc__c</fullName>
    <label>Product Group 1 Description</label>
    <length>100</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>PG2_Desc__c</fullName>
    <label>Product Group 2 Description</label>
    <length>100</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>PG3_Desc__c</fullName>
    <label>Product Group 3 Description</label>
    <length>100</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>PG4_Desc__c</fullName>
    <label>Product Group 4 Description</label>
    <length>100</length>
    <type>Text</type>
  </fields>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Source_Record__c.object
<CustomObject>
  <description>Includes Accounts from different sources mapped to one golden account. Fully integrated ( Read Only for all users)</description>
  <fields>
    <fullName>CIM_Account__c</fullName>
    <label>CIM Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Source Records</relationshipLabel>
    <relationshipName>Source_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>25</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Customer_Id__c</fullName>
    <label>Customer Id</label>
    <length>50</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Source_Id__c</fullName>
    <label>Source Id</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>63</fullName>
          <label>CRM Data, External CRM Data</label>
        </value>
        <value>
          <fullName>7</fullName>
          <label>BPCS</label>
        </value>
        <value>
          <fullName>1</fullName>
          <label>M3</label>
        </value>
        <value>
          <fullName>30</fullName>
          <label>Distributors</label>
        </value>
        <value>
          <fullName>62</fullName>
          <label>Ecommerce</label>
        </value>
        <value>
          <fullName>2</fullName>
          <label>AX</label>
        </value>
        <value>
          <fullName>31</fullName>
          <label>SAP</label>
        </value>
        <value>
          <fullName>60</fullName>
          <label>SFDC</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Inactive</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Source Record</label>
  <nameField>
    <label>Account Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Source Records</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Test_OrderManagement_CC.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Ahmed LOUDRASSI (Salesforce) 20191113
Description:    OrderManagement_CC Class
--------------------------------------------------------------------------------------------------------*/

@isTest(seeAllData=false)
public with sharing class Test_OrderManagement_CC {
    /*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        List<User> userList = TestDataFactory.createUsers(1, '#System: System Administrator');
        System.runas(userList.get(0)) {
            /*List<PermissionSet> permissions = [SELECT Id FROM PermissionSet 
            WHERE Name = 'Global_System_Use_Any_API'
            OR Name = 'New_Salesforce_Mobile_App'
            OR Name = 'Geopointe_Base_Permissions'
            OR Name = 'Global_Analytics_Viewer'
            OR Name = 'Global_Analytics_All_permissions'];
            List<PermissionSetAssignment> permisssionSetsAssign = new List<PermissionSetAssignment>();
            for(PermissionSet ps : permissions) {
            permisssionSetsAssign.add(new PermissionSetAssignment(AssigneeId = userList.get(0).id, PermissionSetId = ps.Id));
            }
            System.debug('ahmed ' +permisssionSetsAssign.size());
            //insert permisssionSetsAssign;*/
        }
        TestDataFactory.createBypassCustomSetting();
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
    }

    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();
        
        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }

    @isTest
    private static void testUIThemeDisplayed() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            System.assertEquals(true, OrderManagement_CC.uIThemeDisplayed().contains('Theme'));
        }
    }
    @isTest 
    private static void testGetPriceBooks() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            TestDataFactory.createPricebooks(2, 'TestPricebook');
            Test.startTest();
            List<PriceBook2>  pricebooks = OrderManagement_CC.getPriceBooks();
            Test.stopTest();
            System.assertEquals(2, pricebooks.size());
        }
    }
    @isTest
    private static void testGetPriceBooksEntriesCurrencies() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'Pricebook');
            List<Product2> products = TestDataFactory.createProducts(3);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            Test.startTest();
            List<AggregateResult> pricebooksEntriescurrencies = 
                OrderManagement_CC.getPriceBooksEntriesCurrencies(pricebooks.get(0).Id);
            Test.stopTest();
        }
    }
    @isTest
    private static void testGetOrder() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            insert orders;
            Test.startTest();
            Order order = OrderManagement_CC.getOrder(orders.get(0).Id);
            Test.stopTest();
            System.assertEquals(true, order.Id == orders.get(0).Id);
        }
    }
    @isTest
    private static void testGetOrderItems() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            insert orders;
            List<OrderItem> orderItems = TestDataFactory.createOrderItems(1, orders, pricebookEntries);
            Test.startTest();
            List<OrderItem> orderItemsTest = OrderManagement_CC.getOrderItems(orders.get(0).Id, 1, 10);
            Test.stopTest();
            System.assertEquals(true, orderItems.size() == orderItemsTest.size());
        } 
    }
    @isTest
    private static void testCloneOrder() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            insert orders;
            List<OrderItem> orderItems = TestDataFactory.createOrderItems(1, orders, pricebookEntries);
            Test.startTest();
            Order order = OrderManagement_CC.cloneOrder(orders.get(0).Id, '');
            Test.stopTest();
            System.assertEquals(true, order.Pricebook2Id == orders.get(0).Pricebook2Id);
        }
    }
    
    @isTest
    private static void testInsertOrderItems() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            insert orders;
            List<OrderItem> orderItems = TestDataFactory.returnOrderItems(1, orders, pricebookEntries);
            Test.startTest();
            String result1 = OrderManagement_CC.insertOrderItems(orderItems);
            //String result2 = OrderManagement_CC.insertOrderItems(null);
            Test.stopTest();
            System.assertEquals('SUCCESS', result1);
            //System.assertNotEquals('SUCCESS', result2);
        }
    }
    @isTest
    private static void testCloneOrderItems() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            insert orders;
            List<OrderItem> orderItems = TestDataFactory.returnOrderItems(1, orders, pricebookEntries);
            insert orderItems;
            Test.startTest();
            System.assertEquals(true, OrderManagement_CC.cloneOrderItems(orderItems[0].Id) != null);
            Test.stopTest();
        }
    }
    @isTest
    private static void testGetProductsCounter() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> productsParents = TestDataFactory.returnProducts(1);
            productsParents.get(0).PG1_Desc__c = 'PG1_Desc__c';
            productsParents.get(0).PG2_Desc__c = 'PG2_Desc__c';
            productsParents.get(0).PG3_Desc__c = 'PG3_Desc__c';
            productsParents.get(0).PG4_Desc__c = 'PG4_Desc__c';
            insert productsParents;
            List<Product2> products = TestDataFactory.returnProducts(1);
            products.get(0).GlobalSKUMapping__c = productsParents.get(0).Id;
            insert products;
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Opportunity> opportunities = TestDataFactory.returnOpportunities(1, 'Account_Plan', testUser.Id);
            opportunities.get(0).AccountId = accounts.get(0).Id;
            insert opportunities;
            Test.startTest();
            Integer counter1 = OrderManagement_CC.getProductsCounter(
                pricebooks.get(0).Id,accounts.get(0).Id, 'Product+Article', 'USD',
                                                'PG1_Desc__c', 'PG2_Desc__c', 'PG3_Desc__c', 'PG4_Desc__c', true);
            Integer counter2 = OrderManagement_CC.getProductsCounter(
                pricebooks.get(0).Id,opportunities.get(0).Id, 'Article1,Article2', 'USD',
                'PG1_Desc__c', 'PG2_Desc__c', 'PG3_Desc__c', 'PG4_Desc__c', false);
            Test.stopTest();
        }
    }
      @isTest
    private static void testGetProducts() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> productsParents = TestDataFactory.returnProducts(1);
            productsParents.get(0).PG1_Desc__c = 'PG1_Desc__c';
            productsParents.get(0).PG2_Desc__c = 'PG2_Desc__c';
            productsParents.get(0).PG3_Desc__c = 'PG3_Desc__c';
            productsParents.get(0).PG4_Desc__c = 'PG4_Desc__c';
            insert productsParents;
            List<Product2> products = TestDataFactory.returnProducts(1);
            products.get(0).GlobalSKUMapping__c = productsParents.get(0).Id;
            insert products;
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Opportunity> opportunities = TestDataFactory.returnOpportunities(1, 'Account_Plan', testUser.Id);
            opportunities.get(0).AccountId = accounts.get(0).Id;
            insert opportunities;
            Test.startTest();
            List<Product2> products1 = OrderManagement_CC.getProducts(
                pricebooks.get(0).Id,accounts.get(0).Id, 'Product+Article', 'USD',
                                                    'PG1_Desc__c', 'PG2_Desc__c', 'PG3_Desc__c', 'PG4_Desc__c', 1, 10, true);
            List<Product2> products2 = OrderManagement_CC.getProducts(
                pricebooks.get(0).Id,opportunities.get(0).Id, 'Article1,Article2', 'USD',
                'PG1_Desc__c', 'PG2_Desc__c', 'PG3_Desc__c', 'PG4_Desc__c', 1, 10, false);
            Test.stopTest();
        }
    }
    @isTest
    private static void testGetOrderItemsCounter() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            insert orders;
            TestDataFactory.createOrderItems(1, orders, pricebookEntries);
            Test.startTest();
            System.assertEquals(1, OrderManagement_CC.getOrderItemsCounter(orders.get(0).Id));
            Test.stopTest();
        }
    }
    @isTest
    private static void testDeleteOrderItem() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            insert orders;
            List<OrderItem> orderItems = TestDataFactory.createOrderItems(1, orders, pricebookEntries);
            Test.startTest();
            System.assertEquals('SUCCESS', OrderManagement_CC.deleteOrderItem(orderItems.get(0).Id));
            //System.assertNotEquals('SUCCESS', OrderManagement_CC.deleteOrderItem('Fire Exception'));
            Test.stopTest();
        }
    }
    @isTest
    private static void testGetSBUDescriptions() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> productsParents = TestDataFactory.returnProducts(1);
            productsParents.get(0).PG1_Desc__c = 'PG1_Desc__c';
            productsParents.get(0).PG2_Desc__c = 'PG2_Desc__c';
            productsParents.get(0).PG3_Desc__c = 'PG3_Desc__c';
            productsParents.get(0).PG4_Desc__c = 'PG4_Desc__c';
            insert productsParents;
            List<Product2> products = TestDataFactory.returnProducts(1);
            products.get(0).GlobalSKUMapping__c = productsParents.get(0).Id;
            insert products;
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            Test.startTest();
            String sbu1 = OrderManagement_CC.getSBUDescriptions(pricebooks.get(0).Id,accounts.get(0).Id, 'USD', true);
            String sbu2 = OrderManagement_CC.getSBUDescriptions(pricebooks.get(0).Id,accounts.get(0).Id, 'USD', false);
            Test.stopTest();
        }
    }
    @isTest
    private static void testGetContracts() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.returnPricebooks(1, 'BNL PRE');
            pricebooks.get(0).Contract_Discount_types__c = 'Implants';
            insert pricebooks;
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Opportunity> opportunities = TestDataFactory.returnOpportunities(1, 'Account_Plan', testUser.Id);
            opportunities.get(0).AccountId = accounts.get(0).Id;
            insert opportunities;
            Field_Sales_Project_Members__c prospect1 = new Field_Sales_Project_Members__c();
            prospect1.Account__c = accounts.get(0).Id;
            prospect1.Category__c = 'Implants';
            prospect1.Status__c = 'New';
            insert prospect1;
            List<Contact> contacts = TestDataFactory.returnContacts(1, 'ContactGlobal', testUser.Id);
            contacts.get(0).AccountId = accounts.get(0).Id;
            insert contacts;            
            List<Event> events = TestDataFactory.returnEvents(1, testUser.Id);
            events.get(0).WhatId = accounts.get(0).Id;
            events.get(0).WhoId = contacts.get(0).Id;
            events.get(0).Subject = 'test';

            insert events;
            Test.startTest();
            List<Contract> contracts1 = OrderManagement_CC.getContracts(pricebooks.get(0).Id, accounts.get(0).Id, '');
            List<Contract> contracts2 = OrderManagement_CC.getContracts(pricebooks.get(0).Id, opportunities.get(0).Id, '');
            List<Contract> contracts3 = OrderManagement_CC.getContracts(pricebooks.get(0).Id, events.get(0).Id, '');
            List<Contract> contracts4 = OrderManagement_CC.getContracts(pricebooks.get(0).Id, prospect1.Id, '');
            Test.stopTest();
        }
    }

    @isTest
    private static void testGetRelatedAccountsWithContact() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            /*List<Pricebook2> pricebooks = TestDataFactory.returnPricebooks(1, 'BNL PRE');
            pricebooks.get(0).Contract_Discount_types__c = 'Implants';
            insert pricebooks;*/
            List<Account> accounts = TestDataFactory.createAccounts(3, 'CIM_Account', testUser.Id);
           /* List<Opportunity> opportunities = TestDataFactory.returnOpportunities(1, 'Account_Plan', testUser.Id);
            opportunities.get(0).AccountId = accounts.get(0).Id;
            insert opportunities;
            Field_Sales_Project_Members__c prospect1 = new Field_Sales_Project_Members__c();
            prospect1.Account__c = accounts.get(0).Id;
            prospect1.Category__c = 'Implants';
            prospect1.Status__c = 'New';
            insert prospect1;*/
            List<Contact> contacts = TestDataFactory.returnContacts(1, 'ContactGlobal', testUser.Id);
            contacts.get(0).AccountId = accounts.get(0).Id;
            insert contacts;      
                  
            List<Event> events = TestDataFactory.returnEvents(1, testUser.Id);
            events.get(0).WhatId = accounts.get(0).Id;
            events.get(0).WhoId = contacts.get(0).Id;
            events.get(0).Subject = 'test';
            insert events;
            List<AccountContactRelation> AccountContactRelation = TestDataFactory.returnAccountContactRelationhip(2);
            AccountContactRelation.get(0).AccountId = accounts.get(1).Id;
            AccountContactRelation.get(0).ContactId = contacts.get(0).Id;
            AccountContactRelation.get(1).AccountId = accounts.get(2).Id;
            AccountContactRelation.get(1).ContactId = contacts.get(0).Id;
            insert AccountContactRelation;
            
            Test.startTest();
            List<AccountContactRelation> accountContactRelations = OrderManagement_CC.getRelatedAccountsWithContact( contacts.get(0).Id );
            List<AccountContactRelation> accountContactRelations2 = OrderManagement_CC.getRelatedAccountsWithContact( events.get(0).Id );
            Test.stopTest();
        }
    }

    @isTest
    private static void testCreateOrder() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.returnPricebooks(3, 'BNL PRE');
            pricebooks.get(0).Contract_Discount_types__c = 'Implants';
            pricebooks.get(0).Pricebook_Channel__c = 'Direct';
            pricebooks.get(1).Contract_Discount_types__c = 'Implants';
            pricebooks.get(1).Pricebook_Channel__c = 'Indirect';
            pricebooks.get(2).Contract_Discount_types__c = 'Implants';
            pricebooks.get(2).Pricebook_Channel__c = 'Free Good Order';
            insert pricebooks;
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Opportunity> opportunities = TestDataFactory.returnOpportunities(1, 'Account_Plan', testUser.Id);
            opportunities.get(0).AccountId = accounts.get(0).Id;
            insert opportunities;
            List<Contact> contacts = TestDataFactory.returnContacts(1, 'ContactGlobal', testUser.Id);
            contacts.get(0).AccountId = accounts.get(0).Id;
            insert contacts;
            
            Field_Sales_Project_Members__c prospect1 = new Field_Sales_Project_Members__c();
            prospect1.Account__c = accounts.get(0).Id;
            prospect1.Category__c = 'Implants';
            prospect1.Status__c = 'New';
            
            insert prospect1;
            List<Event> events = TestDataFactory.returnEvents(1, testUser.Id);
            events.get(0).WhatId = accounts.get(0).Id;
            events.get(0).WhoId = contacts.get(0).Id;
            events.get(0).Subject = 'test';

            insert events;

            Test.startTest();
            OrderManagement_CC.createOrder(pricebooks.get(0).Id, accounts.get(0).Id, '', '', '','');
            OrderManagement_CC.createOrder(pricebooks.get(1).Id, opportunities.get(0).Id, '', '', '','');
            OrderManagement_CC.createOrder(pricebooks.get(2).Id, opportunities.get(0).Id, '', '', '','');
            OrderManagement_CC.createOrder(pricebooks.get(0).Id, contacts.get(0).Id, '', '', '',accounts.get(0).Id);
            //OrderManagement_CC.createOrder(pricebooks.get(0).Id, contacts.get(0).Id, '', '', '',null);
            OrderManagement_CC.createOrder(pricebooks.get(0).Id, prospect1.Id, '', '', '','');
            OrderManagement_CC.createOrder(pricebooks.get(0).Id, events.get(0).Id, '', '', '',accounts.get(0).Id);
            OrderManagement_CC.createOrder(pricebooks.get(0).Id, events.get(0).Id, '', '', '',null);
            Test.stopTest();
        }
    }
    @isTest
    private static void testgetAccountRecordType() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.returnPricebooks(3, 'BNL PRE');
            pricebooks.get(0).Contract_Discount_types__c = 'Implants';
            pricebooks.get(0).Pricebook_Channel__c = 'Direct';
            pricebooks.get(1).Contract_Discount_types__c = 'Implants';
            pricebooks.get(1).Pricebook_Channel__c = 'Indirect';
            pricebooks.get(2).Contract_Discount_types__c = 'Implants';
            pricebooks.get(2).Pricebook_Channel__c = 'Free Good Order';
            insert pricebooks;
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Opportunity> opportunities = TestDataFactory.returnOpportunities(1, 'Account_Plan', testUser.Id);
            opportunities.get(0).AccountId = accounts.get(0).Id;
            insert opportunities;
            List<Contact> contacts = TestDataFactory.returnContacts(1, 'ContactGlobal', testUser.Id);
            contacts.get(0).AccountId = accounts.get(0).Id;
            insert contacts;
            
            Field_Sales_Project_Members__c prospect1 = new Field_Sales_Project_Members__c();
            prospect1.Account__c = accounts.get(0).Id;
            prospect1.Category__c = 'Implants';
            prospect1.Status__c = 'New';
            
            insert prospect1;
            List<Event> events = TestDataFactory.returnEvents(1, testUser.Id);
            events.get(0).WhatId = accounts.get(0).Id;
            events.get(0).WhoId = contacts.get(0).Id;
            events.get(0).Subject = 'test';

            insert events;

            Test.startTest();
            OrderManagement_CC.getAccountRecordType( accounts.get(0).Id);
            OrderManagement_CC.getAccountRecordType( opportunities.get(0).Id);
            OrderManagement_CC.getAccountRecordType( contacts.get(0).Id);
            OrderManagement_CC.getAccountRecordType( prospect1.Id);
            OrderManagement_CC.getAccountRecordType( events.get(0).Id);
            Test.stopTest();
        }
    }

    @isTest
    private static void testGetSourceRecords() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.returnPricebooks(1, 'AAAAatest');
            pricebooks.get(0).ShowPricingfromMicroServiceOM__c = true;
            pricebooks.get(0).SourceId__c = '2';
            pricebooks.get(0).CompanyCode__c = '057';
            pricebooks.get(0).Pricebook_Channel__c = 'Direct';
            insert pricebooks;
            List<Account> accounts = TestDataFactory.createAccounts(1, 'CIM_Account', testUser.Id);
            List<Opportunity> opportunities = TestDataFactory.returnOpportunities(1, 'Account_Plan', testUser.Id);
            opportunities.get(0).AccountId = accounts.get(0).Id;
            insert opportunities;
            List<Contact> contacts = TestDataFactory.returnContacts(1, 'ContactGlobal', testUser.Id);
            contacts.get(0).AccountId = accounts.get(0).Id;
            insert contacts;
            
            Field_Sales_Project_Members__c prospect1 = new Field_Sales_Project_Members__c();
            prospect1.Account__c = accounts.get(0).Id;
            prospect1.Category__c = 'Implants';
            prospect1.Status__c = 'New';
            
            insert prospect1;
            List<Event> events = TestDataFactory.returnEvents(1, testUser.Id);
            events.get(0).WhatId = accounts.get(0).Id;
            events.get(0).WhoId = contacts.get(0).Id;
            events.get(0).Subject = 'test';

            insert events;
            Test.startTest();
            List<Source_Record__c> sourceRecords = OrderManagement_CC.getSourceRecords( accounts.get(0).Id,pricebooks.get(0).Id,null);
            List<Source_Record__c> sourceRecords1 = OrderManagement_CC.getSourceRecords( null,accounts.get(0).Id,pricebooks.get(0).Id);
            List<Source_Record__c> sourceRecords2 = OrderManagement_CC.getSourceRecords( opportunities.get(0).Id,pricebooks.get(0).Id,null);
            List<Source_Record__c> sourceRecords3 = OrderManagement_CC.getSourceRecords( contacts.get(0).Id,pricebooks.get(0).Id,null);
            List<Source_Record__c> sourceRecords4 = OrderManagement_CC.getSourceRecords( events.get(0).Id,pricebooks.get(0).Id,null);
            List<Source_Record__c> sourceRecords5 = OrderManagement_CC.getSourceRecords( prospect1.Id,pricebooks.get(0).Id,null);
            Test.stopTest();
        }
    }
	
    @isTest
    private static void testCloneOrderWithPricingMicroServiceCallOut() {
        // Set mock callout class 
      	Test.setMock(HttpCalloutMock.class, new ProductPricingERPCallOutMock()); 
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.returnPricebooks(1, 'BNL PRE');
            pricebooks.get(0).ShowPricingfromMicroServiceOM__c = true;
            pricebooks.get(0).SourceId__c = '2';
            pricebooks.get(0).CompanyCode__c = '057';
            pricebooks.get(0).Pricebook_Channel__c = 'Direct';
            insert pricebooks;
            List<Product2> products = TestDataFactory.returnProducts(1);
            products.get(0).Company_Code__c = '057';
            products.get(0).ERP_Source__c = 2;
            products.get(0).Article__c = '0520055';
            insert products;
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'CIM_Account', testUser.Id);
            Account acc = [SELECT RecordType.DeveloperName FROM Account WHERE Id =: accounts.get(0).Id limit 1];
            List<Source_Record__c> sourceRecords = TestDataFactory.returnSourceRecords(1);
            sourceRecords.get(0).Name = 'test';
            sourceRecords.get(0).Source_Id__c = '2';
            sourceRecords.get(0).Customer_Id__c = '690862';
            sourceRecords.get(0).CIM_Account__c = acc.Id;
            insert sourceRecords;
            List<Order> orders = TestDataFactory.returnOrders(1, 'Direct_global_order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            orders.get(0).SourceRecord__c = sourceRecords.get(0).Id;
            insert orders;
            List<OrderItem> orderItems = TestDataFactory.createOrderItems(1, orders, pricebookEntries);
            //List<OrderItem> orderItems2 = TestDataFactory.createOrderItems(1, orders, pricebookEntries);
            Test.startTest();
            Order order = OrderManagement_CC.cloneOrder(orders.get(0).Id, '');
            ProductPricingERPCallOutWrapper.ProductEntry prodEntry = new ProductPricingERPCallOutWrapper.ProductEntry();
            prodEntry.productId='44';
            prodEntry.quantity=5;
            Test.stopTest();
            System.assertEquals(true, order.Pricebook2Id == orders.get(0).Pricebook2Id);
        }
    }

   
	
}