unpackaged/objects/Article__c.object
<CustomObject>
  <description>Used to add multiple articles to a Case</description>
  <fields>
    <fullName>Article_Number__c</fullName>
    <label>Article Number</label>
    <length>254</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <label>Article Number</label>
  <nameField>
    <displayFormat>A-{000000}</displayFormat>
    <label>Article Id</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Article Numbers</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Case.object
<CustomObject>
  <fields>
    <fullName>Article_Number__c</fullName>
    <description>Used to fill in the article number related to a sevice feedback case.</description>
    <label>Article Number</label>
    <length>254</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Credit_Rebill__c</fullName>
    <label>Credit/Rebill</label>
    <length>254</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>254</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>New_or_Replacement_Order__c</fullName>
    <label>New or Replacement Order</label>
    <length>254</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>254</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Return_Tracking_Number__c</fullName>
    <label>Return Tracking Number</label>
    <length>250</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Tracking_number__c</fullName>
    <label>Tracking Number</label>
    <length>254</length>
    <type>Text</type>
  </fields>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/OrderItem.object
<CustomObject>
  <fields>
    <fullName>Article_Number__c</fullName>
    <formula>PricebookEntry.Product2.Article__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Article Number</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Total_Line_Item_Price__c</fullName>
    <formula>Quantity * UnitPrice *(1- Discount_Percent__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Line Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
</CustomObject>

unpackaged/objects/Product2.object
<CustomObject>
  <fields>
    <fullName>Article__c</fullName>
    <externalId>true</externalId>
    <label>Article (SKU)</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Sales_History__c.object
<CustomObject>
  <description>Detailed Sales History of Products Sold to Accounts</description>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales History</relationshipLabel>
    <relationshipName>SalesHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Article__c</fullName>
    <description>Article (SKU) + Product name</description>
    <formula>Name  &amp; " "  &amp;  Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Article (SKU) + Product name</inlineHelpText>
    <label>Article &amp; Product Name</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>10</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Order_Number__c</fullName>
    <description>This is the Astra Tech order number that this row corresponds to. Note that it is not until the article has been invoiced that the sales history record appears in Salesforce.</description>
    <inlineHelpText>This is the Astra Tech order number that this row corresponds to. Note that it is not until the article has been invoiced that the sales history record appears in Salesforce.</inlineHelpText>
    <label>Order Number</label>
    <length>11</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Price__c</fullName>
    <inlineHelpText>Unit Price</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Tot_Price__c</fullName>
    <formula>IF( Quantity__c =0,  Price__c , Price__c *  Quantity__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Value =  Quantity multiplied by the Price</inlineHelpText>
    <label>Total Price (Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
  <label>Sales History</label>
  <nameField>
    <label>Article (SKU)</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Sales History</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/SC_Case_Questionnaire__mdt.object
<CustomObject>
  <fields>
    <fullName>Amount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amount</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Carrier__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carrier</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Communication &amp; Service</fullName>
          <default>true</default>
          <label>Communication &amp; Service</label>
        </value>
        <value>
          <fullName>E-commerce site</fullName>
        </value>
        <value>
          <fullName>Orders &amp; Billing</fullName>
        </value>
        <value>
          <fullName>Product Related</fullName>
        </value>
        <value>
          <fullName>Shipping</fullName>
        </value>
        <value>
          <fullName>Software Complaint</fullName>
          <label>Software</label>
        </value>
        <value>
          <fullName>Customer Interaction</fullName>
        </value>
        <value>
          <fullName>Billing</fullName>
        </value>
        <value>
          <fullName>Orders</fullName>
        </value>
        <value>
          <fullName>Not a Complaint</fullName>
          <isActive>false</isActive>
          <label>Not a Complaint</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Correctionofvalue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Correction of value</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Credit_Rebill__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credit/Rebill</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Expirationdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Date</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Invoice_number__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice number</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Item_number__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item number</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>LOTnumber__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LOT number</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>New_or_Replacement_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New or Replacement Order</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Order_number__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order number</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Returnnumber__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return number</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Softwarename__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Software name</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Timeofcontact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Time of contact</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Tracking_number__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tracking number</label>
    <type>Checkbox</type>
  </fields>
  <label>SC Case questionnaire</label>
  <pluralLabel>SC Case Questionnaires</pluralLabel>
</CustomObject>

unpackaged/classes/ServiceCloud_Case.cls
public class ServiceCloud_Case {

    @AuraEnabled
    public static Case getCaseInfo(Id recordId){    
    Case cs = [SELECT Id, Subject, OwnerId, Order_Number__c, Return_Tracking_Number__c, Invoice_Number__c FROM Case WHERE Id=: recordId];
    return cs;    
    }
    
    @AuraEnabled
    public static List<Case> getMyOpenCases(){    
    List<Case> cs = [SELECT Id, CaseNumber, OwnerId, Status, Subject, RecordType.Name, IsClosed, Account.BillingAddress, ContactId, AccountId FROM Case WHERE OwnerId=: UserInfo.getUserId() LIMIT 10];
    return cs;    
    }
    
    @AuraEnabled
    public static List<Order> getOrders(Id accountId){
        List<Order> ordrs = [SELECT Id, Status, OrderNumber, EffectiveDate, ActivatedDate FROM Order WHERE AccountId =: accountId ORDER BY ActivatedDate DESC LIMIT 10];
      return ordrs;
    }
    
    @AuraEnabled
    public static Order findOrderDetails(Id orderId){
        Order ordr = [SELECT Id, OrderNumber, EffectiveDate, Status, ActivatedDate, TotalAmount FROM Order WHERE Id =: orderId];
      	return ordr;
    }
    
    @AuraEnabled
    public static List<OrderItem> findOrderRows(Id orderId){
        List<OrderItem> ordrRows = [SELECT Id, Article_Number__c, ListPrice, Total_Line_Item_Price__c, UnitPrice, Product2Id, Product2.Name, Product2.Article__c, OrderId, Quantity FROM OrderItem WHERE OrderId =: orderId];
      	return ordrRows;
    }
    
    /*@AuraEnabled
    public static List<Sales_History__c> findInvoiceRows(String orderNoMovex){
        List<Sales_History__c> salesRows = [SELECT Id, Article__c, Price__c, Name, Account__c, Account__r.Name, Tot_Price__c, Invoice_Number__c, Invoice_Date__c, Quantity__c, Order_Number__c FROM Sales_History__c WHERE Order_Number__c =: orderNoMovex];
      	return salesRows;
    }*/
    
    @AuraEnabled
    public static List<SC_Case_Questionnaire__mdt> findQuestions(){
        List<SC_Case_Questionnaire__mdt> Questions = [SELECT Label, Category__c, Credit_Rebill__c, New_or_Replacement_Order__c, Order_number__c, Item_number__c, Invoice_number__c, Tracking_number__c, Carrier__c, LOTnumber__c, Returnnumber__c, Softwarename__c, Timeofcontact__c, Expirationdate__c, Correctionofvalue__c, Amount__c 
                                                      FROM SC_Case_Questionnaire__mdt];
      	
        return Questions;
    }
    
        @AuraEnabled
    	public static List<SC_Case_Questionnaire__mdt> findSpecificQuestions(String Reason, String Category){
        List<SC_Case_Questionnaire__mdt> Questions = [SELECT Label, Category__c, Credit_Rebill__c, New_or_Replacement_Order__c, Order_number__c, Item_number__c, Invoice_number__c, Tracking_number__c, Carrier__c, LOTnumber__c, Returnnumber__c, Softwarename__c, Timeofcontact__c, Expirationdate__c, Correctionofvalue__c, Amount__c 
                                                      FROM SC_Case_Questionnaire__mdt WHERE Label =: Reason AND Category__c =: Category]; //AND Category__c =: Category
      	
        return Questions;
    }
     
}