unpackaged/objects/Article__c.object
<CustomObject>
  <description>Used to add multiple articles to a Case</description>
  <fields>
    <fullName>Manager_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Assigned</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Article_Numbers2</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Related_Case__c</fullName>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Articles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Rep_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Assigned</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Article_Numbers1</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Return_Exception_Requested__c</fullName>
    <label>Return Exception Requested</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>No Exception</fullName>
          <default>true</default>
          <label>No Exception</label>
        </value>
        <value>
          <fullName>No record of purchase</fullName>
        </value>
        <value>
          <fullName>Shelf life &lt; 1 yr</fullName>
        </value>
        <value>
          <fullName>Purchased &gt; 180 days</fullName>
          <label>Purchased &gt; 180 days - No Exchange</label>
        </value>
        <value>
          <fullName>Not a DS Product</fullName>
        </value>
        <value>
          <fullName>Product Opened</fullName>
        </value>
        <value>
          <fullName>Writing on Product</fullName>
        </value>
        <value>
          <fullName>Product Crushed</fullName>
        </value>
        <value>
          <fullName>Expired</fullName>
        </value>
        <value>
          <fullName>Damaged Product</fullName>
        </value>
        <value>
          <fullName>Ripped label</fullName>
        </value>
        <value>
          <fullName>Blood/Residue Stain</fullName>
        </value>
        <value>
          <fullName>Staples</fullName>
        </value>
        <value>
          <fullName>Missing TX Sticker</fullName>
        </value>
        <value>
          <fullName>Tape Damage</fullName>
        </value>
        <value>
          <fullName>Discolored Labels</fullName>
        </value>
        <value>
          <fullName>Additional Item Not Part of Exchange</fullName>
        </value>
        <value>
          <fullName>No Product In Package</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Article Number</label>
  <nameField>
    <displayFormat>A-{000000}</displayFormat>
    <label>Article Id</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Article Numbers</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/DC_Setting__c.object
<CustomObject>
  <customSettingsType>List</customSettingsType>
  <description>To store the custom settings related to the code built and deployed by Cervello Team.</description>
  <fields>
    <fullName>Value__c</fullName>
    <description>To store the settings</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <label>DC_Setting</label>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Market__c</fullName>
    <description>&lt;ADMINISTRATION&gt; Keep the values of this field aligned with the Price Book Market field values.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>BeNelux</fullName>
        </value>
        <value>
          <fullName>BEX</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>CEE</fullName>
        </value>
        <value>
          <fullName>China</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ</fullName>
        </value>
        <value>
          <fullName>Iberia</fullName>
        </value>
        <value>
          <fullName>India</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Korea</fullName>
        </value>
        <value>
          <fullName>Malaysia</fullName>
        </value>
        <value>
          <fullName>MEA</fullName>
        </value>
        <value>
          <fullName>NA</fullName>
        </value>
        <value>
          <fullName>Nordics</fullName>
        </value>
        <value>
          <fullName>Poland</fullName>
        </value>
        <value>
          <fullName>Russia</fullName>
        </value>
        <value>
          <fullName>Singapore</fullName>
        </value>
        <value>
          <fullName>South Africa</fullName>
        </value>
        <value>
          <fullName>Switzerland</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/DC_UT_AutoApprovalController.cls
@isTest
public class DC_UT_AutoApprovalController {
	
    private static Case caze;
    private static Article__c article;
    
    private static final String CASE_RECORD_TYPE = 'Return Authorizations';
    private static final String ARTICLE_RECORD_TYPE = 'Return Authorization';
    
    private static void beforeTest() {
        
        User currentUser = new User(Id = UserInfo.getUserId());
        currentUser.Market__c = 'NA';
        update currentUser;
        
        RecordType rt = [select Name from RecordType where Name = :CASE_RECORD_TYPE];
        
        //create test Case
        caze = new Case();
        caze.RecordTypeId = rt.Id;
        insert caze;
        
        rt = [select Name from RecordType where Name = :ARTICLE_RECORD_TYPE];
        //create Article__c object
        article = new Article__c();
        article.Related_Case__c = caze.Id;
        article.RecordTypeId = rt.Id;
        article.Return_Exception_Requested__c = 'Writing on Product';
        article.Rep_Assigned__c = UserInfo.getUserId();
        article.Manager_Assigned__c = UserInfo.getUserId();
        insert article;
        
        //create custom settings for test
        DC_Setting__c settings = new DC_Setting__c();
        settings.Name = DC_SettingsUtils.AUTO_APPROVE_CASE_RECORD_TYPE;
        settings.Value__c = CASE_RECORD_TYPE;
        insert settings;
        
        DC_Setting__c settings2 = new DC_Setting__c();
        settings2.Name = DC_SettingsUtils.AUTO_APPROVE_ARTICLE_RECORD_TYPE;
        settings2.Value__c = ARTICLE_RECORD_TYPE;
        insert settings2;
    }
    
    private static testMethod void approveArticlesForCaseTest() {
        beforeTest();
        system.assertNotEquals(null, caze.Id);
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(article.id);
        Approval.ProcessResult result = Approval.process(req1, false);
        System.assert(result.isSuccess());
        List<ProcessInstanceWorkitem> workitems = DC_AutoApprovalService.getWorkitemsForArticles(new List<Article__c> { article });
        system.assertEquals(1, workitems.size());
        
        List<Article__c> articles = DC_ArticleDao.getArticlesByCaseId(caze.Id);
        system.debug(articles);
        
        //DC_AutoApprovalService.approveArticlesForCase(caze.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(caze);
        DC_AutoApprovalController controller = new DC_AutoApprovalController(sc);
        controller.approveArticles();
        
        workitems = DC_AutoApprovalService.getWorkitemsForArticles(new List<Article__c> { article });
        system.assertEquals(0, workitems.size());
    }    
}