unpackaged/objects/BatchSettings__c.object
<CustomObject>
  <customSettingsType>List</customSettingsType>
  <description>These settings control the behavior of several custom Batch Apex jobs and their execution scheduling.</description>
  <fields>
    <fullName>DisableContractTriggerHelperUpdSales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable ContractTriggerHelper_updSales</label>
    <type>Checkbox</type>
  </fields>
  <label>Batch Settings</label>
</CustomObject>

unpackaged/objects/Contract.object
<CustomObject>
  <fields>
    <fullName>Approval_Status__c</fullName>
    <description>This field is used in reporting (for Contract history). It is used as a workaround to track approvals in reports &amp; Dashboards</description>
    <inlineHelpText>This field is used in reporting (for Contract history). It is used as a workaround to track approvals in reports &amp; Dashboards</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Not Submitted for Approval</fullName>
          <default>true</default>
          <label>Not Submitted for Approval</label>
        </value>
        <value>
          <fullName>Pending</fullName>
        </value>
        <value>
          <fullName>Approved</fullName>
        </value>
        <value>
          <fullName>Rejected</fullName>
        </value>
        <value>
          <fullName>Recalled</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Area_manager_DE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area manager (DE)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Contract_End_Date__c</fullName>
    <label>Contract End Date</label>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Contract_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Contract External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
  </fields>
  <fields>
    <fullName>Discount_model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount model</label>
    <referenceTo>Discount_model__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Max_Approved_Discount__c</fullName>
    <label>Max Approved Discount (%)</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>New_customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New customer?</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Owners_Managers_Email_DE__c</fullName>
    <description>Sets the owners manager according to the Manager field on the user record. Used for DE 95% contract fulfillment emails. Should not be visible on Page Layout.</description>
    <inlineHelpText>Sets the owners manager according to the Manager field on the user record. Used for DE 95% contract fulfillment emails. Should not be visible on Page Layout.</inlineHelpText>
    <label>Owners Managers Email (DE)</label>
    <type>Email</type>
  </fields>
  <fields>
    <fullName>Pooled_order_commitment__c</fullName>
    <defaultValue>0</defaultValue>
    <description>If the customer agrees to commit to place a pooled order during the contract period</description>
    <label>Pooled order commitment?</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Revenue_forecast__c</fullName>
    <inlineHelpText>Only applicable for new customers</inlineHelpText>
    <label>Sales estimation/correction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Sales_Correction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sales Correction</label>
    <type>Checkbox</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
    <fullName>Contract</fullName>
    <label>Contract</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Used for contracts based on the new Discount Model for IMPL DE</description>
    <fullName>Pricing_contract</fullName>
    <label>Pricing contract</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Discount_model__c.object
<CustomObject>
  <description>Used for storing discount models related to Contracts</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <label>Discount Model</label>
  <nameField>
    <label>Discount Model Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Discount Model</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Manager_workaround__c</fullName>
    <description>Workaround used to select users Manager</description>
    <inlineHelpText>&lt;!&gt; The value of this field overrides the std field "Manager"</inlineHelpText>
    <label>Manager selection</label>
    <relationshipName>ManagerWorkaround</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/Test_ContractPB.cls
/*------------------------------------------------------------
Author: 		Ahmed LOUDRASSI (Salesforce) 2019-11-25
Description:   	Test Class for the Contract Process Builder.
History
<Date>      <Authors Name>     <Brief Description of Change>

------------------------------------------------------------*/

@isTest(seeAllData=false)
public class Test_ContractPB {
	/*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList1 = TestDataFactory.createUsers(1, 'System Administrator');
       	List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
        List<Discount_Model__c> discountModels = TestDataFactory.createDiscountModels(1, userList1.get(0).Id);
        TestDataFactory.createDEDiscountModelCustomSetting(discountModels.get(0));
        TestDataFactory.createDefaultOrgLevelBypassPB();
        
        BatchSettings__c batchSetting = new BatchSettings__c();
        batchSetting.DisableContractTriggerHelperUpdSales__c = false;
        batchSetting.Name = 'Default';
        insert batchSetting;
    }
    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();

        System.assertEquals(1, testUserList.size(), 'Expected Two user');
    }
    @isTest
    private static void testManagersManagerisASM() {
        User testUser = [SELECT Id, Manager_workaround__r.Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.createAccounts(1, 'Geographical_Account', testUser.Id);
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
       	insert contracts;
        Test.stopTest();
        
        System.assertEquals(testUser.Manager_workaround__r.Id, [SELECT Id, Area_manager_DE__r.Id FROM Contract LIMIT 1].Area_manager_DE__r.Id);
    }
    /*@isTest
    private static void testCheckNewCustomer() {
        User testUser = [SELECT Id, Manager_workaround__r.Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.returnAccounts(1, 'Geographical_Account', testUser.Id);
        accounts1.get(0).TS_CY_D_AllPLs_AllPCs_AllBrands__c = 0;
		accounts1.get(0).TS_CY_1_TD_D_AllPLs_AllPCs_AllBrands__c = 0;
        insert accounts1;
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
        insert contracts;
        Test.stopTest();
        
        System.assertEquals(true, [SELECT Id, New_customer__c FROM Contract LIMIT 1].New_customer__c);
    }*/
    @isTest
    private static void testClearContractOwnerExpirationNoticeOnExpiredContracts() {
        User testUser = [SELECT Id, Manager_workaround__r.Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.createAccounts(1, 'Geographical_Account', testUser.Id);
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).Status = 'Active';
        contracts.get(0).OwnerExpirationNotice = '90';
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
       	insert contracts;
        Test.stopTest();
        
        System.assertEquals(null, [SELECT Id, OwnerExpirationNotice FROM Contract LIMIT 1].OwnerExpirationNotice);
    }
    @isTest
    private static void testDESetMaxApprovedDiscount() {
        User testUser = [SELECT Id, Manager_workaround__r.Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.returnAccounts(1, 'Geographical_Account', testUser.Id);
        accounts1.get(0).Country__c = 'DE';
        insert accounts1;
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).Status = 'Draft';
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
        insert contracts;
        Test.stopTest();
        
        //System.assertEquals(0, [SELECT Id, Max_Approved_Discount__c FROM Contract LIMIT 1].Max_Approved_Discount__c);
    }
    @isTest
    private static void testSetApprovalStatusFieldOnCreation() {
        User testUser = [SELECT Id, Manager_workaround__r.Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.createAccounts(1, 'Geographical_Account', testUser.Id);
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).Approval_Status__c = 'Pending';
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
        insert contracts;
        Test.stopTest();
        System.assertEquals('Not Submitted for Approval', [SELECT Id, Approval_Status__c FROM Contract LIMIT 1].Approval_Status__c);        
    }
    @isTest
    private static void testSetContractExternalID() {
        User testUser = [SELECT Id, Manager_workaround__r.Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.createAccounts(1, 'Geographical_Account', testUser.Id);
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
        insert contracts;
        Test.stopTest();
        Contract contract = [SELECT Id, Contract_External_ID__c, ContractNumber FROM Contract LIMIT 1];
        System.assertEquals(contract.ContractNumber, contract.Contract_External_ID__c);
    }   
    @isTest
    private static void testSetOwnerExpirationNotice() {
        User testUser = [SELECT Id, Manager_workaround__r.Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.returnAccounts(1, 'Geographical_Account', testUser.Id);
        accounts1.get(0).Country__c = 'DE';
        insert accounts1;
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).OwnerExpirationNotice = '15';
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
        insert contracts;
        Test.stopTest();
        
        System.assertEquals('90', [SELECT Id, OwnerExpirationNotice FROM Contract LIMIT 1].OwnerExpirationNotice);
    }
    @isTest
    private static void testSetOwnersManagersEmailDE() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.createAccounts(1, 'Geographical_Account', testUser.Id);
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
        insert contracts;
        Test.stopTest();
        Contract contract = [SELECT Id, Owners_Managers_Email_DE__c, Owner.Manager.Email FROM Contract LIMIT 1];
        System.assertEquals(contract.Owner.Manager.Email, contract.Owners_Managers_Email_DE__c);
    }
    @isTest
    private static void testSetPooledOrderCommitment() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.createAccounts(1, 'Geographical_Account', testUser.Id);
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).Pooled_order_commitment__c = 2;
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
        insert contracts;
        Test.stopTest();
        System.assertEquals(0, [SELECT Id, Pooled_order_commitment__c FROM Contract LIMIT 1].Pooled_order_commitment__c);
    }
    @isTest
    private static void testUpdateContractEndDate() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.createAccounts(1, 'Geographical_Account', testUser.Id);
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).StartDate = Date.today();
        contracts.get(0).Status = 'Draft';
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
        insert contracts;
        Test.stopTest();
        //System.assertEquals(Date.today(), [SELECT Id, Contract_End_Date__c FROM Contract LIMIT 1].Contract_End_Date__c);
    }
    @isTest
    private static void testUpdateContractSalesOnEnd() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.createAccounts(1, 'Geographical_Account', testUser.Id);
        List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts1);
        contracts.get(0).Contract_End_Date__c = Date.today();
        contracts.get(0).Revenue_forecast__c = 10000;
        contracts.get(0).Sales_Correction__c = true;
        Test.startTest();
        insert contracts;
        Test.stopTest();
    }
}