unpackaged/objects/BatchSettings__c.object
<CustomObject>
  <customSettingsType>List</customSettingsType>
  <description>These settings control the behavior of several custom Batch Apex jobs and their execution scheduling.</description>
  <fields>
    <fullName>CampMgmtEngagementTriggerIsEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked, the CampMgmtEngagementTrigger Apex trigger is run on all modifications to Engagement records.</description>
    <inlineHelpText>When checked, the CampMgmtEngagementTrigger Apex trigger is run on all modifications to Engagement records.</inlineHelpText>
    <label>Enable CampMgmtEngagementTrigger</label>
    <type>Checkbox</type>
  </fields>
  <label>Batch Settings</label>
</CustomObject>

unpackaged/objects/Campaign.object
<CustomObject>
  <fields>
    <fullName>Speaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used by HQ T&amp;E.</description>
    <label>Speaker</label>
    <lookupFilter>
      <active>true</active>
      <errorMessage>No contact categorized as speaker matches your search criteria. Make sure field "Speaker Type" is set on the Contact.</errorMessage>
      <filterItems>
        <field>Contact.Speaker_Type__c</field>
        <operation>notEqual</operation>
        <value></value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Session</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
  </fields>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN.</description>
    <fullName>DI_Campaign</fullName>
    <label>Course/Event/Exhibition</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN SESSION, related to a CAMPAIGN.</description>
    <fullName>DI_Campaign_Session</fullName>
    <label>Campaign Session</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Speaker__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked if the Contact is a Speaker.</inlineHelpText>
    <label>Speaker</label>
    <type>Checkbox</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Engagement__c.object
<CustomObject>
  <description>Speaker Engagements and Requests, Moderator Engagements &amp; Requests</description>
  <fields>
    <fullName>Session__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Campaign.RecordTypeId</field>
        <operation>equals</operation>
        <value>DI: Campaign Session</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Speaker Engagements</relationshipLabel>
    <relationshipName>SpeakerRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Speaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Speaker</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
      <filterItems>
        <field>Contact.Speaker__c</field>
        <operation>equals</operation>
        <value>True</value>
      </filterItems>
      <filterItems>
        <field>Contact.Local_Speaker__c</field>
        <operation>equals</operation>
        <value>True</value>
      </filterItems>
      <filterItems>
        <field>Contact.National_Speaker__c</field>
        <operation>equals</operation>
        <value>True</value>
      </filterItems>
      <filterItems>
        <field>Contact.International_Speaker__c</field>
        <operation>equals</operation>
        <value>True</value>
      </filterItems>
      <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Speaker Engagements</relationshipLabel>
    <relationshipName>Requets</relationshipName>
    <type>Lookup</type>
  </fields>
  <label>Speaker Engagement</label>
  <nameField>
    <label>Request Title</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Speaker Engagements</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/CampMgmtEngagementTriggerTest.cls
@isTest
private class CampMgmtEngagementTriggerTest
{
    static testmethod void insertTest01()
    {
        Campaign campaign = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Campaign');      
        Campaign session = CampMgmtTestHelpers.createTestSession(campaign.Id, 'Test Session 1', 'DI_Campaign_Session');
        Account account = CampMgmtTestHelpers.createTestAccount('Test Account 1');
        Contact contact = CampMgmtTestHelpers.createTestContact(account.Id, 'Testis', 'Testisson', 'email@email.com');
        
        enableTrigger();
        
        Engagement__c engagement = new Engagement__c();
        engagement.Name = 'Test Engagement 1';
        engagement.Session__c = session.Id;
        engagement.Speaker__c = contact.Id;
        insert engagement;

        // TODO: Assert something.
    }
    
    private static void enableTrigger()
    {
        BatchSettings__c settings = new BatchSettings__c();
        settings.Name = 'Default';
        settings.CampMgmtEngagementTriggerIsEnabled__c = true;
        insert settings;
    }
}