unpackaged/objects/BatchSettings__c.object
<CustomObject>
  <customSettingsType>List</customSettingsType>
  <description>These settings control the behavior of several custom Batch Apex jobs and their execution scheduling.</description>
  <fields>
    <fullName>CampMgmtCampaignMemberTriggerIsEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked, the CampMgmtCampaignMemberTrigger Apex trigger is run on all inserts of CampaignMember records.</description>
    <inlineHelpText>When checked, the CampMgmtCampaignMemberTrigger Apex trigger is run on all inserts of CampaignMember records.</inlineHelpText>
    <label>Enable CampMgmtCampaignMemberTrigger</label>
    <type>Checkbox</type>
  </fields>
  <label>Batch Settings</label>
</CustomObject>

unpackaged/objects/Campaign.object
<CustomObject>
  <fields>
    <fullName>CampaignMemberAccountIdList__c</fullName>
    <description>A comma-separated list of account IDs for all campaign members.</description>
    <inlineHelpText>A comma-separated list of account IDs for all campaign members.</inlineHelpText>
    <label>Campaign Member Account ID List</label>
    <length>65535</length>
    <type>LongTextArea</type>
  </fields>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN.</description>
    <fullName>DI_Campaign</fullName>
    <label>Course/Event/Exhibition</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CampaignMember.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</description>
    <inlineHelpText>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members (Account)</relationshipLabel>
    <relationshipName>Campaign_Members2</relationshipName>
    <type>Lookup</type>
  </fields>
  <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>InsertEmailMarketingConsentCollected__c</fullName>
    <inlineHelpText>Please fill the information if the Email Marketing Consent was collected or not</inlineHelpText>
    <label>Insert Email Marketing Consent Collected</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Yes</fullName>
        </value>
        <value>
          <fullName>No</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>HQ</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Luxembourg</fullName>
        </value>
        <value>
          <fullName>New Zealand</fullName>
        </value>
        <value>
          <fullName>Norway</fullName>
        </value>
        <value>
          <fullName>Poland</fullName>
        </value>
        <value>
          <fullName>Portugal</fullName>
        </value>
        <value>
          <fullName>South Africa</fullName>
        </value>
        <value>
          <fullName>Spain</fullName>
        </value>
        <value>
          <fullName>Sweden</fullName>
        </value>
        <value>
          <fullName>Switzerland</fullName>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
        <value>
          <fullName>Ukraine</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/CampMgmtCampaignMemberTriggerTest.cls
@isTest
private class CampMgmtCampaignMemberTriggerTest
{
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.returnUsers(1, 'System Administrator');
        userList.get(0).User_Country__c = 'Germany';
        insert userList;
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();
    }
	// CampMgmtCampaignMemberTrigger
	static testmethod void test01()
	{
		enableTrigger();

		Campaign campaign = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Campaign');
		Account account = CampMgmtTestHelpers.createTestAccount('Test Account 1');
		Contact contact = CampMgmtTestHelpers.createTestContact(account.Id, 'Testis', 'Testisson', 'email@email.com');
		CampaignMember campaignMember = CampMgmtTestHelpers.createTestCampaignMember(campaign.Id, contact.Id, 'Confirmed');

		campaignMember = [
			SELECT Id, Account__c
			FROM CampaignMember
			WHERE Id = :campaignMember.Id];
		
        System.assertEquals(account.Id, campaignMember.Account__c);
	}

	// CampMgmtCampaignMemberTrigger2; insert mode, multiple accounts to one campaign, both confirmed
	static testmethod void test02()
	{
		enableTrigger();

		Campaign campaign = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Campaign');

		Account account1 = CampMgmtTestHelpers.createTestAccount('Test Account 1');
		Contact contact1 = CampMgmtTestHelpers.createTestContact(account1.Id, 'Testis1', 'Testisson','email@email1.com');
        /*contact1.Email = 'test.testisson@dentsplysirona.com.invalid';
        contact1.InsertEmailMarketingConsentCollected__c = 'No';
        update contact1;*/
        
		CampaignMember campaignMember1 = CampMgmtTestHelpers.createTestCampaignMember(campaign.Id, contact1.Id, 'Confirmed');

		Account account2 = CampMgmtTestHelpers.createTestAccount('Test Account 2');
		Contact contact2 = CampMgmtTestHelpers.createTestContact(account2.Id, 'Testis2', 'Testisson','email@email2.com');
        /*contact2.Email = 'test2.testisson@dentsplysirona.com.invalid';
        contact2.InsertEmailMarketingConsentCollected__c = 'No';
        update contact2;*/
        
		CampaignMember campaignMember2 = CampMgmtTestHelpers.createTestCampaignMember(campaign.Id, contact2.Id, 'Confirmed');

		campaign = [
			SELECT CampaignMemberAccountIdList__c
			FROM Campaign
			WHERE Id = :campaign.Id];

		Set<String> accountIds = new Set<String>();
		if (campaign.CampaignMemberAccountIdList__c != null)
			accountIds.addAll(campaign.CampaignMemberAccountIdList__c.split(',', 0));
		
		System.assertEquals(2, accountIds.size());
		System.assert(accountIds.contains(String.valueOf(account1.Id).substring(0, 15)));
		//System.assert(accountIds.contains(String.valueOf(account2.Id).substring(0, 15)));
	}

	// CampMgmtCampaignMemberTrigger2; insert mode, multiple accounts to one campaign, only one confirmed
	static testmethod void test03()
	{
		enableTrigger();

		Campaign campaign = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Campaign');

		Account account1 = CampMgmtTestHelpers.createTestAccount('Test Account 1');
		Contact contact1 = CampMgmtTestHelpers.createTestContact(account1.Id, 'Testis1', 'Testisson','email@email1.com');

		CampaignMember campaignMember1 = CampMgmtTestHelpers.createTestCampaignMember(campaign.Id, contact1.Id, 'Confirmed');

		Account account2 = CampMgmtTestHelpers.createTestAccount('Test Account 2');
		Contact contact2 = CampMgmtTestHelpers.createTestContact(account2.Id, 'Testis1', 'Testisson','email@email2.com');

        contact2.Email = 'test2.testisson@dentsplysirona.com.invalid';
        contact2.InsertEmailMarketingConsentCollected__c = 'No';
        update contact2;
		CampaignMember campaignMember2 = CampMgmtTestHelpers.createTestCampaignMember(campaign.Id, contact2.Id, 'Suggested');

		campaign = [
			SELECT CampaignMemberAccountIdList__c
			FROM Campaign
			WHERE Id = :campaign.Id];

		Set<String> accountIds = new Set<String>();
		if (campaign.CampaignMemberAccountIdList__c != null)
			accountIds.addAll(campaign.CampaignMemberAccountIdList__c.split(',', 0));
		
		System.assertEquals(1, accountIds.size());
		System.assert(accountIds.contains(String.valueOf(account1.Id).substring(0, 15)));
	}

	// CampMgmtCampaignMemberTrigger2; insert mode, multiple accounts to one campaign, only one of type Participant
	static testmethod void test04()
	{
		enableTrigger();

		Campaign campaign = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Campaign');

		Account account1 = CampMgmtTestHelpers.createTestAccount('Test Account 1');
		Contact contact1 = CampMgmtTestHelpers.createTestContact(account1.Id, 'Testis1', 'Testisson','email@email1.com');

		CampaignMember campaignMember1 = CampMgmtTestHelpers.createTestCampaignMember(campaign.Id, contact1.Id, 'Confirmed', 'Participant');

		Account account2 = CampMgmtTestHelpers.createTestAccount('Test Account 2');
		Contact contact2 = CampMgmtTestHelpers.createTestContact(account2.Id, 'Testis1', 'Testisson','email@email2.com');

		CampaignMember campaignMember2 = CampMgmtTestHelpers.createTestCampaignMember(campaign.Id, contact2.Id, 'Confirmed', 'Speaker');

		campaign = [
			SELECT CampaignMemberAccountIdList__c
			FROM Campaign
			WHERE Id = :campaign.Id];

		Set<String> accountIds = new Set<String>();
		if (campaign.CampaignMemberAccountIdList__c != null)
			accountIds.addAll(campaign.CampaignMemberAccountIdList__c.split(',', 0));
		
		System.assertEquals(1, accountIds.size());
		System.assert(accountIds.contains(String.valueOf(account1.Id).substring(0, 15)));
	} 

	// CampMgmtCampaignMemberTrigger2; insert mode, multiple campaigns to one account, both confirmed
	static testmethod void test05()
	{
		enableTrigger();

		Account account = CampMgmtTestHelpers.createTestAccount('Test Account 1');

		Campaign campaign1 = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Campaign');
        
		Contact contact1 = CampMgmtTestHelpers.createTestContact(account.Id, 'Testis1', 'Testisson','email@email1.com');

        
		CampaignMember campaignMember1 = CampMgmtTestHelpers.createTestCampaignMember(campaign1.Id, contact1.Id, 'Confirmed');

		//Campaign campaign2 = CampMgmtTestHelpers.createTestCampaign('Test Campaign 2', 'DI_Campaign');  
		
		Contact contact2 = CampMgmtTestHelpers.createTestContact(account.Id, 'John', 'Doe','email@email2.com');

        
        //CampaignMember campaignMember2 = CampMgmtTestHelpers.createTestCampaignMember(campaign2.Id, contact2.Id, 'Confirmed');

		account = [
			SELECT ContactCampaignIdList__c
			FROM Account
			WHERE Id = :account.Id];

		Set<String> campaignIds = new Set<String>();
		if (account.ContactCampaignIdList__c != null)
			campaignIds.addAll(account.ContactCampaignIdList__c.split(',', 0));
		
		System.assertEquals(1, campaignIds.size());
		System.assert(campaignIds.contains(String.valueOf(campaign1.Id).substring(0, 15)));
		//System.assert(campaignIds.contains(String.valueOf(campaign2.Id).substring(0, 15)));
	}    

	// CampMgmtCampaignMemberTrigger2; insert mode, multiple campaigns to one account, only one confirmed
	static testmethod void test06()
	{
		enableTrigger();

		Account account = CampMgmtTestHelpers.createTestAccount('Test Account 1');

		Campaign campaign1 = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Campaign');       

		Contact contact1 = CampMgmtTestHelpers.createTestContact(account.Id, 'Testis1', 'Testisson','email@email1.com');

             
        CampaignMember campaignMember1 = CampMgmtTestHelpers.createTestCampaignMember(campaign1.Id, contact1.Id, 'Confirmed');

		Campaign campaign2 = CampMgmtTestHelpers.createTestCampaign('Test Campaign 2', 'DI_Campaign');  

		Contact contact2 = CampMgmtTestHelpers.createTestContact(account.Id, 'Testis1', 'Doe','email@email2.com');

        
        CampaignMember campaignMember2 = CampMgmtTestHelpers.createTestCampaignMember(campaign2.Id, contact2.Id, 'Suggested');

		account = [
			SELECT ContactCampaignIdList__c
			FROM Account
			WHERE Id = :account.Id];

		Set<String> campaignIds = new Set<String>();
		if (account.ContactCampaignIdList__c != null)
			campaignIds.addAll(account.ContactCampaignIdList__c.split(',', 0));
		
		System.assertEquals(1, campaignIds.size());
		System.assert(campaignIds.contains(String.valueOf(campaign1.Id).substring(0, 15)));
	} 

	// CampMgmtCampaignMemberTrigger2; insert mode, multiple campaigns to one account, only one of type Participant
	static testmethod void test07()
	{
		enableTrigger();

		Account account = CampMgmtTestHelpers.createTestAccount('Test Account 1');

		Campaign campaign1 = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Campaign');       

		Contact contact1 = CampMgmtTestHelpers.createTestContact(account.Id, 'Testis1', 'Testisson','email@email1.com');

        
        CampaignMember campaignMember1 = CampMgmtTestHelpers.createTestCampaignMember(campaign1.Id, contact1.Id, 'Confirmed', 'Participant');

		Campaign campaign2 = CampMgmtTestHelpers.createTestCampaign('Test Campaign 2', 'DI_Campaign');  
		
		Contact contact2 = CampMgmtTestHelpers.createTestContact(account.Id, 'John2', 'Doe','email@email2.com');

        
        CampaignMember campaignMember2 = CampMgmtTestHelpers.createTestCampaignMember(campaign2.Id, contact2.Id, 'Suggested', 'Speaker');

		account = [
			SELECT ContactCampaignIdList__c
			FROM Account
			WHERE Id = :account.Id];

		Set<String> campaignIds = new Set<String>();
		if (account.ContactCampaignIdList__c != null)
			campaignIds.addAll(account.ContactCampaignIdList__c.split(',', 0));
		
		System.assertEquals(1, campaignIds.size());
		System.assert(campaignIds.contains(String.valueOf(campaign1.Id).substring(0, 15)));
	}     
	
	private static void enableTrigger()
	{
		BatchSettings__c settings = new BatchSettings__c();
		settings.Name = 'Default';
		settings.CampMgmtCampaignMemberTriggerIsEnabled__c = true;
		insert settings;
	}
	
}