unpackaged/objects/BatchSettings__c.object
<CustomObject>
  <customSettingsType>List</customSettingsType>
  <description>These settings control the behavior of several custom Batch Apex jobs and their execution scheduling.</description>
  <fields>
    <fullName>OrderSetAccountOwnerIsEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked, the OrderSetAccountOwner Apex trigger is run on all inserts and updates of Order records.</description>
    <inlineHelpText>When checked, the OrderSetAccountOwner Apex trigger is run on all inserts and updates of Order records.</inlineHelpText>
    <label>Enable OrderSetAccountOwner</label>
    <type>Checkbox</type>
  </fields>
  <label>Batch Settings</label>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Discount_model__c.object
<CustomObject>
  <description>Used for storing discount models related to Contracts</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <label>Discount Model</label>
  <nameField>
    <label>Discount Model Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Discount Model</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Discount_row__c.object
<CustomObject>
  <fields>
    <fullName>Allowed_discount__c</fullName>
    <label>Allowed discount</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Discount_Model__c</fullName>
    <label>Discount Model</label>
    <referenceTo>Discount_model__c</referenceTo>
    <relationshipLabel>Discount row</relationshipLabel>
    <relationshipName>Discount_row</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Discount_lever__c</fullName>
    <label>Discount lever</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Revenue: materials</fullName>
        </value>
        <value>
          <fullName>Revenue: equipments &amp; instruments</fullName>
        </value>
        <value>
          <fullName>Implant: materials</fullName>
        </value>
        <value>
          <fullName>Implants: equipments &amp; instruments</fullName>
        </value>
        <value>
          <fullName>Abutments: materials</fullName>
        </value>
        <value>
          <fullName>Abutments: equipments &amp; instruments</fullName>
        </value>
        <value>
          <fullName>Pooled implant order: Material</fullName>
        </value>
        <value>
          <fullName>Pooled implant order: Equipment</fullName>
        </value>
        <value>
          <fullName>Payment type</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Equals__c</fullName>
    <label>Equals</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Max__c</fullName>
    <label>Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Min__c</fullName>
    <label>Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Payment_terms_months__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Allowed payment terms (months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <label>Discount row</label>
  <nameField>
    <displayFormat>A-{0000}</displayFormat>
    <label>Discount row Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Discount row</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OrdersOwned</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Allowed_discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Allowed discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_payment_terms_months__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Allowed payment terms (months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Order_Amount_global__c</fullName>
    <formula>(Order_amount_before_disc_globa__c + Order_bundle_amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Order_Type__c</fullName>
    <description>Order Type for DNA</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Free Goods Order</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Telesales</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Discount on Demand</fullName>
        </value>
        <value>
          <fullName>PREP</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Payment_terms_months__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Payment terms (months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Payment_type__c</fullName>
    <inlineHelpText>Please choose the payment type by which the customer would like to pay</inlineHelpText>
    <label>Payment type</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>DS credit card</fullName>
        </value>
        <value>
          <fullName>Credit card</fullName>
        </value>
        <value>
          <fullName>Bank transfer</fullName>
        </value>
        <value>
          <fullName>Promissory note</fullName>
        </value>
        <value>
          <fullName>Cheque</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Payment_type_discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Payment type discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Regional_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Pricebook2.object
<CustomObject>
  <fields>
    <fullName>Discount_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount Model</label>
    <referenceTo>Discount_model__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
  </fields>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/OrderTriggerHelper.cls
/*-------------------------------------------------------------------------------------
Author: 		Miguel Coimbra (Salesforce) 2020-06-10
Description:    Order Trigger Helper Class
Test Class:     Test_OrderTrigger
History 
----------------------------------------------------------------------------------------*/
public class OrderTriggerHelper {
    /*------------------------------------------------------------  
    Description:    User Story: #1833: Caculate the Allowed Discount for Turkish Orders (Of Type "Implants")
                    This method is called from the Order trigger before updating a new Order and is fired upon adding, editing or deleting 
                    a new Order Item (where the parent is updated) If the code on the Order Item trigger is removed. This logic is no longer called! 
    ------------------------------------------------------------*/
    
    public static void calculateAllowedDiscount(List<Order> ordersList){

        if (ordersList.isEmpty()) return ;

        Set<Id> newOrderIdsSet = (new Map<Id,SObject>(ordersList)).keySet();

        Map<Id, Id> pbId_dmIdMap= new Map<Id,Id>{};

        for (Order o : [SELECT Pricebook2.Discount_Model__c FROM Order WHERE  Country__c = 'TR' AND Order_Type__c = 'Implants' AND Id in: newOrderIdsSet]){
            pbId_dmIdMap.put(o.Pricebook2Id, o.Pricebook2.Discount_Model__c);
        }

        if (pbId_dmIdMap.isEmpty()) return ; 

        final String REVENUE_MATERIALS = 'Revenue: materials';
        final String PAYMENT_TYPE = 'Payment type';
        // Provide all related Discount Rows (associated with the relevant Discount Models 
        List<Discount_row__c> discountRowsList = [SELECT Id, Max__c, Min__c, Discount_Model__c, Discount_lever__c, Equals__c, Allowed_discount__c, Payment_terms_months__c FROM Discount_row__c WHERE 
                                                        (Discount_lever__c =: REVENUE_MATERIALS OR Discount_lever__c =: PAYMENT_TYPE ) and Discount_Model__c in: pbId_dmIdMap.Values()];

        for (Order o: ordersList){
            // OrderAmountglobal is calculated with the right value when a field referenced by a Roll Up Summary field is modified. (This happens for instance when a new value is added) 
            Double OrderAmountglobal = o.Order_Amount_global__c ; 
            if (String.isBlank(o.Payment_type__c)){
                o.Payment_type_discount__c = 0 ;
            }else{
                for (Discount_row__c dr: discountRowsList){
                    if (dr.Discount_Model__c == pbId_dmIdMap.get(o.Pricebook2Id) && PAYMENT_TYPE.equals(dr.Discount_Lever__c) && dr.Equals__c == o.Payment_type__c){
                        o.Payment_type_discount__c = dr.Allowed_Discount__c;
                        break ; 
                    }
                }
            }
            
            for (Discount_row__c dr: discountRowsList){
                if (dr.Discount_Model__c == pbId_dmIdMap.get(o.Pricebook2Id) && REVENUE_MATERIALS.equals(dr.Discount_Lever__c) 
                && dr.Max__c >= OrderAmountglobal && dr.Min__c <= OrderAmountglobal){
                    o.Allowed_Discount__c = dr.Allowed_Discount__c ;
                    o.Allowed_payment_terms_months__c = dr.Payment_terms_months__c ;
                    break ; 
                }
            }
        }     
    }
     /*------------------------------------------------------------  
    Description:    Code migrated from OrderSetAccountOwner (as a result,  OrderSetAccountOwner.trigger has been removed. )
                    Called before Insert and before Update                    
    Author:    Miguel Coimbra (20200615)
    ------------------------------------------------------------*/

    public static void setAccountOwnerAndRegionalManagerOnOrder(List<Order> newOrdersList){ 
        
        // Don't run unless configured to do so.
        BatchSettings__c settings = BatchSettings__c.getInstance('Default');
        if (!Test.isRunningTest() && !settings.OrderSetAccountOwnerIsEnabled__c)
            return; 

        Set<ID> relatedAccountIds = new Set<ID>();
        for (Order o : newOrdersList)
            if (o.AccountId != null)
                relatedAccountIds.add(o.AccountId);
        Map<ID, Account> accountMap = new Map<Id, Account>([SELECT Id, OwnerId, Owner.ManagerId FROM Account WHERE Id IN :relatedAccountIds]);

        for (Order o : newOrdersList)
        {
            if (o.AccountId != null)
            {
                Account a = accountMap.get(o.AccountId);
                if (a != null)
                {
                    o.Account_Owner__c = a.OwnerId; 
                    o.Regional_Manager__c = a.Owner.ManagerId; 
                }
            }
        }
    }

}