unpackaged/objects/BatchSettings__c.object
<CustomObject>
  <customSettingsType>List</customSettingsType>
  <description>These settings control the behavior of several custom Batch Apex jobs and their execution scheduling.</description>
  <fields>
    <fullName>DisableContractTriggerHelperUpdSales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable ContractTriggerHelper_updSales</label>
    <type>Checkbox</type>
  </fields>
  <label>Batch Settings</label>
</CustomObject>

unpackaged/objects/Contract.object
<CustomObject>
  <fields>
    <fullName>Abutment_commitment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Abutment commitment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_Implants_equipment__c</fullName>
    <label>Allowed discount Implants: equipment</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_Implants_materials__c</fullName>
    <label>Allowed discount Implants: materials</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_abutment_equipment__c</fullName>
    <label>Allowed discount abutment: equipment</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_abutment_materials__c</fullName>
    <label>Allowed discount abutment: materials</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_pooling_equipment__c</fullName>
    <label>Allowed discount pooling, equipment</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_pooling_materials__c</fullName>
    <label>Allowed discount pooling, materials</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_revenue_equipments__c</fullName>
    <label>Allowed discount revenue: equipment</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_revenue_materials__c</fullName>
    <label>Allowed discount revenue: materials</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Contract_length__c</fullName>
    <description>Contract length in months</description>
    <label>Contract length (months)</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>Status</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>12</fullName>
        </value>
        <value>
          <fullName>24</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Discount_model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount model</label>
    <referenceTo>Discount_model__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>General_practitioner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>General practitioner?</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Implant_commitment_perc_input__c</fullName>
    <label>Implant commitment (%)</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>90</fullName>
        </value>
        <value>
          <fullName>100</fullName>
        </value>
        <value>
          <fullName>110</fullName>
        </value>
        <value>
          <fullName>120</fullName>
        </value>
        <value>
          <fullName>130</fullName>
        </value>
        <value>
          <fullName>80</fullName>
          <isActive>false</isActive>
          <label>80</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Implant_volume_L12M__c</fullName>
    <label>Implant volume L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Payment_discount__c</fullName>
    <label>Payment discount</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>0</fullName>
        </value>
        <value>
          <fullName>2</fullName>
        </value>
        <value>
          <fullName>3</fullName>
        </value>
        <value>
          <fullName>4</fullName>
        </value>
        <value>
          <fullName>5</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Payment_terms__c</fullName>
    <formula>Account.Payment_Terms_D_JP__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment terms</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Pooled_order_commitment__c</fullName>
    <defaultValue>0</defaultValue>
    <description>If the customer agrees to commit to place a pooled order during the contract period</description>
    <label>Pooled order commitment?</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Previous_contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous contract</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Contract.AccountId</field>
        <operation>equals</operation>
        <valueField>$Source.AccountId</valueField>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Previous contract</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Sales_L12M__c</fullName>
    <label>Sales L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Sales_L24M__c</fullName>
    <label>Sales L24M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
    <fullName>Contract</fullName>
    <label>Contract</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Used for contracts based on the new Discount Model for IMPL DE</description>
    <fullName>Pricing_contract</fullName>
    <label>Pricing contract</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Discount_model__c.object
<CustomObject>
  <description>Used for storing discount models related to Contracts</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <label>Discount Model</label>
  <nameField>
    <label>Discount Model Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Discount Model</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/Test_ContractTrigger.cls
/*------------------------------------------------------------
Author: 		Kevin Do (Salesforce) 2020-01-17
Description:   	Test Class for all ContractTriggerHelper methods.
History
<Date>      <Authors Name>     <Brief Description of Change>
20200117 	Kevin Do			Created Class
------------------------------------------------------------*/

@isTest(seeAllData=false)
public class Test_ContractTrigger {
    public static final Boolean RUN_TRIGGERS = true;
    public static final Boolean RUN_PROCESS_BUILDER = false;

    @TestSetup
    static void setup() {
        TestDataFactory.createBypassCustomSetting(RUN_TRIGGERS, RUN_PROCESS_BUILDER);
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
        List<Discount_model__c> discountModelList = TestDataFactory.createDiscountModels(1, userList[0].Id);
        TestDataFactory.createDEDiscountModelCustomSetting(discountModelList[0]);
        TestDataFactory.createDiscountRows(discountModelList[0].Id);
		
        BatchSettings__c batchSetting = new BatchSettings__c();
        batchSetting.DisableContractTriggerHelperUpdSales__c = false;
        batchSetting.Name = 'Default';
        insert batchSetting;
        
        
    }

    @IsTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();
        
        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }

    /*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Test method for ContractTriggerHelper.updateSalesHistory()
                 Asserts that contract fields are set with correct values from Account before insert.
    History :
    --------------------------------------------------------------------------------------------------------*/
    @IsTest
    private static void testUpdateSalesHistory() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> testAccountList = TestDataFactory.returnAccounts(3, 'Lab_Customer_D', testUser.Id);
        Account testAccount0 = testAccountList[0];
        testAccount0.Country__c = 'DE';
        // Fields needed for Account.Sales_L12MD__c formula field
        testAccount0.TS_CY_D_AllPLs_AllPCs_AllBrands__c = 1000;
        testAccount0.TS_CY_1_D_AllPLs_AllPCs_AllBrands__c = 2000;
        testAccount0.TS_CY_1_TD_D_AllPLs_AllPCs_AllBrands__c = 100;
        // Fields needed for Account.Sold_Implants_L12M__c formula field
        testAccount0.TQ_CY_1_D_DI_Implants_AllBrands__c = 1000;
        testAccount0.TQ_CY_1_TD_D_DI_Implants_AllBrands__c = 100;
        testAccount0.TQ_CY_D_DI_Implants_AllBrands__c = 2000;
        // Fields needed for Account.Sales_L13_24M_D__c formula field
        testAccount0.TS_CY_2_D_AllPLs_AllPCs_AllBrands__c = 1000;
        testAccount0.TS_CY_2_TD_D_AllPLs_AllPCs_AllBrands__c = 100;
        insert testAccountList;
        Id testAccountId = testAccount0.Id;

        Account accountToAssert = [
            SELECT Id, Sales_L12M_D__c, Sold_Implants_L12M__c, Sales_L13_24M_D__c 
            FROM Account
            WHERE Id = :testAccountId
            LIMIT 1
        ];

        // Insert one Contract that should be referenced in Contract.Previous_contract__c
        Contract initialContract = new Contract();
        initialContract.RecordTypeId = GlobalUtils.getRecordTypeId('Contract', 'Pricing_contract');
        initialContract.StartDate = Date.today();
        initialContract.Status = 'Draft';
        initialContract.Contract_length__c = '12';
        initialContract.AccountId = testAccount0.Id;
        initialContract.Implant_commitment_perc_input__c = '100';
        initialContract.General_practitioner__c = false;
        insert initialContract;

        List<Contract> insertContractList = new List<Contract>();
        Map<Id, Contract> testContractMap = new Map<Id, Contract>();
        for (Integer i = 0; i < 20; i++) {
            Contract testContract = new Contract();
            testContract.RecordTypeId = GlobalUtils.getRecordTypeId('Contract', 'Pricing_contract');
            testContract.StartDate = Date.today();
            testContract.Status = 'Draft';
            testContract.Contract_length__c = '12';
            testContract.AccountId = testAccount0.Id;
            testContract.Implant_commitment_perc_input__c = '100';
            testContract.General_practitioner__c = false;
            insertContractList.add(testContract);
        }
        
        Test.startTest();
        insert insertContractList;
        Test.stopTest();
        
        List<Contract> testContractList = [
            SELECT Id, Sales_L12M__c, Implant_volume_L12M__c, Sales_L24M__c, Implant_commitment_perc_input__c, Abutment_commitment__c, Pooled_order_commitment__c
            FROM Contract
            WHERE CreatedById = :testUser.Id
        ];

        for (Contract testContract : testContractList) {
            System.assertEquals(accountToAssert.Sales_L12M_D__c, testContract.Sales_L12M__c);
            System.assertEquals(accountToAssert.Sold_Implants_L12M__c, testContract.Implant_volume_L12M__c);
            System.assertEquals(accountToAssert.Sales_L12M_D__c + accountToAssert.Sales_L13_24M_D__c, testContract.Sales_L24M__c);
            System.assertEquals(initialContract.Id, testContract.Previous_contract__c);
        }
    }

    /*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Test method for ContractTriggerHelper.updateSalesHistory()
                 Asserts that contract discount is set according to discount rows
    History :
    --------------------------------------------------------------------------------------------------------*/
    @IsTest
    private static void testUpdateAllowedDiscount() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Discount_model__c> testDiscountModelList = [SELECT Id FROM Discount_model__c WHERE OwnerId = :testUser.Id LIMIT 1];
        Id testDiscountModelId = testDiscountModelList[0].Id;
        List<Account> testAccountList = TestDataFactory.returnAccounts(3, 'Lab_Customer_D', testUser.Id);
        Account testAccount0 = testAccountList[0];
        testAccount0.Country__c = 'DE';
        // Fields needed for Account.Sales_L12MD__c formula field
        testAccount0.TS_CY_D_AllPLs_AllPCs_AllBrands__c = 1000;
        testAccount0.TS_CY_1_D_AllPLs_AllPCs_AllBrands__c = 2000;
        testAccount0.TS_CY_1_TD_D_AllPLs_AllPCs_AllBrands__c = 100;
        // Fields needed for Account.Sold_Implants_L12M__c formula field
        testAccount0.TQ_CY_1_D_DI_Implants_AllBrands__c = 1000;
        testAccount0.TQ_CY_1_TD_D_DI_Implants_AllBrands__c = 100;
        testAccount0.TQ_CY_D_DI_Implants_AllBrands__c = 2000;
        // Fields needed for Account.Sales_L13_24M_D__c formula field
        testAccount0.TS_CY_2_D_AllPLs_AllPCs_AllBrands__c = 1000;
        testAccount0.TS_CY_2_TD_D_AllPLs_AllPCs_AllBrands__c = 100;
        // Payment_Terms_D_JP__C referenced as is by Contract.Payment_terms__c 
        testAccount0.Payment_Terms_D_JP__c = 'LOW';
        insert testAccountList;
        Id testAccountId = testAccount0.Id;

        Account accountToAssert = [
            SELECT Id, Sales_L12M_D__c, Sold_Implants_L12M__c, Sales_L13_24M_D__c 
            FROM Account
            WHERE Id = :testAccountId
            LIMIT 1
        ];

        List<Contract> insertContractList = new List<Contract>();
        Map<Id, Contract> testContractMap = new Map<Id, Contract>();
        for (Integer i = 0; i < 20; i++) {
            Contract testContract = new Contract();
            testContract.RecordTypeId = GlobalUtils.getRecordTypeId('Contract', 'Pricing_contract');
            testContract.StartDate = Date.today();
            testContract.Status = 'Draft';
            testContract.Contract_length__c = '12';
            testContract.AccountId = testAccount0.Id;
            testContract.Implant_commitment_perc_input__c = '100';
            testContract.General_practitioner__c = false;
            testContract.Discount_model__c = testDiscountModelId;
            insertContractList.add(testContract);
        }
        
        Test.startTest();
        insert insertContractList;
        Test.stopTest();

        List<Contract> testContractList = [
            SELECT Id, Sales_L12M__c, Implant_volume_L12M__c, Sales_L24M__c, Implant_commitment_perc_input__c, Abutment_commitment__c, Pooled_order_commitment__c
            FROM Contract
            WHERE CreatedById = :testUser.Id
        ];

        for (Contract testContract : testContractList) {
            System.assertEquals(1, testContract.Allowed_discount_revenue_materials__c);
            System.assertEquals(1, testContract.Allowed_discount_revenue_equipments__c);
            System.assertEquals(1, testContract.Allowed_discount_Implants_materials__c);
            System.assertEquals(1, testContract.Allowed_discount_Implants_equipment__c);
            System.assertEquals(1, testContract.Allowed_discount_abutment_materials__c);
            System.assertEquals(1, testContract.Allowed_discount_abutment_equipment__c);
            System.assertEquals(1, testContract.Allowed_discount_pooling_materials__c);
            System.assertEquals(1, testContract.Allowed_discount_pooling_equipment__c);
            System.assertEquals(null, testContract.Payment_discount__c);
        }
    }  

}