unpackaged/objects/BatchSettings__c.object
<CustomObject>
  <customSettingsType>List</customSettingsType>
  <description>These settings control the behavior of several custom Batch Apex jobs and their execution scheduling.</description>
  <fields>
    <fullName>CampMgmtCampaignTriggerIsEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked, the CampMgmtCampaignTrigger Apex trigger is run on all inserts of Campaign records.</description>
    <inlineHelpText>When checked, the CampMgmtCampaignTrigger Apex trigger is run on all inserts of Campaign records.</inlineHelpText>
    <label>Enable CampMgmtCampaignTrigger</label>
    <type>Checkbox</type>
  </fields>
  <label>Batch Settings</label>
</CustomObject>

unpackaged/objects/Campaign.object
<CustomObject>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN.</description>
    <fullName>DI_Campaign</fullName>
    <label>Course/Event/Exhibition</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN SESSION, related to a CAMPAIGN.</description>
    <fullName>DI_Campaign_Session</fullName>
    <label>Campaign Session</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <fullName>DI_Mailing</fullName>
    <label>Mailing</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>First Draft of DNA Campaign setup</description>
    <fullName>DNA_Campaign</fullName>
    <label>DNA Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Inside Sales Campaign</description>
    <fullName>Inside_Sales_Campaign</fullName>
    <label>Inside Sales Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/CampMgmtCampaignTriggerTest.cls
//30-Jan-2019 added campaigntype: Inside Sales Campaign :Lightning Migration: amitkumar.prabhat@mindtree.com
//
@isTest
private class CampMgmtCampaignTriggerTest
{
    @TestSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.returnUsers(1, 'System Administrator');
        userList.get(0).User_Country__c = 'Germany';
        insert userList;
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();
    }
	// Related sessions are deactivated when campaign is deactivated.
	static testmethod void test01()
	{
		enableTrigger();

		Campaign campaign = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Campaign');
		Campaign session1 = CampMgmtTestHelpers.createTestSession(campaign.Id, 'Test Session 1', 'DI_Campaign_Session');
		Campaign session2 = CampMgmtTestHelpers.createTestSession(campaign.Id, 'Test Session 2', 'DI_Campaign_Session');

		campaign = [SELECT Id, IsActive FROM Campaign WHERE Id = :campaign.Id];
		session1 = [SELECT Id, IsActive FROM Campaign WHERE Id = :session1.Id];
		session2 = [SELECT Id, IsActive FROM Campaign WHERE Id = :session2.Id];

		System.assertEquals(true, campaign.IsActive);
		System.assertEquals(true, session1.IsActive);
		System.assertEquals(true, session2.IsActive);

		campaign.IsActive = false;
		update campaign;

		session1 = [SELECT Id, IsActive FROM Campaign WHERE Id = :session1.Id];
		session2 = [SELECT Id, IsActive FROM Campaign WHERE Id = :session2.Id];

		System.assertEquals(false, session1.IsActive);
		System.assertEquals(false, session2.IsActive);
	}
    
	// Correct campaign member status values are created for created 'DI_Mailing' campaigns.
	static testmethod void test02()
	{
		enableTrigger();

		Campaign campaign = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Mailing');
	}    
    
	// Correct campaign member status values are created for created DNA_Campaign' campaigns.
	static testmethod void test03()
	{
		enableTrigger();

        Campaign campaign = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DNA_Campaign');
	} 

    static testmethod void test04()
	{
		enableTrigger();

        Campaign campaign = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'Inside_Sales_Campaign');
	}
	private static void enableTrigger()
	{
		BatchSettings__c settings = new BatchSettings__c();
		settings.Name = 'Default';
		settings.CampMgmtCampaignTriggerIsEnabled__c = true;
		insert settings;
	}
}