unpackaged/objects/BOM__c.object
<CustomObject>
  <fields>
    <fullName>Product_bundle__c</fullName>
    <label>Product bundle</label>
    <referenceTo>Product_bundle__c</referenceTo>
    <relationshipLabel>Bill of Material</relationshipLabel>
    <relationshipName>Bill_of_Material</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <label>Bill of Material</label>
  <nameField>
    <label>Bill of Material Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Bill of Material</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Albania</fullName>
        </value>
        <value>
          <fullName>Algeria</fullName>
        </value>
        <value>
          <fullName>Argentina</fullName>
        </value>
        <value>
          <fullName>Armenia</fullName>
        </value>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Azerbaijan</fullName>
        </value>
        <value>
          <fullName>Bahrain</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Bosnia and Herzegovina</fullName>
        </value>
        <value>
          <fullName>Botswana</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Bulgaria</fullName>
        </value>
        <value>
          <fullName>Cambodia</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Chile</fullName>
        </value>
        <value>
          <fullName>China</fullName>
        </value>
        <value>
          <fullName>Colombia</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Ecuador</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order</label>
    <type>Checkbox</type>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Order_bundle__c.object
<CustomObject>
  <fields>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order bundles</relationshipLabel>
    <relationshipName>Order_bundles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Product_bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product bundle</label>
    <referenceTo>Product_bundle__c</referenceTo>
    <relationshipLabel>Order bundles</relationshipLabel>
    <relationshipName>Order_bundles</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <label>Order bundle</label>
  <nameField>
    <displayFormat>Bundle{0000}</displayFormat>
    <label>Order bundle Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Order bundles</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Product2.object
<CustomObject>
  <fields>
    <fullName>SBU_Name__c</fullName>
    <label>SBU Name</label>
    <length>100</length>
    <type>Text</type>
  </fields>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Product_bundle__c.object
<CustomObject>
  <fields>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <label>Product bundle</label>
  <nameField>
    <label>Product bundle Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Product bundle</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/OrderEmailBOMTest.cls
@isTest
public with sharing class OrderEmailBOMTest {    
    
@isTest
private static void OrderEmailBOM_Test(){

        //PageReference pageRef = Component.OrderEmailBOMs;
        //Test.setCurrentPage(pageRef);
        
        Account a = new Account(Name='Test account 1', CurrencyIsoCode = 'EUR', Country__c = 'NL');
        insert a;
        
        Contact c = new Contact(LastName='Testsson', Firstname='Test', Account = a);
        insert c;
        
        Pricebook2 p = new Pricebook2(Name = 'Test pricebook 1');
        insert p;
        
        Order o = DC_UT_DataUtils.generateOrder(a.id, Date.today(), a.CurrencyIsoCode);
        o.Pricebook2Id = p.id;
        insert o;
       
        DateTime expected = DateTime.newInstance(2016, 4, 21, 8, 13, 16);
            
        ApexPages.currentPage().getParameters().put('related_to_id', o.id);              
        
        OrderEmailBOM controller = new OrderEmailBOM();
        
        controller.currentRecordId = o.id;
                
            //- create test products
    
        Product2 product1 = DC_UT_DataUtils.generateProduct('Product1', 'Brand1',
          'Line1', 'L4_GD_P1');
        product1.SBU_Name__c = 'Prevention';
        Product2 product2 = DC_UT_DataUtils.generateProduct('Product2', 'Brand1',
          'Line1', 'L4_GD_P2');
        Product2 product3 = DC_UT_DataUtils.generateProduct('Product3', 'Brand2',
          'Line2', 'L4_GD_P3');
        Product2[] products = new Product2[] {product1, product2, product3};
        insert products;  
        
        //- create test bundle
        Product_bundle__c bundle1 = DC_UT_DataUtils.generateBundle('Bundle1', p.Id, p.CurrencyIsoCode);
        insert bundle1;
    
        BOM__c bundleProduct1 = DC_UT_DataUtils.generateBOM(product1.Name, bundle1.id, 2);
        insert bundleProduct1;
    
        BOM__c bundleProduct2 = DC_UT_DataUtils.generateBOM(product2.Name, bundle1.id, 1);
        insert bundleProduct2;
        
        Order_bundle__c bundle1_order = new Order_bundle__c();
        bundle1_order.Product_bundle__c = bundle1.Id;
        bundle1_order.Order__c = o.Id;
        bundle1_order.Quantity__c = 1;
        insert bundle1_order;

        controller.getOrdrBundList();       
 
        System.AssertNotEquals(null, controller.currentRecordID);
        System.AssertEquals(controller.ordr.Id, controller.currentRecordID);
        System.AssertNotEquals(0, controller.OrderBundList.size());
             
        controller.getEmailBOM();        
        System.AssertNotEquals(0, controller.BOM_total.size());
                        
    }
    
    @isTest
private static void OrderPdfBOM_Test(){

        //PageReference pageRef = Component.OrderEmailBOMs;
        //Test.setCurrentPage(pageRef);
        
        Account a = new Account(Name='Test account 1', CurrencyIsoCode = 'EUR', Country__c = 'NL');
        insert a;
        
        Contact c = new Contact(LastName='Testsson', Firstname='Test', Account = a);
        insert c;
        
        Pricebook2 p = new Pricebook2(Name = 'Test pricebook 1');
        insert p;
        
        Order o = DC_UT_DataUtils.generateOrder(a.id, Date.today(), a.CurrencyIsoCode);
        o.Pricebook2Id = p.id;
        insert o;
       
        DateTime expected = DateTime.newInstance(2016, 4, 21, 8, 13, 16);
            
        ApexPages.currentPage().getParameters().put('id', o.id);              
        
        OrderPdfBOM controller = new OrderPdfBOM();
        
        controller.currentRecordId = o.id;
                
            //- create test products
    
        Product2 product1 = DC_UT_DataUtils.generateProduct('Product1', 'Brand1',
          'Line1', 'L4_GD_P1');
        product1.SBU_Name__c = 'Prevention';
        Product2 product2 = DC_UT_DataUtils.generateProduct('Product2', 'Brand1',
          'Line1', 'L4_GD_P2');
        Product2 product3 = DC_UT_DataUtils.generateProduct('Product3', 'Brand2',
          'Line2', 'L4_GD_P3');
        Product2[] products = new Product2[] {product1, product2, product3};
        insert products;  
        
        //- create test bundle
        Product_bundle__c bundle1 = DC_UT_DataUtils.generateBundle('Bundle1', p.Id, p.CurrencyIsoCode);
        insert bundle1;
    
        BOM__c bundleProduct1 = DC_UT_DataUtils.generateBOM(product1.Name, bundle1.id, 2);
        insert bundleProduct1;
    
        BOM__c bundleProduct2 = DC_UT_DataUtils.generateBOM(product2.Name, bundle1.id, 1);
        insert bundleProduct2;
        
        Order_bundle__c bundle1_order = new Order_bundle__c();
        bundle1_order.Product_bundle__c = bundle1.Id;
        bundle1_order.Order__c = o.Id;
        bundle1_order.Quantity__c = 1;
        insert bundle1_order;

        controller.getOrdrBundList();       
 
        System.AssertNotEquals(null, controller.currentRecordID);
        System.AssertEquals(controller.ordr.Id, controller.currentRecordID);
        System.AssertNotEquals(0, controller.OrderBundList.size());
             
        controller.getEmailBOM();        
        System.AssertNotEquals(0, controller.BOM_total.size());
                        
    }

    
    
     
    
    }