unpackaged/objects/BOM__c.object
<CustomObject>
  <fields>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bill of Material</relationshipLabel>
    <relationshipName>Bill_of_Material</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Product_bundle__c</fullName>
    <label>Product bundle</label>
    <referenceTo>Product_bundle__c</referenceTo>
    <relationshipLabel>Bill of Material</relationshipLabel>
    <relationshipName>Bill_of_Material</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <label>Bill of Material</label>
  <nameField>
    <label>Bill of Material Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Bill of Material</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Order_bundle__c.object
<CustomObject>
  <fields>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order bundles</relationshipLabel>
    <relationshipName>Order_bundles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Product_bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product bundle</label>
    <referenceTo>Product_bundle__c</referenceTo>
    <relationshipLabel>Order bundles</relationshipLabel>
    <relationshipName>Order_bundles</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Total_price__c</fullName>
    <label>Total price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <label>Order bundle</label>
  <nameField>
    <displayFormat>Bundle{0000}</displayFormat>
    <label>Order bundle Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Order bundles</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Pricebook2.object
<CustomObject>
  <fields>
    <fullName>Direct_orders_Show_prices__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Direct orders: Show prices</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Indirect_orders_Show_discount_field__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indirect orders: Show discount field</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Indirect_orders_Show_prices__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indirect orders: Show prices</label>
    <type>Checkbox</type>
  </fields>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Product_bundle__c.object
<CustomObject>
  <fields>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Product bundle</relationshipLabel>
    <relationshipName>Product_bundle</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Total_price__c</fullName>
    <label>Total price</label>
    <summarizedField>BOM__c.Row_price__c</summarizedField>
    <summaryForeignKey>BOM__c.Product_bundle__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
  </fields>
  <label>Product bundle</label>
  <nameField>
    <label>Product bundle Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Product bundle</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/OrderEmailBOM.cls
public class OrderEmailBOM {

    public List<BOM__c> BOM_rows {get; set;}
    public List<BOM__c> BOM_total {get; set;}
    public Product_bundle__c ProdBundle2 {get; set;}
    public Order ordr {get; set;}
    public Id currentRecordId {get;set;}
    public List <Product_bundle__c> ProdBundList {get; set;}
    public List <Order_bundle__c> OrderBundList {get; set;}
    public Pricebook2 pb {get; set;}
    
    public OrderEmailBOM() {
        ProdBundList = new List <Product_bundle__c> ();
        OrderBundList = new List <Order_bundle__c> ();
        ordr = new Order ();
        
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('related_To_id');
                
    }
    
    public List<Order_bundle__c> getOrdrBundList () {
    
    if(currentRecordId != null) {
        ordr = [SELECT Id, Pricebook2.Id, RecordType.Name FROM Order Where Id =: currentRecordId];
        OrderBundList = [SELECT Id, Product_Bundle__r.Id,Product_Bundle__r.Name, Total_price__c, Quantity__c, Order__r.CurrencyIsoCode FROM Order_bundle__c WHERE Order__r.Id =: currentRecordID];
        pb = [SELECT Id, Name, Indirect_orders_Show_prices__c, Direct_orders_Show_prices__c, Indirect_orders_Show_discount_field__c FROM Pricebook2 WHERE Id =: ordr.Pricebook2.Id];
    }
    return OrderBundList;
    }
       
    public List<BOM__c> getEmailBOM () {
         
        if (OrderBundList.size() > 0) {
        for (Order_bundle__c i: OrderBundList) {
        ProdBundle2 = [SELECT Id, Name FROM Product_Bundle__c WHERE Id =: i.Product_Bundle__r.Id];     
      
        If (ProdBundle2.Id != null){
        ProdBundList.add(prodBundle2);
        }
        
        }
        }
    
    
       
    Bom_total = new List<BOM__c>();
    if (ProdBundList.size() > 0 ) {
    for (Product_bundle__c j: ProdBundList) {
    BOM_rows = [select Id, Name, Product__c, Quantity__c, Product_bundle__c, Product_bundle__r.Id, Discount__c from BOM__c WHERE Product_bundle__r.Id =: j.Id];
    If(Bom_rows.size()>0){
    BOM_total.addAll(BOM_rows);
    }
    }
    }   
    return BOM_total;
    }
    
}