unpackaged/objects/Call_Report__c.object
<CustomObject>
  <fields>
    <fullName>Call_Notes__c</fullName>
    <label>Call Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
  </fields>
  <fields>
    <fullName>Courses__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Courses</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Left_Sample__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Left a Sample</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Met_with_Assistant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Met with Assistant</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Met_with_Decision_Maker__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Met with Decision Maker</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Placed_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Placed Order</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Products_discussed_ENDO__c</fullName>
    <description>SBU: Endodontics, Countries: All - Used for call reporting of products. Controlled by VF to show on page layout if SBU= Endodontics</description>
    <label>Products discussed (ENDO)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <controllingField>Assigned_To_User_Country__c</controllingField>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>AH Plus</fullName>
        </value>
        <value>
          <fullName>AH TEMP</fullName>
        </value>
        <value>
          <fullName>Appex Locator</fullName>
        </value>
        <value>
          <fullName>Conform Fit Guttapercha</fullName>
        </value>
        <value>
          <fullName>EF1123 - Universal</fullName>
        </value>
        <value>
          <fullName>EF1124 - NEXT</fullName>
        </value>
        <value>
          <fullName>EF1210 - WaveOne</fullName>
        </value>
        <value>
          <fullName>EF1211 - GOLD</fullName>
        </value>
        <value>
          <fullName>EF1721 - Universal HF</fullName>
        </value>
        <value>
          <fullName>EF1820 - ProGlider</fullName>
        </value>
        <value>
          <fullName>EF2990 - MAccess</fullName>
        </value>
        <value>
          <fullName>EF2A60 - MAccess</fullName>
        </value>
        <value>
          <fullName>EF2D60 - MAccess</fullName>
        </value>
        <value>
          <fullName>Endoactivator</fullName>
        </value>
        <value>
          <fullName>ENDODONZIA</fullName>
        </value>
        <value>
          <fullName>EO3210 - GuttaCore</fullName>
        </value>
        <value>
          <fullName>EO8320 - AH26/AH PLUS JET</fullName>
        </value>
        <value>
          <fullName>EQ2110 - Propex</fullName>
        </value>
        <value>
          <fullName>EQ2111 - Pixi</fullName>
        </value>
        <value>
          <fullName>EQ4240 - X-Smart</fullName>
        </value>
        <value>
          <fullName>EQ4241 - PLUS</fullName>
        </value>
        <value>
          <fullName>EQ4242 - IQ</fullName>
        </value>
        <value>
          <fullName>EQ4310 - X-Smart</fullName>
        </value>
        <value>
          <fullName>EQ4311 - PLUS</fullName>
        </value>
        <value>
          <fullName>EQ4312 - IQ</fullName>
        </value>
        <value>
          <fullName>Glide path files</fullName>
        </value>
        <value>
          <fullName>Glyde</fullName>
        </value>
        <value>
          <fullName>Gp Modern</fullName>
        </value>
        <value>
          <fullName>Guttacore</fullName>
        </value>
        <value>
          <fullName>Guttacore &amp; plastic obturation</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Products_discussed_IMPL__c</fullName>
    <description>SBU: Implants, Countries: All - Used for call reporting of products. Controlled by VF to show on page layout if SBU= Implants</description>
    <label>Products discussed (IMPL)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <controllingField>Assigned_To_User_Country__c</controllingField>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Acuris</fullName>
        </value>
        <value>
          <fullName>Ankylos</fullName>
        </value>
        <value>
          <fullName>Aquasil</fullName>
        </value>
        <value>
          <fullName>Astra Tech Implant System</fullName>
        </value>
        <value>
          <fullName>Astra Tech Implant System EV</fullName>
        </value>
        <value>
          <fullName>Astra Tech Implant System Profile</fullName>
        </value>
        <value>
          <fullName>ATIS EV - Smartfix</fullName>
        </value>
        <value>
          <fullName>Atlantis</fullName>
        </value>
        <value>
          <fullName>ATLANTIS Abutments</fullName>
        </value>
        <value>
          <fullName>ATLANTIS ISUS</fullName>
        </value>
        <value>
          <fullName>ATLANTIS Suprastructures</fullName>
        </value>
        <value>
          <fullName>Azento</fullName>
        </value>
        <value>
          <fullName>Azento: Astra Tech</fullName>
        </value>
        <value>
          <fullName>Azento: XiVE</fullName>
        </value>
        <value>
          <fullName>Celtra</fullName>
        </value>
        <value>
          <fullName>Custombase</fullName>
        </value>
        <value>
          <fullName>Frialit</fullName>
        </value>
        <value>
          <fullName>Frios</fullName>
        </value>
        <value>
          <fullName>Geistlich</fullName>
        </value>
        <value>
          <fullName>IO scanning</fullName>
        </value>
        <value>
          <fullName>MIS</fullName>
        </value>
        <value>
          <fullName>MIS 4BONE BCH</fullName>
        </value>
        <value>
          <fullName>MIS 4BONE RCM</fullName>
        </value>
        <value>
          <fullName>MIS 4Matrix+</fullName>
        </value>
        <value>
          <fullName>MIS BONDBONE</fullName>
        </value>
        <value>
          <fullName>MIS C1</fullName>
        </value>
        <value>
          <fullName>MIS C1 B+ o C1B</fullName>
        </value>
        <value>
          <fullName>MIS Connect</fullName>
        </value>
        <value>
          <fullName>MIS Lance +</fullName>
        </value>
        <value>
          <fullName>MIS Lance o EF5</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Products_discussed_ORTH__c</fullName>
    <description>SBU: Orthodontics, Countries: All - Used for call reporting of products. Controlled by VF to show on page layout if SBU= Orthodontics</description>
    <label>Products discussed (ORTH)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <controllingField>Assigned_To_User_Country__c</controllingField>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Acceccories</fullName>
        </value>
        <value>
          <fullName>Accu Arch</fullName>
        </value>
        <value>
          <fullName>Accu Force</fullName>
        </value>
        <value>
          <fullName>Adhesives</fullName>
        </value>
        <value>
          <fullName>ADHESIVES &amp; CEMENTS</fullName>
        </value>
        <value>
          <fullName>Allure</fullName>
        </value>
        <value>
          <fullName>APPLIANCE CASES</fullName>
        </value>
        <value>
          <fullName>Arcs</fullName>
        </value>
        <value>
          <fullName>Bands</fullName>
        </value>
        <value>
          <fullName>BBC</fullName>
        </value>
        <value>
          <fullName>Bio-Bite Correctors (Class II Correctors)</fullName>
        </value>
        <value>
          <fullName>Bondable Tubes</fullName>
        </value>
        <value>
          <fullName>Bonding/Etchant</fullName>
        </value>
        <value>
          <fullName>Brackets</fullName>
        </value>
        <value>
          <fullName>Buttons</fullName>
        </value>
        <value>
          <fullName>CB3</fullName>
        </value>
        <value>
          <fullName>CB7</fullName>
        </value>
        <value>
          <fullName>CCO</fullName>
        </value>
        <value>
          <fullName>Cerec Ortho</fullName>
        </value>
        <value>
          <fullName>Clear BKT</fullName>
        </value>
        <value>
          <fullName>Courses</fullName>
        </value>
        <value>
          <fullName>CURING LIGHTS</fullName>
        </value>
        <value>
          <fullName>Digital/Techno</fullName>
        </value>
        <value>
          <fullName>DISPENSER</fullName>
        </value>
        <value>
          <fullName>Drufo</fullName>
        </value>
        <value>
          <fullName>Dry Field/DB</fullName>
        </value>
        <value>
          <fullName>DSKK Buccal Tubes</fullName>
        </value>
        <value>
          <fullName>DSKK Metal BKT</fullName>
        </value>
        <value>
          <fullName>DSKK SUS Wire</fullName>
        </value>
        <value>
          <fullName>ELASTICS</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Products_discussed_PREV__c</fullName>
    <description>SBU: Preventive, Countries: All - Used for call reporting of products. Controlled by VF to show on page layout if SBU= Preventive</description>
    <label>Products discussed (PREV)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <controllingField>Assigned_To_User_Country__c</controllingField>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>ABLAZIONE E TRATTAMENTI</fullName>
        </value>
        <value>
          <fullName>ACCESSORI RADIOLOGIA</fullName>
        </value>
        <value>
          <fullName>Anestadent</fullName>
        </value>
        <value>
          <fullName>Anestethics</fullName>
        </value>
        <value>
          <fullName>Cavitron</fullName>
        </value>
        <value>
          <fullName>Cavitron Inserts</fullName>
        </value>
        <value>
          <fullName>Cavitron Units</fullName>
        </value>
        <value>
          <fullName>Desinfección (ZH/DS)</fullName>
        </value>
        <value>
          <fullName>DISINFEZIONE E STERILIZZAZIONE</fullName>
        </value>
        <value>
          <fullName>Fluorides</fullName>
        </value>
        <value>
          <fullName>Infection Control</fullName>
        </value>
        <value>
          <fullName>MIDWEST RDH Freedom</fullName>
        </value>
        <value>
          <fullName>Nupro</fullName>
        </value>
        <value>
          <fullName>Nupro White Varnish</fullName>
        </value>
        <value>
          <fullName>ORAQIX</fullName>
        </value>
        <value>
          <fullName>Oraqix Topical Anaesthetic</fullName>
        </value>
        <value>
          <fullName>Other Preventive</fullName>
        </value>
        <value>
          <fullName>Oxivir</fullName>
        </value>
        <value>
          <fullName>Pastas/Barniz Nupro</fullName>
        </value>
        <value>
          <fullName>Practice Protect Instrument Disinfection &amp; Cleaning Liquid</fullName>
        </value>
        <value>
          <fullName>Practice Protect Spray</fullName>
        </value>
        <value>
          <fullName>Practice Protect Wipes</fullName>
        </value>
        <value>
          <fullName>Prophy</fullName>
        </value>
        <value>
          <fullName>PS2120 - Jet-Plus</fullName>
        </value>
        <value>
          <fullName>PS2130 - Plus</fullName>
        </value>
        <value>
          <fullName>PS2140 - Select SPS</fullName>
        </value>
        <value>
          <fullName>PS2150 - Bobcat 25K</fullName>
        </value>
        <value>
          <fullName>PS3300 - SLI/TFI 30K</fullName>
        </value>
        <value>
          <fullName>PS3400 - 25K</fullName>
        </value>
        <value>
          <fullName>Purevac Mirror Tip</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>track_event__c</fullName>
    <defaultValue>false</defaultValue>
    <description>can be used to track events individually by country</description>
    <inlineHelpText>check the box if you want to track this event</inlineHelpText>
    <label>track event</label>
    <type>Checkbox</type>
  </fields>
  <label>Call Report</label>
  <nameField>
    <displayFormat>CR-{0000}</displayFormat>
    <label>Call Report Number</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Call Reports</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CallReportExtension.cls
public class CallReportExtension {
public Id evId; 
public Event Ev{get;set;}  
    public CallReportExtension(ApexPages.StandardController Controller) {
        evId = System.currentPageReference().getParameters().get('id');
        system.debug(evId);
        ev = [SELECT Id, SBU__c, Subject, Call_Report__c,Call_Report__r.track_event__c, Call_Report__r.Call_Notes__c,Call_Report__r.Met_with_Decision_Maker__c, Call_Report__r.Met_with_Assistant__c, Call_Report__r.Placed_Order__c, Call_Report__r.Left_Sample__c, Call_Report__r.Courses__c, Call_Report__r.Products_discussed_ENDO__c, Call_Report__r.Products_discussed_IMPL__c,Call_Report__r.Products_discussed_ORTH__c,Call_Report__r.Products_discussed_PREV__c, Call_Report__r.Products_discussed_PROS__c,Call_Report__r.Products_discussed_REST__c,Call_Report__r.Products_discussed_CDCM__c, Call_Report__r.Products_discussed_INST__c,Call_Report__r.Products_discussed_TRCE__c,Call_Report__r.Products_discussed_IMAG__c,Call_Report__r.Other_SBU_discussed__c,Call_Report__r.Other_SBU_notes__c FROM Event WHERE Id = :evId LIMIT 1 ALL ROWS];
        
        system.debug(ev.Call_Report__r.Call_Notes__c);
    }
}