unpackaged/objects/Call_Report__c.object
<CustomObject>
  <fields>
    <fullName>Call_Notes__c</fullName>
    <label>Call Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
  </fields>
  <label>Call Report</label>
  <nameField>
    <displayFormat>CR-{0000}</displayFormat>
    <label>Call Report Number</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Call Reports</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/GlobalBypassProcessesSettings__c.object
<CustomObject>
  <customSettingsType>Hierarchy</customSettingsType>
  <description>Global Bypass Control Panel</description>
  <fields>
    <fullName>RunProcessBuilder__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Compatible Objects: Account, AccountMergeRequest, CallReport, CAmpaignMember, Campaign, Case, ontact, Contract, EmailMessage, Event, Expert, KOLInfo, LoyaltyProgramParticipant, OpporutnityTrigger, OrderItem, Order, ProgramParticipation, Lead</inlineHelpText>
    <label>Run All Process Builders</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>RunTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Compatible Objects: Account, AccountMergeRequest, CallReport, CAmpaignMember, Campaign, Case, ontact, Contract, EmailMessage, Event, Expert, KOLInfo, LoyaltyProgramParticipant, OpporutnityTrigger, OrderItem, Order, ProgramParticipation, Lead</inlineHelpText>
    <label>Run All Triggers</label>
    <type>Checkbox</type>
  </fields>
  <label>Global Bypass Processes Settings</label>
</CustomObject>

unpackaged/classes/Test_BatchSetEventDescription.cls
/**
 * @description       : test class for BatchSetEventDescription
 * @author            : kdoruibin@salesforce.com
 * @group             : 
 * @last modified on  : 05-10-2021
 * @last modified by  : kdoruibin@salesforce.com
 * Modifications Log 
 * Ver   Date         Author                     Modification
 * 1.0   05-10-2021   kdoruibin@salesforce.com   Initial Version
**/
@IsTest
public class Test_BatchSetEventDescription {
    
    @TestSetup
    static void makeData(){
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
        List<Event> testEventList = TestDataFactory.returnEvents(2, userList.get(0).Id);
        for (Event testEvent : testEventList) {
            testEvent.Customer_Facing_Event__c = true;
        }
        insert testEventList;
    }

    @IsTest
    private static void testBatchSetEventDescription() {
        GlobalBypassProcessesSettings__c existingbypassSettings = [Select Id from GlobalBypassProcessesSettings__c LIMIT 1];
        existingbypassSettings.RunTriggers__c = false;
        existingbypassSettings.RunProcessBuilder__c = false;
        update existingbypassSettings;
        
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        for (List<Call_Report__c> callReportList : [SELECT Id, Call_Notes__c FROM Call_Report__c]) {
            for (Call_Report__c callReport : callReportList) {
                callReport.Call_Notes__c = 'Test123';
            }
            update callReportList;
        }

        Test.startTest();
        BatchSetEventDescription batchJob = new BatchSetEventDescription(String.valueOf(System.today().year()));
        Database.executeBatch(batchJob);
        Test.stopTest();

        for (Event eventToTest : [SELECT Description, Call_Report__r.Call_Notes__c FROM Event WHERE CreatedByid = :testUser.Id]) {
            System.assertEquals(eventToTest.Call_Report__r.Call_Notes__c, eventToTest.Description);
        }
    }
}