unpackaged/objects/Call_Report__c.object
<CustomObject>
  <fields>
    <fullName>Call_Notes__c</fullName>
    <label>Call Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
  </fields>
  <fields>
    <fullName>Event_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Event ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
  </fields>
  <fields>
    <fullName>Met_with_Assistant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Met with Assistant</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Met_with_Decision_Maker__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Met with Decision Maker</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Other_SBU_Products_Discussed__c</fullName>
    <label>Other SBU Products Discussed</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Whoops</fullName>
        </value>
        <value>
          <fullName>These should have been loaded in by APEX</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Placed_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Placed Order</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Products_Discussed__c</fullName>
    <label>Products Discussed</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Whoops</fullName>
        </value>
        <value>
          <fullName>These should have been loaded in by APEX</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Call Report</label>
  <nameField>
    <displayFormat>CR-{0000}</displayFormat>
    <label>Call Report Number</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Call Reports</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CallReport.cls
public with sharing class CallReport {

    public CallReport(ApexPages.StandardController controller) {        
        string eventId = controller.getRecord().Id;
        
        if(eventId != null){
            List<Call_Report__c> callReports = [SELECT Id,
                                                    Call_Notes__c,
                                                    Met_with_Assistant__c,
                                                    Met_with_Decision_Maker__c,
                                                    Other_SBU_Products_Discussed__c,
                                                    Placed_Order__c,
                                                    Products_Discussed__c
                                                FROM Call_Report__c 
                                                WHERE event_id__c = :eventId 
                                                ORDER BY Id]; // order by to ensure that the order is deterministic
            
            if(!callReports.isEmpty()){
                CallReport = callReports[0];
            }            
        }
    }
    
    public boolean EventHasCallReport { get { return CallReport != null; } }
    public Call_Report__c CallReport { get; set; }
}