unpackaged/objects/Call_Report__c.object
<CustomObject>
  <fields>
    <fullName>ActivitySubtype__c</fullName>
    <description>200330 CFE 2.0</description>
    <label>Activity Subtype</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>ActivityType__c</controllingField>
      <restricted>true</restricted>
      <valueSetName>ActivitySubtype</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>ActivityType__c</fullName>
    <description>200330 CFE 2.0</description>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>ActivityType</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>EndDateTime__c</fullName>
    <description>200331 CFE 2.0</description>
    <label>End</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>EventWhoIds__c</fullName>
    <description>Test text field to hold EventWhoIds.</description>
    <label>EventWhoIds</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>ProductGroup__c</fullName>
    <description>200317 CFE 2.0 POC</description>
    <label>Product Group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>SBU_Full_Names</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>StartDateTime__c</fullName>
    <description>200324 test start datetime field to be used to populate Event.StartDateTime</description>
    <label>Start</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>Subject__c</fullName>
    <description>TFUS-000002466</description>
    <inlineHelpText>Leave the subject blank to have Salesforce use your default subject</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <label>Call Report</label>
  <nameField>
    <displayFormat>CR-{0000}</displayFormat>
    <label>Call Report Number</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Call Reports</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Field_Sales_Project_Members__c.object
<CustomObject>
  <description>Used to track targets for sales for specified initiatives based on target lists, regional initiatives, or customer interactions.</description>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Field_Sales_Project_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <label>Sales Lead</label>
  <nameField>
    <displayFormat>Ld-{0000000}</displayFormat>
    <label>LD ID</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Sales Leads</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET</businessProcess>
    <fullName>GET</fullName>
    <label>X DO NOT USE 2t</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/CallReportQuickActionPocController.cls
/**
 * @description       : Called by CallReportQuickActionPoc.js
 *                      Creates an Event as a CFE and relates it to the Created Call_Report__c record
 *                      that was created via the 'Report Event' action.
 * @author            : kdoruibin@salesforce.com
 * @group             : 
 * @last modified on  : 12-11-2020
 * @last modified by  : kdoruibin@salesforce.com
 * Modifications Log 
 * Ver   Date         Author                     Modification
 * 1.0   12-10-2020   kdoruibin@salesforce.com   Initial Version
**/
public with sharing class CallReportQuickActionPocController {
    @AuraEnabled
    public static String createEvent(Id callReportId, Id eventWhatId, String coTravel) {
        Call_Report__c callReport = [
            SELECT Id, StartDateTime__c, EndDateTime__c, ProductGroup__c, EventWhoIds__c, CreatedById, ActivityType__c, ActivitySubtype__c, Subject__c
            FROM Call_Report__c
            WHERE Id = :callReportId
        ];

        List<String> whoIdList = new List<String>();
        if (String.isNotBlank(callReport.EventWhoIds__c)) {
            whoIdList = (List<String>) JSON.deserialize(callReport.EventWhoIds__c, List<String>.class);
        }

        Address eventAddress;
        Contact eventContact;
        if (eventWhatId.getSobjectType() == Contact.sObjectType) {
            Id contactId = whoIdList.isEmpty() ? eventWhatId : whoIdList.get(0);
            eventContact = [SELECT AccountId, MailingAddress FROM Contact WHERE Id = :contactId];
            eventAddress = eventContact?.MailingAddress;
        } else if (eventWhatId.getSobjectType() == Lead.sObjectType) {
            eventAddress = [SELECT Address FROM Lead WHERE Id = :eventWhatId]?.Address;
        } else if (eventWhatId.getSobjectType() == Account.sObjectType) {
            eventAddress = [SELECT BillingAddress FROM Account WHERE Id = :eventWhatId]?.BillingAddress;
        } else if (eventWhatId.getSobjectType() == Opportunity.sObjectType) {
            eventAddress = [SELECT Account.BillingAddress FROM Opportunity WHERE Id = :eventWhatId]?.Account?.BillingAddress;
        } else if (eventWhatId.getSobjectType() == Order.sObjectType) {
            eventAddress = [SELECT Account.BillingAddress FROM Order WHERE Id = :eventWhatId]?.Account?.BillingAddress;
        } else if (eventWhatId.getSobjectType() == Field_Sales_Project_Members__c.sObjectType) {
            eventAddress = [SELECT Account__r.BillingAddress FROM Field_Sales_Project_Members__c WHERE Id = :eventWhatId]?.Account__r?.BillingAddress;
        }

        // List<String> whoIdList = (List<String>) JSON.deserialize(callReport.EventWhoIds__c, List<String>.class); //
        // Contact eventWho = [SELECT Id, AccountId, MailingStreet, MailingCity, MailingState, MailingCountry FROM Contact WHERE Id = :whoIdList[0]]; //
        String locationStringFormatted;
        if (eventAddress != null) {
            List<Object> locationParameters = new List<Object>{
                String.isNotBlank(eventAddress?.Street) ? eventAddress.Street : ''
                , String.isNotBlank(eventAddress?.City) ? ', ' + eventAddress.City : ''
                , String.isNotBlank(eventAddress?.State) ? ', ' + eventAddress.State : ''
                , String.isNotBlank(eventAddress?.Country) ? ', ' + eventAddress.Country : ''
            };
            locationStringFormatted = String.format('{0}{1}{2}{3}', locationParameters);
        }

        Event newEvent = new Event(
            Call_Report__c = callReportId
            , Customer_Facing_Event__c = true
            , OwnerId = callReport.CreatedById
            , WhoId = whoIdList.isEmpty() ? null : whoIdList.get(0)
            , WhatId = eventContact == null ? eventWhatId : eventContact.AccountId
            , IsAllDayEvent = false
            , StartDateTime = callReport.StartDateTime__c
            , EndDateTime = callReport.EndDateTime__c
            , SBU__c = callReport.ProductGroup__c
            , Astra_Tech_Type__c = callReport.ActivityType__c //'Cold Call'
            , Activity_Subtype__c = callReport.ActivitySubtype__c
            , Subject = callReport.Subject__c
            , Event_Status__c = 'Completed'
            , Location = locationStringFormatted
            ,Co_travel__c = coTravel
        );

        try {
            insert newEvent;
        } catch (Exception e) {
            DebugLog.addException(e, 'CallReportQuickActionPocController');
            throw new AuraHandledException(e.getMessage());
        }

        List<EventRelation> newEventRelationList = new List<EventRelation>();
        for (Id whoId : whoIdList) {
            if (whoId == newEvent.WhoId) continue;
            newEventRelationList.add(new EventRelation(
                EventId = newEvent.Id
                , RelationId = whoId
                , IsParent = true
                , IsWhat = false
            ));
        }

        try {
            insert newEventRelationList;
        } catch (Exception e) {
            DebugLog.addException(e, 'CallReportQuickActionPocController');
            throw new AuraHandledException(e.getMessage());
        }

        return newEvent.Id;
    }
    @AuraEnabled(cacheable=true)
    public static List<String> getPickListValuesIntoList(){
       List<String> pickListValuesList= new List<String>();
		Schema.DescribeFieldResult fieldResult = Event.Co_travel__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     
		return pickListValuesList;
    }
}