unpackaged/objects/Campaign.object
<CustomObject>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CampaignMember.object
<CustomObject>
  <fields>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
  </fields>
  <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
  <fields>
    <fullName>NA_Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>NA_Category__c</controllingField>
      <valueSetDefinition>
        <value>
          <fullName>3D Upgrade</fullName>
        </value>
        <value>
          <fullName>ACB with ASA</fullName>
        </value>
        <value>
          <fullName>AH Plus</fullName>
        </value>
        <value>
          <fullName>AH Temp</fullName>
        </value>
        <value>
          <fullName>AlginX</fullName>
        </value>
        <value>
          <fullName>All Ceramics</fullName>
        </value>
        <value>
          <fullName>All Other Endo</fullName>
        </value>
        <value>
          <fullName>All Other - Niti Rotary Files</fullName>
        </value>
        <value>
          <fullName>All Other – Obturation</fullName>
        </value>
        <value>
          <fullName>Anaestadent</fullName>
        </value>
        <value>
          <fullName>Ancillary</fullName>
        </value>
        <value>
          <fullName>ANKYLOS</fullName>
        </value>
        <value>
          <fullName>Apex Locator</fullName>
        </value>
        <value>
          <fullName>Aquasil</fullName>
        </value>
        <value>
          <fullName>Aquasil Ultra Plus</fullName>
        </value>
        <value>
          <fullName>ATIS</fullName>
        </value>
        <value>
          <fullName>ATIS EV</fullName>
        </value>
        <value>
          <fullName>ATIS TX</fullName>
        </value>
        <value>
          <fullName>Atlantis</fullName>
        </value>
        <value>
          <fullName>Atlantis Abutments</fullName>
        </value>
        <value>
          <fullName>Atlantis Suprastructures</fullName>
        </value>
        <value>
          <fullName>Automate</fullName>
        </value>
        <value>
          <fullName>Axeos</fullName>
        </value>
        <value>
          <fullName>Azento Astra Tech</fullName>
        </value>
        <value>
          <fullName>Azento EV</fullName>
        </value>
        <value>
          <fullName>Azento XiVE</fullName>
        </value>
        <value>
          <fullName>Bioceramic</fullName>
        </value>
        <value>
          <fullName>Bluecam</fullName>
        </value>
        <value>
          <fullName>Bonding</fullName>
        </value>
        <value>
          <fullName>Bone</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>NA_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>User_Country__c</controllingField>
      <valueSetDefinition>
        <value>
          <fullName>3D Imaging</fullName>
        </value>
        <value>
          <fullName>ATLANTIS</fullName>
        </value>
        <value>
          <fullName>CEREC Equipment</fullName>
        </value>
        <value>
          <fullName>Consumables</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Solutions</fullName>
        </value>
        <value>
          <fullName>Endentulous</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Extra Oral Imaging</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>InLab</fullName>
        </value>
        <value>
          <fullName>Intra Oral Imaging</fullName>
        </value>
        <value>
          <fullName>Midwest Equipment</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Regenerative</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET</businessProcess>
    <fullName>GET</fullName>
    <label>X DO NOT USE 2t</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/OpportunityInsertAsynch.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Ahmed LOUDRASSI (Salesforce) 20191022
Description:    Opportunity Insert Asynch Class
History

20210318   Roberto Narbona		 Updated to send opp ID back into Opportunity__c field for Campaign Members and have physical relationship. Story TFUS-000002828
20210318   Roberto Narbona		 Added DebugLog line if insert fails. TFUS-000003578
----------------------------------------------------------------------------------------*/


public class OpportunityInsertAsynch implements Queueable {

    private List<CampaignMemberTriggerHelper.oppWrapper> opportunities;

    public OpportunityInsertAsynch(List<CampaignMemberTriggerHelper.oppWrapper> records) {
        this.opportunities = records;

    }

    public void execute(QueueableContext context) {

        Map<Id,Opportunity> memberIdWithOpp =new Map<Id,Opportunity>();

        List<CampaignMember>  campaignMemberToUpdateList =new List<CampaignMember>();

        //Check for already existing opportunities towards the related accounts

        Set<Id> accountIds = new Set<Id>();

        for(CampaignMemberTriggerHelper.oppWrapper opportunityWrapper : opportunities){
            Opportunity opp = opportunityWrapper.opp;
            accountIds.add(opp.AccountId);
        }

        Map<Id, List<Opportunity>> oppMap = new Map<Id, List<Opportunity>>();
        Map<Id, String> cmsWithExistingOpps = new Map<Id, String>();
        
        List<Account> accOpps = [SELECT Id, (SELECT Id, Name, StageName, NA_Category__c, NA_Brand__c FROM Opportunities WHERE IsClosed = FALSE) FROM Account WHERE Id IN: accountIds];
                
        for(Account a : accOpps){
            oppMap.put(a.Id, a.Opportunities);
        }

        //Loop all opportunities to create
        for (CampaignMemberTriggerHelper.oppWrapper opportunity : opportunities) {
            
            Opportunity opp = opportunity.opp;
            List<OpportunityTeamMember> oppMembers = opportunity.oppMembers;


            //Check for existing open opportunities
            List<Opportunity> existingOpps = oppMap.get(opp.AccountId);

            Boolean matchExists = false;

            for(Opportunity existingOpp : existingOpps){
                System.debug('Existing opp: ' + existingOpp);
                if(existingOpp.NA_Brand__c == opp.NA_Brand__c){
                    matchExists = true;
                    cmsWithExistingOpps.put(opportunity.CampaignMemberIdUpdate, existingOpp.Id);
                }
            }

            //Create opportunity if no open opportunity is found
            if(matchExists == false){

                    memberIdWithOpp.put(opportunity.CampaignMemberIdUpdate,opportunity.opp); //populating member ID with opportunity map

                    try{
                        insert opp;
                    }
                    catch(Exception e){
                        DebugLog.addException(e, 'OpportunityInsertAsynch class. Opportunity not created after responded campaign member');
                		System.debug(e);
                    }

                    for(OpportunityTeamMember oppMember : oppMembers){
                        oppMember.OpportunityId = opp.Id;
                    }

                    try{
                        insert oppMembers;
                    }
                    catch(Exception e){
                        DebugLog.addException(e, 'OpportunityInsertAsynch class. oppMembers not created after responded campaign member');
                        System.debug(e);
                    }

            }
            
        } 
        //identifying campaign members to update, assigning the right opportunity ID and updating the record.

        System.debug('Members with existing opportunity: ' + cmsWithExistingOpps);

        for(CampaignMember campaignMemberToUpdate : [SELECT ID, Opportunity__c FROM CampaignMember WHERE Id IN: cmsWithExistingOpps.keySet()]){ 
            campaignMemberToUpdate.Opportunity__c = cmsWithExistingOpps.get(campaignMemberToUpdate.Id);
            campaignMemberToUpdateList.add(campaignMemberToUpdate);
        }
        
        for(CampaignMember campaignMemberToUpdate :[SELECT ID, Opportunity__c FROM CampaignMember WHERE Id IN: memberIdWithOpp.keySet()]){
            campaignMemberToUpdate.Opportunity__c = memberIdWithOpp.get(campaignMemberToUpdate.Id).Id;
            campaignMemberToUpdateList.add(campaignMemberToUpdate);
        }
        if(campaignMemberToUpdateList.size()>0){	
            try{
                update campaignMemberToUpdateList;
            }
            catch(Exception e){
                DebugLog.addError(e.getMessage());
            }
        }  
    }
}