unpackaged/objects/Campaign.object
<CustomObject>
  <fields>
    <fullName>Profession__c</fullName>
    <inlineHelpText>Add the type of contacts that is the target of this campaign</inlineHelpText>
    <label>Target Contacts</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Clinical Manager</fullName>
        </value>
        <value>
          <fullName>Dental Assistant</fullName>
        </value>
        <value>
          <fullName>Dental Student</fullName>
        </value>
        <value>
          <fullName>Dental Technician</fullName>
        </value>
        <value>
          <fullName>Denturist</fullName>
        </value>
        <value>
          <fullName>Doctor</fullName>
        </value>
        <value>
          <fullName>Endodontist</fullName>
        </value>
        <value>
          <fullName>Faculty/Instructor/Professor</fullName>
        </value>
        <value>
          <fullName>General Dentist</fullName>
        </value>
        <value>
          <fullName>General Manager</fullName>
        </value>
        <value>
          <fullName>General surgeon</fullName>
        </value>
        <value>
          <fullName>Head Nurse</fullName>
        </value>
        <value>
          <fullName>Head of Hospital</fullName>
        </value>
        <value>
          <fullName>Hygienist/Infection control</fullName>
        </value>
        <value>
          <fullName>Implant Manager</fullName>
        </value>
        <value>
          <fullName>Implantologist</fullName>
        </value>
        <value>
          <fullName>Lab Manager</fullName>
        </value>
        <value>
          <fullName>Lab Owner</fullName>
        </value>
        <value>
          <fullName>Marketing</fullName>
        </value>
        <value>
          <fullName>Maxillofasial surgeon</fullName>
        </value>
        <value>
          <fullName>Nurse</fullName>
        </value>
        <value>
          <fullName>Oral Radiologist</fullName>
        </value>
        <value>
          <fullName>Oral surgeon</fullName>
        </value>
        <value>
          <fullName>Orthodontist</fullName>
        </value>
        <value>
          <fullName>Other staff Dental</fullName>
        </value>
        <value>
          <fullName>Owner</fullName>
        </value>
        <value>
          <fullName>Pediodontist</fullName>
        </value>
        <value>
          <fullName>Periodontist</fullName>
        </value>
        <value>
          <fullName>Pharmacist</fullName>
        </value>
        <value>
          <fullName>Plastic surgeon</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>SBU_Focus__c</fullName>
    <description>Used to track which SBU the Campaigns target for promotion/training.</description>
    <inlineHelpText>Pick the SBU(s) that this Campaign targets for promotion/training.</inlineHelpText>
    <label>SBU</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
        <value>
          <fullName>Imaging Systems</fullName>
        </value>
        <value>
          <fullName>Instruments</fullName>
        </value>
        <value>
          <fullName>US Consumables</fullName>
        </value>
        <value>
          <fullName>Maillefer</fullName>
        </value>
        <value>
          <fullName>Midwest</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Session_End_Date_Time__c</fullName>
    <description>Used by HQ T&amp;E</description>
    <label>Session End Date &amp; Time</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>Session_Start_Date_Time__c</fullName>
    <description>Use by HQ T&amp;E</description>
    <label>Session Start Date &amp; Time</label>
    <type>DateTime</type>
  </fields>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>HQ</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Luxembourg</fullName>
        </value>
        <value>
          <fullName>New Zealand</fullName>
        </value>
        <value>
          <fullName>Norway</fullName>
        </value>
        <value>
          <fullName>Poland</fullName>
        </value>
        <value>
          <fullName>Portugal</fullName>
        </value>
        <value>
          <fullName>South Africa</fullName>
        </value>
        <value>
          <fullName>Spain</fullName>
        </value>
        <value>
          <fullName>Sweden</fullName>
        </value>
        <value>
          <fullName>Switzerland</fullName>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
        <value>
          <fullName>Ukraine</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <defaultValue>CASE($User.User_Country__c,  
"Australia","Australia",
"Austria","Austria",
"Belarus","Belarus",
"Belgium","Belgium",
"Brazil","Brazil",
"Canada", "Canada",
"China","China",
"Denmark","Denmark",
"Finland","Finland",
"France","France",
"Germany","Germany",
"Holland","Holland",
"Hong Kong","Hong Kong",
"India","India",
"Indonesia","Indonesia",
"Italy","Italy",
"Japan","Japan",
"Kazakhstan","Kazakhstan",
"Luxembourg","Luxembourg",
"Malaysia","Malaysia",
"New Zealand","New Zealand",
"Norway","Norway",
"Philippines","Philippines",
"Portugal","Portugal",
"Poland","Poland",
"Russia","Russia",
"Saudi Arabia","Saudi Arabia",
"Singapore","Singapore",
"Slovakia","Slovakia",
"South Africa","South Africa",
"South Korea","South Korea",
"Spain","Spain",
"Sweden","Sweden",
"Switzerland","Switzerland",
"Taiwan","Taiwan",
"Thailand","Thailand",
"Turkey","Turkey",
"UAE","UAE",
"UK", "UK",
"Ukraine", "Ukraine",
"USA","USA",
"Vietnam","Vietnam",
"HQ: SE")</defaultValue>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ: SE</fullName>
        </value>
        <value>
          <fullName>Hungary</fullName>
        </value>
        <value>
          <fullName>India</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Ireland</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Jordan</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Kuwait</fullName>
        </value>
        <value>
          <fullName>Latvia</fullName>
        </value>
        <value>
          <fullName>Lithuania</fullName>
        </value>
        <value>
          <fullName>Luxembourg</fullName>
        </value>
        <value>
          <fullName>Malaysia</fullName>
        </value>
        <value>
          <fullName>Malta</fullName>
        </value>
        <value>
          <fullName>New Zealand</fullName>
        </value>
        <value>
          <fullName>Sweden</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>true</active>
    <businessProcess>DENTAL</businessProcess>
    <fullName>DENTAL</fullName>
    <label>X DO NOT USE 1</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET</businessProcess>
    <fullName>GET</fullName>
    <label>X DO NOT USE 2t</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>FieldSalesRatioPerc__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Describes if the user should be counted as a full-time sales rep(100%) or not. 
Example 1: If a rep is only working as a sales rep for 50% of the time and has other dutys or is only working part time, add 50% in this field. 
Example 2. If a manager is also workin 25% with field sales (equivalent as a sales rep) add 25% in this field.

Note that Administration time should not be deducted from this field</description>
    <inlineHelpText>Describes if the user should be counted as a full-time sales rep (100%) or a part-time sales rep (for example 50%).

Note that administrative time should not be deducted.</inlineHelpText>
    <label>Field Sales Ratio (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_CERE__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA CAD/CAM CEREC</description>
    <inlineHelpText>SIRONA CAD/CAM CEREC</inlineHelpText>
    <label>SBU Ratio (CDCM)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_ENDO__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (ENDO)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_IMAG__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA Imaging systems Intra &amp; Extra Oral</description>
    <inlineHelpText>SIRONA Imaging systems Intra &amp; Extra Oral</inlineHelpText>
    <label>SBU Ratio (IMAG)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_IMPL__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (IMPL)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_INST__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA Instruments</description>
    <inlineHelpText>SIRONA Instruments</inlineHelpText>
    <label>SBU Ratio (INST)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_ORTH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (ORTH)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_PREV__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (PREV)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_PROS__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (PROS)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_REST__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (REST)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Type__c</fullName>
    <inlineHelpText>Sales Representative  = District Managers, Territory Managers, Account Managers

Sales Manager = Regional Sales Mgrs, Division Sales Mgrs, National Sales Mgrs</inlineHelpText>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Account Maintenance Team Member</fullName>
        </value>
        <value>
          <fullName>Area Sales Manager</fullName>
        </value>
        <value>
          <fullName>Clinical Affairs</fullName>
        </value>
        <value>
          <fullName>Complaints Handling</fullName>
        </value>
        <value>
          <fullName>Customer Service</fullName>
        </value>
        <value>
          <fullName>Finance</fullName>
        </value>
        <value>
          <fullName>Inside Sales Representative</fullName>
        </value>
        <value>
          <fullName>Key Account Manager</fullName>
        </value>
        <value>
          <fullName>Managing Director</fullName>
        </value>
        <value>
          <fullName>Marketing</fullName>
        </value>
        <value>
          <fullName>National Admin</fullName>
        </value>
        <value>
          <fullName>Operations</fullName>
        </value>
        <value>
          <fullName>Other</fullName>
        </value>
        <value>
          <fullName>Product Manager</fullName>
        </value>
        <value>
          <fullName>Regional Sales Manager</fullName>
        </value>
        <value>
          <fullName>Sales Manager</fullName>
        </value>
        <value>
          <fullName>Sales Representative</fullName>
        </value>
        <value>
          <fullName>Training &amp; Event Management</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/newCampaignOverrideTest.cls
@isTest
public class newCampaignOverrideTest {
   
        public static testMethod void newCampaignOverride() {
            //create test user
            profile p = [SELECT Id From profile Where Name = '#System: System Administrator'];
            userrole r = [SELECT Id From UserRole Where Name = 'System Administrators'];
//            Account a = new Account(Name='Test Acc');
            Campaign c = new Campaign();
//            Contact c = new Contact (LastName='Test Atl Acc');
            user u = new User(  firstname = 'tuserFname',
                              lastName = 'tuserLastname',
                              email = 'testtest.testtest@dentsplysirona.com',
                              Username = 'testtesttesttest@dentsplysirona.com',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias ='ttest',
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'sv_SE',
                              LanguageLocaleKey = 'en_US',
                              User_Type__c = 'Other',
                              User_Country__c = 'Sweden',
                              CurrencyIsoCode = 'SEK',
                              ProfileId = p.Id,
                              UserRoleId = r.Id,
                              FieldSalesRatioPerc__c = 0,
                              SBU_Ratio_PREV__c = 0.1,
                              SBU_Ratio_REST__c = 0.2,
                              SBU_Ratio_CERE__c = 0.3,
                              SBU_Ratio_IMAG__c = 0.4,
                              SBU_Ratio_INST__c = 0);
            system.runAs(u){
         Test.startTest(); //switch to testing context
                PageReference pageRef = Page.newCampaignOverridePage; //create a page reference to our Visualforce page
                pageRef.getparameters().put('LinkOrder', 'Program'); 
                Test.setCurrentPage(pageRef);
                
                Apexpages.StandardController sc = new Apexpages.StandardController(c);
                newCampaignOverride ext = new  newCampaignOverride(sc);
                
         
                PageReference pageRef2 = Page.newCampaignOverridePage; //create a page reference to our Visualforce page
                pageRef2.getparameters().put('LinkOrder', 'Trade'); 
                Test.setCurrentPage(pageRef2);
                
               
                newCampaignOverride ext2 = new  newCampaignOverride(sc);
                
                          
                PageReference pageRef4 = Page.newCampaignOverridePage; //create a page reference to our Visualforce page
                pageRef4.getparameters().put('LinkOrder', 'Sponsorship'); 
                Test.setCurrentPage(pageRef4);
                
                Apexpages.StandardController sc4 = new Apexpages.StandardController(c);
                newCampaignOverride ext4 = new  newCampaignOverride(sc4);
                
                PageReference pageRef5 = Page.newCampaignOverridePage; //create a page reference to our Visualforce page
                pageRef5.getparameters().put('RecordType', '01220000000Ax7r'); 
                Test.setCurrentPage(pageRef5);
                
               Apexpages.StandardController sc5 = new Apexpages.StandardController(c);
                newCampaignOverride ext5 = new  newCampaignOverride(sc5);
                
            Test.stopTest(); //revert back to normal context
            }
        }
    public static testMethod void newCampaignOverride2() {
            //create test user
            profile p = [SELECT Id From profile Where Name = '#System: System Administrator'];
            userrole r = [SELECT Id From UserRole Where Name = 'System Administrators'];
//            Account a = new Account(Name='Test Acc');
            Campaign c = new Campaign();
//            Contact c = new Contact (LastName='Test Atl Acc');
            user u = new User(  firstname = 'tuserFname',
                              lastName = 'tuserLastname',
                              email = 'testtest.testtest@dentsplysirona.com',
                              Username = 'testtesttesttest@dentsplysirona.com',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias ='ttest',
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'sv_SE',
                              LanguageLocaleKey = 'en_US',
                              User_Type__c = 'Other',
                              User_Country__c = 'Sweden',
                              CurrencyIsoCode = 'SEK',
                              ProfileId = p.Id,
                              UserRoleId = r.Id,
                              FieldSalesRatioPerc__c = 0,
                              SBU_Ratio_IMPL__c = 0.1,
                              SBU_Ratio_ENDO__c = 0.2,
                              SBU_Ratio_ORTH__c = 0.3,
                              SBU_Ratio_PROS__C = 0.4,
                              SBU_Ratio_IMAG__c = 0);
            system.runAs(u){
         Test.startTest(); //switch to testing context
                
                PageReference pageRef4 = Page.newCampaignOverridePage; //create a page reference to our Visualforce page
                pageRef4.getparameters().put('LinkOrder', 'Sponsorship'); 
                Test.setCurrentPage(pageRef4);
                
                Apexpages.StandardController sc4 = new Apexpages.StandardController(c);
                newCampaignOverride ext4 = new  newCampaignOverride(sc4);
                
                PageReference pageRef5 = Page.newCampaignOverridePage; //create a page reference to our Visualforce page
                pageRef5.getparameters().put('RecordType', '01220000000Ax7r'); 
                Test.setCurrentPage(pageRef5);
                
                //Apexpages.StandardController sc5 = new Apexpages.StandardController(c);
                newCampaignOverride ext5 = new  newCampaignOverride(sc4);
                
            Test.stopTest(); //revert back to normal context
            }
        }
        public static testMethod void newCampaignOverride3() {
            //create test user
            profile p = [SELECT Id From profile Where Name = '#System: System Administrator'];
            userrole r = [SELECT Id From UserRole Where Name = 'System Administrators'];
            Campaign c = new Campaign();
            Account a = new Account(Name='Test Acc');
            Campaign ca = new Campaign (Name='Test Campaign', Session_Start_Date_Time__c=datetime.now(), Session_End_Date_Time__c=datetime.now(), SBU_Focus__c= 'Implants', 
                                       Profession__c='Doctor', Target_Country__c ='Chile', Target_Group__c='Lab', Target_Type__c ='Dental Technician',Strategy__c='All');
            user u = new User(  firstname = 'tuserFname',
                              lastName = 'tuserLastname',
                              email = 'testtest.testtest@dentsplysirona.com',
                              Username = 'testtesttesttest@dentsplysirona.com',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias ='ttest',
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'sv_SE',
                              LanguageLocaleKey = 'en_US',
                              User_Type__c = 'Other',
                              User_Country__c = 'Sweden',
                              CurrencyIsoCode = 'SEK',
                              ProfileId = p.Id,
                              UserRoleId = r.Id,
                              FieldSalesRatioPerc__c = 0,
                              SBU_Ratio_IMPL__c = 0.1,
                              SBU_Ratio_INST__c = 0.4,
                              SBU_Ratio_TRCE__c = 0.5,
                              SBU_Ratio_PROS__C = 0,
                              SBU_Ratio_IMAG__c = 0);
            system.runAs(u){
               //create account
            	insert(a);
            //create contact
            	ca.venue__c=a.Id;
            	insert(ca);
         Test.startTest(); //switch to testing context
                
                PageReference pageRef6 = Page.newCampaignOverridePage; //create a page reference to our Visualforce page
                pageRef6.getparameters().put('LinkOrder', ca.Id); 
                Test.setCurrentPage(pageRef6);
                system.debug(pageref6);
                Apexpages.StandardController sc6 = new Apexpages.StandardController(c);
                newCampaignOverride ext6 = new  newCampaignOverride(sc6);
                ext6.SBU();
                ext6.cancel1();
                
                
                
            Test.stopTest(); //revert back to normal context
            }
        }

}



/*
private class newCampaignOverrideTest {
    //newCampaignOverride.class
    static testMethod void newCampaignOverride() {
        //create test user
        profile p = [SELECT Id From profile Where Name = '#System: System Administrator'];
        userrole r = [SELECT Id From UserRole Where Name = 'System Administrators'];
        
        user u = new User(  firstname = 'tuserFname',
                            lastName = 'tuserLastname',
                            email = 'testtest.testtest@dentsplysirona.com',
                            Username = 'testtesttesttest@dentsplysirona.com',
                            EmailEncodingKey = 'ISO-8859-1',
                            Alias ='ttest',
                            TimeZoneSidKey = 'America/Los_Angeles',
                            LocaleSidKey = 'sv_SE',
                            LanguageLocaleKey = 'en_US',
                            User_Type__c = 'Other',
                            User_Country__c = 'Sweden',
                            CurrencyIsoCode = 'SEK',
                            ProfileId = p.Id,
                            UserRoleId = r.Id,
                            FieldSalesRatioPerc__c = 0,
                            SBU_Ratio_IMPL__c = 0.2,
                            SBU_Ratio_ENDO__c = 0.1,
                            SBU_Ratio_ORTH__c = 0.1,
                            SBU_Ratio_PROS__C = 0.2,
                            SBU_Ratio_IMAG__c = 0.4);
        Test.startTest(); //switch to testing context
        system.runAs(u){
        
        PageReference pageRef = Page.newCampaignOverridePage; //create a page reference to our Visualforce page
        Test.setCurrentPage(pageRef); //set the current page to that page
        ApexPages.StandardController standardController = new ApexPages.standardController(new Campaign()); //instantiate the standard controller for the Opportunity object
        newCampaignOverride ext = new newCampaignOverride(standardController); //construct the extension
        
        //pass some parameters to the page
        pageRef.getParameters().put('save_new', '1'); //set save_new key value pair
        pageRef.getParameters().put('save', '1'); //set save key value pair
        
        //execute the logic
        String validationURLString = ext.prepopulateValues().getURL(); //get the resulting url from the prepopulateValues method
        
        //validate the results
        System.assertEquals(true, validationURLString.toLowerCase().contains('nooverride=1')); //string contains the nooverride key value pair
        //System.assertEquals(true, validationURLString.contains('CF00N20000003jCk8='+u.FirstName)); //string contains the campaign coordinator key value pair
        //System.assertEquals(true, validationURLString.contains('CF00N20000003jCk8_lkid='+u.Id)); //string contains the campaign coordinator lookup ID key value pair
        System.assertEquals(true, validationURLString.contains('cpn5='+Date.Today().format())); //string contains the start date key value pair
        System.assertEquals(true, validationURLString.contains('cpn6='+Date.Today().format())); //string contains the end date key value pair
        System.assertEquals(true, validationURLString.contains('00N20000002oaCI='+u.User_Country__c)); //string contains the campaign country key value pair
        System.assertEquals(true, validationURLString.contains('00N2000000153o1='+u.User_Country__c)); //string contains the country key value pair
        System.assertEquals(true, validationURLString.contains('00N20000003jRJR='+u.User_Country__c)); //string contains the target country key value pair
        System.assertEquals(true, validationURLString.contains('00N0J000003rWNf='+'Imaging+Systems')); //string contains the SBU value = Imaging Systems
        System.assertEquals(true, validationURLString.contains('/701/e')); //string contains the new Opportunity URL
        System.assertEquals(false, validationURLString.toLowerCase().contains('save_new=1')); //string doesn't contain save_new=1
        System.assertEquals(false, validationURLString.toLowerCase().contains('save=1')); //string doesn't contain save=1
        }
        Test.stopTest(); //revert back to normal context
    }

}*/