unpackaged/objects/Campaign.object
<CustomObject>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CampaignMember.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</description>
    <inlineHelpText>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members (Account)</relationshipLabel>
    <relationshipName>Campaign_Members2</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Full_Name__c</fullName>
    <formula>IF( ISBLANK(TEXT(Contact.Salutation)), FirstName &amp; " " &amp; LastName , TEXT(Contact.Salutation)  &amp; " " &amp; FirstName &amp; " " &amp; LastName )</formula>
    <label>Full Name</label>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

unpackaged/classes/CampaignMemberController.cls
/*------------------------------------------------------------	
Author: 	Richard Trum (Glimt) 2019-10-09 	
Description:   	Campaign Member handler class, used mainly for handling the LC CampaignMembersEdit
------------------------------------------------------------*/

public class CampaignMemberController {
	@AuraEnabled
    Public static List<CampaignMember> getMemberList(Id recordId){

        List<CampaignMember> conList = [SELECT Id, Full_Name__c, Account__r.Name, Phone, Email, CampaignId, Status 
                                        FROM CampaignMember 
                                        WHERE CampaignId =: recordId];
        return conList;
    }
    
    
}