unpackaged/objects/Campaign.object
<CustomObject>
  <fields>
    <fullName>SBU_Focus__c</fullName>
    <description>Used to track which SBU the Campaigns target for promotion/training.</description>
    <inlineHelpText>Pick the SBU(s) that this Campaign targets for promotion/training.</inlineHelpText>
    <label>SBU</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
        <value>
          <fullName>Imaging Systems</fullName>
        </value>
        <value>
          <fullName>Instruments</fullName>
        </value>
        <value>
          <fullName>US Consumables</fullName>
        </value>
        <value>
          <fullName>Maillefer</fullName>
        </value>
        <value>
          <fullName>Midwest</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/FakeTests.cls
@isTest
private class FakeTests {
    static testMethod void Fake_Test(){
        Campaign c = new Campaign(Name = 'Test Campaign');
		c.SBU_Focus__c = 'Implants';        
        insert c;
        
        Account a = new Account(Name = 'Test Account');        
        insert a;
        
        BatchException be = new BatchException();
        
        Contact contact = new Contact(FirstName = 'Test', LastName = 'Test'); 
        insert contact;
        Event e = new Event(
			Subject = 'Test', 
			StartDateTime = datetime.now(), 
			EndDateTime = datetime.now().addMinutes(60), 
			WhoId = contact.Id,
			SBU__c = 'Endodontics');

        insert e;        
        ApexPages.StandardController standardController = new ApexPages.StandardController(e);
        CallReport sut = new CallReport(standardController);        
        sut.CallReport = sut.CallReport;
        boolean x = sut.EventHasCallReport;
        
        
        InviteesController inviteesController = new InviteesController();
        inviteesController.EventId = e.Id;
        List<InviteesController.Invitee> invitees = inviteesController.Invitees;        
        
        inviteesController = new InviteesController();
        inviteesController.EventId = e.Id;
        inviteesController.SeedIDs = contact.Id;
        invitees = inviteesController.Invitees;  
        
        EventRelationPickerState erps = new EventRelationPickerState();
        erps.EventId = e.Id;
        erps.ForInvitees = true;
        erps.StringRepresentation = contact.Id;
        
        List<EventRelationPickerState.EventRelationVM> ervms = erps.EventRelationVMs;
        
        //erps.Save();
        
        
        ApexPages.currentPage().getParameters().put('who_id',contact.Id);
        EventWithCallReport ewcr = new EventWithCallReport(standardController);
        ewcr.Event = e;
        ewcr.InviteesPickerState = erps;
        ewcr.SaveCallReport();
    }
}