unpackaged/objects/Campaign.object
<CustomObject>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN.</description>
    <fullName>DI_Campaign</fullName>
    <label>Course/Event/Exhibition</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN SESSION, related to a CAMPAIGN.</description>
    <fullName>DI_Campaign_Session</fullName>
    <label>Campaign Session</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CampaignMember.object
<CustomObject>
  <fields>
    <fullName>Full_Name__c</fullName>
    <formula>IF( ISBLANK(TEXT(Contact.Salutation)), FirstName &amp; " " &amp; LastName , TEXT(Contact.Salutation)  &amp; " " &amp; FirstName &amp; " " &amp; LastName )</formula>
    <label>Full Name</label>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Full_Name__c</fullName>
    <description>Used instead of having to add First and Last Name when grouping in report</description>
    <formula>FirstName &amp; " " &amp; LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula field</inlineHelpText>
    <label>Full Name</label>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Session_Participant__c.object
<CustomObject>
  <description>Used for adding participants in sessions. Initially for Germany only</description>
  <fields>
    <fullName>CampaignMemberId__c</fullName>
    <label>Campaign Member ID</label>
    <length>18</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Sessions</relationshipLabel>
    <relationshipName>Session_Participants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Session Participants</relationshipLabel>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <label>Session Participant</label>
  <nameField>
    <label>Session Participant Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Session Participants</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CampMgmtParticipantTriggerTest.cls
@isTest
private class CampMgmtParticipantTriggerTest
{
	static testmethod void insertTest01()
	{
        Campaign campaign = CampMgmtTestHelpers.createTestCampaign('Test Campaign 1', 'DI_Campaign');      
        Campaign session = CampMgmtTestHelpers.createTestSession(campaign.Id, 'Test Session 1', 'DI_Campaign_Session');
        Account account = CampMgmtTestHelpers.createTestAccount('Test Account 1');
        Contact contact = CampMgmtTestHelpers.createTestContact(account.Id, 'Testis', 'Testisson', 'email@email.com');
		CampaignMember campaignMember = CampMgmtTestHelpers.createTestCampaignMember(campaign.Id, contact.Id, 'Confirmed');

		Session_Participant__c sessionParticipant = new Session_Participant__c();
		sessionParticipant.Session__c = session.Id;
		sessionParticipant.Contact__c = contact.Id;
		// Deliberately NOT setting the CampaignMemberId__c field! 
		sessionParticipant.Name = contact.Full_Name__c;
		insert sessionParticipant;

		sessionParticipant =
		[
			SELECT CampaignMemberId__c
			FROM Session_Participant__c
			WHERE Id = :sessionParticipant.Id
			LIMIT 1
		][0];

		System.assertEquals(campaignMember.Id, sessionParticipant.CampaignMemberId__c);
	}
}