unpackaged/objects/Campaign.object
<CustomObject>
  <fields>
    <fullName>Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Campaign_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Campaign_Region_DE__c</fullName>
    <description>Field used in Germany and France to be able to track campaigns per region (not always the same as cost unit).</description>
    <label>Campaign Region</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>Campaign_Country__c</controllingField>
      <valueSetDefinition>
        <value>
          <fullName>CENTRAL CA</fullName>
        </value>
        <value>
          <fullName>EAST CA</fullName>
        </value>
        <value>
          <fullName>WEST CA</fullName>
        </value>
        <value>
          <fullName>Centro Nord</fullName>
        </value>
        <value>
          <fullName>Centro Sud</fullName>
        </value>
        <value>
          <fullName>Chubu</fullName>
        </value>
        <value>
          <fullName>Clinical 11</fullName>
        </value>
        <value>
          <fullName>Clinical 12</fullName>
        </value>
        <value>
          <fullName>Clinical 13</fullName>
        </value>
        <value>
          <fullName>Clinical 14</fullName>
        </value>
        <value>
          <fullName>Clinical 15</fullName>
        </value>
        <value>
          <fullName>Clinical 21</fullName>
        </value>
        <value>
          <fullName>Clinical 22</fullName>
        </value>
        <value>
          <fullName>Clinical 23</fullName>
        </value>
        <value>
          <fullName>Clinical 24</fullName>
        </value>
        <value>
          <fullName>Clinical 25</fullName>
        </value>
        <value>
          <fullName>Clinical 31</fullName>
        </value>
        <value>
          <fullName>Clinical 32</fullName>
        </value>
        <value>
          <fullName>Clinical 33</fullName>
        </value>
        <value>
          <fullName>Clinical 34</fullName>
        </value>
        <value>
          <fullName>Digital Mid</fullName>
        </value>
        <value>
          <fullName>Digital North</fullName>
        </value>
        <value>
          <fullName>Digital South</fullName>
        </value>
        <value>
          <fullName>Kansai</fullName>
        </value>
        <value>
          <fullName>Kita-Kanto/Tohoku</fullName>
        </value>
        <value>
          <fullName>Kyushu</fullName>
        </value>
        <value>
          <fullName>Minami-Kanto</fullName>
        </value>
        <value>
          <fullName>Nord Est</fullName>
        </value>
        <value>
          <fullName>Nord Ovest</fullName>
        </value>
        <value>
          <fullName>Région Est</fullName>
        </value>
        <value>
          <fullName>All</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Organizing Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>ALL</fullName>
        </value>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>BEX</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Distributor Markets</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ: DE</fullName>
        </value>
        <value>
          <fullName>HQ: NL</fullName>
        </value>
        <value>
          <fullName>HQ: SE</fullName>
        </value>
        <value>
          <fullName>INDIA</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Korea</fullName>
        </value>
        <value>
          <fullName>Luxembourg</fullName>
        </value>
        <value>
          <fullName>Malaysia</fullName>
        </value>
        <value>
          <fullName>New Zealand</fullName>
        </value>
        <value>
          <fullName>Norway</fullName>
        </value>
        <value>
          <fullName>Philippines</fullName>
        </value>
        <value>
          <fullName>Poland</fullName>
        </value>
        <value>
          <fullName>Portugal</fullName>
        </value>
        <value>
          <fullName>Russia</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>SBU_Focus__c</fullName>
    <description>Used to track which SBU the Campaigns target for promotion/training.</description>
    <inlineHelpText>Pick the SBU(s) that this Campaign targets for promotion/training.</inlineHelpText>
    <label>SBU</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
        <value>
          <fullName>Imaging Systems</fullName>
        </value>
        <value>
          <fullName>Instruments</fullName>
        </value>
        <value>
          <fullName>US Consumables</fullName>
        </value>
        <value>
          <fullName>Maillefer</fullName>
        </value>
        <value>
          <fullName>Midwest</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Strategy__c</fullName>
    <label>Strategy/Segment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>All</fullName>
        </value>
        <value>
          <fullName>Get</fullName>
        </value>
        <value>
          <fullName>Grow</fullName>
        </value>
        <value>
          <fullName>Keep</fullName>
        </value>
        <value>
          <fullName>Educate</fullName>
        </value>
        <value>
          <fullName>Referral</fullName>
        </value>
        <value>
          <fullName>Starter</fullName>
        </value>
        <value>
          <fullName>Low</fullName>
        </value>
        <value>
          <fullName>Medium</fullName>
        </value>
        <value>
          <fullName>High</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Used for in-person as well as virtual events where sales leads/opportunities are generated based on attendance</description>
    <fullName>InPersonEventCampaign</fullName>
    <label>In-Person or Virtual Event Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>NA_Regional_Marketing_Coordinator__c</fullName>
    <label>NA: Regional Marketing Coordinator</label>
    <relationshipName>User</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_CERE__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA CAD/CAM CEREC</description>
    <inlineHelpText>SIRONA CAD/CAM CEREC</inlineHelpText>
    <label>SBU Ratio (CDCM)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_ENDO__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (ENDO)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_IMAG__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA Imaging systems Intra &amp; Extra Oral</description>
    <inlineHelpText>SIRONA Imaging systems Intra &amp; Extra Oral</inlineHelpText>
    <label>SBU Ratio (IMAG)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_IMPL__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (IMPL)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_INST__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA Instruments</description>
    <inlineHelpText>SIRONA Instruments</inlineHelpText>
    <label>SBU Ratio (INST)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_ORTH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (ORTH)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_PREV__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (PREV)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_PROS__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (PROS)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_REST__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (REST)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_TRCE__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA Treatment Centers</description>
    <inlineHelpText>SIRONA Treatment Centers</inlineHelpText>
    <label>SBU Ratio (TRCE)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Region__c</fullName>
    <formula>Text(Region__c)</formula>
    <label>User Region</label>
    <type>Text</type>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/newCampaignOverride.cls
/*-------------------------------------------------------------------------------------------------------
Description:  Extension class to VF page newCampaignOverridePage
History
20210906    Richard    Adjusted newCampaignOverride to set Campaign Member RT automatically for physical campaigns (TFUS-3500) 
20210922 	Miguel 	   Bug Fix: Adjusted CampaignMemberRecordType Id to the one from Production
----------------------------------------------------------------------------------------*/

public with sharing class newCampaignOverride {
    private final Campaign pp;
    private ApexPages.StandardController controller;
    public String rType {get; set;}
    public String rTypename {get; set;}
    public String Link {get; set;}
    public String campaignMemberRecordType {get; set;}
    
    
    User u = [Select Id, Name, User_Country__c, SBU_Ratio_IMPL__c, SBU_Ratio_ENDO__c, SBU_Ratio_ORTH__c, SBU_Ratio_PREV__c, SBU_Ratio_PROS__c, SBU_Ratio_REST__c, SBU_Ratio_CERE__c, SBU_Ratio_IMAG__c, SBU_Ratio_INST__c, SBU_Ratio_TRCE__c,NA_Regional_Marketing_Coordinator__c,ManagerId,User_Region__c From User Where id = :UserInfo.getUserId()];
    string SBU = 'Implants';
    double currentSBUPercentage = u.SBU_Ratio_IMPL__c == null ? 0 : u.SBU_Ratio_IMPL__c;
    {
        SBU = 'Implants';
        if(u.SBU_Ratio_ENDO__c != null && u.SBU_Ratio_ENDO__c > currentSBUPercentage){
            SBU = 'Endodontics';
            currentSBUPercentage = u.SBU_Ratio_ENDO__c;
        }
        
        if(u.SBU_Ratio_ORTH__c != null && u.SBU_Ratio_ORTH__c > currentSBUPercentage){
            SBU = 'Orthodontics';
            currentSBUPercentage = u.SBU_Ratio_ORTH__c;
        }
        
        if(u.SBU_Ratio_PREV__c != null && u.SBU_Ratio_PREV__c > currentSBUPercentage){
            SBU = 'Preventive';
            currentSBUPercentage = u.SBU_Ratio_PREV__c;
        }
        
        if(u.SBU_Ratio_PROS__c  != null && u.SBU_Ratio_PROS__c > currentSBUPercentage){
            SBU = 'Prosthetics';
            currentSBUPercentage = u.SBU_Ratio_PROS__c;
        }
        
        if(u.SBU_Ratio_REST__c != null && u.SBU_Ratio_REST__c > currentSBUPercentage){
            SBU = 'Restorative';
            currentSBUPercentage = u.SBU_Ratio_REST__c;
        }
        if(u.SBU_Ratio_CERE__c != null && u.SBU_Ratio_CERE__c > currentSBUPercentage){
            SBU = 'CAD/CAM';
            currentSBUPercentage = u.SBU_Ratio_CERE__c;
        }
        if(u.SBU_Ratio_IMAG__c != null && u.SBU_Ratio_IMAG__c > currentSBUPercentage){
            SBU = 'Imaging Systems';
            currentSBUPercentage = u.SBU_Ratio_IMAG__c;
        }
        if(u.SBU_Ratio_INST__c != null && u.SBU_Ratio_INST__c > currentSBUPercentage){
            SBU = 'Instruments';
            currentSBUPercentage = u.SBU_Ratio_INST__c;
        }
        if(u.SBU_Ratio_TRCE__c != null && u.SBU_Ratio_TRCE__c > currentSBUPercentage){
            SBU = 'Treatment Centers';
            currentSBUPercentage = u.SBU_Ratio_TRCE__c;
        }
    }
    
    
    
    public newCampaignOverride(ApexPages.StandardController controller) {
        
        this.controller = controller;
        pp = (Campaign)Controller.getRecord();
        Link = ApexPages.currentPage().getParameters().get('LinkOrder');
        campaignMemberRecordType = ApexPages.currentPage().getParameters().get('CMRT');
        If(Link == null){
            pp.SBU_Focus__c=SBU;
            rType = ApexPages.currentPage().getParameters().get('RecordType');
        }
        
        
        If(Link=='Program'){
            rType='01220000000Ax3B';
            pp.Campaign_Coordinator__c=u.NA_Regional_Marketing_Coordinator__c;
            pp.Campaign_Approver__c= u.ManagerId;
            pp.Campaign_Region_DE__c=u.User_Region__c;
            //pp.Strategy__c='All';
        }
        
        If(Link=='Sponsorship'){
            rType='01220000000B2A7';
            pp.Campaign_Coordinator__c=u.NA_Regional_Marketing_Coordinator__c;
            pp.Campaign_Approver__c= u.ManagerId;
            pp.Campaign_Region_DE__c=u.User_Region__c;
        }
        
        If(Link=='Trade'){
            rType='01220000000B29s';
            pp.Campaign_Coordinator__c=u.NA_Regional_Marketing_Coordinator__c;
            pp.Campaign_Approver__c= u.ManagerId;
            pp.Campaign_Region_DE__c=u.User_Region__c;
        }
        
        If(Link!='Trade' && Link!='Sponsorship'&& Link!='Program' && Link!=null){//Mean that it will be a campaign ID
            rType='01220000000ANcm';
            Campaign Ca = [Select Id,Name,StartDate,EndDate,Country__c,Profession__c,Target_Country__c,Target_Group__c,Target_Type__c,Strategy__c,SBU_Focus__c,Venue__c from Campaign where Id =: Link];
            pp.Parent_Event__c = ca.Id;
            pp.Session_Start_Date_Time__c = Ca.StartDate;
            pp.Session_End_Date_Time__c = Ca.EndDate;
            pp.SBU_Focus__c = ca.SBU_Focus__c;
            pp.Profession__c = Ca.Profession__c;
            pp.Target_Country__c = Ca.Target_Country__c;
            pp.Target_Group__c = Ca.Target_Group__c;
            pp.Target_Type__c = Ca.Target_Type__c;
            pp.Strategy__c = Ca.Strategy__c;
            pp.Venue__c = Ca.Venue__c;
        }
        
        rTypename=Schema.SObjectType.Campaign.getRecordTypeInfosById().get(rType).getDeveloperName();
        
        if(rType=='01220000000Ax7r' || rType=='01220000000ANcl'){
            pp.Campaign_Coordinator__c=u.Id;
        }
        if(rType!='01220000000ANcm'){ //not for Campaign sessions
            pp.Campaign_Country__c=u.User_Country__c;
            pp.Country__c=u.User_Country__c;
            pp.Target_Country__c=u.User_Country__c;
            
            
            pp.StartDate=date.today();
            pp.EndDate=date.today();
            pp.OwnerId=u.Id;
            
        }
        
        pp.RecordTypeId=rType;
        pp.CampaignMemberRecordTypeId=campaignMemberRecordType;
        
        if(rTypename == 'InPersonEventCampaign'){
			// Production Campaign Member RT Id 
			pp.CampaignMemberRecordTypeId = '0126M000000jouBQAQ';
        }
        
    }
    public pagereference SBU(){
        Return null;
    }
    public PageReference cancel1(){
        If(Link==null){
            PageReference pr = new PageReference('/701/o');
            pr.setRedirect(true);
            
            return pr;
        }else{
            If(Link.startsWith('701')){
                PageReference pr = new PageReference('/' + Link);
                pr.setRedirect(true);
                return pr;
            }else{
                PageReference pr = new PageReference('/701/o');
                pr.setRedirect(true);
                
                return pr;
            }
        }
        //pr=PageReference('/' + Link);
    }
    
    public PageReference save1(){
        PageReference page;
        page = controller.save();
        if(ApexPages.hasMessages()){
            return page;
        }else{
            return page;}
    }
}