unpackaged/objects/Campaign.object
<CustomObject>
  <fields>
    <fullName>Brand__c</fullName>
    <label>Product Focus (IMPL)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <controllingField>Country__c</controllingField>
      <valueSetDefinition>
        <value>
          <fullName>ANKYLOS</fullName>
          <label>Ankylos</label>
        </value>
        <value>
          <fullName>ASTRA TECH Implant System</fullName>
          <label>Astra Tech Implant System</label>
        </value>
        <value>
          <fullName>Astra Tech Implant System EV</fullName>
        </value>
        <value>
          <fullName>Astra Tech Implant System Profile</fullName>
        </value>
        <value>
          <fullName>ATLANTIS Abutments</fullName>
        </value>
        <value>
          <fullName>ATLANTIS ISUS</fullName>
        </value>
        <value>
          <fullName>Frialit</fullName>
        </value>
        <value>
          <fullName>Frios</fullName>
        </value>
        <value>
          <fullName>MGuide</fullName>
        </value>
        <value>
          <fullName>MIS-C1</fullName>
        </value>
        <value>
          <fullName>MIS-Lance</fullName>
        </value>
        <value>
          <fullName>MIS-Seven</fullName>
        </value>
        <value>
          <fullName>MIS-V3</fullName>
        </value>
        <value>
          <fullName>Not Applicable</fullName>
        </value>
        <value>
          <fullName>OSSIX</fullName>
        </value>
        <value>
          <fullName>SIMPLANT</fullName>
        </value>
        <value>
          <fullName>STEPPS</fullName>
        </value>
        <value>
          <fullName>SYMBIOS</fullName>
        </value>
        <value>
          <fullName>WeldOne</fullName>
        </value>
        <value>
          <fullName>XiVe</fullName>
        </value>
        <value>
          <fullName>Other</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Used in Lightning for the Eloqua integration</description>
    <fullName>Digital_Marketing_Campaign</fullName>
    <label>Digital Marketing Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CampaignMember.object
<CustomObject>
  <fields>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>3D Upgrade</fullName>
        </value>
        <value>
          <fullName>ACB with ASA</fullName>
        </value>
        <value>
          <fullName>AH Plus</fullName>
        </value>
        <value>
          <fullName>AH Temp</fullName>
        </value>
        <value>
          <fullName>AlginX</fullName>
        </value>
        <value>
          <fullName>All Ceramics</fullName>
        </value>
        <value>
          <fullName>All Other Endo</fullName>
        </value>
        <value>
          <fullName>All Other - Niti Rotary Files</fullName>
        </value>
        <value>
          <fullName>All Other – Obturation</fullName>
        </value>
        <value>
          <fullName>Anaestadent</fullName>
        </value>
        <value>
          <fullName>Ancillary</fullName>
        </value>
        <value>
          <fullName>ANKYLOS</fullName>
        </value>
        <value>
          <fullName>Apex Locator</fullName>
        </value>
        <value>
          <fullName>Aquasil</fullName>
        </value>
        <value>
          <fullName>Aquasil Ultra Plus</fullName>
        </value>
        <value>
          <fullName>ATIS</fullName>
        </value>
        <value>
          <fullName>ATIS EV</fullName>
        </value>
        <value>
          <fullName>ATIS TX</fullName>
        </value>
        <value>
          <fullName>Atlantis</fullName>
        </value>
        <value>
          <fullName>Atlantis Abutments</fullName>
        </value>
        <value>
          <fullName>Atlantis Suprastructures</fullName>
        </value>
        <value>
          <fullName>Automate</fullName>
        </value>
        <value>
          <fullName>Axeos</fullName>
        </value>
        <value>
          <fullName>Azento Astra Tech</fullName>
        </value>
        <value>
          <fullName>Azento EV</fullName>
        </value>
        <value>
          <fullName>Azento XiVE</fullName>
        </value>
        <value>
          <fullName>Bioceramic</fullName>
        </value>
        <value>
          <fullName>Bluecam</fullName>
        </value>
        <value>
          <fullName>Bonding</fullName>
        </value>
        <value>
          <fullName>Bone</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Account.RecordType.DeveloperName</field>
        <operation>equals</operation>
        <value>CIM_Account</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Distributor</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members (Dealer)</relationshipLabel>
    <relationshipName>Campaign_Members3</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Description__c</fullName>
    <label>Customer Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
  </fields>
  <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

unpackaged/classes/StandardLeadTriggerHelper.cls
global with sharing class StandardLeadTriggerHelper {
    
    private static final String SOBJECT_NAME = 'Lead';
    
    public static void updateCampaignMembers(List<Lead> newLeadList){
        Set<Id> leadIdSet = new Set<Id>();
        
        for(Lead l : newLeadList){        	
            if(l.IsConverted == true){
                leadIdSet.add(l.ConvertedContactId);
            }
        }
        
        //Find all Campaign Members related to the converted leads
        if(leadIdSet.size()>0){
        	List<CampaignMember> cmList = [SELECT Id, LeadId, Description__c, HasResponded, ContactId, Brand__c, CampaignId, Dealer__c, Campaign.Brand__c FROM CampaignMember WHERE ContactId IN: leadIdSet AND Campaign.RecordType.DeveloperName =: 'Digital_Marketing_Campaign'];
        	Map<Id, CampaignMember> cmMap = new Map<Id, CampaignMember>(cmList);        
       		CampaignMemberTriggerHelper.createOpportunities(cmList, cmMap, true);
        }
    }

}