unpackaged/objects/Campaign.object
<CustomObject>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CampaignMember.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</description>
    <inlineHelpText>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members (Account)</relationshipLabel>
    <relationshipName>Campaign_Members2</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Campaign_End_Date__c</fullName>
    <description>The End Date of the Campaign to which the Campaign Member belongs</description>
    <formula>Campaign.EndDate</formula>
    <inlineHelpText>The End Date of the Campaign to which the Campaign Member belongs</inlineHelpText>
    <label>Campaign End Date</label>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Campaign_Status__c</fullName>
    <formula>TEXT(Campaign.Status)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Status</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Phone__c</fullName>
    <description>Dynamic field that will show the Phone Number of the Member if the Contact belongs to your territories.</description>
    <formula>IF( CONTAINS( Contact.TerritoryUsers__c ,  $User.Movex_Uer_ID__c ) ,  Contact.Phone , "####")</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone #</label>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

unpackaged/classes/DC_CampaignMembersDAO.cls
//Author: Sergey Legostaev
//Date: 04/20/2017
public with sharing class DC_CampaignMembersDAO {
	
    public static List<CampaignMember> getActiveCampaignMembersByContactId(String contactId) {
        return [select Id, CampaignId, Campaign.Name, Status
                                        from CampaignMember where Campaign_End_Date__c >= :Date.today()
                                       		 and ContactId = :contactId and Campaign.IsActive = true];
        //and Campaign_Status__c = 'Confirmed'
        //and (Status = 'To Call' or Status = 'Call Back needed')
    }
    
    public static CampaignMember getCampaignMemberById(String id) {
        return [SELECT Name, Account__c, Contact.AccountId, Campaign.RecordType.Name,
                  ContactId, Contact.Account.Name, Contact.Name, Contact.Title,
                  Phone__c, Account__r.Phone, Account__r.Fax, Contact.Email	
                  FROM CampaignMember WHERE Id = :id];
    }
}