unpackaged/objects/Campaign.object
<CustomObject>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CampaignMember.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</description>
    <inlineHelpText>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members (Account)</relationshipLabel>
    <relationshipName>Campaign_Members2</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Description__c</fullName>
    <label>Customer Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
  </fields>
  <fields>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Distributor</fullName>
        </value>
        <value>
          <fullName>Interpreter</fullName>
        </value>
        <value>
          <fullName>Moderator</fullName>
        </value>
        <value>
          <fullName>Other</fullName>
        </value>
        <value>
          <fullName>Participant</fullName>
          <default>true</default>
          <label>Participant</label>
        </value>
        <value>
          <fullName>Sales Staff</fullName>
        </value>
        <value>
          <fullName>Speaker</fullName>
        </value>
        <value>
          <fullName>Speaker &amp; Moderator</fullName>
        </value>
        <value>
          <fullName>Spouse</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

unpackaged/objects/Investigator__c.object
<CustomObject>
  <description>This object is a M:M relationship managing the relationship between the Research Activities/clinical studies and the Contacts involved</description>
  <fields>
    <fullName>Account__c</fullName>
    <description>A link to the Contacts' Account</description>
    <formula>HYPERLINK("/" &amp; Contact__r.AccountId ,  Contact__r.Account.Name)</formula>
    <inlineHelpText>A link to the Contacts' Account</inlineHelpText>
    <label>Account</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Research Activities/Studies</relationshipLabel>
    <relationshipName>Investigators</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Investigator_Role__c</fullName>
    <description>The Role of the Investigator in the Research Activity/Study</description>
    <inlineHelpText>The Role of the Investigator in the Research Activity/Study</inlineHelpText>
    <label>Investigator Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Principal Investigator</fullName>
        </value>
        <value>
          <fullName>CO-Investigator</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Research_Activity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Link to the Research Activity of which the Contact is a member</description>
    <inlineHelpText>The Link to the Research Activity of which the Contact is a member</inlineHelpText>
    <label>Research Activity</label>
    <referenceTo>Research_Activity__c</referenceTo>
    <relationshipLabel>Investigators</relationshipLabel>
    <relationshipName>Investigators</relationshipName>
    <required>true</required>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Study_Status__c</fullName>
    <formula>TEXT(Research_Activity__r.Status__c)</formula>
    <label>Study Status</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Study_Type__c</fullName>
    <formula>Research_Activity__r.RecordType.DeveloperName</formula>
    <label>Study Type</label>
    <type>Text</type>
  </fields>
  <label>Investigator</label>
  <nameField>
    <label>Investigator Role Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Investigators</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Network__c.object
<CustomObject>
  <description>Networks belonging to a Hub Account. Members of the Network (other Accounts with or without Contacts) are related via the Contact Member or Account Member Object.</description>
  <fields>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
  </fields>
  <fields>
    <fullName>Hub_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hub Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Account in Networks</relationshipLabel>
    <relationshipName>Networks</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Network_Type__c</fullName>
    <label>Network Type</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Advisory Board</fullName>
        </value>
        <value>
          <fullName>Lab Customers Network</fullName>
        </value>
        <value>
          <fullName>Lab-to-Lab Network</fullName>
        </value>
        <value>
          <fullName>Training Group</fullName>
        </value>
        <value>
          <fullName>Referral</fullName>
          <default>true</default>
          <label>Referral</label>
        </value>
        <value>
          <fullName>MS Referral</fullName>
        </value>
        <value>
          <fullName>Procurement</fullName>
        </value>
        <value>
          <fullName>KOL Network</fullName>
        </value>
        <value>
          <fullName>Study Group</fullName>
        </value>
        <value>
          <fullName>Commercial Agreement</fullName>
        </value>
        <value>
          <fullName>Scientific Project</fullName>
        </value>
        <value>
          <fullName>Other</fullName>
        </value>
        <value>
          <fullName>Residency</fullName>
        </value>
        <value>
          <fullName>National</fullName>
        </value>
        <value>
          <fullName>Regional</fullName>
        </value>
        <value>
          <fullName>International</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Network</label>
  <nameField>
    <label>Network Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Networks</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Objective__c.object
<CustomObject>
  <description>This account plan is based on the "OGSM" strategic planning methodology: an OGSM is a written and easily communicated statement of an organization’s Objective, Goals, Strategies and Measures. OGSM brings alignment, transparency of priorities and metrics that define success.</description>
  <fields>
    <fullName>Objective__c</fullName>
    <inlineHelpText>"What are we trying to achieve?"
 The Objective should define the playing field and the rules for winning. An Objective is a constant and meaningful reminder to the organization about what success looks like in the future. An effective Objective statement is not generic; it is a customized, business-specific view of where the business is headed.</inlineHelpText>
    <label>Objective</label>
    <length>300</length>
    <type>LongTextArea</type>
  </fields>
  <label>Account Plan Objective</label>
  <nameField>
    <displayFormat>OB-{000}</displayFormat>
    <label>Objective #</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Account Plan Objectives</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Contact.AccountId</field>
        <operation>equals</operation>
        <valueField>$Source.AccountId</valueField>
      </filterItems>
      <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Type__c</fullName>
    <description>field for USC to manage special DOD offer</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>User_CountryPL__c</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>New Customer</fullName>
        </value>
        <value>
          <fullName>New User 1+1</fullName>
          <isActive>false</isActive>
          <label>New User 1+1</label>
        </value>
        <value>
          <fullName>New User 2+1</fullName>
        </value>
        <value>
          <fullName>Tessera Trade Out B7,T3,G3</fullName>
        </value>
        <value>
          <fullName>Trade In</fullName>
        </value>
        <value>
          <fullName>Tradeout 1+1</fullName>
          <isActive>false</isActive>
          <label>Tradeout 1+1</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Research_Activity__c.object
<CustomObject>
  <description>This object contains information of Research Activities. Typical research activities are IIS and CIS studies, which this object is created based on</description>
  <label>Research Activity</label>
  <nameField>
    <label>Research Activity Code</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Research Activites</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/TrackWise__c.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TrackWise</relationshipLabel>
    <relationshipName>TrackWise</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Created_Date__c</fullName>
    <description>Date Created</description>
    <label>Open Date</label>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Customer_Complaint_Code__c</fullName>
    <label>Customer Complaint Code</label>
    <length>180</length>
    <type>Text</type>
  </fields>
  <label>TrackWise</label>
  <nameField>
    <displayFormat>{00000000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>TrackWise</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ContactCardControllerExtension.cls
public class ContactCardControllerExtension {
	private final Contact contact;
	
    public Boolean bolPrintableView {get;set;}
    
    public ContactCardControllerExtension(ApexPages.StandardController stdController) {
        this.contact = (Contact)stdController.getRecord();
    }

	public void init() {
 		String strPrintableView = ApexPages.currentPage().getParameters().get('print');
 		bolPrintableView = (strPrintableView == '1');
	}    
    
 /*   public class Cfe {
		Event e;

        public Cfe(Event event) {
            e = event;
        }
        public Event getEvent() {
            return e;
        }
        public String getObjective() {
            if (e.Objective__c != null)
                return e.Objective__c;
            else
                return e.Description;
        }
    } */
   
    public List<Network__c> getNetworks() {
        List<Network__c> network = new List<Network__c>();
        
        if(contact != null) {
	        network = [select Id, Name, Description__c, Network_Type__c from Network__c where Hub_Account__c = :contact.AccountId LIMIT 5];
        }
        return network;
    }

    public List<Trackwise__c> getTrackwiseComplaints() {
        List<Trackwise__c> trackwise = new List<Trackwise__c>();
        
        if(contact != null) {
	        trackwise = [select Id, Customer_Complaint_Code__c, Created_date__c from Trackwise__c where Account__c = :contact.AccountId LIMIT 5];
        }
        return trackwise;
    }

    public List<Case> getCases() {
        List<Case> cases = new List<Case>();
        
        if(contact != null) {
	        cases = [select Id, CaseNumber, Subject, Description, Type, Status from Case where Account.Id = :contact.AccountId LIMIT 5];
        }
        return cases;
    }

    
    public List<CampaignMember> getCampaignMembers() {
        List<CampaignMember> cm = new List<CampaignMember>();
        
        if(contact != null) {
	        cm = [select Id, Name, Type, Campaign.Name, Campaign.StartDate, Campaign.Type, Status, Type__c from CampaignMember where Contact.Id =  :contact.Id and Type__c = 'Speaker' order by Campaign.StartDate DESC LIMIT 5];
        }
        return cm;
 	}

/*    public List<Cfe> getEvents() {
	    List<Cfe> cfes = new List<Cfe>{};
		String contactId = String.valueOf(contact.Id).substring(0, 15);     
        
        if(contact != null) {
            cfes.clear();
            for (Event c: [select Objective__c, Event_Status__c, Owner.Name, Description, Subject, ActivityDate from Event where Contact_Id__c = :contactId ORDER BY ActivityDate DESC LIMIT 5]) {
                	cfes.add(new Cfe(c));
            }
        }
        return cfes;
 	}

    public List<Cfe> getEvents2() {
        List<Cfe> cfes = new List<Cfe>{};

        if(contact != null) {
            for (Event c: [select Objective__c, Description, Subject from Event where Contact_Id__c = :contact.Id]) {
                	cfes.add(new Cfe(c));
            }
        }
        return cfes;
 	} */

    public List<Event> getEvents3() {
        List<Event> cfes = new List<Event>{};
            
        String contactId = String.valueOf(contact.Id).substring(0, 15);     
                
        if(contact != null) {
            cfes = [select Id, ActivityDate, Subject from Event where Contact_Id__c = :contactId ORDER BY ActivityDate DESC LIMIT 5];
        }
        return cfes;
 	}
    
    public List<Investigator__c> getInvestigator() {
        List<Investigator__c> investigators = new List<Investigator__c>();

        if(contact != null) {
            investigators = [select Account__c, Contact__r.Name, Investigator_Role__c, Research_Activity__c, Study_Status__c, Study_Type__c from Investigator__c where Contact__c = :contact.Id LIMIT 15];
        }
        return investigators;
    }
}