unpackaged/objects/Campaign.object
<CustomObject>
  <fields>
    <fullName>Parent_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used on sessions to show what Campaign is the parent Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Campaign</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Session_Max_Occupancy__c</fullName>
    <description>The maximum number of allowed participants for this session.</description>
    <label># of Session Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Session_Occupancy__c</fullName>
    <description>The number of confirmed participants for this session.</description>
    <label># of Occupied Session Seats</label>
    <summaryForeignKey>Session_Participant__c.Session__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
  </fields>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN SESSION, related to a CAMPAIGN.</description>
    <fullName>DI_Campaign_Session</fullName>
    <label>Campaign Session</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/CampaignMember.object
<CustomObject>
  <fields>
    <fullName>Full_Name__c</fullName>
    <formula>IF( ISBLANK(TEXT(Contact.Salutation)), FirstName &amp; " " &amp; LastName , TEXT(Contact.Salutation)  &amp; " " &amp; FirstName &amp; " " &amp; LastName )</formula>
    <label>Full Name</label>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

unpackaged/objects/Session_Participant__c.object
<CustomObject>
  <description>Used for adding participants in sessions. Initially for Germany only</description>
  <fields>
    <fullName>CampaignMemberId__c</fullName>
    <label>Campaign Member ID</label>
    <length>18</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Sessions</relationshipLabel>
    <relationshipName>Session_Participants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Session Participants</relationshipLabel>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <label>Session Participant</label>
  <nameField>
    <label>Session Participant Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Session Participants</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CampMgmtSessionExtension.cls
public class CampMgmtSessionExtension
{
    private final CampaignMember campaignMember;  
    
    public CampMgmtSessionExtension(ApexPages.StandardController stdController)
    {
   		// Load the main record context.
        if(!Test.isRunningTest())
            stdController.addFields(new String[] { 'CampaignId', 'Full_Name__c', 'ContactId' });
        campaignMember = (CampaignMember)stdController.getRecord();
        
        // Load initial values for the sessionIdList property.
        List<Session_Participant__c> sessionParticipantList = getSessionParticipantList();
        for (Session_Participant__c sessionParticipant : sessionParticipantList)
            sessionIdSet.add(sessionParticipant.Session__c);
    }
    
    // The sessionIdList property represent the list of checked sessions
    // and is backed by the sessionIdSet field.
    private Set<String> sessionIdSet = new Set<String>();     
    public List<String> getSessionIdList() { return new List<String>(sessionIdSet); }
    public void setSessionIdList(List<String> sessionIdList) { this.sessionIdSet = new Set<String>(sessionIdList); }    

    // The sessionList property provides the full set of selectable sessions.
    private List<Campaign> sessionList;
    public List<SelectOption> getSessionList()
    {
        if (sessionList == null)
        {
            sessionList =
            [
                SELECT Id, Name, Session_Occupancy__c, Session_Max_Occupancy__c
                FROM Campaign
                WHERE RecordType.DeveloperName = 'DI_Campaign_Session'
                AND Parent_Event__c = :campaignMember.CampaignId
            ]; 
        }
        
        List<SelectOption> result = new List<SelectOption>();
        
        for (Campaign session : sessionList)
        {
            String maxOccupancy = session.Session_Max_Occupancy__c == null ? '0' : session.Session_Max_Occupancy__c.format();
            List<String> arguments = new List<String> { session.Name , session.Session_Occupancy__c.format(), maxOccupancy };
            String label = String.format(System.Label.CampMgmt_SessionFormatString, arguments);
            result.add(new SelectOption(session.Id, label));
        }

        return result;
    }    

    public PageReference saveSessions()
    {       
        // Get fresh participant list since things may have been changed by others
        // since we initialized the controller.
        List<Session_Participant__c> sessionParticipantList = getSessionParticipantList();
        
        // 1. Delete any Session_Participant__c records from the database that
        // have no corresponding checked sessions.
        
        List<Session_Participant__c> sessionParticipantDeleteList = new List<Session_Participant__c>();
        for (Session_Participant__c sessionParticipant : sessionParticipantList)
        {
            if (!sessionIdSet.contains(sessionParticipant.Session__c))
                sessionParticipantDeleteList.add(sessionParticipant);
        }
        
        Database.delete(sessionParticipantDeleteList);
        
        // 2. Insert new Session_Participant__c records for checked sessions that
        // are not already in the database.

        Map<String, Session_Participant__c> sessionParticipantMap = new Map<String, Session_Participant__c>();
        for (Session_Participant__c sessionParticipant : sessionParticipantList)
            sessionParticipantMap.put(sessionParticipant.Session__c, sessionParticipant);
        
        List<Session_Participant__c> sessionParticipantInsertList = new List<Session_Participant__c>();  
        for (String sessionId : sessionIdSet)
        {
            if (!sessionParticipantMap.containsKey(sessionId))
            {
                Session_Participant__c newSessionParticipant = new Session_Participant__c(
                    Contact__c = campaignMember.ContactId,
                    Name = campaignMember.Full_Name__c,
                    Session__c = sessionId,
                    CampaignMemberId__c = campaignMember.Id
                );
                
                sessionParticipantInsertList.add(newSessionParticipant);
            }              
        }
        
        Database.insert(sessionParticipantInsertList);
        
        // Clear the session cache because session occupancy information has changed.
        sessionList = null;
        
        return null;
    }
    
    private List<Session_Participant__c> getSessionParticipantList()
    {
        List<Session_Participant__c> sessionParticipantList =
        [
            SELECT Session__c
            FROM Session_Participant__c
            WHERE CampaignMemberId__c = :campaignMember.Id
        ]; 
        
        return sessionParticipantList;
    }
}