unpackaged/objects/Campaign.object
<CustomObject>
  <fields>
    <fullName>Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Campaign_Country__c</fullName>
    <description>Country where the Campaign is taking place.</description>
    <inlineHelpText>Country where the Campaign is taking place.</inlineHelpText>
    <label>Campaign Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Algeria</fullName>
        </value>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Bahrain</fullName>
        </value>
        <value>
          <fullName>Bangladesh</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Bulgaria</fullName>
        </value>
        <value>
          <fullName>Cambodia</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Chile</fullName>
        </value>
        <value>
          <fullName>China</fullName>
        </value>
        <value>
          <fullName>Colombia</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>Hungary</fullName>
        </value>
        <value>
          <fullName>Iceland</fullName>
        </value>
        <value>
          <fullName>India</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Country_Code_3_digit__c</fullName>
    <description>TFUS-000002404 Used by Eloqua</description>
    <label>Country Code (3-digit)</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_3_digit</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>Parent_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used on sessions to show what Campaign is the parent Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Campaign</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>SBU_Focus__c</fullName>
    <description>Used to track which SBU the Campaigns target for promotion/training.</description>
    <inlineHelpText>Pick the SBU(s) that this Campaign targets for promotion/training.</inlineHelpText>
    <label>SBU</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
        <value>
          <fullName>Imaging Systems</fullName>
        </value>
        <value>
          <fullName>Instruments</fullName>
        </value>
        <value>
          <fullName>US Consumables</fullName>
        </value>
        <value>
          <fullName>Maillefer</fullName>
        </value>
        <value>
          <fullName>Midwest</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Session_Start_Date_Time__c</fullName>
    <description>Use by HQ T&amp;E</description>
    <label>Session Start Date &amp; Time</label>
    <type>DateTime</type>
  </fields>
  <recordTypes>
    <active>false</active>
    <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
    <fullName>Campaign</fullName>
    <label>Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN.</description>
    <fullName>DI_Campaign</fullName>
    <label>Course/Event/Exhibition</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Use this Record Type if you want to create a CAMPAIGN SESSION, related to a CAMPAIGN.</description>
    <fullName>DI_Campaign_Session</fullName>
    <label>Campaign Session</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <fullName>DI_Mailing</fullName>
    <label>Mailing</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>First Draft of DNA Campaign setup</description>
    <fullName>DNA_Campaign</fullName>
    <label>DNA Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Used in Lightning for the Eloqua integration</description>
    <fullName>Digital_Marketing_Campaign</fullName>
    <label>Digital Marketing Campaign</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Inside Sales Campaign</description>
    <fullName>Inside_Sales_Campaign</fullName>
    <label>Inside Sales Campaign</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Country_Code_3_digit__c</fullName>
    <description>3-digit country code. Used mainly for Wave reporting where it is needed in Wave maps for the map to understand which country we are referring to. Dependent on user country so the three digit code will be automatically entered based on User Country - NOTE: when adding a new User Country you must state which 3 digit code belongs to that country for it to work.</description>
    <label>Country Code (3-digit)</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>User_Country__c</controllingField>
      <restricted>true</restricted>
      <valueSetName>Country_Code_3_digit</valueSetName>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/Test_CampaignTrigger.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Ahmed LOUDRASSI (Salesforce) 20191028
Description:    Campaign  Trigger Helper Class
History
20191028   Ahmed LOUDRASSI   Migrated  CampMgmtCampaignSessionTrigger, CampMgmtCampaignTrigger, CampMgmtCampaignTrigger2, CampMgmtCampaignSharingTrigger triggers. (#)
----------------------------------------------------------------------------------------*/

@isTest(seeAllData=false)
public with sharing class Test_CampaignTrigger {
    /*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<Campaign> campaignList1 = TestDataFactory.returnCampaigns(1, 'DI_Campaign', userList.get(0).Id);
        campaignList1.get(0).SBU_Focus__c = 'Implants';
        campaignList1.get(0).isActive = true;
        campaignList1.get(0).StartDate = Date.today();
        insert campaignList1;       	  
    }

    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();
		
        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }
    @isTest
    public static void testSetCampaignSessionsDefaultValues() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        Campaign campaign = [SELECT Id FROM Campaign LIMIT  1];
        
        List<Campaign> campaignList1 = TestDataFactory.returnCampaigns(1, 'DI_Campaign_Session', testUser.Id);
        campaignList1.get(0).Parent_Event__c = campaign.Id;
        
        Test.startTest();
        insert campaignList1;
        Test.stopTest();
        
        System.assertEquals(Date.today(), [SELECT Id, Session_Start_Date_Time__c, RecordType.DeveloperName FROM Campaign 
                                           	WHERE Id =: campaignList1.get(0).Id LIMIT 1].Session_Start_Date_Time__c);
    }
    @isTest
    public static void testSetCampaignMemberStatus() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Campaign> campaignList1 = TestDataFactory.returnCampaigns(1, 'DNA_Campaign', testUser.Id);
        List<Campaign> campaignList2 = TestDataFactory.returnCampaigns(1, 'DI_Mailing', testUser.Id);
        List<Campaign> campaignList3 = TestDataFactory.returnCampaigns(1, 'Inside_Sales_Campaign', testUser.Id);
        campaignList1.addAll(campaignList2);
        campaignList1.addAll(campaignList3);
        Test.startTest();
        insert campaignList1;
        Test.stopTest();
        //System.assertEquals('test', [SELECT Id, Label FROM CampaignMemberStatus WHERE CampaignId =: campaignList1.get(1).Id].Label);
        //System.assertEquals(8, [SELECT Id FROM CampaignMemberStatus WHERE CampaignId =: campaignList1.get(1).Id].size());
        //System.assertEquals(8, [SELECT Id FROM CampaignMemberStatus WHERE CampaignId =: campaignList1.get(2).Id].size());
    }
    @isTest
    public static void testDeactivateCampaignSessions() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        Campaign campaignParent = [SELECT Id FROM Campaign WHERE RecordType.DeveloperName = 'DI_Campaign'];        
        
        List<Campaign> campaignList1 = TestDataFactory.returnCampaigns(1, 'DI_Campaign_Session', testUser.Id);
        campaignList1.get(0).Parent_Event__c = campaignParent.Id;
        campaignList1.get(0).isActive = true;
        
        Test.startTest();
        insert campaignList1;
        campaignParent.isActive = false;
        update campaignParent;
        Test.stopTest();
        System.assertEquals(false, [SELECT Id, isActive FROM Campaign WHERE Id =: campaignList1.get(0).Id].isActive);
    }
    @isTest
    public static void testCampaignSharing() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        List<Campaign> campaignList1 = TestDataFactory.returnCampaigns(1, 'DI_Campaign', testUser.Id);
        campaignList1.get(0).SBU_Focus__c = 'Implants';
        campaignList1.get(0).Campaign_Approver__c = testUser.Id;
        Test.startTest();
        insert campaignList1;
        Test.stopTest();
        System.assertEquals(1, [SELECT Id FROM CampaignShare 
                                WHERE CampaignId =: campaignList1.get(0).Id AND UserOrGroupId =: testUser.Id].size());
    }
    @isTest
    public static void testsetCountryOnInsert() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        
        List<Campaign> campaignList1 = TestDataFactory.returnCampaigns(3, 'Digital_Marketing_Campaign', testUser.Id);
        campaignList1.get(0).Campaign_Country__c = 'France';
        campaignList1.get(1).Country_Code_3_digit__c = 'FRA';
        
        Test.startTest();
        insert campaignList1;
        Test.stopTest();
        
    }
    @isTest
    public static void testsetCountryOnUpdate() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        
        List<Campaign> campaignList1 = TestDataFactory.returnCampaigns(3, 'Digital_Marketing_Campaign', testUser.Id);
        insert campaignList1;
        campaignList1.get(0).Campaign_Country__c = 'France';
        campaignList1.get(1).Country_Code_3_digit__c = 'FRA';
        
        Test.startTest();
        update campaignList1;
        Test.stopTest();

    }
}