unpackaged/objects/Case.object
<CustomObject>
  <fields>
    <fullName>Project_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Milestone</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>$Source.Related_Development_Project__c</field>
        <operation>equals</operation>
        <valueField>Deployment_Status_Phase__c.Project__c</valueField>
      </filterItems>
      <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Deployment_Status_Phase__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Related_Deployment_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Deployment Project</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Project__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Deployment</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CRM Requests</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
  </fields>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Deployment_Status_Phase__c.object
<CustomObject>
  <description>Ex Deployment Phases</description>
  <fields>
    <fullName>Meeting_Date__c</fullName>
    <label>Milestone Date</label>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>ProjectMilestone</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Not Started</fullName>
        </value>
        <value>
          <fullName>In Progress</fullName>
        </value>
        <value>
          <fullName>Delayed</fullName>
        </value>
        <value>
          <fullName>Done/Passed</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Project Milestone</label>
  <nameField>
    <label>Project Milestone Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>ProjectMilestones</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Project__c.object
<CustomObject>
  <description>Used for internal Project tracking</description>
  <label>Project</label>
  <nameField>
    <label>Project Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Projects</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/TeamForce_CaseHierarchy.cls
public class TeamForce_CaseHierarchy {

    @AuraEnabled
    public static List<Deployment_Status_Phase__c> getCaseList(String recordId){
        List<Deployment_Status_Phase__c> caseList = new List<Deployment_Status_Phase__c>();
        caseList = [SELECT Id, Project__c, Status__c, Name, Meeting_date__c,
                    (SELECT Id, CaseNumber, Subject, Parent.CaseNumber, ParentId, Parent.Subject FROM Cases__r)
                    FROM Deployment_Status_Phase__c 
                    WHERE Project__r.Id =: recordId 
                    ORDER BY Meeting_date__c ASC];    
    return caseList;
    }
    
}