unpackaged/objects/Case.object
<CustomObject>
  <fields>
    <fullName>CaseType__c</fullName>
    <label>Case Type (Global)</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Service complaint</fullName>
          <color>#0B6FCE</color>
          <label>Customer Complaint</label>
        </value>
        <value>
          <fullName>General support/question</fullName>
          <color>#A845DC</color>
          <label>Customer Interaction</label>
        </value>
        <value>
          <fullName>Return</fullName>
          <color>#419249</color>
          <label>Return</label>
        </value>
        <value>
          <fullName>Credit/rebill</fullName>
          <color>#A53711</color>
          <label>Credit/rebill</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Complaint_Category__c</fullName>
    <description>We couldn't use the standard field Type since there are many limitations with standard fields</description>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>CaseType__c</controllingField>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Billing</fullName>
          <color>#339999</color>
          <label>Billing</label>
        </value>
        <value>
          <fullName>Communication &amp; Service</fullName>
          <color>#0B6FCE</color>
          <label>Communication &amp; Service</label>
        </value>
        <value>
          <fullName>Consignment</fullName>
          <color>#419249</color>
          <label>Consignment</label>
        </value>
        <value>
          <fullName>Customer Error</fullName>
        </value>
        <value>
          <fullName>Customer Interaction</fullName>
          <color>#FF0000</color>
          <default>true</default>
          <label>Customer Interaction</label>
        </value>
        <value>
          <fullName>Customer Service Error</fullName>
          <color>#A845DC</color>
          <label>Customer Service Error</label>
        </value>
        <value>
          <fullName>Dropped Implant</fullName>
          <color>#FF9900</color>
          <label>Dropped Implant</label>
        </value>
        <value>
          <fullName>E-commerce site</fullName>
          <color>#A53711</color>
          <label>E-commerce site</label>
        </value>
        <value>
          <fullName>Exchange</fullName>
          <color>#66E9BD</color>
          <label>Exchange</label>
        </value>
        <value>
          <fullName>Hardware</fullName>
        </value>
        <value>
          <fullName>Lost Shipment Error</fullName>
          <color>#0B24BE</color>
          <label>Lost Shipment Error</label>
        </value>
        <value>
          <fullName>Marketing</fullName>
        </value>
        <value>
          <fullName>Orders</fullName>
          <color>#999999</color>
          <label>Orders</label>
        </value>
        <value>
          <fullName>Orders &amp; Billing</fullName>
          <color>#419249</color>
          <label>Orders &amp; Billing</label>
        </value>
        <value>
          <fullName>Over Ordered</fullName>
          <color>#B6E32E</color>
          <label>Over Ordered</label>
        </value>
        <value>
          <fullName>Pricing System Error</fullName>
          <color>#3333FF</color>
          <label>Pricing System Error</label>
        </value>
        <value>
          <fullName>Product Related</fullName>
          <color>#F96FB7</color>
          <label>Product Related</label>
        </value>
        <value>
          <fullName>Rebate</fullName>
        </value>
        <value>
          <fullName>Return</fullName>
          <color>#2F5D85</color>
          <label>Return</label>
        </value>
        <value>
          <fullName>Sales Team Error</fullName>
          <color>#AFCADF</color>
          <label>Sales Team Error</label>
        </value>
        <value>
          <fullName>Shipping</fullName>
          <color>#663300</color>
          <label>Shipping</label>
        </value>
        <value>
          <fullName>Software Complaint</fullName>
          <color>#EFAE73</color>
          <label>Software</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Complaint_Reason2__c</fullName>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>Complaint_Category__c</controllingField>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Academy/Loyalty</fullName>
          <color>#33FFFF</color>
          <label>Academy/Loyalty</label>
        </value>
        <value>
          <fullName>Account maintenance</fullName>
          <color>#FF9900</color>
          <label>Account maintenance</label>
        </value>
        <value>
          <fullName>Account set up</fullName>
          <color>#003300</color>
          <label>Account set up</label>
        </value>
        <value>
          <fullName>Account set up issues</fullName>
          <color>#000000</color>
          <label>Account set up issues</label>
        </value>
        <value>
          <fullName>Assist with order placement</fullName>
          <color>#FF99FF</color>
          <label>Assist with order placement</label>
        </value>
        <value>
          <fullName>Backorder follow up</fullName>
          <color>#CC66CC</color>
          <label>Backorder follow up</label>
        </value>
        <value>
          <fullName>Break-Fix</fullName>
        </value>
        <value>
          <fullName>Cancelled order</fullName>
          <color>#CC33CC</color>
          <label>Cancelled order</label>
        </value>
        <value>
          <fullName>Carrier late delivery</fullName>
          <color>#993399</color>
          <label>Carrier late delivery</label>
        </value>
        <value>
          <fullName>Carrier lost package</fullName>
          <color>#663366</color>
          <label>Carrier lost package</label>
        </value>
        <value>
          <fullName>CEREC direct connect</fullName>
          <color>#666666</color>
          <label>CEREC direct connect</label>
        </value>
        <value>
          <fullName>Courtesy Credit</fullName>
          <color>#78C953</color>
          <label>Courtesy Credit</label>
        </value>
        <value>
          <fullName>Crash</fullName>
          <color>#E27001</color>
          <label>Crash</label>
        </value>
        <value>
          <fullName>Credit</fullName>
          <color>#990000</color>
          <label>Credit</label>
        </value>
        <value>
          <fullName>Customer notes not followed</fullName>
          <color>#009900</color>
          <label>Customer notes not followed</label>
        </value>
        <value>
          <fullName>Customer payment</fullName>
          <color>#339999</color>
          <label>Customer payment</label>
        </value>
        <value>
          <fullName>Customer training</fullName>
          <color>#3333FF</color>
          <label>Customer training</label>
        </value>
        <value>
          <fullName>Delay in Finance order release</fullName>
          <color>#6600CC</color>
          <label>Delay in Finance order release</label>
        </value>
        <value>
          <fullName>Delivered to Incorrect Address</fullName>
          <color>#A845DC</color>
          <label>Delivered to Incorrect Address</label>
        </value>
        <value>
          <fullName>Duplicated Order</fullName>
          <color>#F3D904</color>
          <label>Duplicated Order</label>
        </value>
        <value>
          <fullName>Excessive phone wait time</fullName>
          <color>#6633FF</color>
          <label>Excessive phone wait time</label>
        </value>
        <value>
          <fullName>Excessive wait time for approval</fullName>
          <color>#3366FF</color>
          <label>Excessive wait time for approval</label>
        </value>
        <value>
          <fullName>General inquiry</fullName>
          <color>#00CCCC</color>
          <label>General inquiry</label>
        </value>
        <value>
          <fullName>Hardware</fullName>
          <color>#33CC00</color>
          <label>Hardware</label>
        </value>
        <value>
          <fullName>Incorrect Article/s</fullName>
          <color>#0B24BE</color>
          <label>Incorrect Article/s</label>
        </value>
        <value>
          <fullName>Incorrect articles picked</fullName>
          <color>#FFCC33</color>
          <label>Incorrect articles picked</label>
        </value>
        <value>
          <fullName>Incorrect Components</fullName>
          <color>#B6E32E</color>
          <label>Incorrect Components</label>
        </value>
        <value>
          <fullName>Incorrect Customer Number</fullName>
          <color>#641CCF</color>
          <label>Incorrect Customer Number</label>
        </value>
        <value>
          <fullName>Incorrect Guide Type</fullName>
          <color>#AFCADF</color>
          <label>Incorrect Guide Type</label>
        </value>
        <value>
          <fullName>Incorrect Payment Terms</fullName>
          <color>#57F17C</color>
          <label>Incorrect Payment Terms</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Product_Line__c</fullName>
    <description>The major business units for Dentsply Implants</description>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>SBU__c</controllingField>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Accessories</fullName>
        </value>
        <value>
          <fullName>Adhesives</fullName>
        </value>
        <value>
          <fullName>Air Polishing Unit</fullName>
        </value>
        <value>
          <fullName>Alloy</fullName>
        </value>
        <value>
          <fullName>Amalgams</fullName>
        </value>
        <value>
          <fullName>Anesthesia</fullName>
        </value>
        <value>
          <fullName>Anesthetics</fullName>
        </value>
        <value>
          <fullName>Articulating SDR Flow</fullName>
        </value>
        <value>
          <fullName>ATL Abut</fullName>
        </value>
        <value>
          <fullName>ATL Suprastructures</fullName>
        </value>
        <value>
          <fullName>Attachments</fullName>
        </value>
        <value>
          <fullName>Azento</fullName>
        </value>
        <value>
          <fullName>Bands</fullName>
        </value>
        <value>
          <fullName>Bite Registration Material</fullName>
        </value>
        <value>
          <fullName>Bracket</fullName>
        </value>
        <value>
          <fullName>Burs</fullName>
        </value>
        <value>
          <fullName>Burs Gates</fullName>
        </value>
        <value>
          <fullName>CAD/CAM Materials</fullName>
        </value>
        <value>
          <fullName>CDR</fullName>
        </value>
        <value>
          <fullName>Cements</fullName>
        </value>
        <value>
          <fullName>Ceramic Furnaces</fullName>
        </value>
        <value>
          <fullName>Ceramics</fullName>
        </value>
        <value>
          <fullName>Clamps</fullName>
        </value>
        <value>
          <fullName>Composite Material</fullName>
        </value>
        <value>
          <fullName>Composites &amp; Flowables</fullName>
        </value>
        <value>
          <fullName>Consumables</fullName>
        </value>
        <value>
          <fullName>Core &amp; Post</fullName>
        </value>
        <value>
          <fullName>Couplers</fullName>
        </value>
        <value>
          <fullName>Crown forms</fullName>
        </value>
        <value>
          <fullName>Curing Lights</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>SBU__c</fullName>
    <description>Use only for Service Complaint</description>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>SBU</valueSetName>
    </valueSet>
  </fields>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>InsertEmailMarketingConsentCollected__c</fullName>
    <inlineHelpText>Please fill the information if the Email Marketing Consent was collected or not</inlineHelpText>
    <label>Insert Email Marketing Consent Collected</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Yes</fullName>
        </value>
        <value>
          <fullName>No</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Profession__c</fullName>
    <description>Dependent upon Product Area</description>
    <label>Role/Profession</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Advanced Practice Dental Therapist</fullName>
        </value>
        <value>
          <fullName>Clinical Director</fullName>
        </value>
        <value>
          <fullName>Consultant</fullName>
        </value>
        <value>
          <fullName>Contractor</fullName>
        </value>
        <value>
          <fullName>Dean</fullName>
          <label>Dean/Head</label>
        </value>
        <value>
          <fullName>Dental Assistant</fullName>
        </value>
        <value>
          <fullName>Dental Hygienist</fullName>
        </value>
        <value>
          <fullName>Dental Laboratory General Manager</fullName>
        </value>
        <value>
          <fullName>Dental Laboratory Office Manager</fullName>
        </value>
        <value>
          <fullName>Dental Laboratory Technician</fullName>
        </value>
        <value>
          <fullName>Dental Nurse</fullName>
        </value>
        <value>
          <fullName>Dental Nurse Manager</fullName>
        </value>
        <value>
          <fullName>Dental Student</fullName>
        </value>
        <value>
          <fullName>Dental Technician</fullName>
        </value>
        <value>
          <fullName>Dental Technician Master</fullName>
        </value>
        <value>
          <fullName>Dental Therapist</fullName>
        </value>
        <value>
          <fullName>Dentist</fullName>
        </value>
        <value>
          <fullName>Denturist</fullName>
        </value>
        <value>
          <fullName>Distributor General Manager</fullName>
        </value>
        <value>
          <fullName>Distributor Sales Rep</fullName>
        </value>
        <value>
          <fullName>Doctor</fullName>
        </value>
        <value>
          <fullName>DS Employee</fullName>
        </value>
        <value>
          <fullName>Employee</fullName>
        </value>
        <value>
          <fullName>Endodontist</fullName>
        </value>
        <value>
          <fullName>Faculty/Instructor/Professor</fullName>
        </value>
        <value>
          <fullName>General Dentist</fullName>
        </value>
        <value>
          <fullName>General Manager</fullName>
        </value>
        <value>
          <fullName>Head of Department</fullName>
        </value>
        <value>
          <fullName>Implant Manager</fullName>
        </value>
        <value>
          <fullName>Implantologist</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Test_CaseTrigger.cls
/*-------------------------------------------------------------------------------------------------------
Author:         NISREEN ALSALEH (support@avity.com) 25-March-2021
Description:    Case Trigger Helper Class
--------------------------------------------------------------------------------------------------------*/
@isTest(seeAllData = False)
public class Test_CaseTrigger {
    
     @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
    }
    
@isTest static void myUnitTest() {
        Account acc = new Account(Name='testacc', OneAccount_Type__c = 'Dental Clinic');
        acc.RecordTypeId=Schema.sObjectType.Account.getRecordTypeInfosByName().get('CIM Account').getRecordTypeId();
        insert acc;

        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', Profession__c= 'Consultant',InsertEmailMarketingConsentCollected__c = 'No',AccountId=acc.Id);
        con.RecordTypeId = Schema.sObjectType.Contact.getRecordTypeInfosByName().get('Contact Global').getRecordTypeId();
        insert con;

        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');
        insert ass;

        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;

        Entitlement ent2 = new Entitlement(Name='test2', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-10)), EndDate=Date.valueof(System.now().addYears(3)));
        insert ent2;

        EntitlementContact ec = new EntitlementContact(EntitlementId=ent.Id, ContactId=con.Id);
        insert ec;

        List<Case> listC = new list<Case>();
        List<Id> newCaseIds = new List<Id>();
        for(Integer i=0;i<20;i++){
            Case c = new Case(ContactId=con.Id, AccountId=con.AccountId, Subject='Test Subject'+i, Status='New', CaseType__c= 'General support/question',
                              Complaint_Category__c='Customer Interaction',Complaint_Reason2__c='General inquiry',SBU__c= 'IMPL',Product_Line__c='Implants');
            c.RecordTypeId = Schema.sObjectType.Case.getRecordTypeInfosByName().get('Service Complaint').getRecordTypeId();
            listC.add(c);
        }
        insert listC;   
        for (Case caseObj:listC) {
            newCaseIds.add(caseObj.Id);
        }

        List<Case> entls = [Select EntitlementId, AssetId, ContactId, AccountId From Case Where Id in :newCaseIds];

        for (Case caseObj:entls) {

            System.debug(caseObj.Id + ' here are the values ' + caseObj.EntitlementId + ' and here ent.Id ' + ent.Id);

            System.assertEquals(caseObj.EntitlementId, ent.Id);

        }
        Contact con2 = new Contact(FirstName = 'Jane',
        LastName = 'Doe',
        Email='jane@doe.com',
        Profession__c= 'Consultant',
        InsertEmailMarketingConsentCollected__c = 'No');
        con2.RecordTypeId = Schema.sObjectType.Contact.getRecordTypeInfosByName().get('Contact Global').getRecordTypeId();
        insert con2;
    
        Entitlement ent3 = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent3;

        EntitlementContact ec2 = new EntitlementContact(EntitlementId=ent3.Id, ContactId=con2.Id);
        insert ec2;
        Case c1 = new Case(ContactId=con2.Id, AccountId=con.AccountId, Subject='Test Subject',Status='New', CaseType__c= 'General support/question',
                              Complaint_Category__c='Customer Interaction',Complaint_Reason2__c='General inquiry',SBU__c= 'IMPL',Product_Line__c='Implants');
    	c1.RecordTypeId = Schema.sObjectType.Case.getRecordTypeInfosByName().get('Service Complaint').getRecordTypeId();
        Test.startTest();
            insert c1;
            update c1;
        Test.stopTest();
    }
    
    @isTest static void milestoneTestMethod(){
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        Case c = new case();
        c.status = 'Active';
        c.AccountId = acc.Id;
        c.RecordTypeId = '01220000000AvOOAA0';
        c.SlaStartDate = system.now().addHours(-1); 
        Test.startTest();
            insert c;
            c.status = 'Closed';
            update c;
        Test.stopTest();

    }
    
}