unpackaged/objects/Case.object
<CustomObject>
  <fields>
    <fullName>Project_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Milestone</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>$Source.Related_Development_Project__c</field>
        <operation>equals</operation>
        <valueField>Deployment_Status_Phase__c.Project__c</valueField>
      </filterItems>
      <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Deployment_Status_Phase__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
  </fields>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Deployment_Status_Phase__c.object
<CustomObject>
  <description>Ex Deployment Phases</description>
  <fields>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>ProjectMilestone</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <label>Project Milestone</label>
  <nameField>
    <label>Project Milestone Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>ProjectMilestones</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Project__c.object
<CustomObject>
  <description>Used for internal Project tracking</description>
  <label>Project</label>
  <nameField>
    <label>Project Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Projects</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/TeamForce_CaseHierarchy_Test.cls
@isTest
public with sharing class TeamForce_CaseHierarchy_Test {

    @isTest
    private static void getCaseList_Test(){
        Project__c p = new Project__c();
        p.Name = 'Project';
        insert p;
        
        Deployment_Status_Phase__c pm = new Deployment_Status_Phase__c();
        pm.Project__c = p.Id;
        pm.Name = 'Project milestone';
        insert pm;
        
        Case c = new Case();
        c.Subject = 'Case';
        c.Project_Milestone__c = pm.Id;
        
        TeamForce_CaseHierarchy.getCaseList(p.Id);
        
        
    }   
    
}