unpackaged/objects/Case.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>AT</fullName>
        </value>
        <value>
          <fullName>BY</fullName>
        </value>
        <value>
          <fullName>CH</fullName>
        </value>
        <value>
          <fullName>DE</fullName>
        </value>
        <value>
          <fullName>DK</fullName>
        </value>
        <value>
          <fullName>ES</fullName>
        </value>
        <value>
          <fullName>FI</fullName>
        </value>
        <value>
          <fullName>FR</fullName>
        </value>
        <value>
          <fullName>ID</fullName>
        </value>
        <value>
          <fullName>IT</fullName>
        </value>
        <value>
          <fullName>JP</fullName>
        </value>
        <value>
          <fullName>KZ</fullName>
        </value>
        <value>
          <fullName>MY</fullName>
        </value>
        <value>
          <fullName>NO</fullName>
        </value>
        <value>
          <fullName>PH</fullName>
        </value>
        <value>
          <fullName>SE</fullName>
        </value>
        <value>
          <fullName>UA</fullName>
        </value>
        <value>
          <fullName>US</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Teamforce_Product__c</fullName>
    <description>Add to which "Product" offered by the CRM team the request is related to</description>
    <inlineHelpText>Add to which "Product" offered by the CRM team the request is related to</inlineHelpText>
    <label>Teamforce Product</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Teamforce_Products</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>BEX</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Distributor Markets</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ: DE</fullName>
        </value>
        <value>
          <fullName>HQ: NL</fullName>
        </value>
        <value>
          <fullName>HQ: SE</fullName>
        </value>
        <value>
          <fullName>Hungary</fullName>
        </value>
        <value>
          <fullName>India</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Jordan</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>related_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>CRM Requests</relationshipLabel>
    <relationshipName>CRM_Requests</relationshipName>
    <type>Lookup</type>
  </fields>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Albania</fullName>
        </value>
        <value>
          <fullName>Algeria</fullName>
        </value>
        <value>
          <fullName>Argentina</fullName>
        </value>
        <value>
          <fullName>Armenia</fullName>
        </value>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Azerbaijan</fullName>
        </value>
        <value>
          <fullName>Bahrain</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Bosnia and Herzegovina</fullName>
        </value>
        <value>
          <fullName>Botswana</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Bulgaria</fullName>
        </value>
        <value>
          <fullName>Cambodia</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Chile</fullName>
        </value>
        <value>
          <fullName>China</fullName>
        </value>
        <value>
          <fullName>Colombia</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Ecuador</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Full_Name__c</fullName>
    <description>Used instead of having to add First and Last Name when grouping in report</description>
    <formula>FirstName &amp; " " &amp; LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula field</inlineHelpText>
    <label>Full Name</label>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG Users</label>
        </value>
        <value>
          <fullName>Afghanistan  AFG</fullName>
        </value>
        <value>
          <fullName>Albania  ALB</fullName>
        </value>
        <value>
          <fullName>Algeria  DZA</fullName>
        </value>
        <value>
          <fullName>Argentina  ARG</fullName>
        </value>
        <value>
          <fullName>Armenia  ARM</fullName>
        </value>
        <value>
          <fullName>Australia AUS</fullName>
        </value>
        <value>
          <fullName>Austria  AUT</fullName>
        </value>
        <value>
          <fullName>Bahamas  BHS</fullName>
        </value>
        <value>
          <fullName>Bahrain  BHR</fullName>
        </value>
        <value>
          <fullName>Bangladesh  BGD</fullName>
        </value>
        <value>
          <fullName>Barbados  BRB</fullName>
        </value>
        <value>
          <fullName>Belarus  BLR</fullName>
        </value>
        <value>
          <fullName>Belgium  BEL</fullName>
        </value>
        <value>
          <fullName>Belize  BLZ</fullName>
        </value>
        <value>
          <fullName>Bermuda  BMU</fullName>
        </value>
        <value>
          <fullName>Bhutan  BTN</fullName>
        </value>
        <value>
          <fullName>Bolivia BOL</fullName>
        </value>
        <value>
          <fullName>Bosnia and Herzegovina  BIH</fullName>
        </value>
        <value>
          <fullName>Botswana  BWA</fullName>
        </value>
        <value>
          <fullName>Brazil  BRA</fullName>
        </value>
        <value>
          <fullName>Bulgaria  BGR</fullName>
        </value>
        <value>
          <fullName>Burundi  BDI</fullName>
        </value>
        <value>
          <fullName>Cambodia  KHM</fullName>
        </value>
        <value>
          <fullName>Cameroon  CMR</fullName>
        </value>
        <value>
          <fullName>Canada  CAN</fullName>
        </value>
        <value>
          <fullName>Cape Verde  CPV</fullName>
        </value>
        <value>
          <fullName>Cayman Islands  CYM</fullName>
        </value>
        <value>
          <fullName>Central African Republic  CAF</fullName>
        </value>
        <value>
          <fullName>Chad TCD</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Product2.object
<CustomObject>
  <fields>
    <fullName>Article__c</fullName>
    <externalId>true</externalId>
    <label>Article (SKU)</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Full_Name__c</fullName>
    <formula>FirstName&amp;" "&amp;LastName</formula>
    <label>Full Name</label>
    <type>Text</type>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/ServiceCloud_TestClass.cls
@isTest
public class ServiceCloud_TestClass {

    @isTest
    private static void Case_Test(){
        
    	
        Account acc = new Account(Name='Test account 1', CurrencyIsoCode = 'EUR', Country__c = 'NL');
        insert acc;
        
        Contact con = new Contact(LastName='Testsson', Firstname='Test', Account = acc);
        insert con;
        
        Country__c country = new Country__c(name='australia',Country__c = 'AUS',Country_Name__c = 'Australia AUS');
        insert country;
        
        Case c = new Case(Subject='Test case', ContactId = con.Id, AccountId = acc.Id, OwnerId = UserInfo.getUserId(),Teamforce_Product__c= 'Events',related_Country__c=country.Id);
        insert c;       
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(c);
         
        Case cInfo = ServiceCloud_Case.getCaseInfo(c.Id);
        
        System.AssertEquals(cInfo.OwnerId, UserInfo.getUserId());
        
        List<Case> cList = ServiceCloud_Case.getMyOpenCases();
        
        System.AssertEquals(cList.size(), 1);
        
        
        Pricebook2 p = new Pricebook2();
        p.Name = 'Test pricebook';
        p.CurrencyIsoCode = 'EUR';
        p.IsActive = true;
        
        insert p;
                
        System.AssertNotEquals(p.Id, null);
        
        
        Order order1 = DC_UT_DataUtils.generateOrder(acc.Id, Date.today(), 'EUR');        
        order1.Pricebook2Id = p.Id;
        insert order1;
        
        List<Order> oList = ServiceCloud_Case.getOrders(acc.Id);
        
        System.AssertEquals(oList.size(), 1);
        
        Order o = ServiceCloud_Case.findOrderDetails(order1.Id);
        
        System.AssertNotEquals(o.OrderNumber, '');
        
        
        Product2 prod = new Product2();
        prod.Article__c = 'Test_article';
        prod.Name = 'Test product';
        prod.Description = 'Description';
        prod.IsActive = true;
        prod.CurrencyIsoCode ='EUR';

        insert prod;        
        
        System.AssertNotEquals(prod.Id, null);
        
        PricebookEntry pStandard= new PricebookEntry();
        pStandard.Pricebook2Id = Test.getStandardPricebookId();
        pStandard.Product2Id = prod.Id;
        pStandard.UnitPrice = 100;
        pStandard.CurrencyIsoCode = 'EUR';
        pStandard.IsActive = true;
        
        insert pStandard;
        
        PricebookEntry pEntry= new PricebookEntry();
        pEntry.Pricebook2Id = p.Id;
        pEntry.Product2Id = prod.Id;
        pEntry.UnitPrice = 100;
        pEntry.CurrencyIsoCode = 'EUR';
        pEntry.IsActive = true;
        
        insert pEntry;
                
        System.AssertNotEquals(pEntry.Id, null);        
        
        OrderItem oItem = new OrderItem();        
        if(pEntry.Id != null){
        oItem.PricebookEntryId = pEntry.Id;
        oItem.OrderId = o.Id;
        oItem.UnitPrice = 100;
        oItem.Quantity = 1;
        
        insert oItem;
        }
            
        List<OrderItem> oDetails = ServiceCloud_Case.findOrderRows(o.Id);
        System.AssertEquals(oDetails.size(), 1);
        
        List<SC_Case_Questionnaire__mdt> questions= ServiceCloud_Case.findQuestions();
        System.AssertNotEquals(questions.size(), 0);
        
        List<SC_Case_Questionnaire__mdt> specQuestions= ServiceCloud_Case.findSpecificQuestions('Order Processing','Software Complaint');
        System.AssertNotEquals(questions.size(), 0);
    }
    
    
    //Tests of class ServiceCloud_Contact
    
    @isTest
    private static void Contact_Test(){
    
        Account acc = new Account(Name='Test account 1', CurrencyIsoCode = 'EUR', Country__c = 'NL');
        insert acc;
        
        Contact con = new Contact(LastName='Testsson', Firstname='Test', Account = acc);
        insert con;
        
        Country__c country = new Country__c(name='australia',Country__c = 'AUS',Country_Name__c = 'Australia AUS');
        insert country;
        
        Case c = new Case(Subject='Test case', ContactId = con.Id, AccountId = acc.Id, OwnerId = UserInfo.getUserId(),Teamforce_Product__c= 'Events',related_Country__c=country.Id);
        insert c;  
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(c);
         
        Contact cInfo = ServiceCloud_Contact.getContactInfo(con.Id);
        
        System.AssertNotEquals(cInfo.Name, '');
        
        List<Case> openCases = ServiceCloud_Contact.getOpenCases(con.Id);
        
        System.assertEquals(openCases.size(), 1);
        
        Map<String, String> caseLabels = ServiceCloud_Contact.getCaseFieldLabels();
        
        System.assertNotEquals(caseLabels.size(), 0);
        
    }
    
    
    //Tests of class ServiceCloud_Account
    
    @isTest
    private static void Account_Test(){
            
        Account acc = new Account(Name='Test account 1', CurrencyIsoCode = 'EUR', Country__c = 'NL');
        insert acc;
        
        Contact con = new Contact(LastName='Testsson', Firstname='Test', Account = acc);
        insert con;
        
        Country__c country = new Country__c(name='australia',Country__c = 'AUS',Country_Name__c = 'Australia AUS');
        insert country;
        
        Case c = new Case(Subject='Test case', ContactId = con.Id, AccountId = acc.Id, OwnerId = UserInfo.getUserId(),Teamforce_Product__c= 'Events',related_Country__c=country.Id);
        insert c;      
         
        Account aInfo = ServiceCloud_Account.getAccountInfo(acc.Id);
        
        System.AssertNotEquals(aInfo.Name, '');
        
        List<Case> openCases = ServiceCloud_Account.getOpenCases(acc.Id);
        
        System.assertEquals(openCases.size(), 1); 
        
    }
    
    @isTest
    private static void Account_ETM_Test(){
        
        list<Territory2Type> terriType = [SELECT id, DeveloperName from Territory2Type];
        List<Territory2Model> terrModel = [SELECT Id, DeveloperName FROM Territory2Model WHERE State =: 'Active'];
        List<Territory2> terList = [SELECT Id, DeveloperName FROM Territory2 WHERE Territory2ModelId =: terrModel[0].Id AND Territory2TypeId =: terriType[0].Id];
        
        /*Territory2 ter = new Territory2();
        ter.DeveloperName = 'TestTerritory';
        ter.Territory2ModelId = terrModel[0].Id;
        ter.Name='TestTerritory';
        ter.Territory2TypeId=terriType[0].Id;        
        insert ter;*/

        Account acc = new Account(Name='Test account 1', CurrencyIsoCode = 'EUR', Country__c = 'NL');
        insert acc;
        
        List<UserTerritory2Association> user2ter0 = ServiceCloud_Account.getTerritoryInfo(acc.Id);
        
        System.assertEquals(user2ter0, null);
        
        ObjectTerritory2Association acc2ter = new ObjectTerritory2Association();
        acc2ter.ObjectId = acc.Id;
        acc2ter.Territory2Id = terList[0].Id;
        acc2ter.AssociationCause = 'Territory2Manual';
        insert acc2ter;
        
        List<UserTerritory2Association> user2ter = ServiceCloud_Account.getTerritoryInfo(acc.Id);
        /*user2ter.Territory2Id = terList[0].Id;
        user2ter.UserId = UserInfo.getUserId();
        insert user2ter;*/
        
    } 
    
    //Test of ServiceCloud_FlowLookupController
    
    @isTest
    private static void FlowLookup_Test(){
    
    String res = ServiceCloud_FlowLookupController.searchDB('User', 'Name', 'Id', 10, 'Name', '');           
            
    }
    
    
    @isTest
    private static void FlowLookup_Test_ver2(){
    
    String res = ServiceCloud_FlowLookupController_ver2.searchDB('User', 'Name', 'Id', 10, 'Name', '','Full_Name__c');           
    
    String resExact = ServiceCloud_FlowLookupController_ver2.searchDBexact('User', 'Name', 'Id', 10, 'Name', '','User_Country__c');
        
    }
    
    
    @isTest
    private static void Flow_Case_Test(){
    
        Account acc = new Account(Name='Test account 1', CurrencyIsoCode = 'EUR', Country__c = 'NL');
        insert acc;
        
        Contact con = new Contact(LastName='Testsson', Firstname='Test', Account = acc);
        insert con;
        
        Country__c country = new Country__c(name='australia',Country__c = 'AUS',Country_Name__c = 'Australia AUS');
        insert country;
        
        Case c = new Case(Subject='Test case', ContactId = con.Id, AccountId = acc.Id, OwnerId = UserInfo.getUserId(),Teamforce_Product__c= 'Events',related_Country__c=country.Id);
        insert c;
        
        Case res = ServiceCloud_FlowLookupController_ver2.getCaseInfo(c.Id);
        
    }    
    
}