unpackaged/objects/Case.object
<CustomObject>
  <fields>
    <fullName>Assign_To__c</fullName>
    <label>Assign To</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>User_Country__c</controllingField>
      <valueSetDefinition>
        <value>
          <fullName>Me</fullName>
        </value>
        <value>
          <fullName>Previous Owner</fullName>
        </value>
        <value>
          <fullName>Case Creator</fullName>
        </value>
        <value>
          <fullName>00G0J000003GzvNUAS</fullName>
          <label>Queue: US Guide Tier 2 Support</label>
        </value>
        <value>
          <fullName>00G0J000003GzvMUAS</fullName>
          <label>Queue: US Atlantis Tier 2 Support</label>
        </value>
        <value>
          <fullName>00G0J000003GzvOUAS</fullName>
          <label>Queue: US Manager Support</label>
        </value>
        <value>
          <fullName>00G0J000003GzvPUAS</fullName>
          <label>Queue: US Tier 3 Waltham Atlantis IT</label>
        </value>
        <value>
          <fullName>00G200000013dpIEAQ</fullName>
          <label>Queue: IMPL - Simplant Support 3rd</label>
        </value>
        <value>
          <fullName>00G20000002uPo9EAE</fullName>
          <label>Queue: IMPL - Control Tower</label>
        </value>
        <value>
          <fullName>00G20000002uPoEEAU</fullName>
          <label>Queue: IMPL - ATL Europe</label>
        </value>
        <value>
          <fullName>00G20000002uV5REAU</fullName>
          <label>Queue: IMPL - ATL Supra Support 2nd</label>
        </value>
        <value>
          <fullName>00G0J000003H1b0UAC</fullName>
          <label>Queue: IMPL - Azento Support 2nd</label>
        </value>
        <value>
          <fullName>00G200000013cadEAA</fullName>
          <label>Queue: IMPL - Simplant Support 2nd</label>
        </value>
        <value>
          <fullName>00G20000002uPoJEAU</fullName>
          <label>Queue: IMPL - Venlo Warehouse</label>
        </value>
        <value>
          <fullName>00G0J000002twr9UAA</fullName>
          <label>Queue: DE: DI - ATLANTIS Support</label>
        </value>
        <value>
          <fullName>00G200000013jSGEAY</fullName>
          <label>Queue: DE: DI - Service Complaint</label>
        </value>
        <value>
          <fullName>00G200000013d44EAA</fullName>
          <label>Queue: DE: DI - SIMPLANT Support</label>
        </value>
        <value>
          <fullName>00G0J000002tx8AUAQ</fullName>
          <label>Queue: DE: Product Improvements</label>
        </value>
        <value>
          <fullName>00G20000002uStfEAE</fullName>
          <label>Queue: DE: Retouren Gutschrift</label>
        </value>
        <value>
          <fullName>00G20000002uStpEAE</fullName>
          <label>Queue: DE: Service Reklamationen</label>
        </value>
        <value>
          <fullName>00G20000002uStkEAE</fullName>
          <label>Queue: DE: UPS Rückholung</label>
        </value>
        <value>
          <fullName>00G20000002uStuEAE</fullName>
          <label>Queue: DE: Web-Shop</label>
        </value>
        <value>
          <fullName>00G20000002uStaEAE</fullName>
          <label>Queue: DE: Wert Gutschrift</label>
        </value>
        <value>
          <fullName>00G6M000004GTcqUAG</fullName>
          <label>Queue: UK/IE: CS - IMPL</label>
        </value>
        <value>
          <fullName>00G6M000004GTcvUAG</fullName>
          <label>Queue: UK/IE: CS - PRE</label>
        </value>
        <value>
          <fullName>00G6M000004GTd0UAG</fullName>
          <label>Queue: UK/IE: CS - SuperUser</label>
        </value>
        <value>
          <fullName>00G6M000004GUc8UAG</fullName>
          <label>Queue: SureSmile - Engineering</label>
        </value>
        <value>
          <fullName>00G6M000004GUcNUAW</fullName>
          <label>Queue: SureSmile - Mfg Richardson</label>
        </value>
        <value>
          <fullName>00G6M000004GUcIUAW</fullName>
          <label>Queue: SureSmile - Mfg Mexicali</label>
        </value>
        <value>
          <fullName>00G6M000004GUc3UAG</fullName>
          <label>Queue: SureSmile - Digital Lab</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Support_Email__c</fullName>
    <label>Support Email</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>BEX</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Distributor Markets</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ: DE</fullName>
        </value>
        <value>
          <fullName>HQ: NL</fullName>
        </value>
        <value>
          <fullName>HQ: SE</fullName>
        </value>
        <value>
          <fullName>Hungary</fullName>
        </value>
        <value>
          <fullName>India</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Jordan</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>true</active>
    <businessProcess>Credit and Rebill</businessProcess>
    <description>Used by the Implants Division to track and approve the credit and Credit/Rebill process</description>
    <fullName>Credits_and_Re_bills</fullName>
    <label>Credits and Rebills</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/Test_CasePB.cls
/*------------------------------------------------------------
Author: 		Ahmed LOUDRASSI (Salesforce) 2019-11-28
Description:   	Test Class for the Case Process Builder.
History
<Date>      <Authors Name>     <Brief Description of Change>

------------------------------------------------------------*/

@isTest(seeAllData=false)
public class Test_CasePB {
	/*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
    }
    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();

        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }
    @isTest
    private static void testAssignToEqualsMe() {
       	User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Case> cases = TestDataFactory.returnCases(1, 'Credits_and_Re_bills', testUser.Id);
        cases.get(0).User_Country__c = 'Germany';
        cases.get(0).Assign_To__c = 'Me';
        Test.startTest();
        insert cases;
        Test.stopTest(); 
        Case testCase = [SELECT Id, OwnerId, Assign_To__c FROM Case WHERE Subject = 'TestCase'];
        System.assertEquals(null, testCase.Assign_To__c);
        System.assertEquals(UserInfo.getUserId(), testCase.OwnerId);
    }
    @isTest
    private static void testAssignToEqualsPreviousOwner() {
       	User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Case> cases = TestDataFactory.returnCases(1, 'Credits_and_Re_bills', testUser.Id);
        cases.get(0).User_Country__c = 'Germany';
        cases.get(0).Assign_To__c = 'Previous Owner';
        Test.startTest();
        insert cases;
        Test.stopTest();
        System.assertEquals(null, [SELECT Id, Assign_To__c FROM Case WHERE Subject = 'TestCase'].Assign_To__c);
    }
    @isTest
    private static void testE2CSupportEmail() {
        System.runAs(new User(Id = UserInfo.getUserId())) {
            List<Group> queues = TestDataFactory.createQueues(1, 'Case');
            Group queue = queues.get(0);
            User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
            List<Case> cases = TestDataFactory.returnCases(1, 'Credits_and_Re_bills', queue.Id);
            cases.get(0).Origin = 'Support email';
            Test.startTest();
            insert cases;
            Test.stopTest();
            //System.assertEquals(queue.Name, [SELECT Id, Support_Email__c FROM Case WHERE Subject = 'TestCase'].Support_Email__c);
        }
    }
}