unpackaged/objects/Coaching_Feedback_Report__c.object
<CustomObject>
  <description>Used to capture and track co-travels and meetings reports</description>
  <fields>
    <fullName>Date_of_Meeting__c</fullName>
    <label>Date of Meeting</label>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Report_Type__c</fullName>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Coaching/Co-Travel</fullName>
        </value>
        <value>
          <fullName>Planning Meeting</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Coaching_Feedback_Reports1</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Sales_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Coaching_Feedback_Reports</relationshipName>
    <type>Lookup</type>
  </fields>
  <label>Coaching/Feedback Report</label>
  <nameField>
    <label>Coaching/Feedback Report Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Coaching/Feedback Reports</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Type__c</fullName>
    <inlineHelpText>Sales Representative  = District Managers, Territory Managers, Account Managers

Sales Manager = Regional Sales Mgrs, Division Sales Mgrs, National Sales Mgrs</inlineHelpText>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Account Maintenance Team Member</fullName>
        </value>
        <value>
          <fullName>Area Sales Manager</fullName>
        </value>
        <value>
          <fullName>Clinical Affairs</fullName>
        </value>
        <value>
          <fullName>Complaints Handling</fullName>
        </value>
        <value>
          <fullName>Customer Service</fullName>
        </value>
        <value>
          <fullName>Finance</fullName>
        </value>
        <value>
          <fullName>Inside Sales Representative</fullName>
        </value>
        <value>
          <fullName>Key Account Manager</fullName>
        </value>
        <value>
          <fullName>Managing Director</fullName>
        </value>
        <value>
          <fullName>Marketing</fullName>
        </value>
        <value>
          <fullName>National Admin</fullName>
        </value>
        <value>
          <fullName>Operations</fullName>
        </value>
        <value>
          <fullName>Other</fullName>
        </value>
        <value>
          <fullName>Product Manager</fullName>
        </value>
        <value>
          <fullName>Regional Sales Manager</fullName>
        </value>
        <value>
          <fullName>Sales Manager</fullName>
        </value>
        <value>
          <fullName>Sales Representative</fullName>
        </value>
        <value>
          <fullName>Training &amp; Event Management</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/CoachingReportShareTest.cls
@isTest
public class CoachingReportShareTest {
    @TestSetup
    static void makeData(){
        User u1 = new User(ProfileId = [SELECT Id FROM Profile WHERE Name = 'Lightning Sales Rep'].Id,LastName = 'last01',Email = 'puser0001@dentsplysirona.com',Username = 'puser0012@dentsplysirona.com' + System.currentTimeMillis(),
                            CompanyName = 'TEST',Title = 'title',Alias = 'alias01',TimeZoneSidKey = 'America/Los_Angeles',EmailEncodingKey = 'UTF-8',LanguageLocaleKey = 'en_US',LocaleSidKey = 'en_US',
                            User_Type__c='Sales Manager',User_Country__c='INDIA');
        insert u1;
        
        User u2 = new User(ProfileId = [SELECT Id FROM Profile WHERE Name = 'Lightning Sales Rep'].Id,LastName = 'last02',Email = 'puser0002@dentsplysirona.com',Username = 'puser0002@dentsplysirona.com' + System.currentTimeMillis(),
                            CompanyName = 'TEST',Title = 'title',Alias = 'alias02',TimeZoneSidKey = 'America/Los_Angeles',EmailEncodingKey = 'UTF-8',LanguageLocaleKey = 'en_US',LocaleSidKey = 'en_US',
                            User_Type__c='Sales Representative',User_Country__c='INDIA');
        insert u2;
    }

    static testMethod void CoachingReportShareToRep() 
    {        
        User u = [SELECT Id FROM User WHERE Email = 'puser0001@dentsplysirona.com' LIMIT 1];
        Test.startTest();                    
      
        Coaching_Feedback_Report__c coreport= new Coaching_Feedback_Report__c();
        coreport.Sales_Representative__c=u.Id;
        coreport.Report_Type__c='Coaching/Co-Travel';
        coreport.Date_of_Meeting__c=Date.newInstance(2019, 12, 9);
        
        insert coreport;
        System.debug('coaching report record%%%%%%%%%%%'+coreport);
        Test.StopTest();
        
        List<Coaching_Feedback_Report__share> coachingShare = [SELECT Id, UserOrGroupId, AccessLevel,RowCause FROM Coaching_Feedback_Report__share WHERE ParentId = :coreport.Id AND UserOrGroupId= :u.Id];
       // Test for only one manual share on job.
        System.assertEquals(coachingShare.size(), 1);
       // Test attributes of manual share.
          System.assertEquals(coachingShare[0].AccessLevel, 'Edit');
          System.assertEquals(coachingShare[0].RowCause, 'Manual');
          System.assertEquals(coachingShare[0].UserOrGroupId, u.id);
    }
    
     static testMethod void CoachingReportShareToManager() 
    {        
        User u = [SELECT Id FROM User WHERE Email = 'puser0001@dentsplysirona.com' LIMIT 1];
        
        Test.startTest();                    
        Coaching_Feedback_Report__c coreport= new Coaching_Feedback_Report__c();
        coreport.Sales_Manager__c=u.Id;
        coreport.Report_Type__c='Coaching/Co-Travel';
        coreport.Date_of_Meeting__c=Date.newInstance(2019, 12, 9);
        
        insert coreport;
        System.debug('coaching report record%%%%%%%%%%%'+coreport);
        Test.StopTest();
        
        List<Coaching_Feedback_Report__share> coachingShare = [SELECT Id, UserOrGroupId, AccessLevel,RowCause FROM Coaching_Feedback_Report__share WHERE ParentId = :coreport.Id AND UserOrGroupId= :u.Id];
       // Test for only one manual share on job.
        System.assertEquals(coachingShare.size(), 1);
       // Test attributes of manual share.
          System.assertEquals(coachingShare[0].AccessLevel, 'Edit');
          System.assertEquals(coachingShare[0].RowCause, 'Manual');
          System.assertEquals(coachingShare[0].UserOrGroupId, u.id);
    }
    
    static testMethod void CoachingReportShareToBoth() 
    {        
        User u1 = [SELECT Id FROM User WHERE Email = 'puser0001@dentsplysirona.com' LIMIT 1];
        
        User u2 = [SELECT Id FROM User WHERE Email = 'puser0002@dentsplysirona.com' LIMIT 1];
        
        Test.startTest();                    
        Coaching_Feedback_Report__c coreport= new Coaching_Feedback_Report__c();
        coreport.Sales_Manager__c=u1.Id;
        coreport.Sales_Representative__c=u2.Id;
        coreport.Report_Type__c='Coaching/Co-Travel';
        coreport.Date_of_Meeting__c=Date.newInstance(2019, 12, 9);
        
        insert coreport;
        System.debug('coaching report record%%%%%%%%%%%'+coreport);
        Test.StopTest();
        
        List<Coaching_Feedback_Report__share> coachingShare = [SELECT Id, UserOrGroupId, AccessLevel,RowCause FROM Coaching_Feedback_Report__share WHERE ParentId = :coreport.Id AND (UserOrGroupId= :u1.Id OR UserOrGroupId= :u2.Id)];
       // Test for only one manual share on job.
        System.assertEquals(coachingShare.size(), 2);
       // Test attributes of manual share.
          System.assertEquals(coachingShare[0].AccessLevel, 'Edit');
          System.assertEquals(coachingShare[0].RowCause, 'Manual');
          System.assertEquals(coachingShare[0].UserOrGroupId, u1.id);
          System.assertEquals(coachingShare[1].UserOrGroupId, u2.id);
    }
 }