unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Test</fullName>
        </value>
        <value>
          <fullName>Global Pick List</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Non_ERP_Products__c.object
<CustomObject>
  <fields>
    <fullName>Competitor_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Competitor Product</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>KeyProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Focus Product</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Manufacturer__c</fullName>
    <label>Manufacturer</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Market__c</fullName>
    <formula>IF(TEXT( Product_Market_Mapping__r.Market__c )='IT', 'Italy',IF(TEXT( Product_Market_Mapping__r.Market__c )='ES', 'Iberia', TEXT(Product_Market_Mapping__r.Market__c)))</formula>
    <label>Market</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Product_Category__c</fullName>
    <description>Free Text, optional</description>
    <inlineHelpText>This field controls the grouping of records in the Product Profiling component on Accounts/Contacts</inlineHelpText>
    <label>Product Group (Local)</label>
    <length>250</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Product_Market_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Market Mapping</label>
    <referenceTo>SSIS_ERP_SKU_Metadata_Country_Connectio__c</referenceTo>
    <relationshipName>Products_Profiling</relationshipName>
    <type>Lookup</type>
  </fields>
  <label>Non-ERP Products</label>
  <nameField>
    <label>Product Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Non-ERP Products</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Product_Profiling__c.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products Profiling</relationshipLabel>
    <relationshipName>Products_Profiling</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Competitor_Product__c</fullName>
    <formula>Product_Name__r.Competitor_Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Competitor Product</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Products Profiling</relationshipLabel>
    <relationshipName>Products_Profiling</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Manufacturer__c</fullName>
    <formula>Product_Name__r.Manufacturer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Manufacturer</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Product_Category__c</fullName>
    <formula>Product_Name__r.Product_Category__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <referenceTo>Non_ERP_Products__c</referenceTo>
    <relationshipLabel>Products Profiling</relationshipLabel>
    <relationshipName>Products_Profiling</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
  </fields>
  <label>Product Profiling</label>
  <nameField>
    <displayFormat>PP{000000000}</displayFormat>
    <label>Profiling Id</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Products Profiling</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/SSIS_ERP_SKU_Metadata_Country_Connectio__c.object
<CustomObject>
  <description>This object manages the M:M relationships between the ERP/SKU Metadata/Company Code record and the Country/Global Setting record</description>
  <fields>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is checked the connection between Company code and the country is active.</description>
    <inlineHelpText>If this field is checked the connection between Company code and the country is active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Market</valueSetName>
    </valueSet>
  </fields>
  <label>SSIS: ERP/SKU - Market Mapping</label>
  <nameField>
    <displayFormat>{00000000}</displayFormat>
    <label>SSIS: ERP/SKU Metadata Country Connectio</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>SSIS_ERP_SKU_Market_Mappings</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Market__c</fullName>
    <description>&lt;ADMINISTRATION&gt; Keep the values of this field aligned with the Price Book Market field values.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>BeNelux</fullName>
        </value>
        <value>
          <fullName>BEX</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>CEE</fullName>
        </value>
        <value>
          <fullName>China</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ</fullName>
        </value>
        <value>
          <fullName>Iberia</fullName>
        </value>
        <value>
          <fullName>India</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Korea</fullName>
        </value>
        <value>
          <fullName>Malaysia</fullName>
        </value>
        <value>
          <fullName>MEA</fullName>
        </value>
        <value>
          <fullName>NA</fullName>
        </value>
        <value>
          <fullName>Nordics</fullName>
        </value>
        <value>
          <fullName>Poland</fullName>
        </value>
        <value>
          <fullName>Russia</fullName>
        </value>
        <value>
          <fullName>Singapore</fullName>
        </value>
        <value>
          <fullName>South Africa</fullName>
        </value>
        <value>
          <fullName>Switzerland</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/Test_ProductProfilingHierarchyController.cls
/*------------------------------------------------------------	
Author: 		Richard Trum (Glimt) 2019-11-28 	
Description:   	Test class related to the class ProductProfilingHierarchyController
------------------------------------------------------------*/

@isTest
private class Test_ProductProfilingHierarchyController {
	
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator'); 
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();
    }
    
    @isTest
    private static void testERPProducts(){
    
        User currentUser = TestDataFactory.createUsers(1, 'System Administrator')[0]; 
        system.runAs(currentUser){
            Account acc = new Account();
            acc.Name ='Test account';
            insert acc;
            
            Contact con = new Contact();
            con.FirstName = 'Test';
            con.LastName = 'Test';
            con.AccountId = acc.Id;
            insert con;
            
            SSIS_ERP_SKU_Metadata_Country_Connectio__c pmm = new SSIS_ERP_SKU_Metadata_Country_Connectio__c();
            pmm.Market__c = currentUser.Market__c;
            pmm.Active__c = true;
            insert pmm;
            
            Non_ERP_Products__c ERP = new Non_ERP_Products__c();
            ERP.Name = 'Test product';
            ERP.Competitor_Product__c = false;
            ERP.KeyProduct__c = true;
            ERP.Product_Category__c = 'Implants';
            ERP.Product_Market_Mapping__c = pmm.Id;
            insert ERP;
            
            Product_Profiling__c prodP = new Product_Profiling__c();
            prodP.Product_Name__c = ERP.Id;
            prodP.Account__c = acc.Id;
            prodP.Contact__c = con.Id;
            insert prodP;
            
            Test.startTest();
            
            List<ProductProfilingHierarchyController.HierarchyNode> res = ProductProfilingHierarchyController.getAllProducts(acc.Id);
            System.assertEquals(res.size(), 1);
            
            Map<Id, Product_Profiling__c> resMapAcc = ProductProfilingHierarchyController.getProductProfilingMap(acc.Id);
            System.assertNotEquals(resMapAcc, null);
            
            Map<Id, Product_Profiling__c> resMapCon = ProductProfilingHierarchyController.getProductProfilingMap(con.Id);
            System.assertNotEquals(resMapCon, null);
            
            List<Product_Profiling__c> resAcc = ProductProfilingHierarchyController.getProductProfiling(acc.Id);
            System.assertNotEquals(resAcc, null);
            
            List<Product_Profiling__c> resCon = ProductProfilingHierarchyController.getProductProfiling(con.Id);
            System.assertNotEquals(resCon, null);
            
            Test.stopTest();
        }
        
        
    }

    @isTest
    private static void testDistinctValues(){
    
        User currentUser = TestDataFactory.createUsers(1, 'System Administrator')[0]; 
        system.runAs(currentUser){
            Account acc = new Account();
            acc.Name ='Test account';
            insert acc;
            
            Contact con = new Contact();
            con.FirstName = 'Test';
            con.LastName = 'Test';
            con.AccountId = acc.Id;
            insert con;
            
            SSIS_ERP_SKU_Metadata_Country_Connectio__c pmm = new SSIS_ERP_SKU_Metadata_Country_Connectio__c();
            pmm.Market__c = currentUser.Market__c;
            pmm.Active__c = true;
            insert pmm;
            
            Non_ERP_Products__c ERP = new Non_ERP_Products__c();
            ERP.Name = 'Test product';
            ERP.Competitor_Product__c = false;
            ERP.KeyProduct__c = true;
            ERP.Product_Category__c = 'Implants';
            ERP.Product_Market_Mapping__c = pmm.Id;
            ERP.Manufacturer__c = 'DentsplySirona';
            insert ERP;
            
            Product_Profiling__c prodP = new Product_Profiling__c();
            prodP.Product_Name__c = ERP.Id;
            prodP.Account__c = acc.Id;
            prodP.Contact__c = con.Id;
            insert prodP;
            
            Test.startTest();
            
            List<String> res = ProductProfilingHierarchyController.getDistinctValues('Manufacturer__c', acc.Id);
            System.assertEquals(res.size(), 1);
            
            Boolean deleted = ProductProfilingHierarchyController.deleteProductProfilingRecord(prodP.Id);
                                    
            Test.stopTest();
        }
        
        
    }
    
    
    
}