unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Albania</fullName>
        </value>
        <value>
          <fullName>Algeria</fullName>
        </value>
        <value>
          <fullName>Argentina</fullName>
        </value>
        <value>
          <fullName>Armenia</fullName>
        </value>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Azerbaijan</fullName>
        </value>
        <value>
          <fullName>Bahrain</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Bosnia and Herzegovina</fullName>
        </value>
        <value>
          <fullName>Botswana</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Bulgaria</fullName>
        </value>
        <value>
          <fullName>Cambodia</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Chile</fullName>
        </value>
        <value>
          <fullName>China</fullName>
        </value>
        <value>
          <fullName>Colombia</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Ecuador</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To identify whether a Contact is Inactive or Active</description>
    <inlineHelpText>Check this checkbox if the contact is either retired, deceased or has left position/post</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <description>TFUS-000002053</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Inactive</fullName>
        </value>
        <value>
          <fullName>GDPR – Forget</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Non_ERP_Products__c.object
<CustomObject>
  <fields>
    <fullName>Competitor_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Competitor Product</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Countries__c</fullName>
    <label>Countries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_2_digit</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactive</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>KeyProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Focus Product</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Manufacturer__c</fullName>
    <label>Manufacturer</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>ProductGroupText__c</fullName>
    <label>Product Group (Global)</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Product_Category__c</fullName>
    <description>Free Text, optional</description>
    <inlineHelpText>This field controls the grouping of records in the Product Profiling component on Accounts/Contacts</inlineHelpText>
    <label>Product Group (Local)</label>
    <length>250</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>QuantityUnitOfMeasure__c</fullName>
    <label>Quantity Unit Of Measure</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>pieces</fullName>
          <label>pcs</label>
        </value>
        <value>
          <fullName>pieces/month</fullName>
        </value>
        <value>
          <fullName>pieces/year</fullName>
        </value>
        <value>
          <fullName>boxes</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>SBU__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>CADCAM</fullName>
          <label>CAD/CAM</label>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Imaging</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Labratory</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <description>Used for Japan</description>
    <label>Stock Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Stock Only(Part)</fullName>
        </value>
        <value>
          <fullName>Stock Only</fullName>
        </value>
        <value>
          <fullName>End of Sales(Part)</fullName>
        </value>
        <value>
          <fullName>End of Sales</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Valid_in_my_Market__c</fullName>
    <formula>IF(UPPER(TEXT($User.Market__c))=UPPER(TEXT(Product_Market_Mapping__r.Market__c)), True, 
IF(TEXT($User.Market__c)="South Africa" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="ZA",True,
IF(TEXT($User.Market__c)="Iberia" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="ES",True,
IF(TEXT($User.Market__c)="Thailand" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="TH",True,
IF(TEXT($User.Market__c)="Australia" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="AU",True,
IF(TEXT($User.Market__c)="Hong Kong" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="HK",True,
IF(TEXT($User.Market__c)="Singapore" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="SG",True,
IF(TEXT($User.Market__c)="Germany" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="DE",True,
IF(TEXT($User.Market__c)="Austria" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="AT",True,
IF(TEXT($User.Market__c)="Switzerland" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="DE",True,
IF(TEXT($User.Market__c)="France" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="FR",True,
IF(TEXT($User.Market__c)="Italy" &amp;&amp; TEXT(Product_Market_Mapping__r.Market__c)="IT",True,False)/*italy, iberia &amp; south africa exception*/
)))))))))))</formula>
    <label>Valid in my Market?</label>
    <type>Checkbox</type>
  </fields>
  <label>Non-ERP Products</label>
  <nameField>
    <label>Product Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Non-ERP Products</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Contact.AccountId</field>
        <operation>equals</operation>
        <valueField>$Source.AccountId</valueField>
      </filterItems>
      <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Product_Profiling__c.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products Profiling</relationshipLabel>
    <relationshipName>Products_Profiling</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Competitor_Product__c</fullName>
    <formula>Product_Name__r.Competitor_Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Competitor Product</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Products Profiling</relationshipLabel>
    <relationshipName>Products_Profiling</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Manufacturer__c</fullName>
    <formula>Product_Name__r.Manufacturer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Manufacturer</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Product_Category__c</fullName>
    <formula>Product_Name__r.Product_Category__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <referenceTo>Non_ERP_Products__c</referenceTo>
    <relationshipLabel>Products Profiling</relationshipLabel>
    <relationshipName>Products_Profiling</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
  </fields>
  <fields>
    <fullName>Quantity__c</fullName>
    <description>This has been requested in case 00144434.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Prospect</fullName>
        </value>
        <value>
          <fullName>Low Usage</fullName>
        </value>
        <value>
          <fullName>Medium Usage</fullName>
        </value>
        <value>
          <fullName>High Usage</fullName>
        </value>
        <value>
          <fullName>Installed</fullName>
        </value>
        <value>
          <fullName>Not Interested</fullName>
        </value>
        <value>
          <fullName>Lapsed Usage</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Product Profiling</label>
  <nameField>
    <displayFormat>PP{000000000}</displayFormat>
    <label>Profiling Id</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Products Profiling</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ProductProfilingHierarchyController.cls
/*------------------------------------------------------------  
Author:         Richard Trum (Glimt) 2019-11-27     
Description:    Controller handling custom lightning components related to Product Profiling
------------------------------------------------------------*/

public with sharing class ProductProfilingHierarchyController {
    
    /*------------------------------------------------------------  
    Description:    AuraEnabled method to collect Non-ERP products and related child records 
                    that are related to the user's assigned market
                    Output is stored as a map
    Inputs:         
    ------------------------------------------------------------*/    
    /*@AuraEnabled
    public static Map<Id,HierarchyNode> getHierarchies() {
    
    List<Non_ERP_Products__c> allProducts = [SELECT Id, ParentProduct__c, Name, SBU__c, Competitor_Product__c, KeyProduct__c, 
                                             (SELECT Id, ParentProduct__c, Name, SBU__c, Competitor_Product__c, KeyProduct__c
                                             FROM Non_ERP_products__r) 
                                             FROM Non_ERP_Products__c WHERE (ParentProduct__c =: '' AND Valid_in_my_Market__c =: true)];
        
    Map<Id,HierarchyNode> nodes = new Map<Id,HierarchyNode>();
 
    for (Non_ERP_Products__c a : allProducts) { 
        nodes.put(a.Id, new HierarchyNode(a, false));        
    }
        
    System.debug(nodes);
        
    return nodes;
    */
    
    
    /*------------------------------------------------------------  
    Description:    AuraEnabled method to collect all Non-ERP products 
                    that are related to the user's assigned market
    Inputs:         
    ------------------------------------------------------------*/ 

    @AuraEnabled
    public static List<HierarchyNode> getAllProducts(String recordId) {
    
    String country = '';    
        if(recordId.left(3) == '003'){
            Contact con = [SELECT Id, Account.Country__c FROM Contact WHERE Id =: recordId];
        	country = con.Account.Country__c;
        }
        else{
            Account acc = [SELECT Id, Country__c FROM Account WHERE Id =: recordId];
            country = acc.Country__c;
        }
    	        
    List<Non_ERP_Products__c> allProducts = [SELECT Id, Name, Countries__c, SBU__c, Competitor_Product__c, KeyProduct__c, Product_Category__c, Manufacturer__c, ProductGroupText__c, QuantityUnitOfMeasure__c 
                                             FROM Non_ERP_Products__c WHERE Inactive__c = false AND (Countries__c INCLUDES (:country) OR Valid_in_my_Market__c =: true)];
        
    List<HierarchyNode> nodes = new List<HierarchyNode>();
 
    for (Non_ERP_Products__c a : allProducts) { 
        nodes.add(new HierarchyNode(a, false));        
    }
        
    return nodes;
    }
    
    
    /*------------------------------------------------------------  
    Description:    AuraEnabled method to collect all Product Profiling records 
                    related to either an account or a contact
    Inputs:         @param recordId - The account's or contact's recordId
    ------------------------------------------------------------*/ 
    
    @AuraEnabled
    //public static Map<Id, Product_Profiling__c> getProductProfiling(String recordId) {
    public static List<Product_Profiling__c> getProductProfiling(String recordId){
    List<Product_Profiling__c> profilings = new List<Product_Profiling__c>();
        
        if(recordId.startsWith('003')){
            profilings = [SELECT Id, Product_Name__c, Quantity__c, Product_Category__c, Product_Name__r.Id, Product_Name__r.Manufacturer__c, Product_Name__r.Product_Category__c, Product_Name__r.Name, Product_Name__r.SBU__c, Product_Name__r.Competitor_Product__c, Product_Name__r.KeyProduct__c, Product_Name__r.ProductGroupText__c, Product_Name__r.QuantityUnitOfMeasure__c, Status__c, Account__c, Contact__c, Contact__r.FirstName, Contact__r.LastName FROM Product_Profiling__c WHERE Contact__c =: recordId AND Product_Name__c!= null];    
        }
        else{
            profilings = [SELECT Id, Product_Name__c, Quantity__c, Product_Category__c, Product_Name__r.Id, Product_Name__r.Manufacturer__c, Product_Name__r.Product_Category__c, Product_Name__r.Name, Product_Name__r.SBU__c, Product_Name__r.Competitor_Product__c, Product_Name__r.KeyProduct__c, Product_Name__r.ProductGroupText__c, Product_Name__r.QuantityUnitOfMeasure__c, Status__c, Account__c, Contact__c, Contact__r.FirstName, Contact__r.LastName FROM Product_Profiling__c WHERE Account__c =: recordId  AND Product_Name__c!= null ORDER BY Contact__c ASC NULLS FIRST]; // AND Contact__c =:''    
        }
    
    /*Map<Id, Product_Profiling__c> profilingMap = new Map<Id, Product_Profiling__c>();
           
    For(Product_Profiling__c p : profilings)
        {
            profilingMap.put(p.Product_Name__c, p);
        }*/
     
    return profilings;//profilingMap;
        
    }
    
    /*------------------------------------------------------------  
    Description:    AuraEnabled method to collect all Product Profiling records 
                    related to either an account or a contact
    Inputs:         @param recordId - The account's or contact's recordId
    ------------------------------------------------------------*/ 
    
    @AuraEnabled
    public static Map<Id, Product_Profiling__c> getProductProfilingMap(String recordId) {
    List<Product_Profiling__c> profilings = new List<Product_Profiling__c>();
        
        if(recordId.startsWith('003')){
            profilings = [SELECT Id, Product_Name__c, Quantity__c, Product_Category__c, Product_Name__r.Id, Product_Name__r.Manufacturer__c, Product_Name__r.Product_Category__c, Product_Name__r.Name, Product_Name__r.SBU__c, Product_Name__r.Competitor_Product__c, Product_Name__r.KeyProduct__c, Product_Name__r.ProductGroupText__c, Product_Name__r.QuantityUnitOfMeasure__c, Status__c, Account__c, Contact__c, Contact__r.FirstName, Contact__r.LastName FROM Product_Profiling__c WHERE Contact__c =: recordId AND Product_Name__c != null];    
        }
        else{
            profilings = [SELECT Id, Product_Name__c, Quantity__c, Product_Category__c, Product_Name__r.Id, Product_Name__r.Manufacturer__c, Product_Name__r.Product_Category__c, Product_Name__r.Name, Product_Name__r.SBU__c, Product_Name__r.Competitor_Product__c, Product_Name__r.KeyProduct__c, Product_Name__r.ProductGroupText__c, Product_Name__r.QuantityUnitOfMeasure__c, Status__c, Account__c, Contact__c, Contact__r.FirstName, Contact__r.LastName FROM Product_Profiling__c WHERE Account__c =: recordId AND Product_Name__c != null];    
        }
    
    Map<Id, Product_Profiling__c> profilingMap = new Map<Id, Product_Profiling__c>();
           
    For(Product_Profiling__c p : profilings)
        {
            profilingMap.put(p.Product_Name__c, p);
        }
     
    return profilingMap;
        
    }    
    
    @AuraEnabled
    public static String[] getDistinctValues(String field_name, String recordId) {
        Set<String> valList = new Set<String>();
        
            String country = '';    
        if(recordId.left(3) == '003'){
            Contact con = [SELECT Id, Account.Country__c FROM Contact WHERE Id =: recordId];
        	country = con.Account.Country__c;
        }
        else{
            Account acc = [SELECT Id, Country__c FROM Account WHERE Id =: recordId];
            country = acc.Country__c;
        }
                
    	List<Non_ERP_Products__c> records = [SELECT Id, Name, Countries__c, SBU__c, Manufacturer__c, Competitor_Product__c, KeyProduct__c, Product_Category__c, ProductGroupText__c 
                                             FROM Non_ERP_Products__c WHERE Inactive__c = false AND (Countries__c INCLUDES (:country) OR Valid_in_my_Market__c =: true) ];
		
        for(Non_ERP_Products__c so : records){
            String fieldValue = (String) so.get(field_name);
            valList.add(fieldValue);
            System.debug(fieldValue);
        }
        
        List<String> results = new List<String>();
        
        for(String s : valList){
          results.add(s);  
        }
        
        return results;
        
    }
    
    @AuraEnabled
    public static Boolean deleteProductProfilingRecord(String recordId) {
			
        Product_Profiling__c ppRecord = [SELECT Id, Name FROM Product_Profiling__c WHERE Id =: recordId];
        Boolean success = true;
        try{
            delete ppRecord;
        }catch(Exception e){
            System.debug('An error occured when trying to delete a Product Profiling record: ' + e);
            success = false;    
        }
		
        return success;
        
    }

    public class HierarchyNode {
    @AuraEnabled public Non_ERP_Products__c node;
    @AuraEnabled public String nodeName;    
    @AuraEnabled public List<HierarchyNode> children;
    @AuraEnabled public Boolean isProfiled;
    HierarchyNode(Non_ERP_Products__c acc, Boolean isProfiling) {
        node = acc;
        nodeName = acc.Name;
        children = new List<HierarchyNode>();
        isProfiled = isProfiling;
    }        
	}
    
        /*public class ProductProfilingBundle {
 		
    	@AuraEnabled public String productId;         
     	@AuraEnabled public String productName;
        
  	}*/
}