unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Profession__c</fullName>
    <description>Dependent upon Product Area</description>
    <label>Role/Profession</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Advanced Practice Dental Therapist</fullName>
        </value>
        <value>
          <fullName>Clinical Director</fullName>
        </value>
        <value>
          <fullName>Consultant</fullName>
        </value>
        <value>
          <fullName>Contractor</fullName>
        </value>
        <value>
          <fullName>Dean</fullName>
          <label>Dean/Head</label>
        </value>
        <value>
          <fullName>Dental Assistant</fullName>
        </value>
        <value>
          <fullName>Dental Hygienist</fullName>
        </value>
        <value>
          <fullName>Dental Laboratory General Manager</fullName>
        </value>
        <value>
          <fullName>Dental Laboratory Office Manager</fullName>
        </value>
        <value>
          <fullName>Dental Laboratory Technician</fullName>
        </value>
        <value>
          <fullName>Dental Nurse</fullName>
        </value>
        <value>
          <fullName>Dental Nurse Manager</fullName>
        </value>
        <value>
          <fullName>Dental Student</fullName>
        </value>
        <value>
          <fullName>Dental Technician</fullName>
        </value>
        <value>
          <fullName>Dental Technician Master</fullName>
        </value>
        <value>
          <fullName>Dental Therapist</fullName>
        </value>
        <value>
          <fullName>Dentist</fullName>
        </value>
        <value>
          <fullName>Denturist</fullName>
        </value>
        <value>
          <fullName>Distributor General Manager</fullName>
        </value>
        <value>
          <fullName>Distributor Sales Rep</fullName>
        </value>
        <value>
          <fullName>Doctor</fullName>
        </value>
        <value>
          <fullName>DS Employee</fullName>
        </value>
        <value>
          <fullName>Employee</fullName>
        </value>
        <value>
          <fullName>Endodontist</fullName>
        </value>
        <value>
          <fullName>Faculty/Instructor/Professor</fullName>
        </value>
        <value>
          <fullName>General Dentist</fullName>
        </value>
        <value>
          <fullName>General Manager</fullName>
        </value>
        <value>
          <fullName>Head of Department</fullName>
        </value>
        <value>
          <fullName>Implant Manager</fullName>
        </value>
        <value>
          <fullName>Implantologist</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Expert__c.object
<CustomObject>
  <fields>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>KOL information</relationshipLabel>
    <relationshipName>KOL_information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Not_a_Healthcare_Professional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be ticked if this KOL is not a healthcare professional and therefor not part of/included in the Fair Market Value (FMV) regulations. If this is ticked contracts etc. will not enforce a specific payment range.</description>
    <inlineHelpText>Tick this checkbox if the KOL is not a Healthcare Professional and therefor not part of FMV regulations.</inlineHelpText>
    <label>Not a Healthcare Professional</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Profession__c</fullName>
    <description>Used by Clinical Affairs - also included in some logic for the Fair Market Value calculations so needed a sepaareta list. Ultimate solution would be to merge this with global profession/contcat subtype valueas.</description>
    <inlineHelpText>Add the profession of the KOL</inlineHelpText>
    <label>Profession</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>General Dentist</fullName>
        </value>
        <value>
          <fullName>Endodontist</fullName>
        </value>
        <value>
          <fullName>Pediatric Dentist</fullName>
        </value>
        <value>
          <fullName>Dental Anesthesiology</fullName>
        </value>
        <value>
          <fullName>Geriatric Dentist</fullName>
        </value>
        <value>
          <fullName>Periodontist</fullName>
        </value>
        <value>
          <fullName>Prosthodontist</fullName>
        </value>
        <value>
          <fullName>Special Care Dentistry</fullName>
        </value>
        <value>
          <fullName>Implantologist</fullName>
        </value>
        <value>
          <fullName>Oral and Maxilllofacial Pathology</fullName>
        </value>
        <value>
          <fullName>Orthodontist</fullName>
        </value>
        <value>
          <fullName>Oral and Maxillofacial Radiology</fullName>
        </value>
        <value>
          <fullName>Oral and Maxillofacial Surgeon</fullName>
        </value>
        <value>
          <fullName>Dental Assistant</fullName>
        </value>
        <value>
          <fullName>Laboratory Technician</fullName>
        </value>
        <value>
          <fullName>Dental Hygienist</fullName>
        </value>
        <value>
          <fullName>Oral Medicine Specialist</fullName>
        </value>
        <value>
          <fullName>Office Manager/Practice Administrator</fullName>
        </value>
        <value>
          <fullName>Oral Biologist</fullName>
        </value>
        <value>
          <fullName>Oral Microbiologist</fullName>
        </value>
        <value>
          <fullName>Dental Scientist</fullName>
        </value>
        <value>
          <fullName>Public Health Dentist</fullName>
        </value>
        <value>
          <fullName>Preventive Dentist</fullName>
        </value>
        <value>
          <fullName>Infection Control Specialist</fullName>
        </value>
        <value>
          <fullName>Forensic Dentistry</fullName>
        </value>
        <value>
          <fullName>Forensic Odontology</fullName>
        </value>
        <value>
          <fullName>Laboratory Owner/Upper Level Management</fullName>
        </value>
        <value>
          <fullName>Non-Healthcare Provider</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>KOL information</label>
  <nameField>
    <label>KOL Information</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>KOL information</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/KOLInfoTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------------
Author: 		Richard Trum (Glimt) 2019-11-29
Description:   	KOL Information Trigger Helper Class
Test Class:      
History	
20191129 		Richard Trum			Created triggers in the trigger framework for the KOL Information object
--------------------------------------------------------------------------------------------------------*/

public with sharing class KOLInfoTriggerHelper {
    
    /*------------------------------------------------------------	
	Description:   	Method to prevent duplicate KOL information records to created towards one contact
    Inputs:        	@param contactId
	------------------------------------------------------------*/
    
    public static void preventDuplicateKOLs(List<Expert__c> newKOLList){
        
        for(Expert__c exp : newKOLList){ 
        	List<Expert__c> existingKOLs = [SELECT Id FROM Expert__c WHERE Contact__c =: exp.Contact__c];
        
        	if(existingKOLs.size()>0){
            	exp.addError('A KOL record already exists related to this contact');
     		}
        }
    }
    
    public static void setExpertName(List<Expert__c> expertlist){
      for(Expert__c exp:expertlist){
        if(exp.Contact__c != null){
            Contact c = [select id, FirstName, LastName from Contact where Id=:exp.Contact__c];
            exp.Name = c.FirstName + ' ' + c.LastName + ' - KOL info';
        }

    }
  
    }
    
    public static void setNonHCProfession(List<Expert__c> expertlist){
        for(Expert__c exp : expertlist){          
            if(exp.Profession__c == 'Non-Healthcare Provider'){
                exp.Not_a_Healthcare_Professional__c = true;
                exp.Profession__c = 'Non-Healthcare Provider';
            }
            
        }  
        
    }
    
}