unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>CFEs_Implants_CM__c</fullName>
    <label>CFEs Current Month (IMPL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Albania</fullName>
        </value>
        <value>
          <fullName>Algeria</fullName>
        </value>
        <value>
          <fullName>Argentina</fullName>
        </value>
        <value>
          <fullName>Armenia</fullName>
        </value>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Azerbaijan</fullName>
        </value>
        <value>
          <fullName>Bahrain</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Bosnia and Herzegovina</fullName>
        </value>
        <value>
          <fullName>Botswana</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Bulgaria</fullName>
        </value>
        <value>
          <fullName>Cambodia</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Chile</fullName>
        </value>
        <value>
          <fullName>China</fullName>
        </value>
        <value>
          <fullName>Colombia</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Ecuador</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Country_metadata__mdt.object
<CustomObject>
  <fields>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Account_Strategy_Summary</fullName>
          <default>true</default>
          <label>Account_Strategy_Summary</label>
        </value>
        <value>
          <fullName>Account_CFE_Summary</fullName>
        </value>
        <value>
          <fullName>Account_Sales_Summary</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Sweden</fullName>
          <default>true</default>
          <label>Sweden</label>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>LightningComponent__c</fullName>
    <label>Lightning Component</label>
    <referenceTo>Lightning_Component__mdt</referenceTo>
    <relationshipLabel>Country metadata</relationshipLabel>
    <relationshipName>Country_metadata</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
  </fields>
  <fields>
    <fullName>SBU__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>IMPL</fullName>
          <default>true</default>
          <label>IMPL</label>
        </value>
        <value>
          <fullName>PREV</fullName>
        </value>
        <value>
          <fullName>REST</fullName>
        </value>
        <value>
          <fullName>PROS</fullName>
        </value>
        <value>
          <fullName>ENDO</fullName>
        </value>
        <value>
          <fullName>ORTH</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Team_setup__c</fullName>
    <label>Team setup</label>
    <referenceTo>Team_setup__mdt</referenceTo>
    <relationshipLabel>Country metadata</relationshipLabel>
    <relationshipName>Country_metadata</relationshipName>
    <type>MetadataRelationship</type>
  </fields>
  <fields>
    <fullName>Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible?</label>
    <type>Checkbox</type>
  </fields>
  <label>Country metadata</label>
  <pluralLabel>Country metadata</pluralLabel>
</CustomObject>

unpackaged/objects/Lightning_Component__mdt.object
<CustomObject>
  <description>List of available Lightning Components, used in Team Setup</description>
  <label>Lightning Component</label>
  <pluralLabel>Lightning Components</pluralLabel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Team_setup__mdt.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Sweden</fullName>
          <default>true</default>
          <label>Sweden</label>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
        <value>
          <fullName>Norway</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>SBU__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>IMPL</fullName>
          <default>true</default>
          <label>IMPL</label>
        </value>
        <value>
          <fullName>PREP</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Team setup</label>
  <pluralLabel>Team setups</pluralLabel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>SBU_Ratio_CERE__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA CAD/CAM CEREC</description>
    <inlineHelpText>SIRONA CAD/CAM CEREC</inlineHelpText>
    <label>SBU Ratio (CDCM)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_ENDO__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (ENDO)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_IMAG__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA Imaging systems Intra &amp; Extra Oral</description>
    <inlineHelpText>SIRONA Imaging systems Intra &amp; Extra Oral</inlineHelpText>
    <label>SBU Ratio (IMAG)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_IMPL__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (IMPL)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_INST__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA Instruments</description>
    <inlineHelpText>SIRONA Instruments</inlineHelpText>
    <label>SBU Ratio (INST)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_ORTH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (ORTH)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_PREV__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (PREV)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_PROS__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (PROS)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_REST__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (REST)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_TRCE__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA Treatment Centers</description>
    <inlineHelpText>SIRONA Treatment Centers</inlineHelpText>
    <label>SBU Ratio (TRCE)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Team_Setup_ID__c</fullName>
    <label>Team Setup ID</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Country_Text__c</fullName>
    <formula>Text(User_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User Country - Text</label>
    <type>Text</type>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/LightningAccountController.cls
public class LightningAccountController {    
    @AuraEnabled
    public static List<Contact> getContacts(Id recordId) {
        return [Select Id, FirstName, LastName, Email, Phone From Contact Where AccountId =: recordId];       
    }
    
    @AuraEnabled
    public static Account getAccountInfo(Id recordId) {
        Account acc = [Select Id, Name, CFEs_Implants_CM__c, 
                Account_Strategy_Implants__c, Implants_Potential_Year__c, ATL_ISUS_Potential_Year__c, share_of_potential_implants__c 
                FROM Account Where Id =: recordId];
        return acc;        
    }           
    
    @AuraEnabled
    public static String saveAccount(Id recordId, String Implants_potential) {
        system.debug(Implants_potential);
        String accId ='-';
        Integer ImplPot = Integer.valueOf(Implants_potential);
        Account acc = [SELECT Id, Implants_Potential_Year__c, ATL_ISUS_Potential_Year__c FROM Account WHERE Id=: recordId ];
        
        If(acc.Implants_Potential_Year__c != ImplPot){
        acc.Implants_potential_year__c = ImplPot;
        }

        
          try{              
          update acc;
          }
            catch (Exception e){
            String errorMessage = 'Error: ' + e.getMessage() + ' ' + e.getStackTraceString();
            system.debug(errorMessage);                
            } 
        
        return accId;
    }
    
    @AuraEnabled
    public static Boolean getUserAccess(String ComponentName) {
    String userId = userinfo.getUserId();
    User activeUser = [SELECT Id, Username, Team_Setup_ID__c, User_Country_Text__c, SBU_Ratio_IMPL__c, SBU_Ratio_PREV__c FROM User Where Id =:userId];
        
    List<Country_metadata__mdt> activeCountry = [SELECT Component__c, Team_setup__r.Label, SBU__c, Country__c, Visible__c FROM Country_metadata__mdt WHERE (Team_setup__r.Label =: activeUser.Team_Setup_ID__c AND LightningComponent__r.Label =: ComponentName)];
        
    Boolean isVisible = false;   
        
        For (Country_metadata__mdt c: activeCountry){
          If (c.Visible__c){ 
                isVisible = true;
          }}
             
    return isVisible;
    }
    
    @AuraEnabled
    public static User getUserSBUAccess(String ComponentName) {
    String userId = userinfo.getUserId();
    User activeUser = [SELECT Id, Team_Setup_ID__c, SBU_Ratio_IMPL__c, SBU_Ratio_CERE__c, SBU_Ratio_ENDO__c, SBU_Ratio_IMAG__c, SBU_Ratio_INST__c, SBU_Ratio_ORTH__c, SBU_Ratio_PREV__c, 
                       SBU_Ratio_PROS__c, SBU_Ratio_REST__c, SBU_Ratio_TRCE__c FROM User Where Id =:userId];
    return activeUser;
    }
    
    @AuraEnabled
    public static User getUserInfo(Id recordId) {
    User activeUser = [SELECT Id, Username, FirstName, LastName, Team_Setup_ID__c FROM User Where Id =:recordId];
    return activeUser;
    }
    
    @AuraEnabled
    public static List<Team_setup__mdt> getTeamSetup() {
    String userId = userinfo.getUserId();
    User activeUser = [SELECT Id, Team_Setup_ID__c, User_Country_Text__c FROM User Where Id =:userId];
        
    List<Team_setup__mdt> activeSetup = [SELECT Label FROM Team_setup__mdt ORDER BY Label ASC NULLS LAST];
        
    return activeSetup;
    }
    
   @AuraEnabled
    public static String saveUser(User ThisUser) {
        system.debug(ThisUser);
        String accId ='-';
        
          try{              
          update ThisUser;
          accId = ThisUser.Id;
          }
            catch (Exception e){
            String errorMessage = 'Error: ' + e.getMessage() + ' ' + e.getStackTraceString();
            system.debug(errorMessage);                
            } 
        
        return accId;
    }
    
    
    
}