unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>HQ</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Luxembourg</fullName>
        </value>
        <value>
          <fullName>New Zealand</fullName>
        </value>
        <value>
          <fullName>Norway</fullName>
        </value>
        <value>
          <fullName>Poland</fullName>
        </value>
        <value>
          <fullName>Portugal</fullName>
        </value>
        <value>
          <fullName>South Africa</fullName>
        </value>
        <value>
          <fullName>Spain</fullName>
        </value>
        <value>
          <fullName>Sweden</fullName>
        </value>
        <value>
          <fullName>Switzerland</fullName>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
        <value>
          <fullName>Ukraine</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Non_ERP_Products__c.object
<CustomObject>
  <label>Non-ERP Products</label>
  <nameField>
    <label>Product Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Non-ERP Products</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Product_Profiling__c.object
<CustomObject>
  <fields>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <referenceTo>Non_ERP_Products__c</referenceTo>
    <relationshipLabel>Products Profiling</relationshipLabel>
    <relationshipName>Products_Profiling</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
  </fields>
  <label>Product Profiling</label>
  <nameField>
    <displayFormat>PP{000000000}</displayFormat>
    <label>Profiling Id</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Products Profiling</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>FieldSalesRatioPerc__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Describes if the user should be counted as a full-time sales rep(100%) or not. 
Example 1: If a rep is only working as a sales rep for 50% of the time and has other dutys or is only working part time, add 50% in this field. 
Example 2. If a manager is also workin 25% with field sales (equivalent as a sales rep) add 25% in this field.

Note that Administration time should not be deducted from this field</description>
    <inlineHelpText>Describes if the user should be counted as a full-time sales rep (100%) or a part-time sales rep (for example 50%).

Note that administrative time should not be deducted.</inlineHelpText>
    <label>Field Sales Ratio (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_ENDO__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (ENDO)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_IMAG__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SIRONA Imaging systems Intra &amp; Extra Oral</description>
    <inlineHelpText>SIRONA Imaging systems Intra &amp; Extra Oral</inlineHelpText>
    <label>SBU Ratio (IMAG)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_IMPL__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (IMPL)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_ORTH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (ORTH)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>SBU_Ratio_PROS__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SBU Ratio (PROS)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Type__c</fullName>
    <inlineHelpText>Sales Representative  = District Managers, Territory Managers, Account Managers

Sales Manager = Regional Sales Mgrs, Division Sales Mgrs, National Sales Mgrs</inlineHelpText>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Account Maintenance Team Member</fullName>
        </value>
        <value>
          <fullName>Area Sales Manager</fullName>
        </value>
        <value>
          <fullName>Clinical Affairs</fullName>
        </value>
        <value>
          <fullName>Complaints Handling</fullName>
        </value>
        <value>
          <fullName>Customer Service</fullName>
        </value>
        <value>
          <fullName>Finance</fullName>
        </value>
        <value>
          <fullName>Inside Sales Representative</fullName>
        </value>
        <value>
          <fullName>Key Account Manager</fullName>
        </value>
        <value>
          <fullName>Managing Director</fullName>
        </value>
        <value>
          <fullName>Marketing</fullName>
        </value>
        <value>
          <fullName>National Admin</fullName>
        </value>
        <value>
          <fullName>Operations</fullName>
        </value>
        <value>
          <fullName>Other</fullName>
        </value>
        <value>
          <fullName>Product Manager</fullName>
        </value>
        <value>
          <fullName>Regional Sales Manager</fullName>
        </value>
        <value>
          <fullName>Sales Manager</fullName>
        </value>
        <value>
          <fullName>Sales Representative</fullName>
        </value>
        <value>
          <fullName>Training &amp; Event Management</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/Product_profilling_new_override_test.cls
@isTest
public class Product_profilling_new_override_test {
   
        public static testMethod void Product_profilling_new_override() {
            //create test user
            profile p = [SELECT Id From profile Where Name = '#System: System Administrator'];
            userrole r = [SELECT Id From UserRole Where Name = 'System Administrators'];
            Account a = new Account(Name='Test Acc');
            Non_ERP_Products__c prod = new Non_ERP_Products__c();
            prod.Name = 'Test product';
            Product_Profiling__c pp = new Product_Profiling__c();
            
            Contact c = new Contact (LastName='Test Atl Acc');
            user u = new User(  firstname = 'tuserFname',
                              lastName = 'tuserLastname',
                              email = 'testtest.testtest@dentsplysirona.com',
                              Username = 'testtesttesttest@dentsplysirona.com',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias ='ttest',
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'sv_SE',
                              LanguageLocaleKey = 'en_US',
                              User_Type__c = 'Other',
                              User_Country__c = 'Sweden',
                              CurrencyIsoCode = 'SEK',
                              ProfileId = p.Id,
                              UserRoleId = r.Id,
                              FieldSalesRatioPerc__c = 0,
                              SBU_Ratio_IMPL__c = 0.2,
                              SBU_Ratio_ENDO__c = 0.2,
                              SBU_Ratio_ORTH__c = 0.2,
                              SBU_Ratio_PROS__C = 0.2,
                              SBU_Ratio_IMAG__c = 0.2);
            system.runAs(u){
            //create account
            insert(a);
            //create contact
            c.accountID=a.Id;
            insert(c);
            //create product
           	insert prod;
            pp.Product_Name__c = prod.Id;
                
            Test.startTest(); //switch to testing context
                PageReference pageRef = Page.Product_profilling_new_override_page; //create a page reference to our Visualforce page
                pageRef.getparameters().put('conid', c.Id); 
                Test.setCurrentPage(pageRef);
                
                Apexpages.StandardController sc = new Apexpages.StandardController(pp);
                Product_profilling_new_override ext = new  Product_profilling_new_override(sc);
                ext.save1();
                ext.cancel1();
            Test.stopTest(); //revert back to normal context
            }
        }
}