unpackaged/objects/Contract.object
<CustomObject>
  <fields>
    <fullName>Implant_commitment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Implant commitment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Price__c</fullName>
    <description>The value of the Contract. Used in Vouchers</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Sales_L12M__c</fullName>
    <label>Sales L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
    <fullName>Contract</fullName>
    <label>Contract</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Product2.object
<CustomObject>
  <fields>
    <fullName>GlobalSKUMapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GlobalSKU Mapping</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Mapped LocalSKUs</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>List_Price__c</fullName>
    <description>Used for Implants Germany to calculate the gross price on invoices for comparison towards net prices</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>PG2_Code__c</fullName>
    <label>Product Group 2 Code</label>
    <length>20</length>
    <type>Text</type>
  </fields>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Sales_History__c.object
<CustomObject>
  <description>Detailed Sales History of Products Sold to Accounts</description>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales History</relationshipLabel>
    <relationshipName>SalesHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Corresponding Purchasing Contract or Voucher when a relation exists</description>
    <inlineHelpText>Lookup field to the Corresponding Purchasing Contract or Voucher when a relation exists</inlineHelpText>
    <label>Contract/Voucher</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sales History</relationshipLabel>
    <relationshipName>Sales_History</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Discount_Amount__c</fullName>
    <inlineHelpText>Already subtracted from the Total Value (Tot Price)</inlineHelpText>
    <label>Discount Amount</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Gross_price__c</fullName>
    <formula>IF(Quantity__c=0, 0, Product__r.List_Price__c*Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total gross price = Quantity multiplied by the List Price on the Local SKU</inlineHelpText>
    <label>Gross price (currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Price__c</fullName>
    <inlineHelpText>Unit Price</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to Product object , we use SFDC ID to update this field</description>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sales History</relationshipLabel>
    <relationshipName>Sales_History</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Tot_Price__c</fullName>
    <formula>IF( Quantity__c =0,  Price__c , Price__c *  Quantity__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Value =  Quantity multiplied by the Price</inlineHelpText>
    <label>Total Price (Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
  <label>Sales History</label>
  <nameField>
    <label>Article (SKU)</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Sales History</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/getContractTest.cls
@isTest
public with sharing class getContractTest {    
    
/* @isTest
public static void doActionTest(){

        //PageReference pageRef = Page.Contract_updsales;
        //Test.setCurrentPage(pageRef);
        
        Account a = new Account(Name='Test account 1', TS_CY_D_AllPLs_AllPCs_AllBrands__c = 49214, TQ_CY_D_DI_Implants_AllBrands__c = 209);
        insert a;
        
        Contract c = new Contract(Name='Test contract 1', AccountID=a.Id, Implant_commitment__c=200);
        insert c;
        
        ApexPages.currentPage().getParameters().put('id', c.id);
             
        ApexPages.StandardController stdController = new ApexPages.StandardController(c);
        
        updateContract controller = new updateContract(stdController);
         
        system.assertEquals(null,c.Sales_L12M__c);
        
        controller.navFlow();
        
        system.assertEquals('FLOW',controller.stepname);
        
    }

@isTest
public static void ContractFlowTest(){

        //PageReference pageRef = Page.Contract_Flow;
        //Test.setCurrentPage(pageRef);
        
        Account a = new Account(Name='Test account 1', TS_CY_D_AllPLs_AllPCs_AllBrands__c = 49214, TQ_CY_D_DI_Implants_AllBrands__c = 209);
        insert a;
        
        Contract c = new Contract(Name='Test contract 1', AccountID=a.Id, Implant_commitment__c=200);
        insert c;
        
        ApexPages.currentPage().getParameters().put('id', c.id);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(c);
        
        getContract controller = new getContract(stdController);
        
        controller.doAction();
         
        system.assertEquals(null,c.Sales_L12M__c);
        

    } */
    
/*@isTest
public static void ContractDiscountSimulationTest(){

        //PageReference pageRef = Page.Contract_Discount_simulation;
        //Test.setCurrentPage(pageRef);
        
        Account a = new Account(Name='Test account 1', TS_CY_D_AllPLs_AllPCs_AllBrands__c = 49214, TQ_CY_D_DI_Implants_AllBrands__c = 209);
        insert a;
        
        Contract c = new Contract(Name='Test contract 1', AccountID=a.Id, Implant_commitment__c=200);
        
        ApexPages.currentPage().getParameters().put('id', c.id);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(c);
        
        getContract controller = new getContract(stdController);
        
        system.assertEquals(180,c.Implant_commitment__c);
        
        system.assertEquals(false, controller.hasM);
        
        controller.save();
        
        system.assertEquals(true, controller.hasM);
        
    }*/
@isTest    
public static void ContractSalesHistoryTest(){
        
        Account a = new Account(Name='Test account 1', TS_CY_D_AllPLs_AllPCs_AllBrands__c = 49214, TQ_CY_D_DI_Implants_AllBrands__c = 209);
        insert a;
        
        Contract c = new Contract(Name='Test contract 1', AccountID=a.Id, Implant_commitment__c=200);
        insert c;
        
        ApexPages.currentPage().getParameters().put('id', c.id);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(c);
        
        getContract controller = new getContract(stdController);
        
        Product2 product2 = DC_UT_DataUtils.generateProduct('Product2', 'Brand1','Line1', 'L4_GD_P2');
        product2.PG2_Code__c = 'II12';
        upsert product2;
        
        Product2 product1 = DC_UT_DataUtils.generateProduct('Product1', 'Brand1', 'Line1', 'L4_GD_P1');        
        product1.List_Price__c = 110;
        product1.GlobalSKUMapping__c = product2.id;
        upsert product1;
 
        Product2 product4 = DC_UT_DataUtils.generateProduct('Product4', 'Brand1','Line1', 'L4_GD_P2');
        product4.PG2_Code__c = 'ID85';
        upsert product4;
 
        Product2 product3 = DC_UT_DataUtils.generateProduct('Product3', 'Brand2', 'Line2', 'L4_GD_P3'); 
        product3.List_Price__c = 110;
        product3.GlobalSKUMapping__c = product4.Id;
        upsert product3;
        
        Date Date17 = Date.newInstance(System.Today().year(), 2, 17);
        Date Date16 = Date.newInstance(System.Today().year()-1, 2, 17);
        Date Date15 = Date.newInstance(System.Today().year()-2, 2, 17);
        Date Date14 = Date.newInstance(System.Today().year()-3, 2, 17);
        
        Sales_history__c sales14 = new Sales_history__c(Account__c= a.id, Quantity__c = 2, Contract__c = c.id, Product__c=product1.id, Price__c=100, Invoice_Date__c=Date14); //, Discount_Amount__c = 20
        insert sales14;
        sales14 = [SELECT Id, Account__c, Quantity__c, Contract__c, Product__c, Gross_price__c, Price__c, Tot_price__c, Invoice_date__c, Product__r.GlobalSKUMapping__r.PG2_Code__c FROM Sales_history__c WHERE Id =: sales14.Id];
        
        Sales_history__c sales15 = new Sales_history__c(Account__c= a.id, Quantity__c = 2, Contract__c = c.id, Product__c=product1.id, Price__c=100, Invoice_Date__c=Date15); //, Discount_Amount__c = 20
        insert sales15;
        
        Sales_history__c sales16 = new Sales_history__c(Account__c= a.id, Quantity__c = 2, Contract__c = c.id, Product__c=product1.id, Price__c=100, Invoice_Date__c=Date16); //, Discount_Amount__c = 20
        insert sales16;
        
        Sales_history__c sales17 = new Sales_history__c(Account__c= a.id, Quantity__c = 2, Contract__c = c.id, Product__c=product1.id, Price__c=100, Invoice_Date__c=Date17); //, Discount_Amount__c = 20
        insert sales17;
                
        Sales_history__c sales14_EI = new Sales_history__c(Account__c= a.id, Quantity__c = 2, Contract__c = c.id, Product__c=product3.id, Price__c=100, Invoice_Date__c=Date14); //, Discount_Amount__c = 20
        insert sales14_EI;
        sales14_EI = [SELECT Id, Account__c, Quantity__c, Contract__c, Product__c, Gross_price__c, Price__c, Tot_price__c, Invoice_date__c, Product__r.GlobalSKUMapping__r.PG2_Code__c FROM Sales_history__c WHERE Id =: sales14.Id];
        
        Sales_history__c sales15_EI = new Sales_history__c(Account__c= a.id, Quantity__c = 2, Contract__c = c.id, Product__c=product3.id, Price__c=100, Invoice_Date__c=Date15); //, Discount_Amount__c = 20
        insert sales15_EI;
        
        Sales_history__c sales16_EI = new Sales_history__c(Account__c= a.id, Quantity__c = 2, Contract__c = c.id, Product__c=product3.id, Price__c=100, Invoice_Date__c=Date16); //, Discount_Amount__c = 20
        insert sales16_EI;
        
        Sales_history__c sales17_EI = new Sales_history__c(Account__c= a.id, Quantity__c = 2, Contract__c = c.id, Product__c=product3.id, Price__c=100, Invoice_Date__c=Date17); //, Discount_Amount__c = 20
        insert sales17_EI;
        
        
        system.assertEquals(null, controller.Sales_CY_C);
        system.assertEquals(null, controller.Sales_LY_C);
        system.assertEquals(null, controller.Sales_L2Y_C);
        system.assertEquals(null, controller.Sales_L3Y_C);
        
        system.assertEquals(null, controller.Sales_CY_M_C);
        system.assertEquals(null, controller.Sales_LY_M_C);
        system.assertEquals(null, controller.Sales_L2Y_M_C);
        system.assertEquals(null, controller.Sales_L3Y_M_C);
        
        system.assertEquals(null, controller.Sales_CY_EI_C);
        system.assertEquals(null, controller.Sales_LY_EI_C);
        system.assertEquals(null, controller.Sales_L2Y_EI_C);
        system.assertEquals(null, controller.Sales_L3Y_EI_C);
        
        system.assertEquals(null, controller.Discount_CY_C);
        system.assertEquals(null, controller.Discount_LY_C);
        system.assertEquals(null, controller.Discount_L2Y_C);
        system.assertEquals(null, controller.Discount_L3Y_C);
        
        system.assertEquals(null, controller.Discount_CY_M_C);
        system.assertEquals(null, controller.Discount_LY_M_C);
        system.assertEquals(null, controller.Discount_L2Y_M_C);
        system.assertEquals(null, controller.Discount_L3Y_M_C);
        
        system.assertEquals(null, controller.Discount_CY_EI_C);
        system.assertEquals(null, controller.Discount_LY_EI_C);
        system.assertEquals(null, controller.Discount_L2Y_EI_C);
        system.assertEquals(null, controller.Discount_L3Y_EI_C);
        
        system.assertEquals(null, controller.Implants_CY_C);
        system.assertEquals(null, controller.Implants_LY_C);
        system.assertEquals(null, controller.Implants_L2Y_C);
        system.assertEquals(null, controller.Implants_L3Y_C);
               
        controller.getSales_CY();
    
        system.assertEquals(400, controller.Sales_CY_C);
        system.assertEquals(400, controller.Sales_CY_C);
        system.assertEquals(400, controller.Sales_L2Y_C);
        system.assertEquals(400, controller.Sales_L3Y_C);
        
        system.assertEquals(200, controller.Sales_CY_M_C);
        system.assertEquals(200, controller.Sales_LY_M_C);
        system.assertEquals(200, controller.Sales_L2Y_M_C);
        system.assertEquals(200, controller.Sales_L3Y_M_C);
        
        system.assertEquals(200, controller.Sales_CY_EI_C);
        system.assertEquals(200, controller.Sales_LY_EI_C);
        system.assertEquals(200, controller.Sales_L2Y_EI_C);
        system.assertEquals(200, controller.Sales_L3Y_EI_C);
        
        system.assertEquals(40, controller.Discount_CY_C);
        system.assertEquals(40, controller.Discount_LY_C);
        system.assertEquals(40, controller.Discount_L2Y_C);
        system.assertEquals(40, controller.Discount_L3Y_C);
        
        system.assertEquals(20, controller.Discount_CY_M_C);
        system.assertEquals(20, controller.Discount_LY_M_C);
        system.assertEquals(20, controller.Discount_L2Y_M_C);
        system.assertEquals(20, controller.Discount_L3Y_M_C);
        
        system.assertEquals(20, controller.Discount_CY_EI_C);
        system.assertEquals(20, controller.Discount_LY_EI_C);
        system.assertEquals(20, controller.Discount_L2Y_EI_C);
        system.assertEquals(20, controller.Discount_L3Y_EI_C);
        
        system.assertEquals(0, controller.Implants_CY_C);
        system.assertEquals(0, controller.Implants_LY_C);
        system.assertEquals(0, controller.Implants_L2Y_C);
        system.assertEquals(0, controller.Implants_L3Y_C);
        
        system.assertEquals(8, controller.Sales_Account.size());
    
    
    	controller.getContractStatus();
    	system.AssertEquals(0, controller.ContractImplantsSalesActivation);
        
    }
    
    
    }