unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Dental Clinic Contact</fullName>
        </value>
        <value>
          <fullName>Dental Laboratory Contact</fullName>
        </value>
        <value>
          <fullName>Distributor Contact</fullName>
        </value>
        <value>
          <fullName>Hospital Contact</fullName>
        </value>
        <value>
          <fullName>University Contact</fullName>
        </value>
        <value>
          <fullName>Wholesaler Contact</fullName>
        </value>
        <value>
          <fullName>Purchasing Group Contact</fullName>
        </value>
        <value>
          <fullName>Government Contact</fullName>
        </value>
        <value>
          <fullName>DENTSPLY SIRONA Contact</fullName>
        </value>
        <value>
          <fullName>Competitor Contact</fullName>
        </value>
        <value>
          <fullName>Other Contact</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Full_Name__c</fullName>
    <description>Used instead of having to add First and Last Name when grouping in report</description>
    <formula>FirstName &amp; " " &amp; LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula field</inlineHelpText>
    <label>Full Name</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by OBIEE to mark the primary contact, automatically checked when created in workflow</description>
    <label>Primary Contact</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Sub_Contact_Type__c</fullName>
    <label>Contact Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>Contact_Type__c</controllingField>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Brand Manager</fullName>
        </value>
        <value>
          <fullName>Buyer/Procurement</fullName>
        </value>
        <value>
          <fullName>CEO</fullName>
        </value>
        <value>
          <fullName>Clinical Director</fullName>
        </value>
        <value>
          <fullName>Clinical Manager</fullName>
        </value>
        <value>
          <fullName>Clinical Tutor</fullName>
        </value>
        <value>
          <fullName>Consultant</fullName>
        </value>
        <value>
          <fullName>Dean</fullName>
        </value>
        <value>
          <fullName>Dental Assistant</fullName>
        </value>
        <value>
          <fullName>Dental Engineer</fullName>
        </value>
        <value>
          <fullName>Dental Nurse</fullName>
        </value>
        <value>
          <fullName>Dental Nurse Manager</fullName>
        </value>
        <value>
          <fullName>Dental Student</fullName>
        </value>
        <value>
          <fullName>Dental Technician</fullName>
        </value>
        <value>
          <fullName>Dental Technician Master</fullName>
        </value>
        <value>
          <fullName>Denturist</fullName>
        </value>
        <value>
          <fullName>Department Head</fullName>
        </value>
        <value>
          <fullName>Distributor Sales Rep</fullName>
        </value>
        <value>
          <fullName>Doctor</fullName>
        </value>
        <value>
          <fullName>Endodontist</fullName>
        </value>
        <value>
          <fullName>Faculty/Instructor/Professor</fullName>
        </value>
        <value>
          <fullName>General Dentist</fullName>
        </value>
        <value>
          <fullName>General Manager</fullName>
        </value>
        <value>
          <fullName>General surgeon</fullName>
        </value>
        <value>
          <fullName>Head Nurse</fullName>
        </value>
        <value>
          <fullName>Head of Department</fullName>
        </value>
        <value>
          <fullName>Head of Education</fullName>
        </value>
        <value>
          <fullName>Head of Hospital</fullName>
        </value>
        <value>
          <fullName>Hygiene Therapist</fullName>
        </value>
        <value>
          <fullName>Hygienist</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/flowRecordVisualPickerController.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Kevin Ruibin Do (Salesforce) 20200617
Description:    Apex Controller for flow_recordVisualPickerController
Test Class:     Test_flowRecordVisualPicker
History 
20201015        Kevin Ruibin Do - Added check for Primary_Contact__c = false
20200617        Kevin Ruibin Do - Created Class
--------------------------------------------------------------------------------------------------------*/

public with sharing class flowRecordVisualPickerController {
    @AuraEnabled(cacheable=true)
    public static List<Contact> getRelatedContacts(String recordId) {
        return [
            SELECT Id, Full_Name__c, FirstName, LastName, Email, Title, Contact_Type__c, Sub_Contact_Type__c
            FROM Contact WHERE AccountId =: recordId AND Primary_Contact__c = false ORDER BY Full_Name__c ASC NULLS LAST
        ];
    }

    /**
    * @description Method to query records that will be shown in the visual picker
    * @author kdoruibin@salesforce.com | 02-16-2021 
    * @param String recordId 
    * @param String queryString 
    * @return string 
    **/
    @AuraEnabled(cacheable=true)
    public static string getRecords(String recordId, String queryString){
        try {
            return JSON.serialize(Database.query(queryString));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}