unpackaged/objects/Contract.object
<CustomObject>
  <fields>
    <fullName>Discount_End_year__c</fullName>
    <inlineHelpText>Discount granted to the customer based on the total sales at the end of the year. Not applied to the order</inlineHelpText>
    <label>Discount End Year</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
    <fullName>Contract</fullName>
    <label>Contract</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Account_for_Sample_in_AX__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to track sample in AX</description>
    <label>Payer Account</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>DENTSPLY</value>
      </filterItems>
      <filterItems>
        <field>Account.Sub_Account_Type__c</field>
        <operation>equals</operation>
        <value>Sales Rep</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Internal</value>
      </filterItems>
      <filterItems>
        <field>Account.Sub_Account_Type__c</field>
        <operation>equals</operation>
        <value>Free Goods</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sample Orders</relationshipLabel>
    <relationshipName>Sample_Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Allowed_discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Allowed discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Discount_to_be_used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Contract Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Order_Type__c</fullName>
    <description>Order Type for DNA</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Free Goods Order</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Telesales</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Discount on Demand</fullName>
        </value>
        <value>
          <fullName>PREP</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Pricebook_Name__c</fullName>
    <formula>Pricebook2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricebook Name</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>SIMPLANT_Software_Evaluation__c</fullName>
    <label>SIMPLANT Software Evaluation</label>
    <summarizedField>OrderItem.SIMPLANT_Software_Line_Item__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
  </fields>
  <fields>
    <fullName>User_CountryPL__c</fullName>
    <label>User CountryPL</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>BEX</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Distributor Markets</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ: DE</fullName>
        </value>
        <value>
          <fullName>HQ: NL</fullName>
        </value>
        <value>
          <fullName>HQ: SE</fullName>
        </value>
        <value>
          <fullName>Hungary</fullName>
        </value>
        <value>
          <fullName>INDIA</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Jordan</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/OrderItem.object
<CustomObject>
  <fields>
    <fullName>Account_for_Sample_in_AX__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account for Sample in AX</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>DENTSPLY</value>
      </filterItems>
      <filterItems>
        <field>Account.Sub_Account_Type__c</field>
        <operation>equals</operation>
        <value>Sales Rep</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Brand__c</fullName>
    <formula>PricebookEntry.Product2.Brand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>DiscountApproval_Line_Item__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount Approval Line Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Discount_Approval_Eval__c</fullName>
    <formula>IF( AND(Discount_Percent__c  &gt; 0, (LEN( Text(Sales_Special__c))&gt;0)),"NO APPROVAL NEEDED", 

IF(AND(Discount_Percent__c  &gt; 0,(LEN( Text(Sales_Special__c))=0)), "YES - APPROVAL NEEDED",

IF(Discount_Percent__c  &gt; 0, "YES - APPROVAL NEEDED",
IF(Discount_Percent__c   = 0, "NO APPROVAL NEEDED",

"YES"))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Approval Evaluation</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Free_of_Charge_Delivery__c</fullName>
    <description>Used to state who should deliver a free of charge item - it can be either a dealer, Dentsply Sirona Customer Service or given directly during meeting by Sales Rep</description>
    <label>Free of Charge Delivery</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Dealer</fullName>
        </value>
        <value>
          <fullName>Customer Service</fullName>
        </value>
        <value>
          <fullName>Sales Rep</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Item_at_100__c</fullName>
    <formula>IF( Discount_Percent__c  &gt; 0.99,1,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item at 100%?</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>MTF_EvaluationNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MTF Evaluation Line Item</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>MTF_Evaluation__c</fullName>
    <formula>CASE( PricebookEntry.Product2.Article__c ,
"US228005", 1,
"US228010", 1,
"US228025", 1,
"US420038",1,
"US420039",1,
"US420075", 1,
"US420076",1,
"US420077", 1,
"US420078",1,
"US400175",1,
"US400173", 1,
"US400174",1,
"US400191",1,
"US400192",1,
"US400175", 1,
"US400176",1,
"US400177",1,
"US400178",1,
"US791101", 1,
"US791102", 1,
"US791104", 1,
"US791204", 1,
"US790101", 1,
"US790102", 1,
"US790104", 1,
"US790202", 1,
"US790204", 1,
"US400193", 1,
"US420048", 1,
"US400172", 1,
"US400178", 1,
"US400194", 1,
"US420049", 1,

"US600172", 1,
"US600173", 1,
"US600174", 1,
"US600175", 1,
"US600176", 1,
"US600177", 1,
"US600178", 1,
"US600191", 1,
"US600192", 1,
"US600193", 1,
"US600194", 1,
"US620038", 1,
"US620039", 1,
"US620048", 1,
"US620049", 1,
"US620075", 1,
"US620076", 1,
"US620077", 1,
"US620078", 1,


0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MTF Evaluation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Non_SIMPLANT_Evaluation__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Populated by a workflow update, this enables the order to evaluate how many Simplant/Non Simplant Line items are on this order for Approval Process Purposes</inlineHelpText>
    <label>Non-SIMPLANT Evaluation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Number_of_Items_at_100_Discount__c</fullName>
    <label>Number of Items at 100% Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>SIMPLANT_Line_Item__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Populated by a workflow rule which evaluates the formula field SIMPLANT Order and brings back a numerical value. This field will be used in a rollup summary to the Order for evaluation in an approval process for North America</description>
    <inlineHelpText>Populated by a workflow rule which evaluates the formula field SIMPLANT Order and brings back a numerical value. This field will be used in a rollup summary to the Order for evaluation in an approval process for North America</inlineHelpText>
    <label>SIMPLANT Line Item</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>SIMPLANT_Software_Evaluation__c</fullName>
    <formula>CASE(PricebookEntry.Product2.PG4_Code__c,
"ID8111",1,
"ID8201",1,
"ID8202",1,
"ID8203",1,
"ID8205",1,
"ID8206",1,
"ID8207",1,
"ID8211",1,
"ID8212",1,
"ID8213",1,
"ID8215",1,
"ID8216",1,
"ID8217",1,
"ID8222",1,
"ID8231",1,
"ID8232",1,
"ID8241",1,
"ID8251",1,
"ID8252",1,
"ID8255",1,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SIMPLANT Software Evaluation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>SIMPLANT_Software_Line_Item__c</fullName>
    <label>SIMPLANT Software Line Item</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Value_of_Samples_for_Sales_Rep__c</fullName>
    <label>Value of Samples for Sales Rep</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Value_of_free_product__c</fullName>
    <label>Value of free product</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
</CustomObject>

unpackaged/objects/Product2.object
<CustomObject>
  <fields>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>100</length>
    <type>Text</type>
  </fields>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/OrderItemTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------------
Author: 		LOUDRASSI Ahmed (Salesforce) 2020-02-25
Description:    OrderItem Trigger Helper Class
Test Class:     
History 
Kevin Ruibin Do 20210419    Updated totalAmountOfSamplesAndFreeProducts to also set value when there are no free products
Richard Trum	20200804	Changed setDiscountAllowedforTurkey to use the Contract field Discount__c instead of Discount_End_year__c
Miguel Coimbra	20200511	Added descriptions
----------------------------------------------------------------------------------------*/
public class OrderItemTriggerHelper {
    /*------------------------------------------------------------  
    Description:    define Order Discount Percent to max 100 (as per logic defined on Order Management 2.0)
    Inputs:         @param newOrderItemList
    ------------------------------------------------------------*/
    public static void set100PercentForFOC(List<OrderItem> newOrderItemtList) {
        Set<ID> orderIds = new Set<ID>();
        for(OrderItem orderItem: newOrderItemtList) {
            orderIds.add(orderItem.OrderId);
        }
        Map<Id,Order> parentOrders = new Map<ID, Order>([SELECT Id, Pricebook2Id, Pricebook_Name__c FROM Order WHERE ID IN :orderIds]); 
        for (OrderItem orderItem: newOrderItemtList) {
            Order parentOrder = parentOrders.get(orderItem.OrderId);
            if (parentOrder.Pricebook2Id != null && String.isNotBlank(orderItem.Free_of_Charge_Delivery__c)) {
                orderItem.Discount_Percent__c = 100;
            }
        }
    }
    /*------------------------------------------------------------  
    Description:   
    Inputs:         @param newOrderItemList
    ------------------------------------------------------------*/
    public static void totalAmountOfSamplesAndFreeProducts(List<OrderItem> newOrderItemtList) { 
        for(OrderItem orderItem: newOrderItemtList) {
            if(orderItem.Quantity > 0) {
                // Amount Samples
                if(String.isBlank(orderItem.Account_for_Sample_in_AX__c)) {
                    orderItem.Value_of_Samples_for_Sales_Rep__c = 0;
                } else {
                    orderItem.Value_of_Samples_for_Sales_Rep__c = orderItem.UnitPrice * orderItem.Quantity;
                }
                // Value of Free Products
                if(orderItem.Discount_Percent__c == 100) {
                    orderItem.Value_of_free_product__c = orderItem.UnitPrice * orderItem.Quantity;
                } else {
                    orderItem.Value_of_free_product__c = 0;
                }
            }
        } 
    }
    /*------------------------------------------------------------  
    Description:    
    Inputs:         @param newOrderItemList
    ------------------------------------------------------------*/
    public static void orderProductEvaluation(List<OrderItem> newOrderItemtList) { 
        Set<ID> orderIds = new Set<ID>();
        for(OrderItem orderItem: newOrderItemtList) {
            orderIds.add(orderItem.OrderId);
        }
        Map<Id,Order> parentOrders = new Map<ID, Order>([SELECT Id, User_CountryPL__c FROM Order WHERE ID IN :orderIds]); 
        for(OrderItem orderItem: newOrderItemtList) {
            if(String.isNotBlank(parentOrders.get(orderItem.OrderId).User_CountryPL__c)) {
                // ORDER: Update SIMPLANT Evaluation
                orderItem.SIMPLANT_Line_Item__c = 'SIMPLANT'.equals(orderItem.PricebookEntry.Product2.Brand__c) ? 1 : 0;
                // ORDER: Update MTF Evaluation
                orderItem.MTF_EvaluationNumber__c = orderItem.MTF_Evaluation__c == 1 ? 1 : 0;
                // ORDER: Discount Approval Evaluation
                orderItem.DiscountApproval_Line_Item__c  = 'NO APPROVAL NEEDED'.equals(orderItem.Discount_Approval_Eval__c) ? 0 : 1; 
                // ORDER: Update NON-SIMPLANT Evaluation
                orderItem.Non_SIMPLANT_Evaluation__c = 'SIMPLANT'.equals(orderItem.PricebookEntry.Product2.Brand__c) ? 0 : 1;
                // SIMPLANT Software Line Item Eval
                orderItem.SIMPLANT_Software_Line_Item__c = orderItem.SIMPLANT_Software_Evaluation__c;
                // Update # of Items at 100% Discount
                orderItem.Number_of_Items_at_100_Discount__c = orderItem.Item_at_100__c;
            }
        }
    }
    /*------------------------------------------------------------  
    Description:    Method migrated from Process Builder on Order Product 
    Inputs:         @param newOrderItemList
    ------------------------------------------------------------*/
    public static void setDiscountAllowedforTurkey(List<OrderItem> newOrderItemtList) { 
        Set<ID> orderIds = new Set<ID>();
        for(OrderItem orderItem: newOrderItemtList) {
            orderIds.add(orderItem.OrderId);
        }
        Map<Id,Order> parentOrders = new Map<ID, Order>
            ([SELECT Id, Pricebook2Id, Country__c, Discount_to_be_used__c, 
              Allowed_discount__c, Order_Type__c, Contract.Discount_End_year__c, Contract.Discount__c FROM Order WHERE ID IN :orderIds]); 
        Map<Id,Order> ordersToUpdate = new Map<Id,Order> ();
        for(OrderItem orderItem: newOrderItemtList) {
            Order parentOrder = parentOrders.get(orderItem.OrderId);
            if('TR'.equals(parentOrder.Country__c) &&
              	String.isNotBlank(parentOrder.Pricebook2Id) &&
              	'Implants'.equals(parentOrder.Order_Type__c)) {
               	if(String.isNotBlank(parentOrder.ContractId)) {
                  //parentOrder.Discount_to_be_used__c = parentOrder.Contract.Discount_End_year__c;
                	parentOrder.Discount_to_be_used__c = parentOrder.Contract.Discount__c;
                } else {
                    parentOrder.Discount_to_be_used__c = 0;
                }
                if(!ordersToUpdate.containsKey(parentOrder.Id)) {
                    ordersToUpdate.put(parentOrder.Id, parentOrder);
                }
            }
        }
        update ordersToUpdate.values();
    }

}