unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Chinese</fullName>
        </value>
        <value>
          <fullName>Danish</fullName>
        </value>
        <value>
          <fullName>Dutch</fullName>
        </value>
        <value>
          <fullName>English</fullName>
        </value>
        <value>
          <fullName>Finnish</fullName>
        </value>
        <value>
          <fullName>Flemish</fullName>
        </value>
        <value>
          <fullName>French</fullName>
        </value>
        <value>
          <fullName>German</fullName>
        </value>
        <value>
          <fullName>Italian</fullName>
        </value>
        <value>
          <fullName>Japanese</fullName>
        </value>
        <value>
          <fullName>Norwegian</fullName>
        </value>
        <value>
          <fullName>Portuguese</fullName>
        </value>
        <value>
          <fullName>Russian</fullName>
        </value>
        <value>
          <fullName>Spanish</fullName>
        </value>
        <value>
          <fullName>Swedish</fullName>
        </value>
        <value>
          <fullName>Thai</fullName>
        </value>
        <value>
          <fullName>Vietnamese</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>HQ</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Luxembourg</fullName>
        </value>
        <value>
          <fullName>New Zealand</fullName>
        </value>
        <value>
          <fullName>Norway</fullName>
        </value>
        <value>
          <fullName>Poland</fullName>
        </value>
        <value>
          <fullName>Portugal</fullName>
        </value>
        <value>
          <fullName>South Africa</fullName>
        </value>
        <value>
          <fullName>Spain</fullName>
        </value>
        <value>
          <fullName>Sweden</fullName>
        </value>
        <value>
          <fullName>Switzerland</fullName>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
        <value>
          <fullName>Ukraine</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>WhenCollected__c</fullName>
    <label>When collected?</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>WhereCollected__c</fullName>
    <label>Where collected?</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>In use for all countries</description>
    <fullName>ContactGlobal</fullName>
    <label>Contact Global</label>
  </recordTypes>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Emails__c.object
<CustomObject>
  <description>Used to track Emails for a contact and consent along with it. Required for GDPR and other data privacy and anti-spam regulations. 
Object populated and updated by the system based on email updates/changes from the contact.</description>
  <fields>
    <fullName>Consent_Collection_Method__c</fullName>
    <description>Used to track how the consent was collected.</description>
    <label>Consent Collection Method</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Verbally Phone</fullName>
        </value>
        <value>
          <fullName>Verbally Face-To-Face</fullName>
        </value>
        <value>
          <fullName>Digitally</fullName>
        </value>
        <value>
          <fullName>Hard Copy Signed Form</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Emails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
  </fields>
  <fields>
    <fullName>Email_Marketing_Consent__c</fullName>
    <label>Email Marketing Consent</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Please Select Yes or No</fullName>
        </value>
        <value>
          <fullName>Yes</fullName>
        </value>
        <value>
          <fullName>No</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Email__c</fullName>
    <description>The email address</description>
    <label>Email</label>
    <type>Email</type>
  </fields>
  <fields>
    <fullName>WhenCollected__c</fullName>
    <label>When collected?</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>WhereCollected__c</fullName>
    <label>Where collected?</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <label>Email Consent Tracking</label>
  <nameField>
    <label>Emails Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Emails Consent Tracking</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/LoyaltyProgram__c.object
<CustomObject>
  <description>Used to track programs that an Account is participating at. Example could be a loyalty Program. 

Note that the API label says LoyaltyProgram since that was the first design of it and intention for it - but has been relabeled to have a broader meaning and sense since whereas types of programs has arised as a need.</description>
  <label>Account Program</label>
  <nameField>
    <label>Account Program Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Account Programs</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/LoyaltyProgramParticipant__c.object
<CustomObject>
  <fields>
    <fullName>AcceptedTermsAndConditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted Terms and Conditions</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Program Members</relationshipLabel>
    <relationshipName>LoyaltyProgramParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Program Members</relationshipLabel>
    <relationshipName>Account_Program_Members</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Email__c</fullName>
    <description>Email of the person signing the T&amp;C</description>
    <label>Email</label>
    <type>Email</type>
  </fields>
  <fields>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Random string generated on insert. Used as external id to be sent out via email to customers to not expose the real Salesforce Id.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
  </fields>
  <fields>
    <fullName>FirstName__c</fullName>
    <description>First Name of the person agreeing to the T&amp;C.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LastName__c</fullName>
    <description>Last Name of the person signing the T&amp;C</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LoyaltyProgram__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Program</label>
    <referenceTo>LoyaltyProgram__c</referenceTo>
    <relationshipLabel>Account Program Members</relationshipLabel>
    <relationshipName>LoyaltyProgramParticipants</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>PracticeName__c</fullName>
    <description>Practice Name of the person signing the T&amp;C.</description>
    <label>Practice Name</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>TermsAndConditionsConsentDate__c</fullName>
    <label>Terms and Conditions Consent Date</label>
    <type>DateTime</type>
  </fields>
  <label>Account Program Member</label>
  <nameField>
    <displayFormat>LPP-{0000}</displayFormat>
    <label>Account Program Member Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Account Program Members</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Contact.AccountId</field>
        <operation>equals</operation>
        <valueField>$Source.AccountId</valueField>
      </filterItems>
      <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/Test_OneDSCanadaTermsAndConditions_CC.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Kevin Ruibin Do (Salesforce) 20200908
Description:    Test class for OneDSCanadaTermsAndConditions_CC
History 
20200908        Kevin Ruibin Do - Created Class
--------------------------------------------------------------------------------------------------------*/

@isTest(seeAllData=false)
public class Test_OneDSCanadaTermsAndConditions_CC {

    @testSetup
    static void makeData(){
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.returnUsers(1, 'System Administrator');
        userList[0].User_Country__c = 'Canada';
        insert userList;
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();

        // Setup Account, Contact, and LoyaltyProgramParticipant__c
        System.runAs(userList[0]) {
            List<Account> accountList = TestDataFactory.returnAccounts(1, 'CIM_Account', userList[0].Id);
            insert accountList;
    
            List<Contact> contactList = TestDataFactory.returnContacts(1, 'ContactGlobal', userList[0].Id);
            contactList[0].Preferred_Language__c = 'English';
            insert contactList;

            List<LoyaltyProgram__c> loyaltyProgramList = new List<Loyaltyprogram__c>();
            loyaltyProgramList.add(new LoyaltyProgram__c (
                Name = 'Apex Test'
            ));
            insert loyaltyProgramList;
    
            List<LoyaltyProgramParticipant__c> loyaltyPPList = new List<LoyaltyProgramParticipant__c>();
            loyaltyPPList.add(new LoyaltyProgramParticipant__c(
                LoyaltyProgram__c = loyaltyProgramList[0].Id
                ,Account__c = accountList[0].Id
                ,Contact__c = contactList[0].Id
            )); 
            insert loyaltyPPList;
        }
    }

    @isTest
    private static void testController() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact WHERE OwnerId =: testUser.Id];
        LoyaltyProgramParticipant__c loyaltyParticipant = [SELECT Id, Name, ExternalId__c FROM LoyaltyProgramParticipant__c WHERE CreatedById = :testUser.Id LIMIT 1];

        System.debug('debug::'+loyaltyParticipant);

        // Test the page
        Pagereference pageRef = Page.OneDSCanadaTermsAndConditions;
        Test.setCurrentPage(pageRef);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('Id', loyaltyParticipant.ExternalId__c);
        Datetime testDatetime = System.now();

        Test.startTest();
        OneDsCanadaTermsAndConditions_CC controller = new OneDsCanadaTermsAndConditions_CC();
        controller.firstName = 'Test FirstName';
        controller.lastName = 'Test LastName';
        controller.practiceName = 'Test PracticeName';
        controller.email = 'test@email.com';
        controller.hasAccepted = true;
        controller.accept();
        Test.stopTest();

        // Assert that fields were properly updated
        loyaltyParticipant = [SELECT FirstName__c, LastName__c, PracticeName__c, Email__c, AcceptedTermsAndConditions__c, TermsAndConditionsConsentDate__c, Contact__c FROM LoyaltyProgramparticipant__c WHERE Id = :loyaltyParticipant.Id];
        System.debug('loyaltyParticipant::'+loyaltyParticipant);

        System.assertEquals(null, controller.error);
        System.assertEquals(controller.firstName, loyaltyParticipant.FirstName__c);
        System.assertEquals(controller.lastName, loyaltyParticipant.LastName__c);
        System.assertEquals(controller.practiceName, loyaltyParticipant.PracticeName__c);
        System.assertEquals(controller.email, loyaltyParticipant.Email__c);
        System.assertEquals(controller.hasAccepted, loyaltyParticipant.AcceptedTermsAndConditions__c);
        System.assert(loyaltyParticipant.TermsAndConditionsConsentDate__c.isSameDay(testDatetime), 'Consent date was not set correctly on LoyaltyProgramParticipant__c');
        
        // Assert that Consent is properly updated
       /* Emails__c emailConsentRecord = [SELECT Id, Consent_Collection_Method__c, WhenCollected__c, WhereCollected__c FROM Emails__c WHERE Contact__c = :loyaltyParticipant.Contact__c ORDER BY CreatedDate DESC LIMIT 1];
        System.assertEquals('Digitally', emailConsentRecord.Consent_Collection_Method__c);
        // System.assertEquals('Yes', emailConsentRecord.Email_Marketing_Consent__c);
        System.assertEquals('Canada One DS Terms and Conditions Site', emailConsentRecord.WhereCollected__c);
        System.assert(emailConsentRecord.WhenCollected__c.isSameDay(testDatetime), 'Consent date was not set correctly on Contact');
    */}

    @IsTest
    private static void testControllerError() {
        // Test the page without providing any Id
        Pagereference pageRef = Page.OneDSCanadaTermsAndConditions;
        Test.setCurrentPage(pageRef);

        Test.startTest();
        OneDsCanadaTermsAndConditions_CC controller = new OneDsCanadaTermsAndConditions_CC();
        Test.stopTest();

        System.assertEquals(true, controller.error);
    }
}