unpackaged/objects/Contract.object
<CustomObject>
  <fields>
    <fullName>Discount_model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount model</label>
    <referenceTo>Discount_model__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
    <fullName>Contract</fullName>
    <label>Contract</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Discount_model__c.object
<CustomObject>
  <description>Used for storing discount models related to Contracts</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <label>Discount Model</label>
  <nameField>
    <label>Discount Model Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Discount Model</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Source_Record__c.object
<CustomObject>
  <description>Includes Accounts from different sources mapped to one golden account. Fully integrated ( Read Only for all users)</description>
  <fields>
    <fullName>CIM_Account__c</fullName>
    <label>CIM Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Source Records</relationshipLabel>
    <relationshipName>Source_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>25</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Customer_Id__c</fullName>
    <label>Customer Id</label>
    <length>50</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Inactive</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Source Record</label>
  <nameField>
    <label>Account Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Source Records</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Test_ContractUpdateSalesData.cls
@IsTest
public class Test_ContractUpdateSalesData {

    /*-------------------------------------------------------------------------------------------------------
    Company: Glimt
    Description: Test method for ContractTriggerHelper.updateSalesData()
                 Asserts that contract sales is collected correctly
    History :
    --------------------------------------------------------------------------------------------------------*/
    @IsTest
    private static void testUpdateSalesData() {
     	
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<Discount_model__c> discountModelList = TestDataFactory.createDiscountModels(1, userList[0].Id);
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Discount_model__c> testDiscountModelList = [SELECT Id FROM Discount_model__c WHERE OwnerId = :testUser.Id LIMIT 1];
        Id testDiscountModelId = testDiscountModelList[0].Id;
        List<Account> testAccountList = TestDataFactory.returnAccounts(3, 'CIM_Account', testUser.Id);
        Account testAccount0 = testAccountList[0];
        testAccount0.Country__c = 'DE';		        
        insert testAccountList;
        Id testAccountId = testAccount0.Id;
		
        Source_Record__c src = new Source_Record__c();
        src.CIM_Account__c = testAccount0.Id;
        src.Customer_Id__c = '12345';
        src.Company_Code__c = 'DE';
        src.Status__c = 'Active';
        insert src;
                
        Account accountToAssert = [
            SELECT Id, Sales_L12M_D__c, Sold_Implants_L12M__c, Sales_L13_24M_D__c 
            FROM Account
            WHERE Id = :testAccountId
            LIMIT 1
        ];
		List<String> input = new List<String>();
        input.add(accountToAssert.Id);
		List<ContractTriggerHelper.ContractSalesDataResponse> response = ContractTriggerHelper.updateSalesData(input);        
                
   		}  
    
    
}