unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Albania</fullName>
        </value>
        <value>
          <fullName>Algeria</fullName>
        </value>
        <value>
          <fullName>Argentina</fullName>
        </value>
        <value>
          <fullName>Armenia</fullName>
        </value>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Azerbaijan</fullName>
        </value>
        <value>
          <fullName>Bahrain</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Bosnia and Herzegovina</fullName>
        </value>
        <value>
          <fullName>Botswana</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Bulgaria</fullName>
        </value>
        <value>
          <fullName>Cambodia</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Chile</fullName>
        </value>
        <value>
          <fullName>China</fullName>
        </value>
        <value>
          <fullName>Colombia</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Ecuador</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
        <value>
          <fullName>Ireland</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To identify whether a Contact is Inactive or Active</description>
    <inlineHelpText>Check this checkbox if the contact is either retired, deceased or has left position/post</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>InsertEmailMarketingConsentCollected__c</fullName>
    <inlineHelpText>Please fill the information if the Email Marketing Consent was collected or not</inlineHelpText>
    <label>Insert Email Marketing Consent Collected</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Yes</fullName>
        </value>
        <value>
          <fullName>No</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>In use for all countries</description>
    <fullName>ContactGlobal</fullName>
    <label>Contact Global</label>
  </recordTypes>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Expert__c.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <formula>TEXT(Contact__r.Account.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the KOL is no longer active as KOL but we still want to keep information if re-activated again.</description>
    <inlineHelpText>Checked if the KOL is no longer active as KOL.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
  </fields>
  <label>KOL information</label>
  <nameField>
    <label>KOL Information</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>KOL information</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ContactTriggerTest.cls
/*------------------------------------------------------------
Author:         Roberto Narbona
Description:    Test Class for all ContactTriggerHelper methods.
History
<Date>      <Authors Name>      <Brief Description of Change>
20200401    Roberto Narbona     New tests mwthod to cover ContactTriggerHelper.showNoDeleteError TFUS-000002832
------------------------------------------------------------*/

@isTest(seeAllData=false)
public class ContactTriggerTest {

    /*-------------------------------------------------------------------------------------------------------
    Company: 
    Description: Setup one user for the test class
    History : TFUS-000002832
    --------------------------------------------------------------------------------------------------------*/
    
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
    }

    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();

        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }



    /*-------------------------------------------------------------------------------------------------------
    Company: 
    Description: Test method for ContactTriggerHelper.showNoDeleteError
    History : TFUS-000002832
    --------------------------------------------------------------------------------------------------------*/
    
    @isTest
    private static void testNoDeleteKOLError() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> testAccountList = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
        List<Contact> testContactList = TestDataFactory.returnContacts(202, 'ContactGlobal', testUser.Id);
        for(Integer i = 0; i <=  testContactList.size()-1; i++){
            testContactList[i].AccountId = testAccountList[0].Id;
            testContactList[i].Country__c = 'IE';
        }
        insert testContactList;
        system.debug(testContactList);
        List<Expert__c> testKOLList = TestDataFactory.createExperts(1, testContactList);
        System.runAs(testUser) {
            Test.startTest();
               try{
                    delete testContactList;
                }catch(DMLexception e){
                    system.assert(e.getMessage().contains(Label.KOLDeleteError),Label.KOLDeleteError);                       
                }
            Test.stopTest(); 
        }  
    }

    /*-------------------------------------------------------------------------------------------------------
    Company: 
    Description: Test method for ContactTriggerHelper.
    History : 
    --------------------------------------------------------------------------------------------------------*/
    @isTest
    private static void setValuesbeforeInsert() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> testAccountList = TestDataFactory.returnAccounts(3, 'Non_ERP_Account', testUser.Id);
        testAccountList[0].Country__c = 'US';
        testAccountList[1].Country__c = 'BR';
        insert testAccountList;
        List<Contact> testContactList = TestDataFactory.returnContacts(202, 'ContactGlobal', testUser.Id);
        for(Integer i = 0; i <=  testContactList.size()-1; i++){
            testContactList[i].AccountId = testAccountList[0].Id;
            //testContactList[i].Country__c = 'IE';
        }
        testContactList[1].AccountId = testAccountList[1].Id;
        testContactList[2].Inactive__c = true;
        testContactList[3].Email = 'test@test.is';
        testContactList[3].InsertEmailMarketingConsentCollected__c = 'Yes';
        System.runAs(testUser) {
            Test.startTest();
                insert testContactList;
                system.debug(testAccountList[0].Country__c);
                system.debug(testContactList[0].Country__c);
                system.debug(testContactList[0].Account.Country__c);
                //system.assert( testContactList[0].country__c,'Ireland');
            Test.stopTest(); 
        }  
    }

    @isTest
    private static void setValuesbeforeUpdate() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> testAccountList = TestDataFactory.returnAccounts(3, 'Non_ERP_Account', testUser.Id);
        testAccountList[0].Country__c = 'US';
        testAccountList[1].Country__c = 'BR';
        insert testAccountList;
        List<Contact> testContactList = TestDataFactory.returnContacts(202, 'ContactGlobal', testUser.Id);
        for(Integer i = 0; i <=  testContactList.size()-1; i++){
            testContactList[i].AccountId = testAccountList[0].Id;
            //testContactList[i].Country__c = 'IE';
        }
        testContactList[1].AccountId = testAccountList[1].Id;
        testContactList[2].Inactive__c = true;
        testContactList[3].Email = 'test@test.is';
        testContactList[3].InsertEmailMarketingConsentCollected__c = 'Yes';
        insert testContactList;
        testContactList[3].Email = null;
        testContactList[3].HasOptedOutOfEmail = false;
        testContactList[4].Email = 'test@test.is';
        testContactList[4].InsertEmailMarketingConsentCollected__c = 'Yes';
        System.runAs(testUser) {
            Test.startTest();
                update testContactList;
                system.debug(testAccountList[0].Country__c);
                system.debug(testContactList[0].Country__c);
                system.debug(testContactList[0].Account.Country__c);
                //system.assert( testContactList[0].country__c,'Ireland');
            Test.stopTest(); 
        }  
    }
}