unpackaged/objects/Contract.object
<CustomObject>
  <fields>
    <fullName>Discount_End_year__c</fullName>
    <inlineHelpText>Discount granted to the customer based on the total sales at the end of the year. Not applied to the order</inlineHelpText>
    <label>Discount End Year</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Revenue_forecast__c</fullName>
    <inlineHelpText>Only applicable for new customers</inlineHelpText>
    <label>Sales estimation/correction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Sales_Correction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sales Correction</label>
    <type>Checkbox</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
    <fullName>Contract</fullName>
    <label>Contract</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <description>Used for contracts based on the new Discount Model for IMPL DE</description>
    <fullName>Pricing_contract</fullName>
    <label>Pricing contract</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Account_for_Sample_in_AX__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to track sample in AX</description>
    <label>Payer Account</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>DENTSPLY</value>
      </filterItems>
      <filterItems>
        <field>Account.Sub_Account_Type__c</field>
        <operation>equals</operation>
        <value>Sales Rep</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Internal</value>
      </filterItems>
      <filterItems>
        <field>Account.Sub_Account_Type__c</field>
        <operation>equals</operation>
        <value>Free Goods</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sample Orders</relationshipLabel>
    <relationshipName>Sample_Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Allowed_discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Allowed discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Discount_to_be_used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Contract Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Order_Type__c</fullName>
    <description>Order Type for DNA</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Free Goods Order</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Telesales</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Discount on Demand</fullName>
        </value>
        <value>
          <fullName>PREP</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_CountryPL__c</fullName>
    <label>User CountryPL</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>BEX</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Croatia</fullName>
        </value>
        <value>
          <fullName>Cyprus</fullName>
        </value>
        <value>
          <fullName>Czech Republic</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Distributor Markets</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greece</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ: DE</fullName>
        </value>
        <value>
          <fullName>HQ: NL</fullName>
        </value>
        <value>
          <fullName>HQ: SE</fullName>
        </value>
        <value>
          <fullName>Hungary</fullName>
        </value>
        <value>
          <fullName>INDIA</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Jordan</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>true</active>
    <fullName>Free_Good_Order</fullName>
    <label>Free Good Order</label>
  </recordTypes>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/OrderItem.object
<CustomObject>
  <fields>
    <fullName>Account_for_Sample_in_AX__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account for Sample in AX</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>DENTSPLY</value>
      </filterItems>
      <filterItems>
        <field>Account.Sub_Account_Type__c</field>
        <operation>equals</operation>
        <value>Sales Rep</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Free_of_Charge_Delivery__c</fullName>
    <description>Used to state who should deliver a free of charge item - it can be either a dealer, Dentsply Sirona Customer Service or given directly during meeting by Sales Rep</description>
    <label>Free of Charge Delivery</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Dealer</fullName>
        </value>
        <value>
          <fullName>Customer Service</fullName>
        </value>
        <value>
          <fullName>Sales Rep</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>MTF_EvaluationNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MTF Evaluation Line Item</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>SIMPLANT_Line_Item__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Populated by a workflow rule which evaluates the formula field SIMPLANT Order and brings back a numerical value. This field will be used in a rollup summary to the Order for evaluation in an approval process for North America</description>
    <inlineHelpText>Populated by a workflow rule which evaluates the formula field SIMPLANT Order and brings back a numerical value. This field will be used in a rollup summary to the Order for evaluation in an approval process for North America</inlineHelpText>
    <label>SIMPLANT Line Item</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Value_of_Samples_for_Sales_Rep__c</fullName>
    <label>Value of Samples for Sales Rep</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
</CustomObject>

unpackaged/classes/Test_OrderItemTrigger.cls
/*------------------------------------------------------------
Author: 		LOUDRASSI Ahmed (Salesforce) 2020-02-25
Description:   	Test Class for all OrderItemTriggerHelper methods.
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/

@isTest(seeAllData=false)
public class Test_OrderItemTrigger {

    /*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, '#System: System Administrator');
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
    }

    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();

        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }
    @isTest
    private static void testSetPercentForFOC() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(3, 'Non_ERP_Account', testUser.Id);
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            insert orders;
            List<OrderItem> orderItems = TestDataFactory.returnOrderItems(1, orders, pricebookEntries);
            orderItems.get(0).Free_of_Charge_Delivery__c = 'Dealer';
            Test.startTest();
            insert orderItems;
            update orderItems;
            Test.stopTest();
            System.assertEquals(100, [SELECT Id, Discount_Percent__c FROM OrderItem].Discount_Percent__c);
        }
    }
    @isTest
    private static void testOrderProductEvaluation() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(3, 'Non_ERP_Account', testUser.Id);
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            orders.get(0).User_CountryPL__c = 'USA';
            insert orders;
            List<OrderItem> orderItems = TestDataFactory.returnOrderItems(1, orders, pricebookEntries);
            Test.startTest();
            insert orderItems;
            update orderItems;
            Test.stopTest();
            OrderItem orderItem = [SELECT Id, SIMPLANT_Line_Item__c, MTF_EvaluationNumber__c FROM OrderItem LIMIT 1];
            System.assertEquals(0, orderItem.SIMPLANT_Line_Item__c);
            System.assertEquals(0, orderItem.MTF_EvaluationNumber__c);
        }
    }
    @isTest
    private static void totalAmountOfSamplesAndFreeProducts() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.returnAccounts(1, 'Non_ERP_Account', testUser.Id);
            accounts.get(0).Sub_Account_Type__c = 'Sales Rep';
            accounts.get(0).OneAccount_Type__c = 'DENTSPLY';
            insert accounts;
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            insert orders;
            List<OrderItem> orderItems = TestDataFactory.returnOrderItems(1, orders, pricebookEntries);
            orderItems.get(0).Account_for_Sample_in_AX__c = accounts.get(0).Id;
            Test.startTest();
            insert orderItems;
            update orderItems;
            Test.stopTest();
            OrderItem orderItem = [SELECT Id, Value_of_Samples_for_Sales_Rep__c, Quantity, UnitPrice FROM OrderItem LIMIT 1];
            System.assertEquals(true, orderItem.Value_of_Samples_for_Sales_Rep__c == (orderItem.Quantity * orderItem.UnitPrice));
        }
    }
    @isTest
    private static void testSetDiscountAllowedforTurkey() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Pricebook2> pricebooks = TestDataFactory.createPricebooks(1, 'BNL PRE');
            List<Product2> products = TestDataFactory.createProducts(1);
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(1, pricebooks, products);
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Contract> contracts = TestDataFactory.returnContracts(1, 'Pricing_contract', testUser.Id, accounts);
            contracts.get(0).Revenue_forecast__c = 10000;
            contracts.get(0).Sales_Correction__c = true;
            contracts.get(0).Discount_End_year__c = 15;
            contracts.get(0).Discount__c = 15;
            insert contracts;
            List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts);
            orders.get(0).Pricebook2Id = pricebooks.get(0).Id;
            orders.get(0).Country__c = 'TR';
            orders.get(0).Order_Type__c = 'Implants';
            orders.get(0).Allowed_discount__c = 10;
            orders.get(0).ContractId = contracts.get(0).Id;
            /*
            orders.get(1).Pricebook2Id = pricebooks.get(0).Id;
            orders.get(1).Country__c = 'TR';
            orders.get(1).Order_Type__c = 'Implants';
            orders.get(1).Allowed_discount__c = 10;*/
            insert orders;
            List<OrderItem> orderItems = TestDataFactory.returnOrderItems(1, orders, pricebookEntries);
            Test.startTest();
            insert orderItems;
            Test.stopTest();
            /*Order order1 = [SELECT Id, Allowed_discount__c, Discount_to_be_used__c FROM Order WHERE Id = :orders.get(0).Id];
            System.assertEquals(order1.Allowed_discount__c, order1.Discount_to_be_used__c);*/
            Order order2 = [SELECT Id, Contract.Discount_End_year__c, Discount_to_be_used__c FROM Order WHERE Id = :orders.get(0).Id];
            System.assertEquals(15, order2.Discount_to_be_used__c);
        }
    }
}