unpackaged/objects/Contract.object
<CustomObject>
  <fields>
    <fullName>Abutment_commitment_pick__c</fullName>
    <label>Abutment commitment</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>≤80% of implants commitment</fullName>
          <label>&lt;80% of implants commitment</label>
        </value>
        <value>
          <fullName>&gt;80% of implants commitment</fullName>
          <label>≥80% of implants commitment</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Allowed_discount_Implants_equipment__c</fullName>
    <label>Allowed discount Implants: equipment</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_Implants_materials__c</fullName>
    <label>Allowed discount Implants: materials</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_abutment_equipment__c</fullName>
    <label>Allowed discount abutment: equipment</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_abutment_materials__c</fullName>
    <label>Allowed discount abutment: materials</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_equipment__c</fullName>
    <formula>IF(Allowed_discount_Implants_equipment__c +  Allowed_discount_revenue_equipments__c + Allowed_discount_abutment_equipment__c &gt; 0, Allowed_discount_Implants_equipment__c +  Allowed_discount_revenue_equipments__c + Allowed_discount_abutment_equipment__c +  Allowed_discount_pooling_equipment__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allowed discount, equipment</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_materials__c</fullName>
    <formula>IF(Allowed_discount_Implants_materials__c +  Allowed_discount_revenue_materials__c +  Allowed_discount_abutment_materials__c &gt; 0, Allowed_discount_Implants_materials__c +  Allowed_discount_revenue_materials__c +  Allowed_discount_abutment_materials__c +  Allowed_discount_pooling_materials__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allowed discount, materials</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_pooling_equipment__c</fullName>
    <label>Allowed discount pooling, equipment</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_pooling_materials__c</fullName>
    <label>Allowed discount pooling, materials</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_revenue_equipments__c</fullName>
    <label>Allowed discount revenue: equipment</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Allowed_discount_revenue_materials__c</fullName>
    <label>Allowed discount revenue: materials</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Contract_discount_equipment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Contract discount, equipment</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Contract_discount_pricing_materials__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Contract discount, materials</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Correction_of_sales_needed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Correction of sales needed?</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Discount_model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount model</label>
    <referenceTo>Discount_model__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Implant_commitment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Implant commitment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Implant_commitment_abs__c</fullName>
    <formula>VALUE(TEXT(Implant_commitment_perc_input__c)) *0.01* IF(Implant_forecast__c &gt;0, Implant_forecast__c, Implant_volume_L12M__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Implant commitment (#)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Implant_commitment_perc__c</fullName>
    <formula>IF(
IF( Implant_forecast__c &gt;0, Implant_forecast__c, Implant_volume_L12M__c)
*VALUE(TEXT(Implant_commitment_perc_input__c))*0.01 &gt; IF( General_practitioner__c = true, 14, 29),
VALUE(TEXT(Implant_commitment_perc_input__c))*0.01, 0)</formula>
    <label>Implant commitment (%)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Implant_commitment_perc_input__c</fullName>
    <label>Implant commitment (%)</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>90</fullName>
        </value>
        <value>
          <fullName>100</fullName>
        </value>
        <value>
          <fullName>110</fullName>
        </value>
        <value>
          <fullName>120</fullName>
        </value>
        <value>
          <fullName>130</fullName>
        </value>
        <value>
          <fullName>80</fullName>
          <isActive>false</isActive>
          <label>80</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Implant_forecast__c</fullName>
    <inlineHelpText>Only applicable for new customers</inlineHelpText>
    <label>Implant estimation/correction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Implant_volume_L12M__c</fullName>
    <label>Implant volume L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Negative_discount_equipment__c</fullName>
    <formula>IF( Previous_contract__r.Deserved_discount_equipment__c - Previous_contract__r.Allowed_discount_Implants_equipment__c &lt; 0, Previous_contract__r.Deserved_discount_equipment__c - Previous_contract__r.Allowed_discount_Implants_equipment__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Negative discount, equipment</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Negative_discount_materials__c</fullName>
    <formula>IF( Previous_contract__r.Deserved_discount_materials__c - Previous_contract__r.Allowed_discount_Implants_materials__c &lt; 0, Previous_contract__r.Deserved_discount_materials__c - Previous_contract__r.Allowed_discount_Implants_materials__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Negative discount, materials</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>New_customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New customer?</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Payment_discount__c</fullName>
    <label>Payment discount</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>0</fullName>
        </value>
        <value>
          <fullName>2</fullName>
        </value>
        <value>
          <fullName>3</fullName>
        </value>
        <value>
          <fullName>4</fullName>
        </value>
        <value>
          <fullName>5</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Pooled_order_commitment__c</fullName>
    <defaultValue>0</defaultValue>
    <description>If the customer agrees to commit to place a pooled order during the contract period</description>
    <label>Pooled order commitment?</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Previous_contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous contract</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Contract.AccountId</field>
        <operation>equals</operation>
        <valueField>$Source.AccountId</valueField>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Previous contract</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Remains_impl_material__c</fullName>
    <formula>IF( AND(New_customer__c = False, Sales_Correction__c = False, Correction_of_sales_needed__c =false), 
IF((Row_discount_impl_mat__r.Max_perc__c* Implant_volume_L12M__c - Implant_commitment_abs__c )&gt;0, (Row_discount_impl_mat__r.Max_perc__c* Implant_volume_L12M__c - Implant_commitment_abs__c), null), 
IF((Row_discount_impl_mat__r.Max_perc__c* Implant_forecast__c - Implant_commitment_abs__c)&gt;0, (Row_discount_impl_mat__r.Max_perc__c* Implant_forecast__c - Implant_commitment_abs__c), null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remains to next level of discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Revenue_basis_for_allowance__c</fullName>
    <formula>IF(New_customer__c = False &amp;&amp; Sales_Correction__c = False, Sales_L12M__c , Revenue_forecast__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Revenue: basis for allowance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Revenue_forecast__c</fullName>
    <inlineHelpText>Only applicable for new customers</inlineHelpText>
    <label>Sales estimation/correction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Row_discount_impl_mat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Row discount impl mat</label>
    <referenceTo>Discount_row__c</referenceTo>
    <relationshipLabel>Contracts (Row discount impl mat)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Row_discount_rev_mat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Row discount rev mat</label>
    <referenceTo>Discount_row__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Sales_L12M__c</fullName>
    <label>Sales L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
    <fullName>Contract</fullName>
    <label>Contract</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Discount_model__c.object
<CustomObject>
  <description>Used for storing discount models related to Contracts</description>
  <fields>
    <fullName>Webshop_discount__c</fullName>
    <label>Webshop discount</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Percent</type>
  </fields>
  <label>Discount Model</label>
  <nameField>
    <label>Discount Model Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Discount Model</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Discount_row__c.object
<CustomObject>
  <fields>
    <fullName>Discount_Model__c</fullName>
    <label>Discount Model</label>
    <referenceTo>Discount_model__c</referenceTo>
    <relationshipLabel>Discount row</relationshipLabel>
    <relationshipName>Discount_row</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Max__c</fullName>
    <label>Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Max_perc__c</fullName>
    <label>Max (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Min__c</fullName>
    <label>Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Min_perc__c</fullName>
    <label>Min (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
  </fields>
  <label>Discount row</label>
  <nameField>
    <displayFormat>A-{0000}</displayFormat>
    <label>Discount row Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Discount row</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Sales_History__c.object
<CustomObject>
  <description>Detailed Sales History of Products Sold to Accounts</description>
  <fields>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Corresponding Purchasing Contract or Voucher when a relation exists</description>
    <inlineHelpText>Lookup field to the Corresponding Purchasing Contract or Voucher when a relation exists</inlineHelpText>
    <label>Contract/Voucher</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sales History</relationshipLabel>
    <relationshipName>Sales_History</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Discount_Model__c</fullName>
    <label>Discount Model</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <label>Sales History</label>
  <nameField>
    <label>Article (SKU)</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Sales History</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/getContract.cls
public with sharing class getContract {
public Contract contr {get;set;}
public String currentRecordId {get;set;}
//public String parameterValue {get;set;}
//public Flow.Interview.Contract_update_allowed_discount myFlow {get; set;}
//public Flow.Interview.Contract_Update_sales_history myFlow2 {get; set;}
//public PageReference conlink {get; set;}

public getContract(ApexPages.StandardController stdController) {
currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
contr = [select id, Name, StartDate, Discount_Model__r.Webshop_discount__c, New_customer__c, Correction_of_sales_needed__c, Payment_discount__c, Revenue_forecast__c, Implant_forecast__c, Account.Id, Revenue_basis_for_allowance__c,
Allowed_discount_revenue_materials__c, Negative_discount_materials__c, Negative_discount_equipment__c, 
Allowed_discount_revenue_equipments__c, Allowed_discount_Implants_materials__c, Allowed_discount_Implants_equipment__c, 
Allowed_discount_abutment_materials__c, Allowed_discount_abutment_equipment__c, Allowed_discount_pooling_materials__c, 
Allowed_discount_pooling_equipment__c, Allowed_discount_materials__c, Sales_L12M__c, Abutment_commitment_pick__c, 
Pooled_order_commitment__c, Previous_contract__r.Contract_discount_pricing_materials__c, Previous_contract__r.Contract_discount_equipment__c, 
Allowed_discount_equipment__c, Remains_impl_material__c, Row_discount_rev_mat__r.Min__c, Row_discount_rev_mat__r.Max__c, 
Row_discount_impl_mat__r.Min_perc__c, Row_discount_impl_mat__r.Max_perc__c, Implant_volume_L12M__c, 
Implant_commitment__c, Implant_commitment_perc__c, Implant_commitment_perc_input__c, Implant_commitment_abs__c, Pooled_order_commitment_perc_input__c, Abutment_commitment_formula__c
from Contract where id =: currentRecordId ];
//parameterValue = ApexPages.CurrentPage().getparameters().get('nameParam');
}

public List<Sales_History__c> Sales_Account {get; set;}

public Decimal Sales_CY_C {get; set;}
public Decimal Sales_LY_C {get; set;}
public Decimal Sales_L2Y_C {get; set;}
public Decimal Sales_L3Y_C {get; set;}

public Decimal Sales_CY_M_C {get; set;}
public Decimal Sales_LY_M_C {get; set;}
public Decimal Sales_L2Y_M_C {get; set;}
public Decimal Sales_L3Y_M_C {get; set;}

public Decimal Sales_CY_EI_C {get; set;}
public Decimal Sales_LY_EI_C {get; set;}
public Decimal Sales_L2Y_EI_C {get; set;}
public Decimal Sales_L3Y_EI_C {get; set;}

public Decimal Sales_CY_A {get; set;}
public Decimal Sales_LY_A {get; set;}
public Decimal Sales_L2Y_A {get; set;}
public Decimal Sales_L3Y_A {get; set;}

public Decimal Discount_CY_C {get; set;}
public Decimal Discount_LY_C {get; set;}
public Decimal Discount_L2Y_C {get; set;}
public Decimal Discount_L3Y_C {get; set;}

public Decimal Discount_CY_M_C {get; set;}
public Decimal Discount_LY_M_C {get; set;}
public Decimal Discount_L2Y_M_C {get; set;}
public Decimal Discount_L3Y_M_C {get; set;}

public Decimal Discount_CY_EI_C {get; set;}
public Decimal Discount_LY_EI_C {get; set;}
public Decimal Discount_L2Y_EI_C {get; set;}
public Decimal Discount_L3Y_EI_C {get; set;}

public Decimal Implants_CY_C {get; set;}
public Decimal Implants_LY_C {get; set;}
public Decimal Implants_L2Y_C {get; set;}
public Decimal Implants_L3Y_C {get; set;}

public Decimal Abutments_CY_C {get; set;}
public Decimal Abutments_LY_C {get; set;}
public Decimal Abutments_L2Y_C {get; set;}
public Decimal Abutments_L3Y_C {get; set;}

public Decimal ContractImplantsSalesActivation {get; set;}
public Decimal ContractAbutmentsSalesActivation {get; set;}

public PageReference getSales_CY () {

Sales_CY_C = 0;
Sales_LY_C = 0;
Sales_L2Y_C = 0;
Sales_L3Y_C = 0;

Sales_CY_M_C = 0;
Sales_LY_M_C = 0;
Sales_L2Y_M_C = 0;
Sales_L3Y_M_C = 0;

Sales_CY_EI_C = 0;
Sales_LY_EI_C = 0;
Sales_L2Y_EI_C = 0;
Sales_L3Y_EI_C = 0;

Discount_CY_M_C = 0;
Discount_LY_M_C = 0;
Discount_L2Y_M_C = 0;
Discount_L3Y_M_C = 0;

Discount_CY_EI_C = 0;
Discount_LY_EI_C = 0;
Discount_L2Y_EI_C = 0;
Discount_L3Y_EI_C = 0;

Discount_CY_C = 0;
Discount_LY_C = 0;
Discount_L2Y_C = 0;
Discount_L3Y_C = 0;

Implants_CY_C = 0;
Implants_LY_C = 0;
Implants_L2Y_C = 0;
Implants_L3Y_C = 0;

Abutments_CY_C = 0;
Abutments_LY_C = 0;
Abutments_L2Y_C = 0;
Abutments_L3Y_C = 0;

Sales_CY_A = 0;
Sales_LY_A = 0;
Sales_L2Y_A = 0;
Sales_L3Y_A = 0;

Sales_Account = [Select Id, Account__c, Quantity__c, Contract__c, Implants_Qty__c, Product__r.GlobalSKUMapping__r.PG2_Code__c, Discount_Amount__c, Tot_Price__c, Discount_Model__c, Gross_price__c, Invoice_Date__c, Invoice_Year_numeric__c FROM Sales_History__c WHERE Account__c =: contr.Account.Id];

For (Sales_history__c salesH : Sales_account) {
 
    if (salesH.Invoice_Year_numeric__c == System.Today().year()){
    Sales_CY_C = Sales_CY_C + salesH.Tot_Price__c;
    Implants_CY_C = Implants_CY_C + salesH.Implants_Qty__c;
    Discount_CY_C= Discount_CY_C + salesH.Gross_price__c - salesH.Tot_Price__c;    
    /*If (salesH.Discount_Amount__c>0){
    Discount_CY_C = Discount_CY_C + salesH.Discount_Amount__c;    
    }*/
    
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II11')||
            (salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II12')||
            (salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II13')||
            (salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II14')||
            (salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II16')||
            (salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II17')||
            (salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'IR31')||
            (salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'IR32')
             ){
            Sales_CY_M_C = Sales_CY_M_C + salesH.Tot_Price__c;
            Discount_CY_M_C= Discount_CY_M_C + salesH.Gross_price__c - salesH.Tot_Price__c;
            /*If (salesH.Discount_Amount__c>0){
            Discount_CY_M_C = Discount_CY_M_C + salesH.Discount_Amount__c; 
            }*/
        }
        
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II15')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II18')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'IR30')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID85')
           ) {
        Sales_CY_EI_C = Sales_CY_EI_C + salesH.Tot_Price__c;
        Discount_CY_EI_C= Discount_CY_EI_C + salesH.Gross_price__c - salesH.Tot_Price__c;            
            
            /*If (salesH.Discount_Amount__c>0){
            Discount_CY_EI_C = Discount_CY_EI_C + salesH.Discount_Amount__c; 
            }*/
        }
        
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II12')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID21')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID22')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID23')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID28')) {
        Abutments_CY_C = Abutments_CY_C + salesH.Quantity__c;
        
        }
        
        
    }

    if (salesH.Invoice_Year_numeric__c == (System.Today().year()-1)){
    Sales_LY_C = Sales_LY_C + salesH.Tot_Price__c;
    Implants_LY_C = Implants_LY_C + salesH.Implants_Qty__c;
    Discount_LY_C= Discount_LY_C + salesH.Gross_price__c - salesH.Tot_Price__c;    
            /*If (salesH.Discount_Amount__c>0){
            Discount_LY_C = Discount_LY_C + salesH.Discount_Amount__c;
            }*/
    
    
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II11')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II12')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II13')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II14')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II16')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II17')) {
        Sales_LY_M_C = Sales_LY_M_C + salesH.Tot_Price__c;
        Discount_LY_M_C= Discount_LY_M_C + salesH.Gross_price__c - salesH.Tot_Price__c;
             /*If (salesH.Discount_Amount__c>0){
             Discount_LY_M_C = Discount_LY_M_C + salesH.Discount_Amount__c; 
             }*/
        }
        
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II15')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II18')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'IR30')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID85')
           ) {
        Sales_LY_EI_C = Sales_LY_EI_C + salesH.Tot_Price__c;
        Discount_LY_EI_C= Discount_LY_EI_C + salesH.Gross_price__c - salesH.Tot_Price__c;    
            /*If (salesH.Discount_Amount__c>0){
            Discount_LY_EI_C = Discount_LY_EI_C + salesH.Discount_Amount__c; 
            }*/
        }
        
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II12')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID21')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID22')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID23')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID28')) {
        Abutments_LY_C = Abutments_LY_C + salesH.Quantity__c;
        }
              
      
    }

    if (salesH.Invoice_Year_numeric__c == (System.Today().year()-2)){
    Sales_L2Y_C = Sales_L2Y_C + salesH.Tot_Price__c;
    Implants_L2Y_C = Implants_L2Y_C + salesH.Implants_Qty__c;
    Discount_L2Y_C= Discount_L2Y_C + salesH.Gross_price__c - salesH.Tot_Price__c;    
    /*If (salesH.Discount_Amount__c>0){
        Discount_L2Y_C = Discount_L2Y_C + salesH.Discount_Amount__c;
    }*/
    
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II11')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II12')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II13')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II14')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II16')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II17')) {
        Sales_L2Y_M_C = Sales_L2Y_M_C + salesH.Tot_Price__c;
        Discount_L2Y_M_C= Discount_L2Y_M_C + salesH.Gross_price__c - salesH.Tot_Price__c;            
            /*If (salesH.Discount_Amount__c>0){
            Discount_L2Y_M_C = Discount_L2Y_M_C + salesH.Discount_Amount__c;
            }*/ 
            
        }
        
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II15')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II18')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'IR30')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID85')
           ) {
        Sales_L2Y_EI_C = Sales_L2Y_EI_C + salesH.Tot_Price__c;
        Discount_L2Y_EI_C= Discount_L2Y_EI_C + salesH.Gross_price__c - salesH.Tot_Price__c;        
            /*If (salesH.Discount_Amount__c>0){
            Discount_L2Y_EI_C = Discount_L2Y_EI_C + salesH.Discount_Amount__c;
            }*/
        } 
        
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II12')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID21')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID22')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID23')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID28')) {
        Abutments_L2Y_C = Abutments_L2Y_C + salesH.Quantity__c;
        }           
    
    }
    
        if (salesH.Invoice_Year_numeric__c == (System.Today().year()-3)){
    Sales_L3Y_C = Sales_L3Y_C + salesH.Tot_Price__c;
    Implants_L3Y_C = Implants_L3Y_C + salesH.Implants_Qty__c;
    Discount_L3Y_C= Discount_L3Y_C + salesH.Gross_price__c - salesH.Tot_Price__c;
       /*If (salesH.Discount_Amount__c>0){
        Discount_L3Y_C = Discount_L3Y_C + salesH.Discount_Amount__c;       
       }*/
    
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II11')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II12')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II13')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II14')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II16')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II17')) {
        Sales_L3Y_M_C = Sales_L3Y_M_C + salesH.Tot_Price__c;
        Discount_L3Y_M_C= Discount_L3Y_M_C + salesH.Gross_price__c - salesH.Tot_Price__c;            
            /*If (salesH.Discount_Amount__c>0){
            Discount_L3Y_M_C = Discount_L3Y_M_C + salesH.Discount_Amount__c; 
            }*/
        }
        
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II15')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II18')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'IR30')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID85')  
           ) {
        Sales_L3Y_EI_C = Sales_L3Y_EI_C + salesH.Tot_Price__c;
        Discount_L3Y_EI_C= Discount_L3Y_EI_C + salesH.Gross_price__c - salesH.Tot_Price__c;        
            /*If (salesH.Discount_Amount__c>0){
            Discount_L3Y_EI_C = Discount_L3Y_EI_C + salesH.Discount_Amount__c;
            }*/
        } 
        
        if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II12')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID21')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID22')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID23')
            ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID28')) {
        Abutments_L3Y_C = Abutments_L3Y_C + salesH.Quantity__c;
        }
              
    }
    
   
}

return null;
}


public PageReference getContractStatus () {

ContractImplantsSalesActivation = 0;
ContractAbutmentsSalesActivation = 0;

Sales_Account = [Select Id, Account__c, Quantity__c, Contract__c, Implants_Qty__c, Product__r.GlobalSKUMapping__r.PG2_Code__c, Discount_Amount__c, Discount_Model__c, Tot_Price__c, Gross_price__c, Invoice_Date__c, Invoice_Year_numeric__c FROM Sales_History__c WHERE Account__c =: contr.Account.Id];
    
For (Sales_history__c salesH : Sales_account) {

        if(salesH.Contract__c == currentRecordId || (salesH.Discount_Model__c == 'DE-DENTAL2' && salesH.Invoice_Date__c >= contr.StartDate)) {
                ContractImplantsSalesActivation = ContractImplantsSalesActivation + salesH.Implants_Qty__c;
        
                if ((salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'II12')
                    ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID21')
                    ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID22')
                    ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID23')
                    ||(salesH.Product__r.GlobalSKUMapping__r.PG2_Code__c == 'ID28')){
         
                     ContractAbutmentsSalesActivation = ContractAbutmentsSalesActivation + salesH.Quantity__c;          
                   
                 }
         }    

}

return null;

}



public Boolean HasM {get; set;}

Public void save(){

try{
upsert contr;
HasM = false;
}

catch(Exception ex){
ApexPages.addMessages(ex);
HasM = true;
}

}


public void doAction () {
}

public String stepname {get; set;}

public void navFlow () {
stepname = 'FLOW';
}

public void navEnd () {
stepname = 'END';
}


}