unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Chinese</fullName>
        </value>
        <value>
          <fullName>Danish</fullName>
        </value>
        <value>
          <fullName>Dutch</fullName>
        </value>
        <value>
          <fullName>English</fullName>
        </value>
        <value>
          <fullName>Finnish</fullName>
        </value>
        <value>
          <fullName>Flemish</fullName>
        </value>
        <value>
          <fullName>French</fullName>
        </value>
        <value>
          <fullName>German</fullName>
        </value>
        <value>
          <fullName>Italian</fullName>
        </value>
        <value>
          <fullName>Japanese</fullName>
        </value>
        <value>
          <fullName>Norwegian</fullName>
        </value>
        <value>
          <fullName>Portuguese</fullName>
        </value>
        <value>
          <fullName>Russian</fullName>
        </value>
        <value>
          <fullName>Spanish</fullName>
        </value>
        <value>
          <fullName>Swedish</fullName>
        </value>
        <value>
          <fullName>Thai</fullName>
        </value>
        <value>
          <fullName>Vietnamese</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>HQ</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Luxembourg</fullName>
        </value>
        <value>
          <fullName>New Zealand</fullName>
        </value>
        <value>
          <fullName>Norway</fullName>
        </value>
        <value>
          <fullName>Poland</fullName>
        </value>
        <value>
          <fullName>Portugal</fullName>
        </value>
        <value>
          <fullName>South Africa</fullName>
        </value>
        <value>
          <fullName>Spain</fullName>
        </value>
        <value>
          <fullName>Sweden</fullName>
        </value>
        <value>
          <fullName>Switzerland</fullName>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
        <value>
          <fullName>Ukraine</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>true</active>
    <description>In use for all countries</description>
    <fullName>ContactGlobal</fullName>
    <label>Contact Global</label>
  </recordTypes>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/LoyaltyProgramParticipant__c.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Program Members</relationshipLabel>
    <relationshipName>LoyaltyProgramParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Program Members</relationshipLabel>
    <relationshipName>Account_Program_Members</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Random string generated on insert. Used as external id to be sent out via email to customers to not expose the real Salesforce Id.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
  </fields>
  <label>Account Program Member</label>
  <nameField>
    <displayFormat>LPP-{0000}</displayFormat>
    <label>Account Program Member Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Account Program Members</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/Test_LoyaltyParticipantTrigger.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Kevin Ruibin Do (Salesforce) 20200908
Description:    Test class for LoyaltyProgramParticipant trigger methods
History 
20200908        Kevin Ruibin Do - Created Class
--------------------------------------------------------------------------------------------------------*/

@IsTest(seeAllData=false)
public class Test_LoyaltyParticipantTrigger {
    @testSetup
    static void makeData(){
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.returnUsers(1, 'System Administrator');
        userList[0].User_Country__c = 'Canada';
        insert userList;
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();

        // Setup Account, Contact, and LoyaltyProgramParticipant__c
        System.runAs(userList[0]) {
            List<Account> accountList = TestDataFactory.returnAccounts(1, 'CIM_Account', userList[0].Id);
            insert accountList;
    
            List<Contact> contactList = TestDataFactory.returnContacts(1, 'ContactGlobal', userList[0].Id);
            contactList[0].Preferred_Language__c = 'English';
            insert contactList;
        }
    }

    @IsTest
    public static void testSetExternalId() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        Account testAccount = [SELECT Id FROM Account WHERE OwnerId = :testUser.Id LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact WHERE OwnerId = :testUser.Id LIMIT 1];

        Test.startTest();
        System.runAs(testUser) {
            LoyaltyProgramParticipant__c testParticipant = new LoyaltyProgramParticipant__c(
                Account__c = testAccount.Id
                ,Contact__c = testContact.Id
            );
            insert testParticipant;
        }
        Test.stopTest();

        System.assert(String.isNotEmpty([SELECT ExternalId__c FROM LoyaltyProgramParticipant__c WHERE CreatedById = :testUser.Id LIMIT 1].ExternalId__c), 'External Id was not set');
    }
}