unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Profession__c</fullName>
    <description>Dependent upon Product Area</description>
    <label>Role/Profession</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Advanced Practice Dental Therapist</fullName>
        </value>
        <value>
          <fullName>Clinical Director</fullName>
        </value>
        <value>
          <fullName>Consultant</fullName>
        </value>
        <value>
          <fullName>Contractor</fullName>
        </value>
        <value>
          <fullName>Dean</fullName>
          <label>Dean/Head</label>
        </value>
        <value>
          <fullName>Dental Assistant</fullName>
        </value>
        <value>
          <fullName>Dental Hygienist</fullName>
        </value>
        <value>
          <fullName>Dental Laboratory General Manager</fullName>
        </value>
        <value>
          <fullName>Dental Laboratory Office Manager</fullName>
        </value>
        <value>
          <fullName>Dental Laboratory Technician</fullName>
        </value>
        <value>
          <fullName>Dental Nurse</fullName>
        </value>
        <value>
          <fullName>Dental Nurse Manager</fullName>
        </value>
        <value>
          <fullName>Dental Student</fullName>
        </value>
        <value>
          <fullName>Dental Technician</fullName>
        </value>
        <value>
          <fullName>Dental Technician Master</fullName>
        </value>
        <value>
          <fullName>Dental Therapist</fullName>
        </value>
        <value>
          <fullName>Dentist</fullName>
        </value>
        <value>
          <fullName>Denturist</fullName>
        </value>
        <value>
          <fullName>Distributor General Manager</fullName>
        </value>
        <value>
          <fullName>Distributor Sales Rep</fullName>
        </value>
        <value>
          <fullName>Doctor</fullName>
        </value>
        <value>
          <fullName>DS Employee</fullName>
        </value>
        <value>
          <fullName>Employee</fullName>
        </value>
        <value>
          <fullName>Endodontist</fullName>
        </value>
        <value>
          <fullName>Faculty/Instructor/Professor</fullName>
        </value>
        <value>
          <fullName>General Dentist</fullName>
        </value>
        <value>
          <fullName>General Manager</fullName>
        </value>
        <value>
          <fullName>Head of Department</fullName>
        </value>
        <value>
          <fullName>Implant Manager</fullName>
        </value>
        <value>
          <fullName>Implantologist</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Expert__c.object
<CustomObject>
  <fields>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>KOL information</relationshipLabel>
    <relationshipName>KOL_information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Designer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Designer</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Not_a_Healthcare_Professional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be ticked if this KOL is not a healthcare professional and therefor not part of/included in the Fair Market Value (FMV) regulations. If this is ticked contracts etc. will not enforce a specific payment range.</description>
    <inlineHelpText>Tick this checkbox if the KOL is not a Healthcare Professional and therefor not part of FMV regulations.</inlineHelpText>
    <label>Not a Healthcare Professional</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Profession__c</fullName>
    <description>Used by Clinical Affairs - also included in some logic for the Fair Market Value calculations so needed a sepaareta list. Ultimate solution would be to merge this with global profession/contcat subtype valueas.</description>
    <inlineHelpText>Add the profession of the KOL</inlineHelpText>
    <label>Profession</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>General Dentist</fullName>
        </value>
        <value>
          <fullName>Endodontist</fullName>
        </value>
        <value>
          <fullName>Pediatric Dentist</fullName>
        </value>
        <value>
          <fullName>Dental Anesthesiology</fullName>
        </value>
        <value>
          <fullName>Geriatric Dentist</fullName>
        </value>
        <value>
          <fullName>Periodontist</fullName>
        </value>
        <value>
          <fullName>Prosthodontist</fullName>
        </value>
        <value>
          <fullName>Special Care Dentistry</fullName>
        </value>
        <value>
          <fullName>Implantologist</fullName>
        </value>
        <value>
          <fullName>Oral and Maxilllofacial Pathology</fullName>
        </value>
        <value>
          <fullName>Orthodontist</fullName>
        </value>
        <value>
          <fullName>Oral and Maxillofacial Radiology</fullName>
        </value>
        <value>
          <fullName>Oral and Maxillofacial Surgeon</fullName>
        </value>
        <value>
          <fullName>Dental Assistant</fullName>
        </value>
        <value>
          <fullName>Laboratory Technician</fullName>
        </value>
        <value>
          <fullName>Dental Hygienist</fullName>
        </value>
        <value>
          <fullName>Oral Medicine Specialist</fullName>
        </value>
        <value>
          <fullName>Office Manager/Practice Administrator</fullName>
        </value>
        <value>
          <fullName>Oral Biologist</fullName>
        </value>
        <value>
          <fullName>Oral Microbiologist</fullName>
        </value>
        <value>
          <fullName>Dental Scientist</fullName>
        </value>
        <value>
          <fullName>Public Health Dentist</fullName>
        </value>
        <value>
          <fullName>Preventive Dentist</fullName>
        </value>
        <value>
          <fullName>Infection Control Specialist</fullName>
        </value>
        <value>
          <fullName>Forensic Dentistry</fullName>
        </value>
        <value>
          <fullName>Forensic Odontology</fullName>
        </value>
        <value>
          <fullName>Laboratory Owner/Upper Level Management</fullName>
        </value>
        <value>
          <fullName>Non-Healthcare Provider</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>KOL information</label>
  <nameField>
    <label>KOL Information</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>KOL information</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Test_KOLInfoTrigger.cls
/*------------------------------------------------------------
Author: 		Richard Trum (Glimt) 2019-12-05
Description:   	Test Class for all KOLInfoTriggerHelper methods.
History
<Date>      <Authors Name>     <Brief Description of Change>
20191205 	Richard Trum		Created test class for the trigger framework for the KOL Information (Expert__c) object
								Based on the Test_AccountTrigger class from Salesforce
------------------------------------------------------------*/

@isTest(seeAllData=false)
public class Test_KOLInfoTrigger {

    /*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
    }

    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();

        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }

    /*-------------------------------------------------------------------------------------------------------
    Company: Glimt
    Description: Test method for KOLInfoTriggerHelper.preventDuplicateKOLs()
    History :
    --------------------------------------------------------------------------------------------------------*/
    @isTest
    private static void testPreventDuplicateKOLs() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        List<Account> testAccountList = TestDataFactory.returnAccounts(1, 'Non_ERP_Account', testUser.Id);
        Account testAccount = testAccountList[0];
        
        Contact testContact = new Contact();
        testContact.FirstName ='Test';
        testContact.LastName = 'Contact';
        testContact.AccountId = testAccount.Id;
        insert testContact;
        
        Expert__c testKOL = new Expert__c();
        testKOL.Contact__c = testContact.Id;
        testKOL.Name = 'Test KOL';
        insert testKOL;
        
        Test.startTest();
        // Test inserting a second KOL Information record towards the same Contact
        Expert__c validateKOL = new Expert__c();
        validateKOL.Contact__c = testContact.Id;
        validateKOL.Name = 'Validating KOL duplication';
        
        try {
        	insert validateKOL;
        }
        catch(DmlException e){
            System.assertNotEquals(null, e.getDmlMessage(0));
        }
        Test.stopTest();

    }
    
    /*-------------------------------------------------------------------------------------------------------
    Company: Glimt
    Description: Test method for KOLInfoTriggerHelper.setExpertName
				 Migrated from the trigger setExpertName
    History :
    --------------------------------------------------------------------------------------------------------*/
    @isTest
    private static void testSetExpertName() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        List<Account> testAccountList = TestDataFactory.returnAccounts(1, 'Non_ERP_Account', testUser.Id);
        Account testAccount = testAccountList[0];
        
        Contact testContact = new Contact();
        testContact.FirstName ='Test';
        testContact.LastName = 'Contact';
        testContact.AccountId = testAccount.Id;
        insert testContact;
        
        testContact = [SELECT Id, FirstName, LastName FROM Contact WHERE Id =: testContact.Id];
        
        Expert__c testKOL = new Expert__c();
        testKOL.Contact__c = testContact.Id;
        testKOL.Name = 'Test KOL';
        insert testKOL;
                
        Test.startTest();
        
		testKOL.Designer__c = true;
        update testKOL;
        
        Test.stopTest();
		
		testKOL = [SELECT Id, Contact__c, Name FROM Expert__c WHERE Id =: testKOL.Id];
        System.assertEquals('Test Contact - KOL info', testKOL.Name);        

    } 
    
        /*-------------------------------------------------------------------------------------------------------
    Company: Glimt
    Description: Test method for KOLInfoTriggerHelper.setNonHCProfession
    History :
    --------------------------------------------------------------------------------------------------------*/
    @isTest
    private static void testSetNonHCProfession() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        List<Account> testAccountList = TestDataFactory.returnAccounts(1, 'Non_ERP_Account', testUser.Id);
        Account testAccount = testAccountList[0];
        
        Contact testContact = new Contact();
        testContact.FirstName ='Test';
        testContact.LastName = 'Contact';
        testContact.AccountId = testAccount.Id;
        insert testContact;
        
        testContact = [SELECT Id, FirstName, LastName FROM Contact WHERE Id =: testContact.Id];
        
        Expert__c testKOL = new Expert__c();
        testKOL.Contact__c = testContact.Id;
        testKOL.Name = 'Test KOL';
        insert testKOL;
                
        Test.startTest();
        
		testKOL.Profession__c = 'Non-Healthcare Provider';
        update testKOL;
        
        Test.stopTest();
		
		testKOL = [SELECT Id, Contact__c, Profession__c, Not_a_Healthcare_Professional__c, Name FROM Expert__c WHERE Id =: testKOL.Id];
        System.assertEquals(true, testKOL.Not_a_Healthcare_Professional__c);        

    }  
    
}