unpackaged/objects/Contact.object
<CustomObject>
  <fields>
    <fullName>Email_Consent_collected__c</fullName>
    <description>This field is used as part of the data privacy, e.g. GDPR process to make sure we are collecting information about whether a consent has been collected or not for sending marketing emails. If yes is selected that Email Consent Date fields will be updated with Todays date. If no the email opt out checkbox will be checked. Using workflows. Email still kept for both selections</description>
    <inlineHelpText>I confirm that I have obtained the customers permission for their email address to be used by Dentsply Sirona for Marketing communications.</inlineHelpText>
    <label>Email Marketing Consent collected</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Please Select Yes or No</fullName>
        </value>
        <value>
          <fullName>Yes</fullName>
        </value>
        <value>
          <fullName>No</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>HowCollected__c</fullName>
    <label>How collected?</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>GDPR_consent_method</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>InsertEmailMarketingConsentCollected__c</fullName>
    <inlineHelpText>Please fill the information if the Email Marketing Consent was collected or not</inlineHelpText>
    <label>Insert Email Marketing Consent Collected</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Yes</fullName>
        </value>
        <value>
          <fullName>No</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Chinese</fullName>
        </value>
        <value>
          <fullName>Danish</fullName>
        </value>
        <value>
          <fullName>Dutch</fullName>
        </value>
        <value>
          <fullName>English</fullName>
        </value>
        <value>
          <fullName>Finnish</fullName>
        </value>
        <value>
          <fullName>Flemish</fullName>
        </value>
        <value>
          <fullName>French</fullName>
        </value>
        <value>
          <fullName>German</fullName>
        </value>
        <value>
          <fullName>Italian</fullName>
        </value>
        <value>
          <fullName>Japanese</fullName>
        </value>
        <value>
          <fullName>Norwegian</fullName>
        </value>
        <value>
          <fullName>Portuguese</fullName>
        </value>
        <value>
          <fullName>Russian</fullName>
        </value>
        <value>
          <fullName>Spanish</fullName>
        </value>
        <value>
          <fullName>Swedish</fullName>
        </value>
        <value>
          <fullName>Thai</fullName>
        </value>
        <value>
          <fullName>Vietnamese</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>WhenCollected__c</fullName>
    <label>When collected?</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>WhereCollected__c</fullName>
    <label>Where collected?</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/LoyaltyProgram__c.object
<CustomObject>
  <description>Used to track programs that an Account is participating at. Example could be a loyalty Program. 

Note that the API label says LoyaltyProgram since that was the first design of it and intention for it - but has been relabeled to have a broader meaning and sense since whereas types of programs has arised as a need.</description>
  <label>Account Program</label>
  <nameField>
    <label>Account Program Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Account Programs</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/LoyaltyProgramParticipant__c.object
<CustomObject>
  <fields>
    <fullName>AcceptedTermsAndConditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted Terms and Conditions</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Program Members</relationshipLabel>
    <relationshipName>LoyaltyProgramParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Program Members</relationshipLabel>
    <relationshipName>Account_Program_Members</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Email__c</fullName>
    <description>Email of the person signing the T&amp;C</description>
    <label>Email</label>
    <type>Email</type>
  </fields>
  <fields>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Random string generated on insert. Used as external id to be sent out via email to customers to not expose the real Salesforce Id.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
  </fields>
  <fields>
    <fullName>FirstName__c</fullName>
    <description>First Name of the person agreeing to the T&amp;C.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LastName__c</fullName>
    <description>Last Name of the person signing the T&amp;C</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LoyaltyProgram__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Program</label>
    <referenceTo>LoyaltyProgram__c</referenceTo>
    <relationshipLabel>Account Program Members</relationshipLabel>
    <relationshipName>LoyaltyProgramParticipants</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>PaymentPreference__c</fullName>
    <label>Payment Preference</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>Subtype__c</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Quarterly Payouts</fullName>
        </value>
        <value>
          <fullName>Annual Rebate Voucher</fullName>
        </value>
        <value>
          <fullName>Annual Cash Payout</fullName>
        </value>
        <value>
          <fullName>Annual Product Credit Voucher</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>PracticeName__c</fullName>
    <description>Practice Name of the person signing the T&amp;C.</description>
    <label>Practice Name</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>TermsAndConditionsConsentDate__c</fullName>
    <label>Terms and Conditions Consent Date</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>TermsAndConditionsDocumentLink__c</fullName>
    <description>Link to the T&amp;C document that the customer accepted</description>
    <inlineHelpText>Link to the T&amp;C document that the customer accepted</inlineHelpText>
    <label>Terms and Conditions Document Link</label>
    <type>Url</type>
  </fields>
  <label>Account Program Member</label>
  <nameField>
    <displayFormat>LPP-{0000}</displayFormat>
    <label>Account Program Member Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Account Program Members</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/OneDSTermsAndConditionsSetting__mdt.object
<CustomObject>
  <description>Localization settings for the OneDS Terms and Conditions public site.</description>
  <fields>
    <fullName>ConsentStatement__c</fullName>
    <description>Consent statement in localized language</description>
    <label>ConsentStatement</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>DocumentPublicLink__c</fullName>
    <description>Public link to the Terms and Conditions document</description>
    <label>DocumentPublicLink</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>InfoText__c</fullName>
    <description>Info text in locaized language</description>
    <label>InfoText</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LabelConsent__c</fullName>
    <description>Consent label in localized language</description>
    <label>LabelConsent</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LabelEmail__c</fullName>
    <description>Label for the Email field</description>
    <label>LabelEmail</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LabelFirstName__c</fullName>
    <description>Label for the First Name field</description>
    <label>LabelFirstName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LabelLastName__c</fullName>
    <description>Label for the Last Name field</description>
    <label>LabelLastName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LabelPaymentPreference__c</fullName>
    <description>TFUS-000002998</description>
    <label>Label Payment Preference</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LabelPracticeName__c</fullName>
    <description>Label for the Practice Name field</description>
    <label>LabelPracticeName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LabelSubmit__c</fullName>
    <description>Submit label in localized language</description>
    <label>LabelSubmit</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>LabelTermsAndConditions__c</fullName>
    <description>Label for Terms and Conditions Link in localized language</description>
    <label>LabelTermsAndConditions</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Language__c</fullName>
    <description>Language matching Contact.Preferred_Language__c value</description>
    <label>Language</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>ProgramName__c</fullName>
    <description>TFUS-000002698 Used in OneDsCanadaTermsAndConditions_CC to find relevant mtd record in SOQL query by matching `LoyaltyProgramParticipant__c.LoyaltyProgram__r.Name`</description>
    <label>Program Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>SuccessMessage__c</fullName>
    <description>Success Message in localized language</description>
    <label>SuccessMessage</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Title__c</fullName>
    <description>Title in localized language</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <label>OneDS Terms and Conditions Setting</label>
  <pluralLabel>OneDS Terms and Conditions Settings</pluralLabel>
</CustomObject>

unpackaged/classes/OneDsCanadaTermsAndConditions_CC.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Kevin Ruibin Do (Salesforce) 20200911
Description:    Custom controller for OneDSCanadaTermsAndConditions vf page
                TFUS-000002124
Tesst Class:    Test_OneDSCanadaTermsAndConditions_CC
History:        20200911    Kevin Ruibin Do - Created Class
--------------------------------------------------------------------------------------------------------*/

public without sharing class OneDsCanadaTermsAndConditions_CC {
    private final LoyaltyProgramParticipant__c lPParticipant { get; set; }
    private final OneDSTermsAndConditionsSetting__mdt pageSetting { get; set; }

    public String title { get; set; }
    public String infoText { get; set; }
    
    public String documentLink { get; set; }
    public String termsAndConditionsLabel { get; set; }
    
    public String firstName { get; set; }
    public String firstNameLabel { get; set; }
    
    public String lastName { get; set; }
    public String lastNameLabel { get; set; }
    
    public String practiceName { get; set; }
    public String practiceNameLabel { get; set; }

    public String paymentPreference { get; set; }
    public String paymentPreferenceLabel { get; set; }
    
    public String email { get; set; }
    public String emailLabel { get; set; }

    public String consentLabel { get; set; }
    public String consentStatement { get; set; }

    public String submitLabel { get; set; }
    public String successMessage { get; set; }
    public String errorMessage { get; set; }
    
    public Boolean hasAccepted { get; set; }
    public Boolean error { get; set; }
    public Boolean isSubmitted { get; set; }
    
    public String customerId { get; set; }

    // Default values
    {
        title = 'One DS Rewards Terms and Conditions';
        errorMessage = 'Something went wrong';
    }

    public OneDsCanadaTermsAndConditions_CC(/* ApexPages.StandardController stdController */) {
        // Get the id url parameter to use as query key
        customerId = Apexpages.currentPage().getParameters().get('id');
        String preferredLanguage = 'English';

        List<LoyaltyProgramParticipant__c> lPParticipantList = new List<LoyaltyProgramParticipant__c>();
        List<OneDSTermsAndConditionsSetting__mdt> OneDSTermsAndConditionsSettingList = new List<OneDSTermsAndConditionsSetting__mdt>();

        try {
            // Query participant record that has a matching ExternalID__c to the id url-parameter

            // TODO EMAIL readonly populated from related Contact
            lPParticipantList = [
                SELECT Name, FirstName__c, LastName__c, PracticeName__c, Email__c, AcceptedTermsAndConditions__c, TermsAndConditionsConsentDate__c, PaymentPreference__c, Contact__c, Contact__r.Preferred_Language__c, Contact__r.Email, LoyaltyProgram__r.Name, Account__r.Name
                FROM LoyaltyProgramParticipant__c
                WHERE ExternalId__c =: customerId
                LIMIT 1
            ];

            if (!lPParticipantList.isEmpty()) {
                // Query custom metadata type record with correct language settings
                lPParticipant = lPParticipantList[0];
                if (String.isNotBlank(lPParticipant.Contact__r.Preferred_Language__c)) preferredLanguage = lPParticipant.Contact__r.Preferred_Language__c;
                String programName = lPParticipant?.LoyaltyProgram__r?.Name;
                // preferredLanguage = lPParticipant.Contact__r.Preferred_Language__c;
                OneDSTermsAndConditionsSettingList = [
                    SELECT Title__c, InfoText__c, DocumentPublicLink__c, LabelTermsAndConditions__c, LabelFirstName__c, LabelLastName__c, LabelPracticeName__c, LabelPaymentPreference__c, LabelEmail__c, LabelConsent__c, ConsentStatement__c, LabelSubmit__c, SuccessMessage__c, Language__c
                    FROM OneDSTermsAndConditionsSetting__mdt
                    WHERE Language__c = :preferredLanguage AND ProgramName__c = :programName
                    LIMIT 1
                ];
            }

            if (!OneDSTermsAndConditionsSettingList.isEmpty()) {
                // Check if customer has already accepted T&C
                hasAccepted = lPParticipant.AcceptedTermsAndConditions__c;
                firstName = lPParticipant.FirstName__c;
                lastName = lPParticipant.LastName__c;
                practiceName = String.isNotEmpty(lPParticipant.PracticeName__c) ? lPParticipant.PracticeName__c : lPParticipant.Account__r?.Name;
                paymentPreference = lPParticipant.PaymentPreference__c;
                email = lPParticipant.Contact__r.Email;
                // Set labels and text based on the cusstomm metadata type record
                pageSetting = OneDSTermsAndConditionsSettingList[0];
                title = pageSetting.Title__c;
                infoText = pageSetting.InfoText__c;
                documentLink = pageSetting.DocumentPublicLink__c;
                termsAndConditionsLabel = pageSetting.LabelTermsAndConditions__c;
                firstNameLabel = pageSetting.LabelFirstName__c;
                lastNameLabel = pageSetting.LabelLastName__c;
                practiceNameLabel = pageSetting.LabelPracticeName__c;
                paymentPreferenceLabel = pageSetting.LabelPaymentPreference__c;
                emailLabel = pageSetting.LabelEmail__c;
                consentLabel = pageSetting.LabelConsent__c;
                consentStatement = pageSetting.ConsentStatement__c;
                submitLabel = pageSetting.LabelSubmit__c;
                successMessage = pageSetting.SuccessMessage__c;
            } else {
                error = true;
            }
        } catch (Exception e) {
            error = true;
        }
    }

    public PageReference accept() {
        //TODO email consent should be set as yes

        // Custom validation if user has clicked the accept checkbox, surface error if not
        if(!hasAccepted) {
            Apexpages.addMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR,
                    'Please accept the terms and conditions before submitting.'
                )
            );
            return null;
        }

        // Assign LoyaltyProgramParticipant__c field values from form
        lPParticipant.FirstName__c = firstName;
        lPParticipant.LastName__c = lastName;
        lPParticipant.PracticeName__c = practiceName;
        lPParticipant.Email__c = email;
        lPParticipant.AcceptedTermsAndConditions__c = hasAccepted;
        lPParticipant.TermsAndConditionsConsentDate__c = System.now();
        lPParticipant.TermsAndConditionsDocumentLink__c = pageSetting.DocumentPublicLink__c;

        // Query and set information on related Contact record
        Contact contactToUpdate = [
            SELECT Id, Email_Consent_Collected__c, WhenCollected__c, WhereCollected__c, HowCollected__c
            FROM Contact
            WHERE Id = :lPParticipant.Contact__c
        ];
        // contactToUpdate.Email_Consent_collected__c = 'Yes';
        contactToUpdate.InsertEmailMarketingConsentCollected__c = 'Yes';
        contactToUpdate.WhenCollected__c = lPParticipant.TermsAndConditionsConsentDate__c;
        contactToUpdate.WhereCollected__c = 'Canada One DS Terms and Conditions Site';
        contactToUpdate.HowCollected__c = 'Digitally';
        
        Savepoint sp = Database.setSavepoint();
        try {
            update lPParticipant;
            update contactToUpdate;
        } catch (Exception e) {
            Database.rollback(sp);
            error = true;
            DebugLog.addException(e, 'OneDsCanadaTermsAndConditions_CC DML error');
        }
        
        isSubmitted = true;
        return null;
    }
}