unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Preferred_dealer_item__c.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Preferred_dealer_items1</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>1 OR (2 AND 3)</booleanFilter>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>ERP Distributor, Non-ERP Distributor, DNA Distributor</value>
      </filterItems>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>CIM Account</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Distributor</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealers (Dealer)</relationshipLabel>
    <relationshipName>Preferred_dealer_items</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Default_dealer__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Default dealer</label>
    <type>Checkbox</type>
  </fields>
  <label>Dealer</label>
  <nameField>
    <displayFormat>PDI{00000}</displayFormat>
    <label>Dealer Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Dealers</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/getPreferredDealerTest.cls
@isTest
public with sharing class getPreferredDealerTest {    
    
@isTest
private static void getPreferredDealer_Test(){

        
        Account a = new Account(Name='Test account 1', CurrencyIsoCode = 'EUR', Country__c = 'NL');
        insert a;
        
        Account d1 = new Account(Name='Dealer account 1', CurrencyIsoCode = 'EUR', Country__c = 'NL', RecordTypeID = '01220000000ckje');
        insert d1;
        
        Account d2 = new Account(Name='Dealer account 2', CurrencyIsoCode = 'EUR', Country__c = 'NL', RecordTypeID = '01220000000ckje');
        insert d2;
        
        Preferred_dealer_item__c pd = new Preferred_dealer_item__c (Account__c=a.Id, Dealer__c = d1.Id, Default_dealer__c = true);
        insert pd;
        
        List<Preferred_dealer_item__c> opps = [SELECT Id, Name, Account__c, Dealer__c FROM Preferred_dealer_item__c Where Account__c =: a.id]; 
        
        //DateTime expected = DateTime.newInstance(2016, 4, 21, 8, 13, 16);
            
        ApexPages.currentPage().getParameters().put('id', a.id);     
        
        ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(opps);   
        
        getPreferredDealers controller = new getPreferredDealers(stdController);
        
        controller.fetchRecords();
        
        system.assertNotEquals(null, controller.acc.id);
        
        system.assertNotEquals(null, controller.prfd.id);
        
        system.assertNotEquals(null, controller.getRadioValue);
        
        system.assertEquals(1, controller.pdeList.size());
        
        system.assertEquals(1, controller.dealerList.size());
        
        controller.addDealer();
        
        system.assertEquals(1, controller.pdeList.size());
        
        controller.dealerList[0].selected_pd = true;
        
        controller.addDealer();
        
        system.assertEquals(2, controller.pdeList.size());
              
        controller.pdeList[1].selected_pd = true;
        controller.pdeList[0].selected_pd = false;
        
        system.assertEquals(2, controller.getDealerOptions().size());
        
        controller.saveDealer();
        
        controller.pdeList[1].selected_pd = true;
        controller.pdeList[0].selected_pd = true;
        
        controller.saveDealer();
        
    } 
    
    
    }