unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
  <fields>
    <fullName>Lost_Opportunity_Reason__c</fullName>
    <label>Lost Opportunity Reason</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>StageName</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Competitor Related</fullName>
        </value>
        <value>
          <fullName>Others</fullName>
        </value>
        <value>
          <fullName>Price Related</fullName>
        </value>
        <value>
          <fullName>Product Feature Related</fullName>
        </value>
        <value>
          <fullName>Service Related</fullName>
        </value>
        <value>
          <fullName>Time Related</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Primary_Contact_s_Email_Address__c</fullName>
    <formula>Primary_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact's Email Address</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Primary_Contact_s_Mobile__c</fullName>
    <formula>Primary_Contact__r.MobilePhone</formula>
    <label>Primary Contact's Mobile</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Primary_Contact_s_Phone__c</fullName>
    <formula>Primary_Contact__r.Phone</formula>
    <label>Primary Contact's Phone</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Product_Line_Interested_In__c</fullName>
    <label>Product Line Interested In</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>CAD/CAM - CEREC</fullName>
        </value>
        <value>
          <fullName>CAD/CAM - InLab</fullName>
        </value>
        <value>
          <fullName>CAD/CAM - Nazaré</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Imaging</fullName>
        </value>
        <value>
          <fullName>Imaging - Extra Oral</fullName>
        </value>
        <value>
          <fullName>Imaging - Intra Oral</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Instruments</fullName>
        </value>
        <value>
          <fullName>Laboratory</fullName>
        </value>
        <value>
          <fullName>Not SBU-specific</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>PREP</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>Restorative Impression Material</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
        <value>
          <fullName>Imaging - 2D</fullName>
        </value>
        <value>
          <fullName>Imaging - 3D</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>S2S_Product_Line_Interested_In__c</fullName>
    <label>S2S Product Line Interested In</label>
    <type>MultiselectPicklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>1</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Source_opp_ID__c</fullName>
    <description>Contact ID (18 Digit)</description>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity ID (18 Digit)</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>User_Country__c</controllingField>
      <valueSetDefinition>
        <value>
          <fullName>Contacted - F2F meeting</fullName>
        </value>
        <value>
          <fullName>customer invoiced</fullName>
        </value>
        <value>
          <fullName>customer ordered</fullName>
        </value>
        <value>
          <fullName>Deferred</fullName>
        </value>
        <value>
          <fullName>Demo Scheduled - Face to Face meeting</fullName>
        </value>
        <value>
          <fullName>Demo Scheduled - Product Demo</fullName>
        </value>
        <value>
          <fullName>Demo Scheduled - Showroom visit</fullName>
        </value>
        <value>
          <fullName>Distributor Weekly List</fullName>
        </value>
        <value>
          <fullName>Lost to competition</fullName>
        </value>
        <value>
          <fullName>Project delayed</fullName>
        </value>
        <value>
          <fullName>Referred to dealer</fullName>
        </value>
        <value>
          <fullName>Rejected</fullName>
        </value>
        <value>
          <fullName>Technical Detail, Quote shared</fullName>
        </value>
        <value>
          <fullName>Waiting for Feedback from HS</fullName>
        </value>
        <value>
          <fullName>Won the Order</fullName>
        </value>
        <value>
          <fullName>Shared Main</fullName>
        </value>
        <value>
          <fullName>Shared Secondary</fullName>
        </value>
        <value>
          <fullName>Top funnel - Awareness step</fullName>
        </value>
        <value>
          <fullName>Top funnel - Identified lead</fullName>
        </value>
        <value>
          <fullName>Mid-funnel - Interest confirmation</fullName>
        </value>
        <value>
          <fullName>Mid-funnel - Live-demo step</fullName>
        </value>
        <value>
          <fullName>Bottom funnel – Quote proposal</fullName>
        </value>
        <value>
          <fullName>Bottom funnel – Actual sales</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <defaultValue>CASE($User.User_Country__c,  
"Australia","Australia",
"Austria","Austria",
"Belarus","Belarus",
"Belgium","Belgium",
"Brazil","Brazil",
"Canada", "Canada",
"China","China",
"Denmark","Denmark",
"Finland","Finland",
"France","France",
"Germany","Germany",
"Holland","Holland",
"Hong Kong","Hong Kong",
"India","India",
"Indonesia","Indonesia",
"Italy","Italy",
"Japan","Japan",
"Kazakhstan","Kazakhstan",
"Luxembourg","Luxembourg",
"Malaysia","Malaysia",
"New Zealand","New Zealand",
"Norway","Norway",
"Philippines","Philippines",
"Portugal","Portugal",
"Poland","Poland",
"Russia","Russia",
"Saudi Arabia","Saudi Arabia",
"Singapore","Singapore",
"Slovakia","Slovakia",
"South Africa","South Africa",
"South Korea","South Korea",
"Spain","Spain",
"Sweden","Sweden",
"Switzerland","Switzerland",
"Taiwan","Taiwan",
"Thailand","Thailand",
"Turkey","Turkey",
"UAE","UAE",
"UK", "UK",
"Ukraine", "Ukraine",
"USA","USA",
"Vietnam","Vietnam",
"HQ: SE")</defaultValue>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ: SE</fullName>
        </value>
        <value>
          <fullName>Hungary</fullName>
        </value>
        <value>
          <fullName>India</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Ireland</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Jordan</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Kuwait</fullName>
        </value>
        <value>
          <fullName>Latvia</fullName>
        </value>
        <value>
          <fullName>Lithuania</fullName>
        </value>
        <value>
          <fullName>Luxembourg</fullName>
        </value>
        <value>
          <fullName>Malaysia</fullName>
        </value>
        <value>
          <fullName>Malta</fullName>
        </value>
        <value>
          <fullName>New Zealand</fullName>
        </value>
        <value>
          <fullName>Thailand</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Xsbu_Account_address__c</fullName>
    <formula>Account.BillingStreet
            &amp; If(Account.BillingStreet='','',", ")  /*if the field is blank we do not write a coma to separate words*/
            &amp; Account.BillingCity
            &amp; If(Account.BillingCity ='','',", ")  /*if the field is blank we do not write a coma to separate words*/
            &amp; Account.BillingState
            &amp; If(Account.BillingState ='','',", ") /*if the field is blank we do not write a coma to separate words*/
            &amp; Account.BillingPostalCode
            &amp; If(Account.BillingPostalCode ='','',", ")  /*if the field is blank we do not write a coma to separate words*/
            &amp; Account.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account address</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Xsbu_Account_name__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>S2S Account name</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Xsbu_Prospect_Sender__c</fullName>
    <formula>CreatedBy.Full_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prospect Sender</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>xsbu_Dealer_s_Sales_Rep__c</fullName>
    <formula>Dealer_s_Sales_Rep__r.Full_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>s2s Dealer's Sales Rep</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>xsbu_Primary_Contact_name__c</fullName>
    <formula>Primary_Contact__r.Full_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>S2S Primary Contact name</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>xsbu_dealer_name__c</fullName>
    <formula>Dealer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>s2s dealer name</label>
    <type>Text</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET</businessProcess>
    <fullName>GET</fullName>
    <label>X DO NOT USE 2t</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/objects/XSBU_2_orgs__c.object
<CustomObject>
  <customSettingsType>List</customSettingsType>
  <description>This is to automoatize XSBU connection setup for the countries listed in this setting</description>
  <fields>
    <fullName>Named_Credential__c</fullName>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Opportunity_RecordType_Id__c</fullName>
    <label>Opportunity RecordType Id</label>
    <length>25</length>
    <type>Text</type>
  </fields>
  <label>XSBU 2 orgs</label>
</CustomObject>

unpackaged/classes/OpportunitySynch.cls
public class OpportunitySynch  {
    @future(callout=true)
    static public void SynchOpportunityInsert(String oppId) {
        Opportunity opp2;
        String sironaOppId;
        
        // Select opp from db to be able to calculate formula fields.
        opp2 = [SELECT Xsbu_Account_address__c, 
                xsbu_Primary_Contact_name__c,
                Primary_Contact_s_Email_Address__c,
                Primary_Contact_s_Mobile__c,
                Primary_Contact_s_Phone__c,
                Product_Line_Interested_In__c,
                Xsbu_Prospect_Sender__c,
                Xsbu_Account_name__c,
                Source_opp_ID__c,
                User_Country__c,
                xsbu_Dealer_s_Sales_Rep__c,
                xsbu_dealer_name__c,
                Name,
//                CurrencyIsoCode,
                Description,
                Lost_Opportunity_Reason__c,
                Amount,
                StageName,
                Sub_Stage__c,
                CloseDate,
                CreatedBy.User_Country__c
                FROM Opportunity WHERE Id = :oppId];

        system.debug('Opp User Country: ' + opp2.CreatedBy.User_Country__c);
        
        XSBU_2_orgs__c XSBUConfig = XSBU_2_orgs__c.getValues(opp2.CreatedBy.User_Country__c);
        //XSBU_2_orgs__c XSBUConfig = XSBU_2_orgs__c.getValues(opp2.User_Country__c);

        system.debug('XSBUConfig: ' + XSBUConfig);        
        
        //XSBU_2_orgs__c XSBUConfig = XSBU_2_orgs__c.getValues('Thailand');
		String XSBUNamedCredential = XSBUConfig.Named_Credential__c;
        String OpportunityRecordTypeIdTheirOrg = XSBUConfig.Opportunity_RecordType_Id__c;
        
//        String XSBUNamedCredential = 'Salesforce_Org';
//        String OpportunityRecordTypeIdTheirOrg = '012W000000093KLIAY';
        
        System.debug('XSBU Config - Named Credential: ' + XSBUNamedCredential);
        
        OpportunityXsbu synchOpp = new OpportunityXsbu();
        
        synchOpp.Xsbu_Account_address = opp2.Xsbu_Account_address__c;
        synchOpp.Primary_Contact_s_Email_Address = opp2.xsbu_Primary_Contact_name__c;
        synchOpp.Primary_Contact_s_Email_Address = opp2.Primary_Contact_s_Email_Address__c;
        synchOpp.Primary_Contact_s_Mobile = opp2.Primary_Contact_s_Mobile__c;
        synchOpp.Primary_Contact_s_Phone = opp2.Primary_Contact_s_Phone__c;
        synchOpp.Product_Line_Interested_In = opp2.Product_Line_Interested_In__c;
        synchOpp.Xsbu_Prospect_Sender = opp2.Xsbu_Prospect_Sender__c;
       //synchOpp.Q_A = opp2.Q_A__c;
        synchOpp.Xsbu_Customer_name = opp2.Xsbu_Account_name__c;
        //synchOpp.S2S_Product_Line_Interested_In = opp2.Product_Line_Interested_In__c;
        synchOpp.Source_opp_ID = opp2.Source_opp_ID__c;
        synchOpp.User_Country = opp2.User_Country__c;
        //synchOpp.xsbu_Dealer_s_Sales_Rep = opp2.xsbu_Dealer_s_Sales_Rep__c; NOT EXIST
        //synchOpp.xsbu_dealer_name = opp2.xsbu_dealer_name__c; NOT EXIST
        synchOpp.Name = opp2.Name;
//        synchOpp.CurrencyIsoCode = opp2.CurrencyIsoCode;
        synchOpp.Description = opp2.Description;
        synchOpp.Lost_Opportunity_Reason = opp2.Lost_Opportunity_Reason__c;
        synchOpp.Amount = opp2.Amount;
        synchOpp.StageName = opp2.StageName;
        synchOpp.Sub_Stage = opp2.Sub_Stage__c;
        synchOpp.CloseDate = opp2.CloseDate;    
		synchOpp.RecordTypeId = OpportunityRecordTypeIdTheirOrg;        
        
        String serializedOpp = JSON.serialize(synchOpp);
        
        serializedOpp = serializedOpp.replace('Xsbu_Account_address','Xsbu_Customer_Address__c');
/*added*/		serializedOpp = serializedOpp.replace('Primary_Contact_s_Name','xsbu_Primary_Contact_name__c');
        serializedOpp = serializedOpp.replace('Primary_Contact_s_Email_Address','Xsbu_Primary_Contact_s_Email_Address__c');
        serializedOpp = serializedOpp.replace('Primary_Contact_s_Mobile','xsbu_Primary_Contact_s_Mobile__c');
        serializedOpp = serializedOpp.replace('Primary_Contact_s_Phone','xsbu_Primary_Contact_s_Phone__c');
        serializedOpp = serializedOpp.replace('Product_Line_Interested_In','xsbu_Product_Line_Interested_In__c');
        serializedOpp = serializedOpp.replace('Xsbu_Prospect_Sender','Xsbu_Prospect_Sender__c');
       //no need of this serializedOpp = serializedOpp.replace('Q_A','Q_A__c');
        serializedOpp = serializedOpp.replace('Xsbu_Customer_name','Xsbu_Customer_name__c');
       //no need of this serializedOpp = serializedOpp.replace('S2S_Product_Line_Interested_In','S2S_Product_Line_Interested_In__c');
        serializedOpp = serializedOpp.replace('Source_opp_ID','xsbu_Source_opp_ID__c');
        serializedOpp = serializedOpp.replace('User_Country','Country__c');
        //serializedOpp = serializedOpp.replace('xsbu_Dealer_s_Sales_Rep','xsbu_Dealer_s_Sales_Rep__c'); NOT EXIST.
        //serializedOpp = serializedOpp.replace('xsbu_dealer_name','xsbu_dealer_name__c'); NOT EXIST.
        //serializedOpp = serializedOpp.replace('Name','Name');
        //serializedOpp = serializedOpp.replace('CurrencyIsoCode','Currency__c');
        //serializedOpp = serializedOpp.replace('Description','Description');
        serializedOpp = serializedOpp.replace('Lost_Opportunity_Reason','Lost_Opportunity_Reason__c');
        //serializedOpp = serializedOpp.replace('Amount','Amount');
        //serializedOpp = serializedOpp.replace('StageName','StageName');
        serializedOpp = serializedOpp.replace('Sub_Stage','xsbu_Sub_Stage__c');
        //serializedOpp = serializedOpp.replace('CloseDate','CloseDate');            
        
        // Callout with changes to DentsplySirona Org and create Opportunity.
        HttpRequest feedRequest = new HttpRequest();
        
        //feedRequest.setEndpoint('callout:Salesforce_Org/services/data/v32.0/sobjects/Opportunity/');
        feedRequest.setEndpoint('callout:' + XSBUNamedCredential + '/services/data/v32.0/sobjects/Opportunity/');
        
        feedRequest.setHeader('content-type', 'application/json');
        feedRequest.setMethod('POST');
        
        feedRequest.setBody(serializedOpp);
        
        Http http = new Http();
        HTTPResponse feedResponse = http.send(feedRequest);
        System.debug(feedResponse.getBody());
        System.debug(feedResponse.getStatusCode());
        
        if(feedResponse.getStatusCode() > 204) {
            throw new CalloutException(feedResponse.getBody());
        } else {
            //OpportunityResult oppResult = (OpportunityResult) JSON.deserializeUntyped(feedResponse.getBody());
            //sironaOppId = oppResult.id;

            Map<String,Object> responsemap = (Map<String,Object>) JSON.deserializeUntyped(feedResponse.getBody());
            sironaOppId = (String)responsemap.get('id');
        }
        
	    feedRequest.setEndpoint('callout:' + XSBUNamedCredential + '/services/data/v32.0/sobjects/Q_A__c/');

		List<Q_A__c> QAList = [SELECT Name, Question__c, Answer__c, Opportunity_Name__c, Source_Id__c FROM Q_A__c WHERE Opportunity_Name__c = : oppId];

		for(Q_A__c QA : QAList) {
            QAXsbu qaxsbu = new QAXsbu();
            
            qaxsbu.Name = QA.Name;
			qaxsbu.Opportunity_Name = sironaOppId;
			qaxsbu.Question = QA.Question__c;
			qaxsbu.Answer = QA.Answer__c;
			qaxsbu.Source_Id = QA.Source_Id__c;

            String serializedQaxsbu = JSON.serialize(qaxsbu);
        
        	serializedQaxsbu = serializedQaxsbu.replace('Opportunity_Name','Opportunity_Name__c');
        	serializedQaxsbu = serializedQaxsbu.replace('Question','Question__c');
        	serializedQaxsbu = serializedQaxsbu.replace('Answer','Answer__c');
        	serializedQaxsbu = serializedQaxsbu.replace('Source_Id','Source_Id__c');

            feedRequest.setBody(serializedQaxsbu);

			http = new Http();
			feedResponse = http.send(feedRequest);
			System.debug(feedResponse.getBody());
			System.debug(feedResponse.getStatusCode());
        
			if(feedResponse.getStatusCode() > 204) {
				throw new CalloutException(feedResponse.getBody());
			}
		}
    }

    public class OpportunityResult {
        public String id;
        public List<String> errors;
        public Boolean success;
	}    
    
/*    @future(callout=true)
    static public void SynchOpportunityUpdate(String oppId, String serializedOpp) {
		HttpRequest feedRequest = new HttpRequest();

		feedRequest.setEndpoint('callout:Salesforce_Org/services/data/v32.0/sobjects/Opportunity/' + oppId + '?_HttpMethod=PATCH');
           
		feedRequest.setHeader('content-type', 'application/json');
		feedRequest.setMethod('POST');

		feedRequest.setBody(serializedOpp);

	    Http http = new Http();
	    HTTPResponse feedResponse = http.send(feedRequest);
		System.debug(feedResponse.getBody());
	    System.debug(feedResponse.getStatusCode());
        
		if(feedResponse.getStatusCode() > 204) {
			throw new CalloutException(feedResponse.getBody());
		}
	} */

    public class CalloutException extends Exception{}    
}