unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET</businessProcess>
    <fullName>GET</fullName>
    <label>X DO NOT USE 2t</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Account_for_Sample_in_AX__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to track sample in AX</description>
    <label>Payer Account</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>DENTSPLY</value>
      </filterItems>
      <filterItems>
        <field>Account.Sub_Account_Type__c</field>
        <operation>equals</operation>
        <value>Sales Rep</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Internal</value>
      </filterItems>
      <filterItems>
        <field>Account.Sub_Account_Type__c</field>
        <operation>equals</operation>
        <value>Free Goods</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sample Orders</relationshipLabel>
    <relationshipName>Sample_Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>CS_Ownership_Assigned__c</fullName>
    <label>CS Ownership Assigned</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Customer_Service_Rep_Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Service Rep Responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <fullName>Free_Good_Order</fullName>
    <label>Free Good Order</label>
  </recordTypes>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Personal_Order_Account__c</fullName>
    <inlineHelpText>Please add the user's personal SFDC account ID for handling Free of Charge orders</inlineHelpText>
    <label>Personal Order Account</label>
    <length>18</length>
    <type>Text</type>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/Test_OrderPB.cls
/*------------------------------------------------------------
Author: 		Ahmed LOUDRASSI (Salesforce) 2019-10-21
Description:   	Test Class for the Opportunity Process Builder.
History
<Date>      <Authors Name>     <Brief Description of Change>

------------------------------------------------------------*/

@isTest(seeAllData=false)
public class Test_OrderPB {
	/*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<Account> accounts1 = TestDataFactory.returnAccounts(1, 'Geographical_Account', userList.get(0).Id);
        userList.get(0).Personal_Order_Account__c = accounts1.get(0).Id;
        update userList;
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
    }
    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();

        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }
    @isTest
    private static void testSetCurrencyToEURInNordics() {
        
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.returnAccounts(1, 'Geographical_Account', testUser.Id);
        accounts1.get(0).Country__c = 'SE';
        insert accounts1;
        List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts1);
        Test.startTest();
        insert orders;
        Test.stopTest();

        System.assertEquals('EUR', [SELECT Id, CurrencyIsoCode FROM Order LIMIT 1].CurrencyIsoCode);
    }
    @isTest
    private static void testGlobalOrderUpdatePayer() {
        User testUser = [SELECT Id, Personal_Order_Account__c FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.returnAccounts(1, 'Geographical_Account', testUser.Id);
        insert accounts1;
        List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts1);
        orders.get(0).Country__c = 'CA';
        System.runAs(testUser) {
            Test.startTest();
            insert orders;
            Test.stopTest(); 
        }  
        System.assertEquals(testUser.Personal_Order_Account__c, [SELECT Id, Account_for_Sample_in_AX__c FROM Order LIMIT 1].Account_for_Sample_in_AX__c);
    }
    @isTest
    private static void testUpdateCSResponsibleDateTime() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts1 = TestDataFactory.returnAccounts(1, 'Geographical_Account', testUser.Id);
        insert accounts1;
        List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts1);
        orders.get(0).Customer_Service_Rep_Responsible__c = testUser.Id;
        System.runAs(testUser) {
            Test.startTest();
            insert orders;
            Test.stopTest(); 
        }  
        Datetime dt = datetime.now();
        Order order = [SELECT Id, CS_Ownership_Assigned__c FROM Order LIMIT 1];
        System.assertEquals(dt.Hour() + dt.minute(), order.CS_Ownership_Assigned__c.Hour() + order.CS_Ownership_Assigned__c.Minute());
    }
}