unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>1 OR (2 AND 3 AND 5) OR (2 AND 3 AND 4)</booleanFilter>
      <errorMessage>You must select a distributor.</errorMessage>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>ERP Distributor, Non-ERP Distributor, DNA Distributor</value>
      </filterItems>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>CIM Account</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Distributor, DNA Distributor</value>
      </filterItems>
      <filterItems>
        <field>Account.DistributorCategories__c</field>
        <operation>notContain</operation>
        <valueField>$Source.NA_Category__c</valueField>
      </filterItems>
      <filterItems>
        <field>Account.DistributorCategories__c</field>
        <operation>equals</operation>
        <value></value>
      </filterItems>
      <infoMessage>Search for the Delaer connected to this opportunity</infoMessage>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET</businessProcess>
    <fullName>GET</fullName>
    <label>X DO NOT USE 2t</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>$Source.AccountId</field>
        <operation>equals</operation>
        <valueField>Preferred_dealer_item__c.Account__r.Id</valueField>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Preferred_dealer_item__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
      <active>false</active>
      <booleanFilter>(1 OR 2 OR 3)</booleanFilter>
      <filterItems>
        <field>Account.RecordType.Id</field>
        <operation>equals</operation>
        <value>01220000000ckje</value>
      </filterItems>
      <filterItems>
        <field>Account.RecordType.Id</field>
        <operation>equals</operation>
        <value>01220000000ckja</value>
      </filterItems>
      <filterItems>
        <field>Account.Name</field>
        <operation>equals</operation>
        <value>4PL Indonesia email delivery test</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Distributor)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Distributor_email__c</fullName>
    <inlineHelpText>Information coming from the Account's General Info Email</inlineHelpText>
    <label>Distributor email</label>
    <type>Email</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Preferred_dealer_item__c.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Preferred_dealer_items1</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>1 OR (2 AND 3)</booleanFilter>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>ERP Distributor, Non-ERP Distributor, DNA Distributor</value>
      </filterItems>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>CIM Account</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Distributor</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealers (Dealer)</relationshipLabel>
    <relationshipName>Preferred_dealer_items</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Dealer_email__c</fullName>
    <formula>Dealer__r.General_Info_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer email</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Default_dealer__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Default dealer</label>
    <type>Checkbox</type>
  </fields>
  <label>Dealer</label>
  <nameField>
    <displayFormat>PDI{00000}</displayFormat>
    <label>Dealer Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Dealers</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/OrderDealer_CC.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Ahmed loudrassi (Salesforce) 20200304
Description:    OrderDealerCmp Controller Class
Test Class:     Test_OrderDealer_CC
History	
20190924 	Roberto Narbona Update sharing enforcement and update where statement for getDistributor query. (#TFUS1935)
----------------------------------------------------------------------------------------*/
public with sharing class OrderDealer_CC {
    // lookup max search results
    private final static Integer MAX_RESULTS = 5;
    
    /*------------------------------------------------------------  
    Description:    method to insert the dealers related list of the order Account
    Inputs:         @param distributors, @param orderId
    ------------------------------------------------------------*/
    @AuraEnabled
    public static List<Preferred_dealer_item__c> saveDealers(List<String> distributors,Id orderId) {
        try {
            Order currentOrder = [select Id, name, AccountId, Account.Name, Account.Country__c from Order where Id=:orderId];
            List<Preferred_dealer_item__c> cust = [Select Id, Name, Account__r.Id, Dealer__c, Dealer__r.Name, 
                                                Default_dealer__c, Dealer_email__c 
                                                FROM Preferred_dealer_item__c 
                                                WHERE (Account__r.Id=: currentOrder.Account.Id) 
                                                AND Dealer__r.OneAccount_Type__c='Distributor'];
            Map<Id,Preferred_dealer_item__c> pdMap= new Map<Id,Preferred_dealer_item__c>();
            for(Preferred_dealer_item__c pd:cust){
                pdMap.put(pd.Dealer__c, pd);
            }
            List <Preferred_dealer_item__c> prefDealerList = new  List <Preferred_dealer_item__c>();
            for(String distributor : distributors){
                if(!pdMap.containsKey(distributor)){
                    Preferred_dealer_item__c prefDealer= new Preferred_dealer_item__c();
                    prefDealer.Dealer__c = distributor;
                    prefDealer.Account__c = currentOrder.AccountId;
                    prefDealerList.add(prefDealer);
                    If (!cust.isEmpty()){
                        prefDealer.Default_dealer__c = false;
                    } else {
                        prefDealer.Default_dealer__c = true;
                    }
                }
            }
            insert prefDealerList;
            return getDealers(orderId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());    
        }
    }
    /*------------------------------------------------------------  
    Description:    method to get the related dealers list of an order
    Inputs:         @param orderId
    ------------------------------------------------------------*/
    @AuraEnabled
    public static List<Preferred_dealer_item__c> getDealers(ID orderId){
        try {
            Order order = [Select Id, AccountId FROM Order Where Id =:orderId];
            return [Select Id, Name, Account__r.Id, Dealer__c,
                                                Dealer__r.ETM2_State_City__c, 
                                                Dealer__r.OneAccount_Type__c,
                                                Dealer__r.Name,Dealer__r.ShippingCity,
                                                Dealer__r.ShippingState,Dealer__r.ShippingPostalCode,
                                                Default_dealer__c, Dealer_email__c 
                                                FROM Preferred_dealer_item__c
                                                WHERE Account__c = :order.AccountId
                                                ORDER BY Dealer__r.Name];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());    
        }
    }
    /*------------------------------------------------------------  
    Description:    Method to set the order dealer and distributor lookup fields
    Inputs:         @param dealerId, @param orderId
    ------------------------------------------------------------*/
    @AuraEnabled
    public static String updateDealerInfo(Id dealerId,String orderId) {
        try{
            Preferred_dealer_item__c dealer = [SELECT id, name, Dealer__c, Dealer_email__c 
                                           FROM Preferred_dealer_item__c 
                                           WHERE Id=:dealerId];
            Order order = [SELECT Id, OrderNumber, Dealer__c, Distributor__c, Distributor_email__c FROM Order WHERE Id =:orderId];
            order.Dealer__c = dealer.Id;
            order.Distributor__c = dealer.Dealer__c;
            order.Distributor_email__c = dealer.Dealer_email__c;
            update order;
            return order.OrderNumber;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());    
        }
    }

    // Lookup Methods
    @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> search(String searchTerm, List<String> selectedIds) {
        // Prepare query paramters
        searchTerm += '*';

        // Execute search query
        List<List<SObject>> searchResults = [
            FIND :searchTerm
            IN ALL FIELDS
            RETURNING
                Account(
                    Id, Name, OneAccount_Type__c, ETM2_State_City__c 
                    WHERE id NOT IN :selectedIds 
                        AND (
                            RecordTypeId = :GlobalUtils.getRecordTypeId('Account','ERP_Distributor')
                            OR RecordTypeId = :GlobalUtils.getRecordTypeId('Account','Non_ERP_Distributor')
                            OR (RecordTypeId = :GlobalUtils.getRecordTypeId('Account','CIM_Account') AND OneAccount_Type__c = 'Distributor')
                        )
                )
            LIMIT :MAX_RESULTS
        ];

        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        // Extract Accounts & convert them into LookupSearchResult
        String accountIcon = 'standard:account';
        Account[] accounts = (List<Account>) searchResults[0];
        for (Account account : accounts) {
            String stateCitySubString = String.isNotBlank(account.ETM2_State_City__c) ? ' • ' + account.ETM2_State_City__c : '';
            results.add(
                new LookupSearchResult(
                    account.Id,
                    'Account',
                    accountIcon,
                    account.Name,
                    account.OneAccount_Type__c + stateCitySubString
                )
            );
        }

        // Optionnaly sort all results on title
        results.sort();

        return results;
    }

    @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> getRecentlyViewed() {
        List<LookupSearchResult> results = new List<LookupSearchResult>();
        // Get recently viewed records of type Account or Opportunity
        List<Account> recentRecords = [
            SELECT Id, Name, BillingCity
            FROM Account
            WHERE (
                RecordTypeId = :GlobalUtils.getRecordTypeId('Account','ERP_Distributor')
                OR RecordTypeId = :GlobalUtils.getRecordTypeId('Account','Non_ERP_Distributor')
                OR (RecordTypeId = :GlobalUtils.getRecordTypeId('Account','CIM_Account') AND OneAccount_Type__c = 'Distributor')
            )
            ORDER BY LastViewedDate DESC
            LIMIT 5
        ];
        // Convert recent records into LookupSearchResult
        for (Account recentRecord : recentRecords) {
            results.add(
                new LookupSearchResult(
                    recentRecord.Id,
                    'Account',
                    'standard:account',
                    recentRecord.Name,
                    'Account • ' + recentRecord.BillingCity
                )
            );
        }
        return results;
    }
}