unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Field_Sales_Project_Members__c.object
<CustomObject>
  <description>Used to track targets for sales for specified initiatives based on target lists, regional initiatives, or customer interactions.</description>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Field_Sales_Project_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>Category__c</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>3D Upgrade</fullName>
        </value>
        <value>
          <fullName>ACB with ASA</fullName>
        </value>
        <value>
          <fullName>AH Plus</fullName>
        </value>
        <value>
          <fullName>AH Temp</fullName>
        </value>
        <value>
          <fullName>AlginX</fullName>
        </value>
        <value>
          <fullName>All Ceramics</fullName>
        </value>
        <value>
          <fullName>All Other Endo</fullName>
        </value>
        <value>
          <fullName>All Other - Niti Rotary Files</fullName>
        </value>
        <value>
          <fullName>All Other – Obturation</fullName>
        </value>
        <value>
          <fullName>Anaestadent</fullName>
        </value>
        <value>
          <fullName>Ancillary</fullName>
        </value>
        <value>
          <fullName>ANKYLOS</fullName>
        </value>
        <value>
          <fullName>Apex Locator</fullName>
        </value>
        <value>
          <fullName>Aquasil</fullName>
        </value>
        <value>
          <fullName>Aquasil Ultra Plus</fullName>
        </value>
        <value>
          <fullName>ATIS</fullName>
        </value>
        <value>
          <fullName>ATIS EV</fullName>
        </value>
        <value>
          <fullName>ATIS TX</fullName>
        </value>
        <value>
          <fullName>Atlantis</fullName>
        </value>
        <value>
          <fullName>Atlantis Abutments</fullName>
        </value>
        <value>
          <fullName>Atlantis Suprastructures</fullName>
        </value>
        <value>
          <fullName>Automate</fullName>
        </value>
        <value>
          <fullName>Axeos</fullName>
        </value>
        <value>
          <fullName>Azento Astra Tech</fullName>
        </value>
        <value>
          <fullName>Azento EV</fullName>
        </value>
        <value>
          <fullName>Azento XiVE</fullName>
        </value>
        <value>
          <fullName>Bioceramic</fullName>
        </value>
        <value>
          <fullName>Bluecam</fullName>
        </value>
        <value>
          <fullName>Bonding</fullName>
        </value>
        <value>
          <fullName>Bone</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>UserCountry__c</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>3D Imaging</fullName>
          <isActive>false</isActive>
          <label>3D Imaging</label>
        </value>
        <value>
          <fullName>ATLANTIS</fullName>
          <isActive>false</isActive>
          <label>ATLANTIS</label>
        </value>
        <value>
          <fullName>CEREC Equipment</fullName>
          <isActive>false</isActive>
          <label>CEREC Equipment</label>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Consumables</fullName>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Digital Solutions</fullName>
          <isActive>false</isActive>
          <label>Digital Solutions</label>
        </value>
        <value>
          <fullName>Endentulous</fullName>
          <isActive>false</isActive>
          <label>Endentulous</label>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Extra Oral Imaging</fullName>
          <isActive>false</isActive>
          <label>Extra Oral Imaging</label>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>InLab</fullName>
          <isActive>false</isActive>
          <label>InLab</label>
        </value>
        <value>
          <fullName>Intra Oral Imaging</fullName>
          <isActive>false</isActive>
          <label>Intra Oral Imaging</label>
        </value>
        <value>
          <fullName>Midwest Equipment</fullName>
          <isActive>false</isActive>
          <label>Midwest Equipment</label>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
          <isActive>false</isActive>
          <label>Preventive</label>
        </value>
        <value>
          <fullName>Procedures</fullName>
          <isActive>false</isActive>
          <label>Procedures</label>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Regenerative</fullName>
          <isActive>false</isActive>
          <label>Regenerative</label>
        </value>
        <value>
          <fullName>Restorative</fullName>
          <isActive>false</isActive>
          <label>Restorative</label>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
          <isActive>false</isActive>
          <label>Treatment Centers</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>1 OR (2 AND 3 AND 5) OR (2 AND 3 AND 4)</booleanFilter>
      <errorMessage>You must select a distributor.</errorMessage>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>ERP Distributor, Non-ERP Distributor, DNA Distributor</value>
      </filterItems>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>CIM Account</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Distributor, DNA Distributor</value>
      </filterItems>
      <filterItems>
        <field>Account.DistributorCategories__c</field>
        <operation>notContain</operation>
        <valueField>$Source.Category__c</valueField>
      </filterItems>
      <filterItems>
        <field>Account.DistributorCategories__c</field>
        <operation>equals</operation>
        <value></value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Leads (Distributor)</relationshipLabel>
    <relationshipName>Prospects</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>SuggestedOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TFUS-000002725</description>
    <label>Suggested Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Leads</relationshipName>
    <type>Lookup</type>
  </fields>
  <label>Sales Lead</label>
  <nameField>
    <displayFormat>Ld-{0000000}</displayFormat>
    <label>LD ID</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Sales Leads</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/LeadOpportunitySetting__mdt.object
<CustomObject>
  <fields>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Consumables</fullName>
          <default>true</default>
          <label>Consumables</label>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>AD</fullName>
          <default>true</default>
          <label>AD</label>
        </value>
        <value>
          <fullName>AE</fullName>
        </value>
        <value>
          <fullName>AF</fullName>
        </value>
        <value>
          <fullName>AG</fullName>
        </value>
        <value>
          <fullName>AI</fullName>
        </value>
        <value>
          <fullName>AL</fullName>
        </value>
        <value>
          <fullName>AM</fullName>
        </value>
        <value>
          <fullName>AN</fullName>
        </value>
        <value>
          <fullName>AO</fullName>
        </value>
        <value>
          <fullName>AQ</fullName>
        </value>
        <value>
          <fullName>AR</fullName>
        </value>
        <value>
          <fullName>AS</fullName>
        </value>
        <value>
          <fullName>AT</fullName>
        </value>
        <value>
          <fullName>AU</fullName>
        </value>
        <value>
          <fullName>AW</fullName>
        </value>
        <value>
          <fullName>AX</fullName>
        </value>
        <value>
          <fullName>AZ</fullName>
        </value>
        <value>
          <fullName>BA</fullName>
        </value>
        <value>
          <fullName>BB</fullName>
        </value>
        <value>
          <fullName>BD</fullName>
        </value>
        <value>
          <fullName>BE</fullName>
        </value>
        <value>
          <fullName>BF</fullName>
        </value>
        <value>
          <fullName>BG</fullName>
        </value>
        <value>
          <fullName>BH</fullName>
        </value>
        <value>
          <fullName>BI</fullName>
        </value>
        <value>
          <fullName>BJ</fullName>
        </value>
        <value>
          <fullName>BL</fullName>
        </value>
        <value>
          <fullName>BM</fullName>
        </value>
        <value>
          <fullName>BN</fullName>
        </value>
        <value>
          <fullName>BO</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Lead &amp; Opportunity Setting</label>
  <pluralLabel>Lead &amp; Opportunity Settings</pluralLabel>
</CustomObject>

unpackaged/classes/BatchSalesLeadAssignSuggestedOwner.cls
/**
 * @description       : This batch class updates the Suggested Owner on Sales Leads based on LeadOpportunitySetting__mdt
 * @author            : kdoruibin@salesforce.com
 * @group             : 
 * @last modified on  : 06-15-2021
 * @last modified by  : kdoruibin@salesforce.com
 * Modifications Log 
 * Ver   Date         Author                     Modification
 * 1.0   06-15-2021   kdoruibin@salesforce.com   Initial Version
**/
global without sharing class BatchSalesLeadAssignSuggestedOwner implements Database.Batchable<sObject>, Database.Stateful {
    private String country;
    private String category;

    global BatchSalesLeadAssignSuggestedOwner() {
        this.country = null;
        this.category = null;
    }

    global BatchSalesLeadAssignSuggestedOwner(String country) {
        this.country = country;
        this.category = null;
    }

    global BatchSalesLeadAssignSuggestedOwner(String country, String category) {
        this.country = country;
        this.category = category;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String queryTemplate;
        List<Object> queryParameters = new List<Object>{
            String.isBlank(country) ? '' : ' AND Account__r.Country__c = \'' + country + '\''
            , String.isBlank(category) ? '' : 'AND Category__c = \'' + category + '\''
        };
        
        queryTemplate = 'SELECT Id, Account__c, Dealer__c, Account__r.Country__c, Dealer__r.Country__c, Category__c, Brand__c, SuggestedOwner__c FROM Field_Sales_Project_Members__c WHERE Status__c != \'Completed\' AND Status__c != \'Cancelled\' AND Status__c != \'Expired\' {0} {1}';

        return Database.getQueryLocator(String.format(queryTemplate, queryParameters));
    }

    global void execute(Database.BatchableContext bc, List<Field_Sales_Project_Members__c> scope) {
        
        try {
            Set<Id> accountIdSet = new Set<Id>();
    
            for (Field_Sales_Project_Members__c salesLead : scope) {
                // Sets used to query the right AccountUserTerritory2View records
                accountIdSet.add(salesLead.Account__c);
                accountIdSet.add(salesLead.Dealer__c);
            }
            
            Map<String, List<LeadOpportunitySetting__mdt>> leadOpptySettingMap = AssignSuggestedOwnerHelper.getLeadOpportunitySettings();
            Map<Id,List<Id>> accountTerritoryMap = AssignSuggestedOwnerHelper.getAccountTerritoryMap(accountIdSet);
            Set<Id> flattenedTerritoryIdSet = AssignSuggestedOwnerHelper.getFlattenedTerritoryIdSet(accountTerritoryMap);
            Map<Id, Map<String, UserTerritory2Association>> territoryIdUserAssociationMap = AssignSuggestedOwnerHelper.getTerritoryIdUserAssociationMap(flattenedTerritoryIdSet);

            List<Field_Sales_Project_Members__c> salesLeadToUpdateList = new List<Field_Sales_Project_Members__c>();

            // Loop through all Sales Leads
            for (Field_Sales_Project_Members__c salesLeadToUpdate : scope) {
                List<LeadOpportunitySetting__mdt> settingList = leadOpptySettingMap.get(salesLeadToUpdate.Account__r.Country__c + salesLeadToUpdate.Category__c);
                Id previousSuggestedUserId = salesLeadToUpdate.SuggestedOwner__c;
                Id suggestedUserId = null;

                if (settingList != null) {
                    // Sometimes there are multiple settings per CountryCategory (e.g. US: Prosthetics ATL and US: MIS Implants)
                    for (LeadOpportunitySetting__mdt setting : settingList) {
                        if (suggestedUserId != null) break;
                        // Sometimes multiple User Roles are defined
                        List<String> userRoleList = setting?.UserRoles__c.split(';');
                        // Only assign SuggestedOwner if the setting matches the Brand of the Sales Lead
                        if (salesLeadToUpdate.Brand__c != null && setting.Brands__c.contains(salesLeadToUpdate.Brand__c)) {
                            // Find the correct account depending on if the setting suggests that the owner should come from the Account or Dealer
                            Id accountId = setting.AssignOwnerFrom__c == 'Dealer' ? salesLeadToUpdate.Dealer__c : salesLeadToUpdate.Account__c;
                            if (accountId != null && accountTerritoryMap.containsKey(accountId)) {
                                // Loop through all territories associated with the Account of the Sales Lead
                                for (Id territoryId : accountTerritoryMap.get(accountId)) {
                                    if (suggestedUserId != null) break;
                                    for (String userRole : userRoleList) {
                                        if (suggestedUserId != null) break;
                                        suggestedUserId = territoryIdUserAssociationMap.get(territoryId)?.get(userRole.trim())?.UserId;
                                    }
                                }
                            }
                        }
                    }
                }

                // If suggested owner is different from the previous value, then assign the new suggested owner
                if (previousSuggestedUserId != suggestedUserId) {
                    salesLeadToUpdate.SuggestedOwner__c = suggestedUserId;
                    salesLeadToUpdateList.add(salesLeadToUpdate);
                }
                
            }
            update salesLeadToUpdateList;
        } catch (Exception e) {
            DebugLog.addException(e, 'Error occured on: BatchAssignSuggestedOwner');
        }

    }

    global void finish(Database.BatchableContext bc) {
        DebugLog.addInfo('Batch successfully finished: BatchAssignSuggestedOwner', bc.getJobId());
    }
}