unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>$Source.AccountId</field>
        <operation>equals</operation>
        <valueField>Preferred_dealer_item__c.Account__r.Id</valueField>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Preferred_dealer_item__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Preferred_dealer_item__c.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Preferred_dealer_items1</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>1 OR (2 AND 3)</booleanFilter>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>ERP Distributor, Non-ERP Distributor, DNA Distributor</value>
      </filterItems>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>CIM Account</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Distributor</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealers (Dealer)</relationshipLabel>
    <relationshipName>Preferred_dealer_items</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Default_dealer__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Default dealer</label>
    <type>Checkbox</type>
  </fields>
  <label>Dealer</label>
  <nameField>
    <displayFormat>PDI{00000}</displayFormat>
    <label>Dealer Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Dealers</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/getPreferredDealers.cls
public with sharing class getPreferredDealers {

public getPreferredDealers(ApexPages.StandardSetController stdController) {
}

public List<Preferred_dealer_item__c> cust {get;set;}
public List<Account> dealers {get;set;}
public Preferred_dealer_item__c prfd {get; set;}
public List<Preferred_dealer_item__c> prfdList {get; set;}
public Account acc {get; set;}
public List<cDealer> pdeList {get; set;}
public List<cAccount> dealerList {get; set;}
public cDealer dealTest {get; set;}
public cAccount dealTest2 {get; set;}
Public String getRadioValue{get;set;}

public void fetchRecords(){
//prfd = [Select Id, Name, Account__c FROM Preferred_dealer_item__c WHERE Id =: ApexPages.currentPage().getParameters().get('id')];
acc = [Select Id, Name, Country__c FROM Account WHERE Id =: ApexPages.currentPage().getParameters().get('id')];
cust = [Select Id, Name, Account__r.Id, Dealer__c, Dealer__r.Name, Default_dealer__c FROM Preferred_dealer_item__c WHERE Account__r.Id=: acc.Id ORDER BY Dealer__r.Name ASC];

dealers = [Select Id, Name FROM Account WHERE (((RecordTypeId=:'01220000000ckje') OR (RecordTypeId=:'01220000000ckja') OR (RecordTypeId=:'0120J000000cmd3')) AND (Country__c =: acc.Country__c)) ORDER BY Name ASC];
this.createPdeList();
this.createDealerList();

if (cust.size() > 0) {
prfdList = [Select Id FROM Preferred_dealer_item__c WHERE (Default_dealer__c =: true AND Account__c =: acc.id)];

if (prfdList.size() > 0) {
prfd = prfdList[0];
getRadioValue = prfdList[0].Id;
}
}

}

public void createPdeList() {
    
    pdeList = new List<cDealer> ();
        
    for(Preferred_dealer_item__c pdTest: cust) {
        dealTest = new cDealer(pdTest);
        If (dealTest.pde!=null) {
        pdeList.add(dealTest);
        }
    }
    
    }
        
public void createDealerList() {
    
dealerList = new List<cAccount>();
Boolean checkDealer = false;
Integer ind = 0;        
    
    for(Account pdTest: dealers) {
        dealTest2 = new cAccount(pdTest);
        If (dealTest2.pde!=null) {
        dealerList.add(dealTest2);
        
        for (Preferred_dealer_item__c pdTest2 : cust) {
        If (pdTest2.Dealer__r.Id == pdTest.Id){
        dealerList.remove(ind);
        ind = ind-1;
        }
        }
        
        ind=ind+1;
        
        }        
    }
    }
    

public void addDealer() {

for(cAccount dealerSelect: dealerList) {

if (dealerSelect.selected_pd == true) {
Preferred_dealer_item__c newDealer = new Preferred_dealer_item__c();
newDealer.Account__c = acc.Id;
newDealer.Dealer__c = dealerSelect.pde.Id;
If (cust.size()>0){
newDealer.Default_dealer__c = false;
} else {
newDealer.Default_dealer__c = true;
}
insert newDealer;
this.fetchRecords();
}

}

}

public Integer DealerNo {get; set;}

public void saveDealer() {
DealerNo = 0;

for(cDealer dealerSelect: pdeList) {

If (dealerSelect.pde.id == getRadioValue){
dealerSelect.pde.Default_dealer__c = true;
update dealerSelect.pde;
//DealerNo = DealerNo +1;
}
else{
dealerSelect.pde.Default_dealer__c = false;
update dealerSelect.pde;
}
}

/*If (DealerNo < 2) {
for(cDealer dealerSelect: pdeList) {
update dealerSelect.pde;
}
}*/

}

public List<SelectOption> getDealerOptions() {

List<SelectOption> options = new List<SelectOption>();

for (cDealer dealerSelect : pdeList) {
options.add(new SelectOption(dealerSelect.pde.id, dealerSelect.pde.Dealer__r.Name));
}

return options;

}


Public class cDealer {
    public Preferred_dealer_item__c pde {get; set;}
    public Boolean selected_pd {get; set;}
    public String pde_link {get; set;}
    
        public cDealer(Preferred_dealer_item__c pd) {
        pde = pd;
        selected_pd = false;
        pde_link= '<a href="' + pde.id + '">'+pde.Name+'</a>';
    }
    }
    
  Public class cAccount {
    public Account pde {get; set;}
    public Boolean selected_pd {get; set;}
    
        public cAccount(Account pd) {
        pde = pd;
        selected_pd = false;
    }
    }


}