unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Field_Sales_Project__c.object
<CustomObject>
  <description>Used by Sales Teams to collect Accounts into different Initiatives.
		These are all managed and created by the Field Sales Teams.</description>
  <fields>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>UserCountry__c</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>3D Imaging</fullName>
          <isActive>false</isActive>
          <label>3D Imaging</label>
        </value>
        <value>
          <fullName>ATLANTIS</fullName>
          <isActive>false</isActive>
          <label>ATLANTIS</label>
        </value>
        <value>
          <fullName>CEREC Equipment</fullName>
          <isActive>false</isActive>
          <label>CEREC Equipment</label>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Consumables</fullName>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Digital Solutions</fullName>
          <isActive>false</isActive>
          <label>Digital Solutions</label>
        </value>
        <value>
          <fullName>Endentulous</fullName>
          <isActive>false</isActive>
          <label>Endentulous</label>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Extra Oral Imaging</fullName>
          <isActive>false</isActive>
          <label>Extra Oral Imaging</label>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>InLab</fullName>
          <isActive>false</isActive>
          <label>InLab</label>
        </value>
        <value>
          <fullName>Intra Oral Imaging</fullName>
          <isActive>false</isActive>
          <label>Intra Oral Imaging</label>
        </value>
        <value>
          <fullName>Midwest Equipment</fullName>
          <isActive>false</isActive>
          <label>Midwest Equipment</label>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
          <isActive>false</isActive>
          <label>Preventive</label>
        </value>
        <value>
          <fullName>Procedures</fullName>
          <isActive>false</isActive>
          <label>Procedures</label>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Regenerative</fullName>
          <isActive>false</isActive>
          <label>Regenerative</label>
        </value>
        <value>
          <fullName>Restorative</fullName>
          <isActive>false</isActive>
          <label>Restorative</label>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
          <isActive>false</isActive>
          <label>Treatment Centers</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Description__c</fullName>
    <inlineHelpText>Description of this Initiative</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
  </fields>
  <fields>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Initiative_Type__c</fullName>
    <label>List Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Marketing Initiative</fullName>
        </value>
        <value>
          <fullName>Regional Initiative</fullName>
        </value>
        <value>
          <fullName>Sales Team Initiative</fullName>
        </value>
        <value>
          <fullName>Inside Sales Target List</fullName>
        </value>
        <value>
          <fullName>Area Initiative</fullName>
          <isActive>false</isActive>
          <label>Area Initiative</label>
        </value>
        <value>
          <fullName>RCO Initiative</fullName>
          <isActive>false</isActive>
          <label>RCO Initiative</label>
        </value>
        <value>
          <fullName>Static/Ops Maintained List</fullName>
          <isActive>false</isActive>
          <label>Static/Ops Maintained List</label>
        </value>
        <value>
          <fullName>Territory Initiative</fullName>
          <isActive>false</isActive>
          <label>Territory Initiative</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Title__c</fullName>
    <inlineHelpText>This helps the naming of the Initiative</inlineHelpText>
    <label>Title</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
  </fields>
  <label>Target List</label>
  <nameField>
    <label>Target List Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Target Lists</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Field_Sales_Project_Members__c.object
<CustomObject>
  <description>Used to track targets for sales for specified initiatives based on target lists, regional initiatives, or customer interactions.</description>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Field_Sales_Project_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>UserCountry__c</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>3D Imaging</fullName>
          <isActive>false</isActive>
          <label>3D Imaging</label>
        </value>
        <value>
          <fullName>ATLANTIS</fullName>
          <isActive>false</isActive>
          <label>ATLANTIS</label>
        </value>
        <value>
          <fullName>CEREC Equipment</fullName>
          <isActive>false</isActive>
          <label>CEREC Equipment</label>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Consumables</fullName>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Digital Solutions</fullName>
          <isActive>false</isActive>
          <label>Digital Solutions</label>
        </value>
        <value>
          <fullName>Endentulous</fullName>
          <isActive>false</isActive>
          <label>Endentulous</label>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Extra Oral Imaging</fullName>
          <isActive>false</isActive>
          <label>Extra Oral Imaging</label>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>InLab</fullName>
          <isActive>false</isActive>
          <label>InLab</label>
        </value>
        <value>
          <fullName>Intra Oral Imaging</fullName>
          <isActive>false</isActive>
          <label>Intra Oral Imaging</label>
        </value>
        <value>
          <fullName>Midwest Equipment</fullName>
          <isActive>false</isActive>
          <label>Midwest Equipment</label>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
          <isActive>false</isActive>
          <label>Preventive</label>
        </value>
        <value>
          <fullName>Procedures</fullName>
          <isActive>false</isActive>
          <label>Procedures</label>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Regenerative</fullName>
          <isActive>false</isActive>
          <label>Regenerative</label>
        </value>
        <value>
          <fullName>Restorative</fullName>
          <isActive>false</isActive>
          <label>Restorative</label>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
          <isActive>false</isActive>
          <label>Treatment Centers</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Field_Sales_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Target List</label>
    <referenceTo>Field_Sales_Project__c</referenceTo>
    <relationshipName>Field_Sales_Project_Members</relationshipName>
    <type>Lookup</type>
  </fields>
  <label>Sales Lead</label>
  <nameField>
    <displayFormat>Ld-{0000000}</displayFormat>
    <label>LD ID</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Sales Leads</pluralLabel>
  <recordTypes>
    <active>true</active>
    <fullName>Outside_Sales_Lead</fullName>
    <label>Outside Sales Lead</label>
  </recordTypes>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
  <fields>
    <fullName>NA_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>User_Country__c</controllingField>
      <valueSetDefinition>
        <value>
          <fullName>3D Imaging</fullName>
        </value>
        <value>
          <fullName>ATLANTIS</fullName>
        </value>
        <value>
          <fullName>CEREC Equipment</fullName>
        </value>
        <value>
          <fullName>Consumables</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Solutions</fullName>
        </value>
        <value>
          <fullName>Endentulous</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Extra Oral Imaging</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>InLab</fullName>
        </value>
        <value>
          <fullName>Intra Oral Imaging</fullName>
        </value>
        <value>
          <fullName>Midwest Equipment</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Regenerative</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Start_Date__c</fullName>
    <description>COS field used for North America Dental.</description>
    <inlineHelpText>Date when a series of Activities will Start.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <businessProcess>Lightning Sales</businessProcess>
    <description>Lightning Pipeline Opportunity</description>
    <fullName>Lightning_Pipeline_Opportunity</fullName>
    <label>Lightning Pipeline Opportunity</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/Test_OpportunityStageGuidance.cls
/*------------------------------------------------------------  
Author:         Richard Trum (Glimt) 2019-11-05     
Description:    Test class for testing the apex class OpportunityStageGuidanceClass
------------------------------------------------------------*/

@IsTest
private class Test_OpportunityStageGuidance {

    @IsTest
    private static void opportunityTest(){
        Account account1 = DC_UT_DataUtils.generateAccount('Account1');
        account1.Country__c = 'IE';
        insert account1;
        
        RecordType recType = [SELECT Id From RecordType WHERE DeveloperName ='Lightning_Pipeline_Opportunity' AND sObjectType = 'Opportunity'];
        
        Opportunity oppty1 = new Opportunity();
        oppty1.AccountId = account1.Id;
        oppty1.Name = 'x';
        oppty1.NA_Category__c = 'Implants';
        oppty1.CloseDate = date.today();
        oppty1.StageName = '0. Prospect';
        oppty1.RecordTypeId = recType.Id;
        insert oppty1;
        
        Test.startTest();
        OpportunityStageGuidanceClass.StageWrapper wrapper = new OpportunityStageGuidanceClass.StageWrapper();
        wrapper = OpportunityStageGuidanceClass.getOppStageGuidance(oppty1.Id, 'Opportunity', 'StageName', 'Account.Country__c', 'NA_Category__c', 'Lightning_Pipeline_Opportunity');
        System.assertEquals(wrapper.currentStage, oppty1.StageName);
        System.assertEquals(wrapper.objectType, 'Opportunity');
        
        try{
        wrapper = OpportunityStageGuidanceClass.getOppStageGuidance(oppty1.Id, 'Oppty', 'StageName', 'Account.Country__c', 'NA_Category__c', 'Lightning_Pipeline_Opportunity');
        } catch(Exception e){
            System.debug(e);
        }
        
        Test.stopTest();
        
    }
    
    @IsTest
    private static void prospectTest(){
        Account account1 = DC_UT_DataUtils.generateAccount('Account1');
        account1.Country__c = 'IE';
        insert account1;
        
        Field_Sales_Project__c initiative = new Field_Sales_Project__c();
        initiative.Title__c = 'Test';
        initiative.Name = 'Test';
        initiative.Start_Date__c = date.today();
        initiative.End_Date__c = date.today();
        initiative.Description__c = 'Testing';
        initiative.Initiative_Type__c = 'Sales Team Initiative';
        insert initiative;
        
        Field_Sales_Project_Members__c prospect1 = new Field_Sales_Project_Members__c();
        prospect1.Account__c = account1.Id;
        prospect1.Category__c = 'Implants';
        prospect1.Status__c = 'New';
        prospect1.Field_Sales_Project__c = initiative.Id;
        insert prospect1;

        Test.startTest();
        OpportunityStageGuidanceClass.StageWrapper wrapper = new OpportunityStageGuidanceClass.StageWrapper();
        wrapper = OpportunityStageGuidanceClass.getOppStageGuidance(prospect1.Id, 'Field_Sales_Project_Members__c', 'Status__c', 'Account__r.Country__c', 'Category__c', 'Outside_Sales_Lead');
        System.assertEquals(wrapper.currentStage, prospect1.Status__c);
        System.assertEquals(wrapper.objectType, 'Field_Sales_Project_Members__c');
        Test.StopTest();
    }

    @IsTest
    private static void testUpdateStage(){
        Account account1 = DC_UT_DataUtils.generateAccount('Account1');
        account1.Country__c = 'IE';
        insert account1;
        
        RecordType recType = [SELECT Id From RecordType WHERE DeveloperName ='Lightning_Pipeline_Opportunity' AND sObjectType = 'Opportunity'];
        
        Opportunity oppty1 = new Opportunity();
        oppty1.AccountId = account1.Id;
        oppty1.Name = 'x';
        oppty1.NA_Category__c = 'Implants';
        oppty1.CloseDate = date.today();
        oppty1.StageName = '0. Prospect';
        oppty1.RecordTypeId = recType.Id;
        insert oppty1;
        
        Test.startTest();
        OpportunityStageGuidanceClass.updateStage2(oppty1.Id, '2. Positioning products', 'StageName');
        Test.stopTest();
        
        System.assertEquals('2. Positioning products', [SELECT StageName FROM Opportunity WHERE Id = :oppty1.Id LIMIT 1]?.StageName);
    }
    
    @IsTest
    private static void testCheckStageType(){
        OpportunityStage testStage = [
            SELECT Id, MasterLabel, IsClosed, IsWon, IsActive 
            FROM OpportunityStage
            LIMIT 1
        ];

        System.assertEquals(testStage?.IsClosed, OpportunityStageGuidanceClass.checkStageType(testStage.MasterLabel)?.IsClosed);
    }
    
}