unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Postal_Codes__c.object
<CustomObject>
  <description>Postal Code Reference for Postal Codes associated with Territories</description>
  <fields>
    <fullName>Country_Picklist__c</fullName>
    <label>Country_Picklist</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>AD</fullName>
        </value>
        <value>
          <fullName>AE</fullName>
        </value>
        <value>
          <fullName>AF</fullName>
        </value>
        <value>
          <fullName>AG</fullName>
        </value>
        <value>
          <fullName>AI</fullName>
        </value>
        <value>
          <fullName>AL</fullName>
        </value>
        <value>
          <fullName>AM</fullName>
        </value>
        <value>
          <fullName>AN</fullName>
        </value>
        <value>
          <fullName>AO</fullName>
        </value>
        <value>
          <fullName>AQ</fullName>
        </value>
        <value>
          <fullName>AR</fullName>
        </value>
        <value>
          <fullName>AS</fullName>
        </value>
        <value>
          <fullName>AT</fullName>
        </value>
        <value>
          <fullName>AU</fullName>
        </value>
        <value>
          <fullName>AW</fullName>
        </value>
        <value>
          <fullName>AX</fullName>
        </value>
        <value>
          <fullName>AZ</fullName>
        </value>
        <value>
          <fullName>BA</fullName>
        </value>
        <value>
          <fullName>BB</fullName>
        </value>
        <value>
          <fullName>BD</fullName>
        </value>
        <value>
          <fullName>BE</fullName>
        </value>
        <value>
          <fullName>BF</fullName>
        </value>
        <value>
          <fullName>BG</fullName>
        </value>
        <value>
          <fullName>BH</fullName>
        </value>
        <value>
          <fullName>BI</fullName>
        </value>
        <value>
          <fullName>BJ</fullName>
        </value>
        <value>
          <fullName>BL</fullName>
        </value>
        <value>
          <fullName>BM</fullName>
        </value>
        <value>
          <fullName>BN</fullName>
        </value>
        <value>
          <fullName>BO</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>DC_ETM_Code__c</fullName>
    <label>ETM Code</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <label>Postal Code</label>
  <nameField>
    <label>Postal Code</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Postal Codes</pluralLabel>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/DC_AccountUpdateBatch.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Denis Zhdanov (dzhdanov@mycervello.com) (Salesforce) 20170818
Description:    DC Account Update Batch This is updating the postal code information in the accounts
History
20170627   Sergey Legostaev (slegostaev@mycervello.com)
20191117   Roberto Narbona -> added country dependency logic
----------------------------------------------------------------------------------------*/

global class DC_AccountUpdateBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    private List<Id> postalCodeIds;
    global  Map<String, Postal_Codes__c> codeMap;
    
    public DC_AccountUpdateBatch(List<Id> postalCodeIds) {    
        this.postalCodeIds = postalCodeIds;
        this.codeMap = new Map<String, Postal_Codes__c>();
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        List<Postal_Codes__c> codes = [Select Id, Name, DC_ETM_Code__c,Country_Picklist__c FROM Postal_Codes__c WHERE Id IN :postalCodeIds];
        Set<String> zipCodes = new Set<String>();
        Set<String> countries = new Set<String>();  
        for(Postal_Codes__c postalCode : codes) {
            codeMap.put(postalCode.Name+postalCode.Country_Picklist__c, postalCode);
            zipCodes.add(postalCode.Name);
            countries.add(postalCode.Country_Picklist__c);
            
        }
        return Database.getQueryLocator('Select Id, DC_ETM_Code__c, Country__c, Postal_Code_Info__c, Postal_Code_Info__r.DC_ETM_Code__c, ETM2_Zip_Code__c FROM Account WHERE ETM2_Zip_Code__c IN :zipCodes and country__c IN :countries');
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope) {
        List<Account> accountsToUpdate = new List<Account>();
        for(Account tempAccount: scope) {
            if((tempAccount.Postal_Code_Info__c == null || tempAccount.Postal_Code_Info__r.DC_ETM_Code__c != tempAccount.DC_ETM_Code__c) && codeMap.get(tempAccount.ETM2_Zip_Code__c.toUpperCase()+tempAccount.Country__c) != null) {
                Postal_Codes__c postalCode = codeMap.get(tempAccount.ETM2_Zip_Code__c.toUpperCase()+tempAccount.Country__c);
                tempAccount.Postal_Code_Info__c = postalCode.Id;
                tempAccount.DC_ETM_Code__c = postalCode.DC_ETM_Code__c;
                accountsToUpdate.add(tempAccount);
            } 
        }  
        try {
            if (accountsToUpdate.isEmpty() == false) {
                update accountsToUpdate;
            }
        } catch (DmlException e) {
            DebugLog.addError(e.getMessage());
        }
    }
    
    global void finish(Database.BatchableContext BC) { 
        DebugLog.addinfo('This is the DC_AccountUpdateBatch JobId:',BC.getJobId());
    }
}