unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <defaultValue>CASE($User.User_Country__c,  
"Australia","Australia",
"Austria","Austria",
"Belarus","Belarus",
"Belgium","Belgium",
"Brazil","Brazil",
"Canada", "Canada",
"China","China",
"Denmark","Denmark",
"Finland","Finland",
"France","France",
"Germany","Germany",
"Holland","Holland",
"Hong Kong","Hong Kong",
"India","India",
"Indonesia","Indonesia",
"Italy","Italy",
"Japan","Japan",
"Kazakhstan","Kazakhstan",
"Luxembourg","Luxembourg",
"Malaysia","Malaysia",
"New Zealand","New Zealand",
"Norway","Norway",
"Philippines","Philippines",
"Portugal","Portugal",
"Poland","Poland",
"Russia","Russia",
"Saudi Arabia","Saudi Arabia",
"Singapore","Singapore",
"Slovakia","Slovakia",
"South Africa","South Africa",
"South Korea","South Korea",
"Spain","Spain",
"Sweden","Sweden",
"Switzerland","Switzerland",
"Taiwan","Taiwan",
"Thailand","Thailand",
"Turkey","Turkey",
"UAE","UAE",
"UK", "UK",
"Ukraine", "Ukraine",
"USA","USA",
"Vietnam","Vietnam",
"HQ: SE")</defaultValue>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ: SE</fullName>
        </value>
        <value>
          <fullName>Hungary</fullName>
        </value>
        <value>
          <fullName>India</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Ireland</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Jordan</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Kuwait</fullName>
        </value>
        <value>
          <fullName>Latvia</fullName>
        </value>
        <value>
          <fullName>Lithuania</fullName>
        </value>
        <value>
          <fullName>Luxembourg</fullName>
        </value>
        <value>
          <fullName>Malaysia</fullName>
        </value>
        <value>
          <fullName>Malta</fullName>
        </value>
        <value>
          <fullName>New Zealand</fullName>
        </value>
        <value>
          <fullName>Thailand</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET</businessProcess>
    <fullName>GET</fullName>
    <label>X DO NOT USE 2t</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Q_A__c.object
<CustomObject>
  <fields>
    <fullName>Questionnaire_Setup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Questionnaire Setup</label>
    <referenceTo>Questionnaire_Setup__c</referenceTo>
    <relationshipLabel>Q &amp; A</relationshipLabel>
    <relationshipName>Q_A</relationshipName>
    <type>Lookup</type>
  </fields>
  <label>Q &amp; A</label>
  <nameField>
    <label>Q &amp; A Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Q &amp; A</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Questionnaire_Setup__c.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <description>Two letters ONLY</description>
    <label>Country</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>AE</fullName>
        </value>
        <value>
          <fullName>AT</fullName>
        </value>
        <value>
          <fullName>BE</fullName>
        </value>
        <value>
          <fullName>BY</fullName>
        </value>
        <value>
          <fullName>CA</fullName>
        </value>
        <value>
          <fullName>DE</fullName>
        </value>
        <value>
          <fullName>DK</fullName>
        </value>
        <value>
          <fullName>EG</fullName>
        </value>
        <value>
          <fullName>ES</fullName>
        </value>
        <value>
          <fullName>FI</fullName>
        </value>
        <value>
          <fullName>FR</fullName>
        </value>
        <value>
          <fullName>GB</fullName>
        </value>
        <value>
          <fullName>ID</fullName>
        </value>
        <value>
          <fullName>IE</fullName>
        </value>
        <value>
          <fullName>IN</fullName>
        </value>
        <value>
          <fullName>IT</fullName>
        </value>
        <value>
          <fullName>KW</fullName>
        </value>
        <value>
          <fullName>KZ</fullName>
        </value>
        <value>
          <fullName>LU</fullName>
        </value>
        <value>
          <fullName>MY</fullName>
        </value>
        <value>
          <fullName>NL</fullName>
        </value>
        <value>
          <fullName>NO</fullName>
        </value>
        <value>
          <fullName>PH</fullName>
        </value>
        <value>
          <fullName>PT</fullName>
        </value>
        <value>
          <fullName>RU</fullName>
        </value>
        <value>
          <fullName>SA</fullName>
        </value>
        <value>
          <fullName>SE</fullName>
        </value>
        <value>
          <fullName>TH</fullName>
        </value>
        <value>
          <fullName>UA</fullName>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Create_Opportunity__c</fullName>
    <inlineHelpText>Would you like to create an opportunity automatically after submitting questionnaire?</inlineHelpText>
    <label>Create Opportunity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Do Not</fullName>
          <label>Do Not Create</label>
        </value>
        <value>
          <fullName>Sirona Opportunity</fullName>
        </value>
        <value>
          <fullName>IMPL GET Opp</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Owner_Of_Opportunity__c</fullName>
    <label>Owner Of Opportunity</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>Create_Opportunity__c</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Based on Dealer ETM</fullName>
        </value>
        <value>
          <fullName>Based on Account ETM</fullName>
        </value>
        <value>
          <fullName>Default User</fullName>
        </value>
        <value>
          <fullName>Based on Manual assignment ETM</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Product_Line__c</fullName>
    <inlineHelpText>The list of Product lines that will be displayed at the beginning of the questionnaire. Make sure to create questions for each product line.</inlineHelpText>
    <label>Product Line</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
      <controllingField>Questionnaire_Type__c</controllingField>
      <restricted>true</restricted>
      <valueSetName>Product_Line</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>Questionnaire_Type__c</fullName>
    <label>Questionnaire Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Questionnaire_Type</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Inactive</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Questionnaire Setup</label>
  <nameField>
    <label>Questionnaire Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Questionnaires Setup</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Type__c</fullName>
    <inlineHelpText>Sales Representative  = District Managers, Territory Managers, Account Managers

Sales Manager = Regional Sales Mgrs, Division Sales Mgrs, National Sales Mgrs</inlineHelpText>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Account Maintenance Team Member</fullName>
        </value>
        <value>
          <fullName>Area Sales Manager</fullName>
        </value>
        <value>
          <fullName>Clinical Affairs</fullName>
        </value>
        <value>
          <fullName>Complaints Handling</fullName>
        </value>
        <value>
          <fullName>Customer Service</fullName>
        </value>
        <value>
          <fullName>Finance</fullName>
        </value>
        <value>
          <fullName>Inside Sales Representative</fullName>
        </value>
        <value>
          <fullName>Key Account Manager</fullName>
        </value>
        <value>
          <fullName>Managing Director</fullName>
        </value>
        <value>
          <fullName>Marketing</fullName>
        </value>
        <value>
          <fullName>National Admin</fullName>
        </value>
        <value>
          <fullName>Operations</fullName>
        </value>
        <value>
          <fullName>Other</fullName>
        </value>
        <value>
          <fullName>Product Manager</fullName>
        </value>
        <value>
          <fullName>Regional Sales Manager</fullName>
        </value>
        <value>
          <fullName>Sales Manager</fullName>
        </value>
        <value>
          <fullName>Sales Representative</fullName>
        </value>
        <value>
          <fullName>Training &amp; Event Management</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/objects/XSBU_2_orgs__c.object
<CustomObject>
  <customSettingsType>List</customSettingsType>
  <description>This is to automoatize XSBU connection setup for the countries listed in this setting</description>
  <fields>
    <fullName>Connection_Id_del__c</fullName>
    <label>Connection Id</label>
    <length>18</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Country_Code_del__c</fullName>
    <label>Country Code</label>
    <length>2</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Named_Credential__c</fullName>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Opportunity_RecordType_Id__c</fullName>
    <label>Opportunity RecordType Id</label>
    <length>25</length>
    <type>Text</type>
  </fields>
  <label>XSBU 2 orgs</label>
</CustomObject>

unpackaged/classes/OpportunityInsertTest.cls
@isTest(SeeAllData=false)
public class OpportunityInsertTest {

    @TestSetup
    private static void makeData() {
        // Create bypass custom setting
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.returnUsers(1, 'System Administrator');
        userList.get(0).User_Country__c = 'Thailand';
        userList.get(0).User_Type__c = 'Standard';
        insert userList;
        // Create global integration custom setting
        TestDataFactory.createGlobalIntegrationSettings(userList);
        // Create XSBU 2 orgs custom setting
        XSBU_2_orgs__c xsbu2Orgs = new XSBU_2_orgs__c();
        xsbu2Orgs.Name = 'Thailand';
        xsbu2Orgs.Country_Code_del__c = 'TH';
        xsbu2Orgs.Named_Credential__c = 'Salesforce_Org';
        xsbu2Orgs.Connection_Id_del__c = '04P0J0000005qmxUAA';
        xsbu2Orgs.Opportunity_RecordType_Id__c = '0121N0000016FfbQAE';
        insert xsbu2Orgs;
        // Create org level process builder bypass custom setting
        TestDataFactory.createDefaultOrgLevelBypassPB();
    }

    public static testMethod void testOpportunitySynch() {

        // Set mock callout class 
      	Test.setMock(HttpCalloutMock.class, new OpportunitySynchHttpCalloutMock()); 

        // Get test user from testSetup
        User u = [SELECT Id FROM User WHERE Alias = 'test1'][0];

        System.runAs(u) {          
            Account testAccount = TestDataFactory.createAccounts(1, 'Non_ERP_Account', u.Id)[0];   

	        Opportunity opp = new Opportunity();
            opp.AccountId = testAccount.Id;
            opp.Name = 'Test XSBU Synch';
            opp.StageName = 'Submitted';
            opp.CloseDate = System.today() + 5;
            Insert opp;
            System.Debug('Opp Created by: ' + opp.CreatedBy.User_Country__c);
            System.debug('Opp Id: ' + opp.Id);

            Questionnaire_Setup__c testQuestionnaire = new Questionnaire_Setup__c();
        	testQuestionnaire.Questionnaire_Type__c = 'xSBU';
        	testQuestionnaire.Country__c = 'TH';
        	testQuestionnaire.Name = 'Test';
        	testQuestionnaire.Product_Line__c = 'Imaging';
        	testQuestionnaire.Status__c = 'Active';
        	testQuestionnaire.Create_Opportunity__c = 'Sirona Opportunity';
        	testQuestionnaire.Owner_Of_Opportunity__c = 'Default User';
        	testQuestionnaire.Partner_Assignment__c = 'Auto';
        	testQuestionnaire.Default_User__c= UserInfo.getUserId();
        	testQuestionnaire.Show_contact_option__c = true;
            insert testQuestionnaire;
            
        	Q_A__c qa = new Q_A__c();
        	qa.Name = 'Test';
        	qa.Question__c = 'Test Question';
        	qa.Answer__c = 'Test Answer';
        	qa.Opportunity_Name__c = opp.Id;
            qa.Account_Name__c = testAccount.Id;
            qa.Questionnaire_setup__c = testQuestionnaire.Id;
            insert qa;

            Test.startTest();
            OpportunitySynch.SynchOpportunityInsert(opp.Id);
            Test.stopTest();
        }
    }
}