unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Questionnaire_Setup__c.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <description>Two letters ONLY</description>
    <label>Country</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>AE</fullName>
        </value>
        <value>
          <fullName>AT</fullName>
        </value>
        <value>
          <fullName>BE</fullName>
        </value>
        <value>
          <fullName>BY</fullName>
        </value>
        <value>
          <fullName>CA</fullName>
        </value>
        <value>
          <fullName>DE</fullName>
        </value>
        <value>
          <fullName>DK</fullName>
        </value>
        <value>
          <fullName>EG</fullName>
        </value>
        <value>
          <fullName>ES</fullName>
        </value>
        <value>
          <fullName>FI</fullName>
        </value>
        <value>
          <fullName>FR</fullName>
        </value>
        <value>
          <fullName>GB</fullName>
        </value>
        <value>
          <fullName>ID</fullName>
        </value>
        <value>
          <fullName>IE</fullName>
        </value>
        <value>
          <fullName>IN</fullName>
        </value>
        <value>
          <fullName>IT</fullName>
        </value>
        <value>
          <fullName>KW</fullName>
        </value>
        <value>
          <fullName>KZ</fullName>
        </value>
        <value>
          <fullName>LU</fullName>
        </value>
        <value>
          <fullName>MY</fullName>
        </value>
        <value>
          <fullName>NL</fullName>
        </value>
        <value>
          <fullName>NO</fullName>
        </value>
        <value>
          <fullName>PH</fullName>
        </value>
        <value>
          <fullName>PT</fullName>
        </value>
        <value>
          <fullName>RU</fullName>
        </value>
        <value>
          <fullName>SA</fullName>
        </value>
        <value>
          <fullName>SE</fullName>
        </value>
        <value>
          <fullName>TH</fullName>
        </value>
        <value>
          <fullName>UA</fullName>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Product_Line__c</fullName>
    <inlineHelpText>The list of Product lines that will be displayed at the beginning of the questionnaire. Make sure to create questions for each product line.</inlineHelpText>
    <label>Product Line</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
      <controllingField>Questionnaire_Type__c</controllingField>
      <restricted>true</restricted>
      <valueSetName>Product_Line</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>Questionnaire_Type__c</fullName>
    <label>Questionnaire Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Questionnaire_Type</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Inactive</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Questionnaire Setup</label>
  <nameField>
    <label>Questionnaire Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Questionnaires Setup</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Questions__c.object
<CustomObject>
  <fields>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Not SBU-Specific</fullName>
          <default>true</default>
          <label>Not SBU-Specific</label>
        </value>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>CAD/CAM - Nazaré</fullName>
        </value>
        <value>
          <fullName>CAD/CAM - CEREC</fullName>
        </value>
        <value>
          <fullName>CAD/CAM - InLab</fullName>
        </value>
        <value>
          <fullName>Imaging</fullName>
        </value>
        <value>
          <fullName>Imaging - Extra Oral</fullName>
        </value>
        <value>
          <fullName>Imaging - Intra Oral</fullName>
        </value>
        <value>
          <fullName>Instruments</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>PREP</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Imaging - 2D</fullName>
        </value>
        <value>
          <fullName>Imaging - 3D</fullName>
        </value>
        <value>
          <fullName>Laboratory</fullName>
        </value>
        <value>
          <fullName>Consumables</fullName>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Question_Body__c</fullName>
    <label>Question Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
  </fields>
  <fields>
    <fullName>Question_Order__c</fullName>
    <label>Question Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Multiselect Checkbox</fullName>
        </value>
        <value>
          <fullName>Picklist</fullName>
        </value>
        <value>
          <fullName>Yes/No Radio Buttons</fullName>
          <label>Radio Buttons</label>
        </value>
        <value>
          <fullName>Free Text</fullName>
        </value>
        <value>
          <fullName>Yes/No/Other</fullName>
          <label>Choice 1/Choice 2/Other</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Questionnaire_Setup__c</fullName>
    <label>Questionnaire Setup</label>
    <referenceTo>Questionnaire_Setup__c</referenceTo>
    <relationshipLabel>Questions List</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Required_Question__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required Question</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Responses__c</fullName>
    <label>Responses</label>
    <length>32768</length>
    <type>LongTextArea</type>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Inactive</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Question</label>
  <nameField>
    <displayFormat>Q{00000}</displayFormat>
    <label>Questions Id</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Questions</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/flowQuestionnaireController.cls
/*------------------------------------------------------------	
	Author: 		Richard Trum (Glimt) 2019-11-28 	
	Description:   	Class for getting Questionnaire_Setup__c records and Questions__c records
					that are used within the flow to create new prospects/leads from an account
	------------------------------------------------------------*/ 
public with sharing class flowQuestionnaireController {

	/*------------------------------------------------------------	
	Description:   	AuraEnabled method to get questions from a certain questionnaire and related to a certain product line
	Inputs:        	@param recordId - the account's Id
					@param questionnaireId - the questionnaire (Questionnaire_Setup__c) Id
					@param category - The category/product line to filter the questions on
	------------------------------------------------------------*/	
    @AuraEnabled
    public static List<QuestionWrapper> getQuestions(String recordId, String questionnaireId, String category) {
        
    Account acc = [SELECT Id, Name, Country__c FROM ACCOUNT WHERE Id =: recordId];    
	
    List<Questions__c> questions = [SELECT Id, Name, Product_Line__c, Question_Body__c, Question_Order__c, Question_Type__c, Questionnaire_Setup__c, Questionnaire_Setup__r.Product_Line__c, Required_Question__c, Status__c, Responses__c
                                    FROM Questions__c WHERE (Questionnaire_Setup__c =: questionnaireId AND (Product_Line__c =: category OR Product_Line__c=:'Not SBU-Specific')) AND Status__c = 'Active' ORDER BY Question_Order__c ASC NULLS LAST];
        
    List<QuestionWrapper> result = new List<QuestionWrapper>();
        
    for(Questions__c q: questions){
            result.add(new QuestionWrapper(q));
    }
        
    return result;

    }

	/*------------------------------------------------------------	
	Description:   	Invokable method (used in flows) to get cross-SBU questionnaires related to a certain country
					This method is handled in apex to be able to filter on the Country__c field which is a multi-select field
	Inputs:        	@param inputs - List of strings to input which country to filter on
	------------------------------------------------------------*/	    
    
    @InvocableMethod
    public static List<Questionnaire_Setup__c> getQuestionnaire(List<String> inputs){
    
    String country = inputs[0];
    List<Questionnaire_Setup__c> qList = new List<Questionnaire_Setup__c>();
    
        try{  
    		 qList = [SELECT Id, Country__c FROM Questionnaire_Setup__c WHERE (Country__c includes (:country) AND Questionnaire_Type__c =: 'xSBU' AND Status__c = 'Active')];
        }
        catch(DmlException e){
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
 
    return qList;
        
    }

	/*------------------------------------------------------------	
	Description:   	Wrapper class to be able to return both the question details as well as the question options as an array
	------------------------------------------------------------*/	     
    
    public class QuestionWrapper {
    @AuraEnabled public Questions__c questionDetails;
    @AuraEnabled public List<String> options;
        
    QuestionWrapper(Questions__c q) {
        questionDetails = q;
        if(String.isBlank(q.Responses__c)){
        }
        else{
        options = q.Responses__c.split(';');
        }    
    }
	}
}