unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Questionnaire_Setup__c.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <description>Two letters ONLY</description>
    <label>Country</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>AE</fullName>
        </value>
        <value>
          <fullName>AT</fullName>
        </value>
        <value>
          <fullName>BE</fullName>
        </value>
        <value>
          <fullName>BY</fullName>
        </value>
        <value>
          <fullName>CA</fullName>
        </value>
        <value>
          <fullName>DE</fullName>
        </value>
        <value>
          <fullName>DK</fullName>
        </value>
        <value>
          <fullName>EG</fullName>
        </value>
        <value>
          <fullName>ES</fullName>
        </value>
        <value>
          <fullName>FI</fullName>
        </value>
        <value>
          <fullName>FR</fullName>
        </value>
        <value>
          <fullName>GB</fullName>
        </value>
        <value>
          <fullName>ID</fullName>
        </value>
        <value>
          <fullName>IE</fullName>
        </value>
        <value>
          <fullName>IN</fullName>
        </value>
        <value>
          <fullName>IT</fullName>
        </value>
        <value>
          <fullName>KW</fullName>
        </value>
        <value>
          <fullName>KZ</fullName>
        </value>
        <value>
          <fullName>LU</fullName>
        </value>
        <value>
          <fullName>MY</fullName>
        </value>
        <value>
          <fullName>NL</fullName>
        </value>
        <value>
          <fullName>NO</fullName>
        </value>
        <value>
          <fullName>PH</fullName>
        </value>
        <value>
          <fullName>PT</fullName>
        </value>
        <value>
          <fullName>RU</fullName>
        </value>
        <value>
          <fullName>SA</fullName>
        </value>
        <value>
          <fullName>SE</fullName>
        </value>
        <value>
          <fullName>TH</fullName>
        </value>
        <value>
          <fullName>UA</fullName>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Create_Opportunity__c</fullName>
    <inlineHelpText>Would you like to create an opportunity automatically after submitting questionnaire?</inlineHelpText>
    <label>Create Opportunity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Do Not</fullName>
          <label>Do Not Create</label>
        </value>
        <value>
          <fullName>Sirona Opportunity</fullName>
        </value>
        <value>
          <fullName>IMPL GET Opp</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Product_Line__c</fullName>
    <inlineHelpText>The list of Product lines that will be displayed at the beginning of the questionnaire. Make sure to create questions for each product line.</inlineHelpText>
    <label>Product Line</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
      <controllingField>Questionnaire_Type__c</controllingField>
      <restricted>true</restricted>
      <valueSetName>Product_Line</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>Questionnaire_Type__c</fullName>
    <label>Questionnaire Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Questionnaire_Type</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Inactive</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Questionnaire Setup</label>
  <nameField>
    <label>Questionnaire Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Questionnaires Setup</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Questions__c.object
<CustomObject>
  <fields>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Not SBU-Specific</fullName>
          <default>true</default>
          <label>Not SBU-Specific</label>
        </value>
        <value>
          <fullName>CAD/CAM</fullName>
        </value>
        <value>
          <fullName>CAD/CAM - Nazaré</fullName>
        </value>
        <value>
          <fullName>CAD/CAM - CEREC</fullName>
        </value>
        <value>
          <fullName>CAD/CAM - InLab</fullName>
        </value>
        <value>
          <fullName>Imaging</fullName>
        </value>
        <value>
          <fullName>Imaging - Extra Oral</fullName>
        </value>
        <value>
          <fullName>Imaging - Intra Oral</fullName>
        </value>
        <value>
          <fullName>Instruments</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Restorative</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>PREP</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
        </value>
        <value>
          <fullName>Imaging - 2D</fullName>
        </value>
        <value>
          <fullName>Imaging - 3D</fullName>
        </value>
        <value>
          <fullName>Laboratory</fullName>
        </value>
        <value>
          <fullName>Consumables</fullName>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Question_Order__c</fullName>
    <label>Question Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Multiselect Checkbox</fullName>
        </value>
        <value>
          <fullName>Picklist</fullName>
        </value>
        <value>
          <fullName>Yes/No Radio Buttons</fullName>
          <label>Radio Buttons</label>
        </value>
        <value>
          <fullName>Free Text</fullName>
        </value>
        <value>
          <fullName>Yes/No/Other</fullName>
          <label>Choice 1/Choice 2/Other</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Questionnaire_Setup__c</fullName>
    <label>Questionnaire Setup</label>
    <referenceTo>Questionnaire_Setup__c</referenceTo>
    <relationshipLabel>Questions List</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Responses__c</fullName>
    <label>Responses</label>
    <length>32768</length>
    <type>LongTextArea</type>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Inactive</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Question</label>
  <nameField>
    <displayFormat>Q{00000}</displayFormat>
    <label>Questions Id</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Questions</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Test_flowQuestionnaireController.cls
/*------------------------------------------------------------	
Author: 		Richard Trum (Glimt) 2019-11-28 	
Description:   	Test class for testing the apex class flowQuestionnaireController
------------------------------------------------------------*/

@isTest
private class Test_flowQuestionnaireController {

    @IsTest
    private static void questionnaireTest(){
		Questionnaire_Setup__c q = new Questionnaire_Setup__c();
		q.Country__c = 'UK;IE';
        q.Questionnaire_Type__c = 'xSBU';
        q.Status__c = 'Active';
        q.Name = 'Test questionnaire';
        q.Create_Opportunity__c = 'Do Not';
        insert q;
        
        Account acc = new Account();
        acc.Name = 'Test account';
        acc.Country__c = 'IE';
        insert acc;
        
        Questions__c quest = new Questions__c();
        quest.Product_Line__c = 'Not SBU-Specific';
        quest.Question_Order__c = 1;
        quest.Question_Type__c = 'Free Text';
        quest.Responses__c = 'Yes;No';
        quest.Questionnaire_Setup__c = q.Id;
        quest.Status__c = 'Active';
		insert quest;        

        Test.startTest();
        List<String> input = new List<String>();
        input.add('UK');
		List<Questionnaire_Setup__c> qList = flowQuestionnaireController.getQuestionnaire(input);
        System.assertNotEquals(qList, null);
        
        List<flowQuestionnaireController.QuestionWrapper> result = flowQuestionnaireController.getQuestions(acc.Id, q.Id, '');
        System.assertEquals(result[0].questionDetails.Question_Order__c, 1);
        
        
        Test.stopTest();
        
    }

}