unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/LeadOpportunitySetting__mdt.object
<CustomObject>
  <fields>
    <fullName>Brands__c</fullName>
    <label>Brands</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Consumables</fullName>
          <default>true</default>
          <label>Consumables</label>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>AD</fullName>
          <default>true</default>
          <label>AD</label>
        </value>
        <value>
          <fullName>AE</fullName>
        </value>
        <value>
          <fullName>AF</fullName>
        </value>
        <value>
          <fullName>AG</fullName>
        </value>
        <value>
          <fullName>AI</fullName>
        </value>
        <value>
          <fullName>AL</fullName>
        </value>
        <value>
          <fullName>AM</fullName>
        </value>
        <value>
          <fullName>AN</fullName>
        </value>
        <value>
          <fullName>AO</fullName>
        </value>
        <value>
          <fullName>AQ</fullName>
        </value>
        <value>
          <fullName>AR</fullName>
        </value>
        <value>
          <fullName>AS</fullName>
        </value>
        <value>
          <fullName>AT</fullName>
        </value>
        <value>
          <fullName>AU</fullName>
        </value>
        <value>
          <fullName>AW</fullName>
        </value>
        <value>
          <fullName>AX</fullName>
        </value>
        <value>
          <fullName>AZ</fullName>
        </value>
        <value>
          <fullName>BA</fullName>
        </value>
        <value>
          <fullName>BB</fullName>
        </value>
        <value>
          <fullName>BD</fullName>
        </value>
        <value>
          <fullName>BE</fullName>
        </value>
        <value>
          <fullName>BF</fullName>
        </value>
        <value>
          <fullName>BG</fullName>
        </value>
        <value>
          <fullName>BH</fullName>
        </value>
        <value>
          <fullName>BI</fullName>
        </value>
        <value>
          <fullName>BJ</fullName>
        </value>
        <value>
          <fullName>BL</fullName>
        </value>
        <value>
          <fullName>BM</fullName>
        </value>
        <value>
          <fullName>BN</fullName>
        </value>
        <value>
          <fullName>BO</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>UserRoles__c</fullName>
    <label>User Roles</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <label>Lead &amp; Opportunity Setting</label>
  <pluralLabel>Lead &amp; Opportunity Settings</pluralLabel>
</CustomObject>

unpackaged/classes/AssignSuggestedOwnerHelper.cls
/**
 * @description       : This class provides helper methods for BatchSalesLeadAssignSuggestedOwner and BatchOpportunityAssignSuggestedOwner
 * @author            : kdoruibin@salesforce.com
 * @group             : 
 * @last modified on  : 06-15-2021
 * @last modified by  : kdoruibin@salesforce.com
 * Modifications Log 
 * Ver   Date         Author                     Modification
 * 1.0   06-15-2021   kdoruibin@salesforce.com   Initial Version
**/
public without sharing class AssignSuggestedOwnerHelper {
    private static Map<String, List<LeadOpportunitySetting__mdt>> leadOpptySettingMap = new Map<String, List<LeadOpportunitySetting__mdt>>();
    private static Map<Id,List<Id>> accountTerritoryMap = new Map<Id,List<Id>>();
    private static Set<Id> flattenedTerritoryIdSet = new Set<Id>();
    private static Map<Id, Map<String, UserTerritory2Association>> territoryIdUserAssociationMap = new Map<Id, Map<String, UserTerritory2Association>>();

    public static void initialize(Set<Id> accountIdSet) {
        leadOpptySettingMap = getLeadOpportunitySettings();
        accountTerritoryMap = getAccountTerritoryMap(accountIdSet);
        flattenedTerritoryIdSet = getFlattenedTerritoryIdSet(accountTerritoryMap);
        territoryIdUserAssociationMap = getTerritoryIdUserAssociationMap(flattenedTerritoryIdSet);
    }
    
    public static Map<String, List<LeadOpportunitySetting__mdt>> getLeadOpportunitySettings() {
        Map<String, List<LeadOpportunitySetting__mdt>> leadOpptySettingMap = new Map<String, List<LeadOpportunitySetting__mdt>>();
        for (LeadOpportunitySetting__mdt leadOpptySetting : LeadOpportunitySetting__mdt.getAll().values()) {
            // Skip setting if mandatory fields are empty
            if (String.isEmpty(leadOpptySetting.Country__c)) continue;
            if (String.isEmpty(leadOpptySetting.Category__c)) continue;
            if (String.isEmpty(leadOpptySetting.UserRoles__c)) continue;
            if (String.isEmpty(leadOpptySetting.Brands__c)) continue;
            
            // Construct Map of settings with Country__c + Category__c as key (e.g. USImplants)
            String settingKeyString = leadOpptySetting.Country__c + leadOpptySetting.Category__c;
            if (leadOpptySettingMap.containsKey(settingKeyString)) {
                leadOpptySettingMap.get(settingKeyString).add(leadOpptySetting);
                } else {
                leadOpptySettingMap.put(settingKeyString, new List<LeadOpportunitySetting__mdt>{leadOpptySetting});
            }
        }
        return leadOpptySettingMap;
    }

    public static Map<Id,List<Id>> getAccountTerritoryMap(Set<Id> accountIdSet) {
        Map<Id,List<Id>> accountTerritoryMap = new Map<Id,List<Id>>();
        for (ObjectTerritory2Association accTerritoryAssociation : [
                SELECT ObjectId, Territory2Id
                FROM ObjectTerritory2Association
                WHERE ObjectId IN :accountIdSet
            ]) {
                // Construct Map of accounts and territories where an accountId leads to a list of associated territories
                if (accountTerritoryMap.containsKey(accTerritoryAssociation.ObjectId)) {
                    accountTerritoryMap.get(accTerritoryAssociation.ObjectId).add(accTerritoryAssociation.Territory2Id);
                } else {
                    accountTerritoryMap.put(accTerritoryAssociation.ObjectId, new List<Id>{accTerritoryAssociation.Territory2Id});
                }
            }
        return accountTerritoryMap;
    }

    public static Set<Id> getFlattenedTerritoryIdSet(Map<Id,List<Id>> listMap) {
        Set<Id> flattenedIdSet = new Set<Id>();
        for (List<Id> idList : listMap.values()) {
            flattenedIdSet.addAll(idList);
        }
        return flattenedIdSet;
    }

    public static Map<Id, Map<String, UserTerritory2Association>> getTerritoryIdUserAssociationMap(Set<Id> flattenedTerritoryIdSet) {
        Map<Id, Map<String, UserTerritory2Association>> territoryIdUserAssociationMap = new Map<Id, Map<String, UserTerritory2Association>>();
        for (UserTerritory2Association userTerritoryAssociation : [
                SELECT Id, Territory2Id, UserId, RoleInTerritory2
                FROM UserTerritory2Association
                WHERE Territory2Id IN :flattenedTerritoryIdSet
            ]) {
                // Construct Map of territories and associated users based on RoleInTerritory2
                if (territoryIdUserAssociationMap.containsKey(userTerritoryAssociation.Territory2Id)) {
                    territoryIdUserAssociationMap.get(userTerritoryAssociation.Territory2Id).put(userTerritoryAssociation.RoleInTerritory2, userTerritoryAssociation);
                } else {
                    territoryIdUserAssociationMap.put(userTerritoryAssociation.Territory2Id, new Map<String, UserTerritory2Association>{userTerritoryAssociation.RoleInTerritory2 => userTerritoryAssociation});
                }
            }
        return territoryIdUserAssociationMap;
    }
}