unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Lightning_Component__mdt.object
<CustomObject>
  <description>List of available Lightning Components, used in Team Setup</description>
  <fields>
    <fullName>Status__c</fullName>
    <defaultValue>'In development'</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>In development</fullName>
          <default>true</default>
          <label>In development</label>
        </value>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Retired</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Lightning Component</label>
  <pluralLabel>Lightning Components</pluralLabel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Team_setup__mdt.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Sweden</fullName>
          <default>true</default>
          <label>Sweden</label>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
        <value>
          <fullName>Norway</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
          <default>true</default>
          <label>Active</label>
        </value>
        <value>
          <fullName>Retired</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Team setup</label>
  <pluralLabel>Team setups</pluralLabel>
</CustomObject>

unpackaged/classes/LightningCompSetupTest.cls
@IsTest
public class LightningCompSetupTest {

    @IsTest
    private static void loadRelatedRecordsTest() {
        String fullName = 'Team_setup';
        String fields = 'DeveloperName, Label, Status__c';
        
        List<SObject> testing = new List<SObject> ();
        List<SObject> testing2 = new List<SObject> ();
        Team_setup__mdt[] rows =
            [SELECT DeveloperName, Label, Status__c
            FROM Team_setup__mdt
            ORDER BY Label 
            LIMIT 10 ];
            
        testing = LightningCompSetup.loadRelatedRecord(fullName, fields);
        System.assertEquals(rows, testing);
        
        testing2 = MetadataRecordDataController.loadRecord(fullName, fields, 'Sweden');
        System.assertEquals(rows, testing2);
        
    }
        
    /*@IsTest
    private static void upsertCmpTest() {
        
        List<SObject> testing = new List<SObject> ();
        Lightning_component__mdt[] rows =
            [SELECT DeveloperName, Label, Status__c
            FROM Lightning_component__mdt
            LIMIT 10];
            
        String record = 'Testing';
        String Descr = 'Testing to create component';
        String Status = 'Active';
        
        String result = '';
        Test.startTest();
        result = LightningCompSetup.upsertCmp(record, Descr, Status);        
        System.assertNotEquals('', result);
        Test.stopTest();
        
    } 
    
    @IsTest
    private static void upsertTeamTest() {
        
        List<SObject> testing = new List<SObject> ();
        Team_setup__mdt[] rows =
            [SELECT DeveloperName, Label, Status__c
            FROM Team_setup__mdt
            LIMIT 10];
            
        String record = 'Testing';
        String Country = 'Sweden';
        String Descr = 'Testing to create component';
        String Status = 'Active';
        
        String result = '';
        result = Test.isRunningTest() ? 'Fake Job Id': LightningCompSetup.upsertTeam(record, Country, Descr, Status);        
        System.assertNotEquals('', result);
        
    }*/ 
    
    @IsTest
    private static void PickListValuesIntoListTest() {
        String Cmp = 'Lightning_Component__mdt';
        String Field = 'Status__c';
        List<String> result = new List<String>();
        result = LightningCompSetup.getPickListValuesIntoList(Cmp, Field);        
        System.assertNotEquals(0, result.size());
        
    } 
    @IsTest
    private static void SessionControllerTest() {
        String result = SessionController.getSessionId();       
        System.assertNotEquals(null, result);
        
    }
    
    @IsTest
    private static void getUserListTest() {
     String SearchStr = '';
     String Countr = '';
     String Tm = '';
        
     List<User> result = LightningCompSetup.getUserList(SearchStr, Countr, Tm);
        
     Countr = 'UK';        
     result = LightningCompSetup.getUserList(SearchStr, Countr, Tm);
        
     Countr = '';
     Tm = 'UK1';        
     result = LightningCompSetup.getUserList(SearchStr, Countr, Tm);    
          
     Countr = 'UK';
     result = LightningCompSetup.getUserList(SearchStr, Countr, Tm);   
        
    }
    
    @IsTest
    private static void updateUserTest() {
        
        User TestUsr = new User();
        TestUsr.FirstName = 'Test';
        TestUsr.LastName = 'Test';
        String Tm = 'UK1';
        
        String result = LightningCompSetup.updateUser(TestUsr, Tm);
        System.assertEquals('error', result);
        
    }
    
        
    @IsTest
    private static void upsertCmpTest() {

        // Given
        CustomMetadataTest.MockPlatform mockPlatform = new CustomMetadataTest.MockPlatform();
        mockPlatform.metadataEnqueueDeploymentResult = new Metadata.DeployResult();
        mockPlatform.metadataEnqueueDeploymentResult.details = new Metadata.DeployDetails();
        mockPlatform.metadataEnqueueDeploymentResult.details.componentFailures = new List<Metadata.DeployMessage>();
        mockPlatform.metadataEnqueueDeploymentResult.details.componentSuccesses = new List<Metadata.DeployMessage>();
        Metadata.DeployMessage deploySuccess = 
            (Metadata.DeployMessage) JSON.deserialize(
                '{"fullName":"Account","success":true}', Metadata.DeployMessage.class);
        mockPlatform.metadataEnqueueDeploymentResult.details.componentSuccesses.add(deploySuccess);
        mockPlatform.eventBusPublishResponse = 
            (List<Database.SaveResult>) JSON.deserialize(
                '[{"id":"e00xx000000001TAAQ","success":true,"errors":[],"warnings":[]}]', List<Database.SaveResult>.class);
        CustomMetadata.Platform = mockPlatform;
        List<Map<SObjectField, Object>> records = 
            new List<Map<SObjectField, Object>> {
                new Map<SObjectField, Object> {
                    Account.Description => 'My Record'
            } };
        
        // When
        String deployId = LightningCompSetup.upsertCmp('Test', 'Test', 'Active', 'Test Testsson');
        
        // Then
        System.assertEquals(
            'Status__c', ((Metadata.CustomMetadata) mockPlatform.metadataEnqueueDeploymentContainer.getMetadata()[0]).values[0].field);
        System.assertEquals(
            'Active', ((Metadata.CustomMetadata) mockPlatform.metadataEnqueueDeploymentContainer.getMetadata()[0]).values[0].value);        
    }    

        @IsTest
    private static void upsertTeamTest() {

        // Given
        CustomMetadataTest.MockPlatform mockPlatform = new CustomMetadataTest.MockPlatform();
        mockPlatform.metadataEnqueueDeploymentResult = new Metadata.DeployResult();
        mockPlatform.metadataEnqueueDeploymentResult.details = new Metadata.DeployDetails();
        mockPlatform.metadataEnqueueDeploymentResult.details.componentFailures = new List<Metadata.DeployMessage>();
        mockPlatform.metadataEnqueueDeploymentResult.details.componentSuccesses = new List<Metadata.DeployMessage>();
        Metadata.DeployMessage deploySuccess = 
            (Metadata.DeployMessage) JSON.deserialize(
                '{"fullName":"Account","success":true}', Metadata.DeployMessage.class);
        mockPlatform.metadataEnqueueDeploymentResult.details.componentSuccesses.add(deploySuccess);
        mockPlatform.eventBusPublishResponse = 
            (List<Database.SaveResult>) JSON.deserialize(
                '[{"id":"e00xx000000001TAAQ","success":true,"errors":[],"warnings":[]}]', List<Database.SaveResult>.class);
        CustomMetadata.Platform = mockPlatform;
        List<Map<SObjectField, Object>> records = 
            new List<Map<SObjectField, Object>> {
                new Map<SObjectField, Object> {
                    Account.Description => 'My Record'
            } };
        
        // When
        String deployId = LightningCompSetup.upsertTeam('Test', 'Sweden', 'Test', 'Active');
        
        // Then
        System.assertEquals(
            'Country__c', ((Metadata.CustomMetadata) mockPlatform.metadataEnqueueDeploymentContainer.getMetadata()[0]).values[0].field);
        System.assertEquals(
            'Sweden', ((Metadata.CustomMetadata) mockPlatform.metadataEnqueueDeploymentContainer.getMetadata()[0]).values[0].value);        
    }   
    
    
    //Test classes for MetadataRecordDataController
    
    @IsTest
    private static void createCountryRecordTest() {

        // Given
        CustomMetadataTest.MockPlatform mockPlatform = new CustomMetadataTest.MockPlatform();
        mockPlatform.metadataEnqueueDeploymentResult = new Metadata.DeployResult();
        mockPlatform.metadataEnqueueDeploymentResult.details = new Metadata.DeployDetails();
        mockPlatform.metadataEnqueueDeploymentResult.details.componentFailures = new List<Metadata.DeployMessage>();
        mockPlatform.metadataEnqueueDeploymentResult.details.componentSuccesses = new List<Metadata.DeployMessage>();
        Metadata.DeployMessage deploySuccess = 
            (Metadata.DeployMessage) JSON.deserialize(
                '{"fullName":"Account","success":true}', Metadata.DeployMessage.class);
        mockPlatform.metadataEnqueueDeploymentResult.details.componentSuccesses.add(deploySuccess);
        mockPlatform.eventBusPublishResponse = 
            (List<Database.SaveResult>) JSON.deserialize(
                '[{"id":"e00xx000000001TAAQ","success":true,"errors":[],"warnings":[]}]', List<Database.SaveResult>.class);
        CustomMetadata.Platform = mockPlatform;
        List<Map<SObjectField, Object>> records = 
            new List<Map<SObjectField, Object>> {
                new Map<SObjectField, Object> {
                    Account.Description => 'My Record'
            } };
        
        // When
        String deployId = MetadataRecordDataController.createCountryRecord('Test', 'SE1', 'Account_CFE_Summary', true);
        
        // Then
        System.assertEquals(
            'LightningComponent__c', ((Metadata.CustomMetadata) mockPlatform.metadataEnqueueDeploymentContainer.getMetadata()[0]).values[0].field);
        System.assertEquals(
            'Account_CFE_Summary', ((Metadata.CustomMetadata) mockPlatform.metadataEnqueueDeploymentContainer.getMetadata()[0]).values[0].value);        
    } 
    
    
        @IsTest
    private static void whenUpsertingBySObjectSendsEvent() {

        // Given
        CustomMetadataTest.MockPlatform mockPlatform = new CustomMetadataTest.MockPlatform();
        mockPlatform.metadataEnqueueDeploymentResult = new Metadata.DeployResult();
        mockPlatform.metadataEnqueueDeploymentResult.details = new Metadata.DeployDetails();
        mockPlatform.metadataEnqueueDeploymentResult.details.componentFailures = new List<Metadata.DeployMessage>();
        mockPlatform.metadataEnqueueDeploymentResult.details.componentSuccesses = new List<Metadata.DeployMessage>();
        Metadata.DeployMessage deploySuccess = 
            (Metadata.DeployMessage) JSON.deserialize(
                '{"fullName":"Account","success":true}', Metadata.DeployMessage.class);
        mockPlatform.metadataEnqueueDeploymentResult.details.componentSuccesses.add(deploySuccess);
        mockPlatform.eventBusPublishResponse = 
            (List<Database.SaveResult>) JSON.deserialize(
                '[{"id":"e00xx000000001TAAQ","success":true,"errors":[],"warnings":[]}]', List<Database.SaveResult>.class);
        CustomMetadata.Platform = mockPlatform;
        List<SObject> records = new List<SObject> { new Account(Description = 'My Record') }; 
        
        // When
        String deployId = MetadataRecordDataController.upsertRecord(records[0]);
        
        // Then
        System.assertEquals(
            'Description', ((Metadata.CustomMetadata) mockPlatform.metadataEnqueueDeploymentContainer.getMetadata()[0]).values[0].field);
        System.assertEquals(
            'My Record', ((Metadata.CustomMetadata) mockPlatform.metadataEnqueueDeploymentContainer.getMetadata()[0]).values[0].value);        
        /*System.assertEquals(
            '[{"success":true,"fullName":"Account"}]', 
            mockPlatform.eventBusPublishEvents[0].get('Description'));*/
    } 


}