unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Sales_History__c.object
<CustomObject>
  <description>Detailed Sales History of Products Sold to Accounts</description>
  <fields>
    <fullName>Account__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales History</relationshipLabel>
    <relationshipName>SalesHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
  </fields>
  <fields>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Payer_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer Lookup</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales History (Payer Lookup)</relationshipLabel>
    <relationshipName>Sales_History</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Payer_Movex_D_JP__c</fullName>
    <description>Showing the Paying Accounts Movex #.</description>
    <inlineHelpText>Showing the Paying Accounts Movex #.</inlineHelpText>
    <label>Payer ERP # (D-JP)</label>
    <length>15</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Price__c</fullName>
    <inlineHelpText>Unit Price</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <label>Sales History</label>
  <nameField>
    <label>Article (SKU)</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Sales History</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/SalesHistorySetPayerLookupTest.cls
@isTest
private class SalesHistorySetPayerLookupTest
{ 
    // Tests the trigger in insert mode.
    static testmethod void insertTest01()
    {
        Account testAccount1 = createTestAccount('XX12345');
        insert testAccount1;
        
        // Test an record with a valid and existing Payer_Movex_D_JP__c value.
        Sales_History__c testHistory1 = createTestHistory(testAccount1, testAccount1.Movex__c);
        
        // Test an record with a non-existing Payer_Movex_D_JP__c value.
        Sales_History__c testHistory2 = createTestHistory(testAccount1, 'XX67890');
  
        // Test an record with no Payer_Movex_D_JP__c value.
        Sales_History__c testHistory3 = createTestHistory(testAccount1, null);
                
        List<Sales_History__c> recordsToInsert = new List<Sales_History__c>();
        recordsToInsert.add(testHistory1);
        recordsToInsert.add(testHistory2);      
        recordsToInsert.add(testHistory3);   
        
        insert recordsToInsert;        
        
        testHistory1 = [SELECT Id, Payer_Lookup__c FROM Sales_History__c WHERE Id = :testHistory1.Id LIMIT 1];
        testHistory2 = [SELECT Id, Payer_Lookup__c FROM Sales_History__c WHERE Id = :testHistory2.Id LIMIT 1];
        testHistory3 = [SELECT Id, Payer_Lookup__c FROM Sales_History__c WHERE Id = :testHistory3.Id LIMIT 1];
        
        System.assertEquals(testAccount1.Id, testHistory1.Payer_Lookup__c);
        System.assertEquals(null, testHistory2.Payer_Lookup__c);
        System.assertEquals(null, testHistory3.Payer_Lookup__c);
    }
    
    static Account createTestAccount(String movex)
    {
        Account testAccount = new Account();
        testAccount.Country__c = 'SE';
        testAccount.Name = 'TotalSales_TestAccount';
        testAccount.Movex__c = movex;
        
        return testAccount;
    }
    
    static Sales_History__c createTestHistory(Account testAccount, string payerMovex)
    {
        Sales_History__c testHistory = new Sales_History__c();
        testHistory.Account__c = testAccount.Id;
        testHistory.Name = '12345';
        testHistory.Invoice_Date__c = Datetime.now().date();
        testHistory.Quantity__c = 5;
        testHistory.Price__c = 10;   
        testHistory.CurrencyIsoCode = 'SEK';
        testHistory.Payer_Movex_D_JP__c = payerMovex;
        
        return testHistory;
    }     
}