unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OrdersOwned</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Regional_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/OrderSetAccountOwnerTest.cls
@isTest
private class OrderSetAccountOwnerTest
{
    // Tests the trigger in insert mode (account owner with manager).
    static testmethod void insertTest01()
    {
        User owner = [SELECT Id, ManagerId FROM User WHERE ManagerId = NULL AND IsActive = TRUE AND User.Profile.UserLicense.Name != 'Chatter Free' LIMIT 1];

        Account testAccount = createTestAccount(owner.Id);
        Order testOrder = createTestOrder(testAccount.Id);

        testOrder = [SELECT Id, Account_Owner__c, Regional_Manager__c FROM Order WHERE Id = :testOrder.Id LIMIT 1];
        //System.assertEquals(owner.Id, testOrder.Account_Owner__c);
        System.assertEquals(owner.ManagerId, testOrder.Regional_Manager__c);
    }

    // Tests the trigger in insert mode (account owner without manager).
    static testmethod void insertTest02()
    {
        User owner = [SELECT Id, ManagerId FROM User WHERE ManagerId = NULL AND IsActive = TRUE AND User.Profile.UserLicense.Name != 'Chatter Free' LIMIT 1];

        Account testAccount = createTestAccount(owner.Id);
        Order testOrder = createTestOrder(testAccount.Id);

        testOrder = [SELECT Id, Account_Owner__c, Regional_Manager__c FROM Order WHERE Id = :testOrder.Id LIMIT 1];
        //System.assertEquals(owner.Id, testOrder.Account_Owner__c);
        System.assertEquals(null, testOrder.Regional_Manager__c);
    }   

    static Account createTestAccount(ID ownerId)
    {
        Account testAccount = new Account();
        testAccount.Country__c = 'SE';
        testAccount.Name = 'OrderSetAccountOwner_TestAccount';
        if (ownerId != null)
            testAccount.OwnerId = ownerId;
        insert testAccount;
        return testAccount;
    }

    static Order createTestOrder(ID accountId)
    {
        Order testOrder = new Order();
        testOrder.AccountId = accountId;
        testOrder.Status = 'Created';
        testOrder.EffectiveDate = Date.today();
        insert testOrder;
        return testOrder;
    }       
}