unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Field_Sales_Project__c.object
<CustomObject>
  <description>Used by Sales Teams to collect Accounts into different Initiatives.
		These are all managed and created by the Field Sales Teams.</description>
  <fields>
    <fullName>AllowUsersToAddNewLeads__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow users to add new leads</label>
    <type>Checkbox</type>
  </fields>
  <fields>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <controllingField>UserCountry__c</controllingField>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>3D Imaging</fullName>
          <isActive>false</isActive>
          <label>3D Imaging</label>
        </value>
        <value>
          <fullName>ATLANTIS</fullName>
          <isActive>false</isActive>
          <label>ATLANTIS</label>
        </value>
        <value>
          <fullName>CEREC Equipment</fullName>
          <isActive>false</isActive>
          <label>CEREC Equipment</label>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Consumables</fullName>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Digital Solutions</fullName>
          <isActive>false</isActive>
          <label>Digital Solutions</label>
        </value>
        <value>
          <fullName>Endentulous</fullName>
          <isActive>false</isActive>
          <label>Endentulous</label>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Extra Oral Imaging</fullName>
          <isActive>false</isActive>
          <label>Extra Oral Imaging</label>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>InLab</fullName>
          <isActive>false</isActive>
          <label>InLab</label>
        </value>
        <value>
          <fullName>Intra Oral Imaging</fullName>
          <isActive>false</isActive>
          <label>Intra Oral Imaging</label>
        </value>
        <value>
          <fullName>Midwest Equipment</fullName>
          <isActive>false</isActive>
          <label>Midwest Equipment</label>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Preventive</fullName>
          <isActive>false</isActive>
          <label>Preventive</label>
        </value>
        <value>
          <fullName>Procedures</fullName>
          <isActive>false</isActive>
          <label>Procedures</label>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Regenerative</fullName>
          <isActive>false</isActive>
          <label>Regenerative</label>
        </value>
        <value>
          <fullName>Restorative</fullName>
          <isActive>false</isActive>
          <label>Restorative</label>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Treatment Centers</fullName>
          <isActive>false</isActive>
          <label>Treatment Centers</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Description__c</fullName>
    <inlineHelpText>Description of this Initiative</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
  </fields>
  <fields>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Initiative_Type__c</fullName>
    <label>List Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Marketing Initiative</fullName>
        </value>
        <value>
          <fullName>Regional Initiative</fullName>
        </value>
        <value>
          <fullName>Sales Team Initiative</fullName>
        </value>
        <value>
          <fullName>Inside Sales Target List</fullName>
        </value>
        <value>
          <fullName>Area Initiative</fullName>
          <isActive>false</isActive>
          <label>Area Initiative</label>
        </value>
        <value>
          <fullName>RCO Initiative</fullName>
          <isActive>false</isActive>
          <label>RCO Initiative</label>
        </value>
        <value>
          <fullName>Static/Ops Maintained List</fullName>
          <isActive>false</isActive>
          <label>Static/Ops Maintained List</label>
        </value>
        <value>
          <fullName>Territory Initiative</fullName>
          <isActive>false</isActive>
          <label>Territory Initiative</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
  </fields>
  <fields>
    <fullName>Title__c</fullName>
    <inlineHelpText>This helps the naming of the Initiative</inlineHelpText>
    <label>Title</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
  </fields>
  <label>Target List</label>
  <nameField>
    <label>Target List Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Target Lists</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/LeadOpportunitySetting__mdt.object
<CustomObject>
  <fields>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Consumables</fullName>
          <default>true</default>
          <label>Consumables</label>
        </value>
        <value>
          <fullName>Digital</fullName>
        </value>
        <value>
          <fullName>Digital Group</fullName>
        </value>
        <value>
          <fullName>Endodontics</fullName>
        </value>
        <value>
          <fullName>Equipment</fullName>
        </value>
        <value>
          <fullName>Equipment &amp; Imaging</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Orthodontics</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Class II</fullName>
        </value>
        <value>
          <fullName>Single Unit Crown</fullName>
        </value>
        <value>
          <fullName>Root To Crown</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>AD</fullName>
          <default>true</default>
          <label>AD</label>
        </value>
        <value>
          <fullName>AE</fullName>
        </value>
        <value>
          <fullName>AF</fullName>
        </value>
        <value>
          <fullName>AG</fullName>
        </value>
        <value>
          <fullName>AI</fullName>
        </value>
        <value>
          <fullName>AL</fullName>
        </value>
        <value>
          <fullName>AM</fullName>
        </value>
        <value>
          <fullName>AN</fullName>
        </value>
        <value>
          <fullName>AO</fullName>
        </value>
        <value>
          <fullName>AQ</fullName>
        </value>
        <value>
          <fullName>AR</fullName>
        </value>
        <value>
          <fullName>AS</fullName>
        </value>
        <value>
          <fullName>AT</fullName>
        </value>
        <value>
          <fullName>AU</fullName>
        </value>
        <value>
          <fullName>AW</fullName>
        </value>
        <value>
          <fullName>AX</fullName>
        </value>
        <value>
          <fullName>AZ</fullName>
        </value>
        <value>
          <fullName>BA</fullName>
        </value>
        <value>
          <fullName>BB</fullName>
        </value>
        <value>
          <fullName>BD</fullName>
        </value>
        <value>
          <fullName>BE</fullName>
        </value>
        <value>
          <fullName>BF</fullName>
        </value>
        <value>
          <fullName>BG</fullName>
        </value>
        <value>
          <fullName>BH</fullName>
        </value>
        <value>
          <fullName>BI</fullName>
        </value>
        <value>
          <fullName>BJ</fullName>
        </value>
        <value>
          <fullName>BL</fullName>
        </value>
        <value>
          <fullName>BM</fullName>
        </value>
        <value>
          <fullName>BN</fullName>
        </value>
        <value>
          <fullName>BO</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>IsTest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTest</label>
    <type>Checkbox</type>
  </fields>
  <label>Lead &amp; Opportunity Setting</label>
  <pluralLabel>Lead &amp; Opportunity Settings</pluralLabel>
</CustomObject>

unpackaged/objects/Preferred_dealer_item__c.object
<CustomObject>
  <fields>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Preferred_dealer_items1</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>1 OR (2 AND 3)</booleanFilter>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>ERP Distributor, Non-ERP Distributor, DNA Distributor</value>
      </filterItems>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>CIM Account</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Distributor</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealers (Dealer)</relationshipLabel>
    <relationshipName>Preferred_dealer_items</relationshipName>
    <type>Lookup</type>
  </fields>
  <label>Dealer</label>
  <nameField>
    <displayFormat>PDI{00000}</displayFormat>
    <label>Dealer Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Dealers</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/Test_LeadController.cls
/*------------------------------------------------------------	
Author: 		Richard Trum (Glimt) 2019-11-28 	
Description:   	Test class for testing the apex class LeadController
------------------------------------------------------------*/

@IsTest

private class Test_LeadController {

    @IsTest
    private static void initiativeTest(){
        Field_Sales_Project__c initTest = new Field_Sales_Project__c();
		initTest.Title__c ='Testing initiative';
        initTest.AllowUsersToAddNewLeads__c = true;
        initTest.Description__c ='Testing to create an initiative';
        initTest.End_Date__c = Date.today();
        initTest.Start_Date__c = Date.today();
        initTest.Initiative_Type__c = 'Regional Initiative';
        insert initTest;

        Test.startTest();
		System.assertNotEquals(LeadController.getInitiatives(), null);
 
        Test.stopTest();
        
    }
    
    @IsTest
    private static void settingsTest(){
        List<LeadOpportunitySetting__mdt> settings = [SELECT DeveloperName, Country__c, Category__c FROM LeadOpportunitySetting__mdt WHERE IsTest__c =: true];

        Test.startTest();
		System.assertNotEquals(LeadController.getSalesLeadSettings(settings[0].Category__c, settings[0].Country__c), null);
 
        Test.stopTest();
        
    }
    
    @IsTest
    private static void TestGetPreferredDealers(){
        
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<Account> accounts = TestDataFactory.returnAccounts(2, 'CIM_account', userList[0].Id);
        accounts[1].OneAccount_Type__c = 'Distributor';
        accounts[1].Name = 'Distributor';
        insert accounts;
        
        Preferred_dealer_item__c pdi = new Preferred_dealer_item__c();
        pdi.Account__c = accounts[0].Id;
        pdi.Dealer__c = accounts[1].Id;
        insert pdi;
        
        List<Preferred_dealer_item__c> result = LeadController.getPreferredDealers(accounts[0].Id);
        List<Account> dealers = LeadController.getDistributors('Distr', accounts[0].Id, 'Equipment & Imaging');
    }

    @isTest
    private static void searchResultReturnRecords() {
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<Id> fixedResults = new List<Id>();
        List<Account> accounts = TestDataFactory.returnAccounts(1, 'CIM_account', userList[0].Id);
        accounts[0].OneAccount_Type__c = 'Distributor';
        accounts[0].Name = 'Distributor';
        accounts[0].DistributorCategories__c = 'Digital Group';
        insert accounts;
        
        fixedResults.add(accounts[0].Id);
        System.debug(fixedResults);
        Test.setFixedSearchResults(fixedResults);
        List<String> selectedIds = new List<String>();

        List<LookupSearchResult> results = LeadController.search('Distr', selectedIds, 'Equipment & Imaging');

        System.assertEquals(1, results.size());
        System.assertEquals(accounts[0].Id, results.get(0).getId());
    }
    
    @IsTest
    private static void TestRecentlyViewed(){
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<Id> fixedResults = new List<Id>();
        List<Account> accounts = TestDataFactory.returnAccounts(2, 'CIM_account', userList[0].Id);
        accounts[1].OneAccount_Type__c = 'Distributor';
        accounts[1].Name = 'Distributor';
        insert accounts;
        
        Preferred_dealer_item__c pdi = new Preferred_dealer_item__c();
        pdi.Account__c = accounts[0].Id;
        pdi.Dealer__c = accounts[1].Id;
        insert pdi;
        
        List<LookupSearchResult> results = LeadController.getRecentlyViewed(accounts[0].Id, 'Equipment & Imaging');
        
    }

}