unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
  <fields>
    <fullName>AWO_Customer__c</fullName>
    <formula>IF( Account.Atlantis_Web_Order_Customer__c=true,"Yes","No")</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AWO Customer?</label>
    <type>Text</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET</businessProcess>
    <fullName>GET</fullName>
    <label>X DO NOT USE 2t</label>
  </recordTypes>
  <recordTypes>
    <active>true</active>
    <businessProcess>GET Atlantis - D</businessProcess>
    <description>Use this Opportunity Type when creating an Opportunity against an Atlantis GET Account</description>
    <fullName>GET_Lab_Atlantis</fullName>
    <label>GET Lab Atlantis</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/Test_UpdOppStageOnLABGETOpps.cls
@isTest
private class Test_UpdOppStageOnLABGETOpps
{
    static testMethod void testUpdOppStageOnLABGETOpps ()
    {
        // Create a suitable test account.
        Account testAccount = new Account();
        testAccount.Country__c = 'SE';
        testAccount.Name = 'Tcp_TestAccount';
        testAccount.Atlantis_Web_Order_Customer__c = false;     
        insert testAccount;
        
        RecordType rt = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType WHERE RecordType.DeveloperName = 'GET_Lab_Atlantis'];
                
        // Create an open GET Lab Atlantis opportunity on the above account.
        Date CDate = date.newinstance(2010,12,31);
        Opportunity AtlOpp = new Opportunity(Name='Test Atl Op', StageName='Positioning Atlantis', RecordTypeId=rt.Id, AccountID=testAccount.Id, CloseDate=CDate, Amount=555, CurrencyISOCode='SEK' );
        insert AtlOpp;
        
        Account testAcc = [select id from Account where id=:testAccount.Id];
        
        Opportunity testOpp = [select id, AWO_Customer__c, StageName, RecordTypeId, Account.Name from Opportunity where id =:AtlOpp.Id];
        System.debug('2:: Opportunity AWO Customer?' + testOpp.AWO_Customer__c+ testOpp.RecordTypeId + testOpp.StageName + testOpp.Id);
        
        test.startTest();
        
        testAccount.Atlantis_Web_Order_Customer__c = TRUE;
        update testAccount;
        
        test.stopTest();
        
        // Retrieve the opportunity & account.
        testOpp = [select id, AWO_Customer__c, StageName, RecordTypeId, Account.Name from Opportunity where id =:AtlOpp.Id];
        System.debug('3:: Opportunity AWO Customer?' + testOpp.AWO_Customer__c+ testOpp.RecordTypeId + testOpp.StageName + testOpp.Id);
        
        testAcc = [select id from Account where id=:testAccount.Id];
    }
 }