unpackaged/objects/Country__c.object
<CustomObject>
  <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>All Implants</fullName>
          <label>Global DPG</label>
        </value>
        <value>
          <fullName>All Ortho</fullName>
        </value>
        <value>
          <fullName>AFG</fullName>
        </value>
        <value>
          <fullName>AGO</fullName>
        </value>
        <value>
          <fullName>ALB</fullName>
        </value>
        <value>
          <fullName>ARE</fullName>
        </value>
        <value>
          <fullName>ARG</fullName>
        </value>
        <value>
          <fullName>ARM</fullName>
        </value>
        <value>
          <fullName>ATF</fullName>
        </value>
        <value>
          <fullName>AUS</fullName>
        </value>
        <value>
          <fullName>AUT</fullName>
        </value>
        <value>
          <fullName>AZE</fullName>
        </value>
        <value>
          <fullName>BDI</fullName>
        </value>
        <value>
          <fullName>BEL</fullName>
        </value>
        <value>
          <fullName>BEN</fullName>
        </value>
        <value>
          <fullName>BFA</fullName>
        </value>
        <value>
          <fullName>BGD</fullName>
        </value>
        <value>
          <fullName>BGR</fullName>
        </value>
        <value>
          <fullName>BHR</fullName>
        </value>
        <value>
          <fullName>BHS</fullName>
        </value>
        <value>
          <fullName>BIH</fullName>
        </value>
        <value>
          <fullName>BLM</fullName>
        </value>
        <value>
          <fullName>BLR</fullName>
        </value>
        <value>
          <fullName>BLZ</fullName>
        </value>
        <value>
          <fullName>BMU</fullName>
        </value>
        <value>
          <fullName>BOL</fullName>
        </value>
        <value>
          <fullName>BRA</fullName>
        </value>
        <value>
          <fullName>BRB</fullName>
        </value>
        <value>
          <fullName>BRN</fullName>
        </value>
        <value>
          <fullName>BTN</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Countries</label>
  <nameField>
    <label>Country Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Countries</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Lightning_Component__mdt.object
<CustomObject>
  <description>List of available Lightning Components, used in Team Setup</description>
  <fields>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
  </fields>
  <fields>
    <fullName>Managed_by__c</fullName>
    <label>Managed by</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <defaultValue>'In development'</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>In development</fullName>
          <default>true</default>
          <label>In development</label>
        </value>
        <value>
          <fullName>Active</fullName>
        </value>
        <value>
          <fullName>Retired</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Lightning Component</label>
  <pluralLabel>Lightning Components</pluralLabel>
</CustomObject>

unpackaged/objects/MetadataDeployment__e.object
<CustomObject>
  <fields>
    <fullName>DeploymentId__c</fullName>
    <label>DeploymentId</label>
    <length>32</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
  </fields>
  <label>MetadataDeployment</label>
  <pluralLabel>Metadata Deployment</pluralLabel>
</CustomObject>

unpackaged/objects/Team_setup__mdt.object
<CustomObject>
  <fields>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Sweden</fullName>
          <default>true</default>
          <label>Sweden</label>
        </value>
        <value>
          <fullName>UK</fullName>
        </value>
        <value>
          <fullName>Norway</fullName>
        </value>
        <value>
          <fullName>USA</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Active</fullName>
          <default>true</default>
          <label>Active</label>
        </value>
        <value>
          <fullName>Retired</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Team setup</label>
  <pluralLabel>Team setups</pluralLabel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Full_Name__c</fullName>
    <formula>FirstName&amp;" "&amp;LastName</formula>
    <label>Full Name</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Profile__c</fullName>
    <description>used to display profile name when data is extracted by dataloader</description>
    <formula>Profile.Name</formula>
    <label>Profile Name</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Team_Setup_ID__c</fullName>
    <label>Team Setup ID</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/LightningCompSetup.cls
public with sharing class LightningCompSetup {

   @AuraEnabled
    public static List<SObject> loadRelatedRecord(String fullName, String fields) {
        List<String> fullNameParts = fullName.split('\\.');
        List<SObject> records = Database.query('select ' + fields + ' from ' + fullNameParts[0] + '__mdt');      
        if(records.size()==0) {
            throw new AuraHandledException('Record not found');
        }
        records.sort();
        return records;
    }
    
   @AuraEnabled
    public static String upsertCmp(String record, String Descr, String Status, String Manager) {        
        return CustomMetadata.Operations
            .callback(
                MetadataDeployment__e.getSObjectType(),
                MetadataDeployment__e.DeploymentId__c, 
                MetadataDeployment__e.Result__c)
            .enqueueUpsertRecords(
                Lightning_Component__mdt.getSObjectType(),
                
                new List<Map<SObjectField, Object>> {
            
            	// Custom Metadata record
            	new Map<SObjectField, Object> {
                Lightning_Component__mdt.DeveloperName => record,
                Lightning_Component__mdt.Label => record,
                Lightning_Component__mdt.Status__c => Status,
                Lightning_Component__mdt.Description__c => Descr,
                Lightning_Component__mdt.Managed_by__c => Manager    
                   
                    } } )    
            .deployId;
    }
    
       @AuraEnabled
    public static String upsertTeam(String record, String Country, String Descr, String Status) {        
        return CustomMetadata.Operations
            .callback(
                MetadataDeployment__e.getSObjectType(),
                MetadataDeployment__e.DeploymentId__c, 
                MetadataDeployment__e.Result__c)
            .enqueueUpsertRecords(
                Team_setup__mdt.getSObjectType(),
                
                new List<Map<SObjectField, Object>> {
            
            	// Custom Metadata record
            	new Map<SObjectField, Object> {
                Team_setup__mdt.DeveloperName => record,
                Team_setup__mdt.Label => record,
                Team_setup__mdt.Country__c => Country,
                Team_setup__mdt.Description__c => Descr,
                Team_setup__mdt.Status__c => Status    
                    } } )    
            .deployId;
    }
    
    @AuraEnabled
    public static List<String> getPickListValuesIntoList(String CmpName, String fldName){
       List<String> pickListValuesList= new List<String>();
		Schema.SObjectField SObjField = Schema.getGlobalDescribe().get(CmpName).getDescribe().fields.getMap().get(fldName);        
        Schema.DescribeFieldResult fieldResult = SObjField.getDescribe();        
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     
		return pickListValuesList;
    }
    
    @AuraEnabled
    public static List<User> getUserList(String searchStr, String Country, String Team){  
       List<User> rawUserList = new List<User>();
        searchStr = searchStr.replace('*', '%');
        if(searchStr == ''){
            searchStr = '%';            
        }
        if(Country ==''){
            		Country = '%';
            
                    if(Team == '') {
        			Team = '%';        
        			rawUserList = [SELECT Id, FirstName, LastName, Full_Name__c, Profile__c, Team_Setup_ID__c, User_Country__c, IsActive FROM User 
                       WHERE (Full_Name__c LIKE: searchStr) 
                       AND IsActive=true 
                       AND ((User_Country__c LIKE: Country) OR User_Country__c = null) 
                       AND ((Team_Setup_Id__c LIKE: Team) OR (Team_Setup_Id__c = null)) 
                       LIMIT 100];    
        				}
       				else{
                 		rawUserList = [SELECT Id, FirstName, LastName, Full_Name__c, Profile__c, Team_Setup_ID__c, User_Country__c, IsActive FROM User 
                      	WHERE (Full_Name__c LIKE: searchStr) 
                      	AND IsActive=true 
                      	AND ((User_Country__c LIKE: Country) OR User_Country__c = null) 
                      	AND (Team_Setup_Id__c LIKE: Team) 
                      	LIMIT 100];                        
                            }  
        }
        else{
                  if(Team == '') {
        			Team = '%';        
        			rawUserList = [SELECT Id, FirstName, LastName, Full_Name__c, Profile__c, Team_Setup_ID__c, User_Country__c, IsActive FROM User 
                       WHERE (Full_Name__c LIKE: searchStr) 
                       AND IsActive=true 
                       AND (User_Country__c LIKE: Country)
                       AND ((Team_Setup_Id__c LIKE: Team) OR (Team_Setup_Id__c = null)) 
                       LIMIT 100];    
        				}
       				else{
                 		rawUserList = [SELECT Id, FirstName, LastName, Full_Name__c, Profile__c, Team_Setup_ID__c, User_Country__c, IsActive FROM User 
                      	WHERE (Full_Name__c LIKE: searchStr) 
                      	AND IsActive=true 
                      	AND (User_Country__c LIKE: Country) 
                      	AND (Team_Setup_Id__c LIKE: Team) 
                      	LIMIT 100];                        
                            }   
                   
        }
        return rawUserList;        
    }
    
    
    @AuraEnabled
    public static String updateUser(User Usr2Upd, String Team2Upd) {
    	
        Usr2Upd.Team_Setup_Id__c = Team2Upd;
        String result = 'Start';
        try{
            update Usr2Upd;
            result='Updated';
        }
        catch (Exception e){
            String errorMessage = 'Error: ' + e.getMessage() + ' ' + e.getStackTraceString();
            system.debug(errorMessage);
            result='error';
        } 
        
    return result;    
    }
    
   /* @AuraEnabled
    public static String DetectAppName() {
        List<CustomApplication> TestApp = new CustomApplication ();
        TestApp = [SELECT FullName, DeveloperName, Label FROM CustomApplication]
        String result = 'Hej';
        return result;
    }*/
    
    @AuraEnabled
    public static String getCurrentApplication()
    {
        // Get tab set describes for each app
        List<Schema.DescribeTabSetResult> tabSetDesc = Schema.describeTabs();        
        List<UserAppInfo> Test2 = [SELECT UserId, Id, AppDefinitionId FROM UserAppInfo WHERE UserId =: UserInfo.getUserId()];
        String result = '';
        List<AppDefinition> Test = new List<AppDefinition>();
        for(UserAppInfo tsr : Test2) {
            Test = [SELECT Id, DurableId, DeveloperName FROM AppDefinition WHERE DurableId =: tsr.AppDefinitionId];
            result = 'You are now logged into the ' + Test[0].DeveloperName +' app';
        }
        return result;
    }
    
    
    
}