unpackaged/objects/DC_User_Territory_Mapping__c.object
<CustomObject>
  <customSettingsType>List</customSettingsType>
  <fields>
    <fullName>User_Territory_10__c</fullName>
    <label>User Territory 10</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_11__c</fullName>
    <label>User Territory 11</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_17__c</fullName>
    <label>User Territory 17</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_1__c</fullName>
    <label>User Territory 1</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_20__c</fullName>
    <label>User Territory 20</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_24__c</fullName>
    <label>User Territory 24</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_25__c</fullName>
    <label>User Territory 25</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_2__c</fullName>
    <label>User Territory 2</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_3__c</fullName>
    <label>User Territory 3</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_4__c</fullName>
    <label>User Territory 4</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_7__c</fullName>
    <label>User Territory 7</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_9__c</fullName>
    <label>User Territory 9</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <label>DC User Territory Mapping</label>
</CustomObject>

unpackaged/objects/Postal_Codes__c.object
<CustomObject>
  <description>Postal Code Reference for Postal Codes associated with Territories</description>
  <fields>
    <fullName>DC_ETM_Code_Last_Updated__c</fullName>
    <defaultValue>null</defaultValue>
    <label>ETM Code Last Updated</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>Territory_10_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 10 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_Codes4U1g</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_11_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 11 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_CodesntuP</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_17_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 17 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_Codes6</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_1_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 1 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_CodesnsNe</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_20_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 20 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_CodesntvI</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_24_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 24 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_Codes1</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_25_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 25 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_Codes2</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_2_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 2 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_Codes9</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_3_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 3 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_CodesQQkw</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_4_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 4 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_Codes</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_7_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 7 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_CodessafR</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Territory_9_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 9 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_Codes5</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>User_Territory_10__c</fullName>
    <label>User Territory 10</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_11__c</fullName>
    <label>User Territory 11</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_17__c</fullName>
    <label>User Territory 17</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_1__c</fullName>
    <label>User Territory 1</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_20__c</fullName>
    <label>User Territory 20</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_24__c</fullName>
    <label>User Territory 24</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_25__c</fullName>
    <label>User Territory 25</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_2__c</fullName>
    <label>User Territory 2</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_3__c</fullName>
    <label>User Territory 3</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_4__c</fullName>
    <label>User Territory 4</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_7__c</fullName>
    <label>User Territory 7</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_9__c</fullName>
    <label>User Territory 9</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <label>Postal Code</label>
  <nameField>
    <label>Postal Code</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Postal Codes</pluralLabel>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/DC_UT_TestUtils.cls
//Author: Sergey Legostaev (slegostaev@mycervello.com) 
//Created: 8/15/2017
@isTest
public class DC_UT_TestUtils {
    
    public static void createTerritorySettings() {
        DC_User_Territory_Mapping__c territorySettings = new DC_User_Territory_Mapping__c();
        system.assert(territorySettings != null, 'DC_User_Territory_Mapping__c should not be null');
        territorySettings.Name = DC_TerritorySettings.TERRITORY_SETTINGS_NAME;
        territorySettings.User_Territory_1__c = 'Territory_1_User__c';
        territorySettings.User_Territory_2__c = 'Territory_2_User__c';
        territorySettings.User_Territory_3__c = 'Territory_3_User__c';
        territorySettings.User_Territory_4__c = 'Territory_4_User__c';
        territorySettings.User_Territory_7__c = 'Territory_7_User__c';
        territorySettings.User_Territory_9__c = 'Territory_9_User__c';
        territorySettings.User_Territory_10__c = 'Territory_10_User__c';
        territorySettings.User_Territory_11__c = 'Territory_11_User__c';
        territorySettings.User_Territory_17__c = 'Territory_17_User__c';
        territorySettings.User_Territory_20__c = 'Territory_20_User__c';
        territorySettings.User_Territory_24__c = 'Territory_24_User__c';
        territorySettings.User_Territory_25__c = 'Territory_25_User__c';
        insert territorySettings;
    }
    
    public static Account createAccount() {
        Account acc = new Account(Name = 'test account');
        acc.BillingPostalCode = '02110';
        insert acc;
        return acc;
    }
    
    public static Postal_Codes__c createPostalCodes() {
        Postal_Codes__c postalCodes = new Postal_Codes__c(Name = '02110',DC_ETM_Code_Last_Updated__c = DateTime.newInstance(2017, 01, 01));
        insert postalCodes;
        return postalCodes;
    }
}