unpackaged/objects/EADashboardByCountryCS__mdt.object
<CustomObject>
  <fields>
    <fullName>CountryCode__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>AD</fullName>
        </value>
        <value>
          <fullName>AE</fullName>
        </value>
        <value>
          <fullName>AF</fullName>
        </value>
        <value>
          <fullName>AG</fullName>
        </value>
        <value>
          <fullName>AI</fullName>
        </value>
        <value>
          <fullName>AL</fullName>
        </value>
        <value>
          <fullName>AM</fullName>
        </value>
        <value>
          <fullName>AN</fullName>
        </value>
        <value>
          <fullName>AO</fullName>
        </value>
        <value>
          <fullName>AQ</fullName>
        </value>
        <value>
          <fullName>AR</fullName>
        </value>
        <value>
          <fullName>AS</fullName>
        </value>
        <value>
          <fullName>AT</fullName>
        </value>
        <value>
          <fullName>AU</fullName>
        </value>
        <value>
          <fullName>AW</fullName>
        </value>
        <value>
          <fullName>AX</fullName>
        </value>
        <value>
          <fullName>AZ</fullName>
        </value>
        <value>
          <fullName>BA</fullName>
        </value>
        <value>
          <fullName>BB</fullName>
        </value>
        <value>
          <fullName>BD</fullName>
        </value>
        <value>
          <fullName>BE</fullName>
        </value>
        <value>
          <fullName>BF</fullName>
        </value>
        <value>
          <fullName>BG</fullName>
        </value>
        <value>
          <fullName>BH</fullName>
        </value>
        <value>
          <fullName>BI</fullName>
        </value>
        <value>
          <fullName>BJ</fullName>
        </value>
        <value>
          <fullName>BL</fullName>
        </value>
        <value>
          <fullName>BM</fullName>
        </value>
        <value>
          <fullName>BN</fullName>
        </value>
        <value>
          <fullName>BO</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>CountryFullName__c</fullName>
    <label>Country Full Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>Belgium</fullName>
        </value>
        <value>
          <fullName>BEX</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>Canada</fullName>
        </value>
        <value>
          <fullName>Default</fullName>
          <default>true</default>
          <label>Default</label>
        </value>
        <value>
          <fullName>Denmark</fullName>
        </value>
        <value>
          <fullName>Distributor</fullName>
        </value>
        <value>
          <fullName>Egypt</fullName>
        </value>
        <value>
          <fullName>Estonia</fullName>
        </value>
        <value>
          <fullName>Faroe Islands</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Greenland</fullName>
        </value>
        <value>
          <fullName>Holland</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ: DE</fullName>
        </value>
        <value>
          <fullName>HQ: NL</fullName>
        </value>
        <value>
          <fullName>HQ: SE</fullName>
        </value>
        <value>
          <fullName>Iceland</fullName>
        </value>
        <value>
          <fullName>INDIA</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Ireland</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Jordan</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>EA Dashboard By Country</label>
  <pluralLabel>EADashboardByCountryCS</pluralLabel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/EaDashboardCountryBased_CC.cls
public class EaDashboardCountryBased_CC {
    
    @AuraEnabled
    public static EADashboardByCountryCS__mdt getHomeDashboardName(String fieldName, String filterFieldName) {
        try {
            User currentUser = GlobalUtils.getCurrentUser();
            String query = 'Select Id, ' + fieldName + ',' + filterFieldName + ' FROM EADashboardByCountryCS__mdt ' + 
                ' Where CountryCode__c = \'' + currentUser.User_Country__c + '\' LIMIT 1';
            List<EADashboardByCountryCS__mdt> eADashboardByCountryCSList = Database.query(query);
            if(eADashboardByCountryCSList.size() > 0) {
                return eADashboardByCountryCSList.get(0);
            }
            query = 'Select Id, ' + fieldName + ',' + filterFieldName + ' FROM EADashboardByCountryCS__mdt ' + 
                ' Where CountryFullName__c = \'' + currentUser.User_Country__c + '\' LIMIT 1';
            eADashboardByCountryCSList = Database.query(query);
            if(eADashboardByCountryCSList.size() > 0) {
                return eADashboardByCountryCSList.get(0);
            }
            query = 'Select Id, ' + fieldName + ',' + filterFieldName + ' FROM EADashboardByCountryCS__mdt ' + 
                'Where CountryCode__c =\'Default\' LIMIT 1';
            eADashboardByCountryCSList = Database.query(query);
            if(eADashboardByCountryCSList.size() > 0) {
                return eADashboardByCountryCSList.get(0);
            }
            query = 'Select Id, ' + fieldName + ',' + filterFieldName + ' FROM EADashboardByCountryCS__mdt ' + 
                'Where CountryFullName__c =\'Default\' LIMIT 1';
            return Database.query(query);
        } catch(Exception e){
            DebugLog.addException(e, e.getMessage());
            return null;
        } 
    }
    @AuraEnabled
    public static EADashboardByCountryCS__mdt getSObjectDashboardName(String fieldName, String filterFieldName, ID recordId, String sObjectFieldName) {
        try {
            String sObjectName = recordId.getSObjectType().getDescribe().getName();
            
            
            String sObjQuery = 'Select Id, '+ sObjectFieldName + 
                ' FROM ' + sObjectName + 
                ' Where Id =\'' + recordId + '\' LIMIT 1'; 
            Sobject sObj = Database.query(sObjQuery);
            
            string whereCountry = null;
            List<String> splitedSObjectFieldName = sObjectFieldName.split('\\.');
            if(splitedSObjectFieldName.size() == 1){
                whereCountry = (String) sObj.get(sObjectFieldName);
            } else{

                sObject sb  = sObj;
                for(integer i=0;i<splitedSObjectFieldName.size()-1;i++){
                    sb=sb.getSobject(splitedSObjectFieldName.get(i));   
                }
                whereCountry = string.valueof(sb.get(splitedSObjectFieldName[splitedSObjectFieldName.size()-1]));
            }
            String query = 'Select Id, ' + fieldName + ',' + filterFieldName + ' FROM EADashboardByCountryCS__mdt ' + 
                'Where CountryCode__c  = \'' + whereCountry + '\' LIMIT 1';
            List<EADashboardByCountryCS__mdt> eADashboardByCountryCSList = Database.query(query);
            if(eADashboardByCountryCSList.size() > 0) {
                return getDashbord(eADashboardByCountryCSList, filterFieldName, sObjectName, recordId);
            }
            query = 'Select Id, ' + fieldName + ',' + filterFieldName + ' FROM EADashboardByCountryCS__mdt ' + 
                'Where CountryFullName__c  = \'' + whereCountry + '\' LIMIT 1';
            eADashboardByCountryCSList = Database.query(query);
            if(eADashboardByCountryCSList.size() > 0) {
                return getDashbord(eADashboardByCountryCSList, filterFieldName, sObjectName, recordId);
            }
            query = 'Select Id, ' + fieldName + ',' + filterFieldName + ' FROM EADashboardByCountryCS__mdt ' + 
                'Where CountryFullName__c =\'Default\' LIMIT 1';
            eADashboardByCountryCSList = Database.query(query);
            if(eADashboardByCountryCSList.size() > 0) {
                return getDashbord(eADashboardByCountryCSList, filterFieldName, sObjectName, recordId);
            }
            query = 'Select Id, ' + fieldName + ',' + filterFieldName + ' FROM EADashboardByCountryCS__mdt ' + 
                'Where CountryCode__c =\'Default\' LIMIT 1';
            return Database.query(query);
        } catch(Exception e){
            DebugLog.addException(e, e.getMessage());
            return null;
        } 
    }
    public static EADashboardByCountryCS__mdt getDashbord(List<EADashboardByCountryCS__mdt> dashboardData, string filterFieldName, string sObjectName, ID recordId) { 
        string filterString =(string) dashboardData.get(0).get(filterFieldName);//AccountPlanFilters__c
        List<String> splitedFilterAPINameList =  filterString.split('#'); //second position contains filterAI name field API
        if(splitedFilterAPINameList.get(1) <> 'recordId'){
            String sObjFilterQuery = 'Select Id, '+ splitedFilterAPINameList.get(1) + 
                ' FROM ' + sObjectName + 
                ' Where Id =\'' + recordId + '\' LIMIT 1'; 
            Sobject sObjFilter = Database.query(sObjFilterQuery);
            String filterFieldIdValue = (String) sObjFilter.get(splitedFilterAPINameList.get(1));
            dashboardData.get(0).put(filterFieldName, filterString.replace('#' + splitedFilterAPINameList.get(1) + '#',filterFieldIdValue));
        }
        return dashboardData.get(0); 
    }
}