unpackaged/objects/Encore_Configuration__mdt.object
<CustomObject>
  <description>Configuration data for Encore</description>
  <fields>
    <fullName>Encore_configuration_value__c</fullName>
    <label>Encore configuration value</label>
    <length>2000</length>
    <type>LongTextArea</type>
  </fields>
  <label>Encore Configuration</label>
  <pluralLabel>Encore Configurations</pluralLabel>
</CustomObject>

unpackaged/classes/EncoreConfiguration.cls
public class EncoreConfiguration {
    
    public static String getWebApiEndpoint()
    {

        Encore_Configuration__mdt[] encoreConfiguration = 
            [SELECT Encore_configuration_value__c FROM Encore_Configuration__mdt WHERE DeveloperName = 'WebAPI_Endpoint'];
       
        if ( encoreConfiguration.size() > 0 )
        {
            System.debug('WebAPI_EndPoint=' + encoreConfiguration[0].Encore_configuration_value__c );

            return encoreConfiguration[0].Encore_configuration_value__c;
        }
        else
        {
            System.debug('getWebApiEndpoint() was unable to get the WebAPI_EndPoint');
            throw new RequiredInfoException();
        }
               
    }
    
}