unpackaged/objects/Integration_Progress__c.object
<CustomObject>
  <fields>
    <fullName>Estimated_Finished_Date__c</fullName>
    <label>Estimated Finished Date</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>Estimated_Start_Date__c</fullName>
    <label>Estimated Start Date</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>EMEA</fullName>
        </value>
        <value>
          <fullName>US</fullName>
        </value>
        <value>
          <fullName>AU</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>GDW Integration</fullName>
        </value>
        <value>
          <fullName>Azure Calculation</fullName>
        </value>
        <value>
          <fullName>Einstein Analytics</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Integration Progress</label>
  <nameField>
    <label>Integration Progress Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Integration Progresses</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Integration_Progress_Setting__mdt.object
<CustomObject>
  <fields>
    <fullName>Estimated_Finished_Date__c</fullName>
    <label>Estimated Finished Date</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>Estimated_Start_Date__c</fullName>
    <label>Estimated Start Date</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>EMEA</fullName>
          <default>true</default>
          <label>EMEA</label>
        </value>
        <value>
          <fullName>US</fullName>
        </value>
        <value>
          <fullName>AU</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>GDW Integration</fullName>
          <default>true</default>
          <label>GDW Integration</label>
        </value>
        <value>
          <fullName>Azure Calculation</fullName>
        </value>
        <value>
          <fullName>Einstein Analytics</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <label>Integration Progress Setting</label>
  <pluralLabel>Integration Progress Settings</pluralLabel>
</CustomObject>

unpackaged/classes/scheduledIntegrationProgress.cls
global class scheduledIntegrationProgress implements Schedulable {
   global void execute(SchedulableContext SC) {

       createIntegrationProgressRecord('GDW Integration','EMEA');
       createIntegrationProgressRecord('Azure Calculation','EMEA');
       createIntegrationProgressRecord('Einstein Analytics','EMEA');

       createIntegrationProgressRecord('GDW Integration','US');
       createIntegrationProgressRecord('Azure Calculation','US');
       createIntegrationProgressRecord('Einstein Analytics','US');
    
       createIntegrationProgressRecord('GDW Integration','AU');
       createIntegrationProgressRecord('Azure Calculation','AU');
       createIntegrationProgressRecord('Einstein Analytics','AU');
   }

    private void createIntegrationProgressRecord(string step, string source) {
        Integration_Progress__c ip = new Integration_Progress__c();

        ip.Step__c = step;
        ip.Status__c = 'PENDING';
        ip.Source__c = source;
        ip.Estimated_Start_Date__c = Datetime.newInstance(Date.today(), Datetime.valueOf([SELECT Estimated_Start_Date__c FROM Integration_Progress_Setting__mdt WHERE Step__c = :step AND source__c = :source].Estimated_Start_Date__c).time());
        ip.Estimated_Finished_Date__c = Datetime.newInstance(Date.today(), Datetime.valueOf([SELECT Estimated_Finished_Date__c FROM Integration_Progress_Setting__mdt WHERE Step__c = :step AND source__c = :source].Estimated_Finished_Date__c).time());
        ip.External_Id__c = [SELECT Label FROM Integration_Progress_Setting__mdt WHERE Step__c = :step AND source__c = :source].Label + '-' + Datetime.now().format('yyyy-MM-dd');
        insert ip;
    }
}