unpackaged/objects/LoyaltyProgramParticipant__c.object
<CustomObject>
  <fields>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Random string generated on insert. Used as external id to be sent out via email to customers to not expose the real Salesforce Id.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
  </fields>
  <label>Account Program Member</label>
  <nameField>
    <displayFormat>LPP-{0000}</displayFormat>
    <label>Account Program Member Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Account Program Members</pluralLabel>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/LoyaltyProgramParticipantTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Kevin Ruibin Do (Salesforce) 20200903
Description:    LoyaltyProgramParticipant__c Trigger Helper Class
History 
20200903        Kevin Ruibin Do - Created LoyaltyProgramParticipantTriggerHelper
20200903        Kevin Ruibin Do - Created Class
--------------------------------------------------------------------------------------------------------*/

/**
 * Author: Kevin Ruibin Do
 * Description: Generates random string and assigns that to ExternalId__c
 */
public with sharing class LoyaltyProgramParticipantTriggerHelper {
    public static void setExternalId(List<LoyaltyProgramParticipant__c> newLoyaltyProgramParticipantList) {
        for(LoyaltyProgramParticipant__c lPParticipant : newLoyaltyProgramParticipantList) {
            Blob b = Crypto.GenerateAESKey(128);
            String h = EncodingUtil.ConvertTohex(b);
            String guid = h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
            lPParticipant.ExternalId__c = guid;
        }
    }
}