unpackaged/objects/Offer_Code__c.object
<CustomObject>
  <description>Used by DNA Inside/Telesales Teams to associate Promotional Codes with Tasks and Campaigns</description>
  <label>Offer Code</label>
  <nameField>
    <label>Offer Code Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Offer Codes</pluralLabel>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/OrderItem.object
<CustomObject>
  <fields>
    <fullName>Article_Number__c</fullName>
    <formula>PricebookEntry.Product2.Article__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Article Number</label>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
  </fields>
  <fields>
    <fullName>Offer_Code_dna__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer Code</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>Offer_Code__c.Offer_Code_Status__c</field>
        <operation>notEqual</operation>
        <value>Expired</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Offer_Code__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Total_Line_Item_Price__c</fullName>
    <formula>Quantity * UnitPrice *(1- Discount_Percent__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Line Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
</CustomObject>

unpackaged/classes/Order_PDF_USC_TeleSales_extension.cls
public class Order_PDF_USC_TeleSales_extension {
    public Id oId; 
    public list<OrderItem> freeprod{get;set;}  
    public list<OrderItem> payprod{get;set;}  
    public Order_PDF_USC_TeleSales_extension(ApexPages.StandardController Controller) {
        oId = System.currentPageReference().getParameters().get('id');
        freeprod = [SELECT Id,Article_Number__c,Quantity,PriceBookEntry.Product2.Name,Offer_Code_dna__r.Name,UnitPrice,Total_Line_Item_Price__c,Order.CurrencyIsoCode  FROM OrderItem WHERE OrderId = : oId and Discount_Percent__c =100 ];
        payprod =  [SELECT Id,Article_Number__c,Quantity,PriceBookEntry.Product2.Name,Offer_Code_dna__r.Name,UnitPrice,Total_Line_Item_Price__c,Order.CurrencyIsoCode  FROM OrderItem WHERE OrderId = : oId and Discount_Percent__c !=100];
        system.debug(oId);
        system.debug(payprod);
        system.debug(freeprod);
    }
}