unpackaged/objects/Opportunity.object
<CustomObject>
  <fields>
    <fullName>Est_ATL_Sales_CY__c</fullName>
    <description>This field shows the Est Atlantis Sales CY for the Account associated with this Opportunity. The field is taken from the Account record and can therefore only by changed on the Account record.</description>
    <formula>IF ( $RecordType.Name ='GROW Lab Atlantis', Amount ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field shows the Est Atlantis Sales CY for the Account associated with this Opportunity. The field is taken from the Account record and can therefore only by changed on the Account record.</inlineHelpText>
    <label>Est ATL Sales CY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <fields>
    <fullName>Est_Sales_CY__c</fullName>
    <description>Shows the Est Sales CY added manually on the Opp by the sales rep. Formerly showed data originating form the Account - formula saved below:  IF ( OR($RecordType.Name ='GROW Restorative', $RecordType.Name ='GROW Surgical'), Amount ,0)</description>
    <formula>Est_Sales_CY_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Est Sales CY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <businessProcess>GROW Atlantis - D</businessProcess>
    <description>Use this Opportunity Type when creating an Opportunity aiming for GROWing an Altantis Lab Account.</description>
    <fullName>GROW_Lab_Atlantis</fullName>
    <label>GROW Lab Atlantis</label>
  </recordTypes>
  <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/Test_PushAmountToOpportunities.cls
@isTest
private class Test_PushAmountToOpportunities
{
    static testMethod void testPushAmountToOpportunities ()
    { 
        // Create account and related opp with record type GROW Lab Atlantis.
        Account AtlAcc = new Account(Name='Test Atl Acc', Est_ATL_Sales_CY__c=99, Est_Sales_CY__c=321);
        insert AtlAcc;
        
        Date CDate = date.newinstance(date.today().year(), 12, 31);
        
        // If we're past the cutoff date, create the opp for next year.
        Date cutOffDate = date.newinstance(date.today().year(), 12, 31); // <- MICHAEL CHANGE HERE!
        if (date.today() > cutOffDate)
            CDate = CDate.addYears(1);
        
        RecordType rtGrowLabAtlantis = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType WHERE RecordType.DeveloperName = 'GROW_Lab_Atlantis'];

        Opportunity AtlOpp = new Opportunity(
            Name='Test Atl Op',
            StageName='In Progress', 
            RecordTypeId=rtGrowLabAtlantis.Id,
            Amount=9999, 
            CurrencyISOCode='SEK',
            CloseDate=CDate,
            AccountID=AtlAcc.Id);
        
        insert AtlOpp;
        
        AtlAcc.Est_ATL_Sales_CY__c = 1234;
        update AtlAcc;      
        
        //Retrieve the opportunity - should now be updated.
        Opportunity checkOpp = [select id, Amount from opportunity where id=:AtlOpp.id];
        
        /*RecordType rtGrowSurgical = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType WHERE RecordType.DeveloperName = 'GROW_Surgical'];

        //Now test that "Est Sales CY" in sync with "Amount" on OPEN Opportunities with Record Type "GROW Surgical" or "GROW Restorative". 
        Opportunity GrowSurgicalOpp = new Opportunity(
            Name='Test Atl Op',
            StageName='In Progress', 
            RecordTypeId=rtGrowSurgical.Id,
            Amount=9999, 
            CurrencyISOCode='SEK',
            CloseDate=CDate,
            AccountID=AtlAcc.Id);
        
        insert GrowSurgicalOpp ;
        
        AtlAcc.Est_Sales_CY__c = 1234;
        update AtlAcc;
        
        test.stopTest();
        
        checkOpp = [select id, Amount from opportunity where id=:GrowSurgicalOpp.id];*/
    }
}