unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Note_for_canceled_orders__c</fullName>
    <label>Note for canceled orders</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/OrderStageGuidance__mdt.object
<CustomObject>
  <description>Used to configure stage guidance for the OrderPathCmp shown for Orders in Lightning.</description>
  <fields>
    <fullName>KeyFieldsReadOnly__c</fullName>
    <description>Fields that are required to submit for approval, but read only in the Key Fields section. Can be left blank.</description>
    <label>Key Fields (ReadOnly)</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>KeyFieldsTitle__c</fullName>
    <defaultValue>"Key Fields"</defaultValue>
    <description>Displayed directly to the user.</description>
    <label>Key Fields Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>KeyFields__c</fullName>
    <description>List of key fields that are required to submit the order for approval. Example: ["Order_Source__c","Distributor__c","ShippingAddress"]</description>
    <label>Key Fields</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>OrderStatus__c</fullName>
    <description>This is used to provide the right guidance depending on the Order.Status field.</description>
    <label>Order Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Created</fullName>
          <default>true</default>
          <label>Created</label>
        </value>
        <value>
          <fullName>Submitted</fullName>
        </value>
        <value>
          <fullName>Processing</fullName>
        </value>
        <value>
          <fullName>Activated</fullName>
        </value>
        <value>
          <fullName>Rejected</fullName>
        </value>
        <value>
          <fullName>ON HOLD</fullName>
          <isActive>false</isActive>
          <label>ON HOLD</label>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Pricebook2Id__c</fullName>
    <description>Used to query the right guidance depending on Order.Pricebook2Id. If left blank, this record becomes the default global configuration.</description>
    <label>Price Book</label>
    <length>18</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>StageGuidanceTitle__c</fullName>
    <defaultValue>"Stage Guidance"</defaultValue>
    <description>Displayed directly to the user. Title of the Stage Guidance section.</description>
    <label>Stage Guidance Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>StageGuidance__c</fullName>
    <description>Displayed directly to the user. This is the guidance text shown in the Stage Guidance section.</description>
    <label>Stage Guidance</label>
    <length>32768</length>
    <type>LongTextArea</type>
  </fields>
  <label>Order Stage Guidance</label>
  <pluralLabel>Order Stage Guidance</pluralLabel>
</CustomObject>

unpackaged/classes/OrderPath_CC.cls
public without sharing class OrderPath_CC {

    @AuraEnabled
    public static boolean checkCancelOrderPermission(){
        try {
            return FeatureManagement.checkPermission('Order_Management_2_0_Cancel_Order');
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string getStageGuidance(String orderId) {
        try {
            Order currentOrder = [SELECT Pricebook2Id, RecordType.DeveloperName, Status FROM ORDER WHERE Id = :orderId LIMIT 1];
            List<OrderStageGuidance__mdt> guidanceSettingList = [
                SELECT StageGuidance__c, StageGuidanceTitle__c, KeyFields__c, KeyFieldsReadOnly__c, KeyFieldsTitle__c, PriceBook2Id__c
                FROM OrderStageGuidance__mdt
                WHERE 
                    (PriceBook2Id__c = :currentOrder.Pricebook2Id OR PriceBook2Id__c = null)
                    AND OrderStatus__c = :currentOrder.Status
                ORDER BY PriceBook2Id__c NULLS LAST
            ];

            if (!guidanceSettingList.isEmpty()) {
                return JSON.serialize(guidanceSettingList?.get(0));
            } else {
                return null;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string submitForApproval(String orderId, String comment) {
        try {
            Approval.ProcessSubmitRequest approvalRequest = new Approval.ProcessSubmitRequest();
            approvalRequest.setComments(comment);
            approvalRequest.setObjectId(orderId);
            approvalRequest.setSubmitterId(UserInfo.getUserId());
            Approval.ProcessResult result = Approval.process(approvalRequest);
            return JSON.serialize(result.isSuccess());
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string orderCancel(String orderId, String comment){
        try {
            Order orderToCancel = [SELECT Id, Status, Note_for_canceled_orders__c FROM Order WHERE Id = :orderId];
            orderToCancel.Status = 'Rejected';
            orderToCancel.Note_for_canceled_orders__c = comment;
            update orderToCancel;
            return 'SUCCESS';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}