unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
        <field>$Source.AccountId</field>
        <operation>equals</operation>
        <valueField>Preferred_dealer_item__c.Account__r.Id</valueField>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Preferred_dealer_item__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
      <active>false</active>
      <booleanFilter>(1 OR 2 OR 3)</booleanFilter>
      <filterItems>
        <field>Account.RecordType.Id</field>
        <operation>equals</operation>
        <value>01220000000ckje</value>
      </filterItems>
      <filterItems>
        <field>Account.RecordType.Id</field>
        <operation>equals</operation>
        <value>01220000000ckja</value>
      </filterItems>
      <filterItems>
        <field>Account.Name</field>
        <operation>equals</operation>
        <value>4PL Indonesia email delivery test</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Distributor)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <recordTypes>
    <active>true</active>
    <fullName>Free_Good_Order</fullName>
    <label>Free Good Order</label>
  </recordTypes>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Preferred_dealer_item__c.object
<CustomObject>
  <fields>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
      <active>true</active>
      <booleanFilter>1 OR (2 AND 3)</booleanFilter>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>ERP Distributor, Non-ERP Distributor, DNA Distributor</value>
      </filterItems>
      <filterItems>
        <field>Account.RecordTypeId</field>
        <operation>equals</operation>
        <value>CIM Account</value>
      </filterItems>
      <filterItems>
        <field>Account.OneAccount_Type__c</field>
        <operation>equals</operation>
        <value>Distributor</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealers (Dealer)</relationshipLabel>
    <relationshipName>Preferred_dealer_items</relationshipName>
    <type>Lookup</type>
  </fields>
  <label>Dealer</label>
  <nameField>
    <displayFormat>PDI{00000}</displayFormat>
    <label>Dealer Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Dealers</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/Test_OrderDealer_CC.cls
/*------------------------------------------------------------
Author:         Ahmed LOUDRASSI (Salesforce) 2020-03-23
Description:    Test Class for all Order_Dealer_CC methods.
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/

@isTest(seeAllData=false)
public class Test_OrderDealer_CC {

    /*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
    }
    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();

        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }
    
    @isTest
    public static void testSaveDealers() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts = TestDataFactory.returnAccounts(2, 'CIM_Account', testUser.Id);
        for(Account account : accounts) {
            account.OneAccount_Type__c = 'Distributor';
        }
        insert accounts;
        List<Id> dealerIds = new List<Id>();
        for (Account account : accounts) {
            dealerIds.add(account.Id);
        }
        List<Order> orders = TestDataFactory.createOrders(1, 'Free_Good_Order', accounts);
        Test.startTest();
        List<Preferred_dealer_item__c> preferredDealers = OrderDealer_CC.saveDealers(dealerIds, orders.get(0).Id);
        List<Preferred_dealer_item__c> preferredDealers1 = OrderDealer_CC.saveDealers(dealerIds, orders.get(0).Id);
        Test.stopTest();
        System.assertEquals(2, preferredDealers.size());
        System.assertEquals(2, OrderDealer_CC.getDealers(orders.get(0).Id).size());
    }

    @isTest
    public static void testSearch() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts = TestDataFactory.returnAccounts(2, 'CIM_Account', testUser.Id);
        for (Account account : accounts) {
            account.OneAccount_Type__c = 'Distributor';
        }
        insert accounts;
        List<Id> fixedSearchResults = new List<Id>();
        for (Account account : accounts) {
            fixedSearchResults.add(account.Id);
        }
        Test.setFixedSearchResults(fixedSearchResults);
        System.assertEquals(2, OrderDealer_CC.search('Test', new List<String>()).size());
    }

    @isTest
    public static void testUpdateDealerInfo() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Account> accounts = TestDataFactory.returnAccounts(2, 'CIM_Account', testUser.Id);
        for(Account account : accounts) {
            account.OneAccount_Type__c = 'Distributor';
        }
        insert accounts;
        List<Order> orders = TestDataFactory.createOrders(1, 'Free_Good_Order', accounts);
        List<Preferred_dealer_item__c> dealers = TestDataFactory.createpreferredDealers(1, accounts, orders);
        Test.startTest();
        String orderNumber1 = OrderDealer_CC.updateDealerInfo(dealers.get(0).Id, orders.get(0).Id);
        Test.stopTest();
        Order order = [SELECT id, Dealer__c, Distributor__c FROM Order WHERE OrderNumber =:orderNumber1];
        system.assertEquals(dealers.get(0).Id, order.Dealer__c);
    }
}