unpackaged/objects/Order.object
<CustomObject>
  <fields>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
      <active>false</active>
      <booleanFilter>(1 OR 2 OR 3)</booleanFilter>
      <filterItems>
        <field>Account.RecordType.Id</field>
        <operation>equals</operation>
        <value>01220000000ckje</value>
      </filterItems>
      <filterItems>
        <field>Account.RecordType.Id</field>
        <operation>equals</operation>
        <value>01220000000ckja</value>
      </filterItems>
      <filterItems>
        <field>Account.Name</field>
        <operation>equals</operation>
        <value>4PL Indonesia email delivery test</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Distributor)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Order_Amount_global__c</fullName>
    <formula>(Order_amount_before_disc_globa__c + Order_bundle_amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
  </fields>
  <fields>
    <fullName>Order_Type__c</fullName>
    <description>Order Type for DNA</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Free Goods Order</fullName>
        </value>
        <value>
          <fullName>Prosthetics</fullName>
        </value>
        <value>
          <fullName>Telesales</fullName>
        </value>
        <value>
          <fullName>Implants</fullName>
        </value>
        <value>
          <fullName>Discount on Demand</fullName>
        </value>
        <value>
          <fullName>PREP</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/DC_OrderDAO.cls
//Author: Sergey Legostaev
//Date: 04/20/2017
public with sharing class DC_OrderDAO {
	
    public static List<Order> getOrdersByAccountId(String accountId) {
        return [select Id, Name, OrderNumber, Status, EffectiveDate, Order_Type__c,
                 Order_Amount_global__c, Distributor__c, Distributor__r.Name from Order where AccountId = :accountId 
               order by EffectiveDate desc];
    }
}