unpackaged/objects/Postal_Codes__c.object
<CustomObject>
  <description>Postal Code Reference for Postal Codes associated with Territories</description>
  <fields>
    <fullName>Territory_6_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory 6 User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_Codes10qK</relationshipName>
    <type>Lookup</type>
  </fields>
  <label>Postal Code</label>
  <nameField>
    <label>Postal Code</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Postal Codes</pluralLabel>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Movex_Uer_ID__c</fullName>
    <label>ERP User ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/DC_PostalCodeProcessingTest.cls
@isTest
public class DC_PostalCodeProcessingTest {
    
    static TestMethod void runTest()
    {        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@dentsplysirona.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@dentsplysirona.com',
                          Movex_Uer_ID__c = 'C202');
        insert u;   
        DC_UT_TestUtils.createTerritorySettings();
        DC_TerritorySettings.resetSettings();
        Postal_Codes__c pc = new Postal_Codes__c(Name = 'TEST', Territory_6_User__c = u.Id);
        insert pc;
        
        Account a = new Account(Name='TestAccount', Postal_Code_Info__c = pc.Id, BillingPostalCode = 'TEST1');
        insert a;
        
        DC_PostalCodeProcessingController contr = new DC_PostalCodeProcessingController();
        contr.startJob();
        
        DC_PostalCodeProcessingController contr2 = new DC_PostalCodeProcessingController();
        
        a.BillingPostalCode = 'TEST';
        update a;
        
        a.Postal_Code_Info__c = null;
        update a;
        
    }
}