unpackaged/objects/Postal_Codes__c.object
<CustomObject>
  <description>Postal Code Reference for Postal Codes associated with Territories</description>
  <fields>
    <fullName>DC_ETM_Code_Last_Updated__c</fullName>
    <defaultValue>null</defaultValue>
    <label>ETM Code Last Updated</label>
    <type>DateTime</type>
  </fields>
  <fields>
    <fullName>DC_ETM_Code__c</fullName>
    <label>ETM Code</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Territory_1__c</fullName>
    <label>User Territory 1</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <label>Postal Code</label>
  <nameField>
    <label>Postal Code</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Postal Codes</pluralLabel>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Movex_Uer_ID__c</fullName>
    <label>ERP User ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/DC_UT_PostalCodeProcessingBatch.cls
//Author: Sergey Legostaev (slegostaev@mycervello.com) 
//Created: 8/17/2017
@isTest
public class DC_UT_PostalCodeProcessingBatch {
	
    private static Postal_Codes__c pc;
    
    private static void beforeTest() {
        DC_UT_TestUtils.createTerritorySettings();
        DC_TerritorySettings.resetSettings();
        
        final String currentUserId = System.UserInfo.getUserId();
        User currentUser = [select id, Movex_Uer_ID__c from User where Id = :currentUserId];
        currentUser.Movex_Uer_ID__c = 'TST';
        update currentUser;
        
        pc = DC_UT_TestUtils.createPostalCodes();
        pc.User_Territory_1__c = currentUser.Movex_Uer_ID__c;
        update pc;    
    }
    
    private static testMethod void initPostalCodesEtm() {
		beforeTest();
        Test.startTest();
        Database.executeBatch(new DC_PostalCodeProcessingBatch());
        Test.stopTest();
        
        pc = [select DC_ETM_Code__c, DC_ETM_Code_Last_Updated__c from Postal_Codes__c where id =:pc.Id];
        system.debug(pc);
    }
}