unpackaged/objects/Program__c.object
<CustomObject>
  <description>USed to track DentsplySirona and other well known programs/memberships available</description>
  <label>Program</label>
  <nameField>
    <label>Program Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Programs</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Program_Participation__c.object
<CustomObject>
  <description>Used to track the program participation of a contact</description>
  <fields>
    <fullName>Participation_Type__c</fullName>
    <label>Participation Type</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetDefinition>
        <value>
          <fullName>Member</fullName>
          <default>true</default>
          <label>Member</label>
        </value>
        <value>
          <fullName>Board Member</fullName>
        </value>
        <value>
          <fullName>Chair/Leader</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Add the program this Contact is a member of</inlineHelpText>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Participations</relationshipLabel>
    <relationshipName>Program_Participations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>SBU__c</fullName>
    <inlineHelpText>Add if the expert program participation is for a specific SBU</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>SBU_Full_Names</valueSetName>
    </valueSet>
  </fields>
  <label>Program Participation</label>
  <nameField>
    <label>Program Participation Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Program Participations</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ProgramParticipationTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Ahmed LOUDRASSI (Salesforce) 20191127
Description:    Expert  Trigger Handler Class
History
20191023   Ahmed LOUDRASSI   Migrated   setProgramParticipationName trigger. (#)
----------------------------------------------------------------------------------------*/
public class ProgramParticipationTriggerHelper {
    
	public static void setProgramParticipationName(List<Program_Participation__c> newProgramParticipationList) {
        List<Program_Participation__c> programParticipationsToUpdateList = new List<Program_Participation__c>();
        List<ID> programParticipationsToUpdateIds = new List<ID>();
        for(Program_Participation__c programParticipation : newProgramParticipationList) {
            if(programParticipation.Program__c != null){
                programParticipationsToUpdateList.add(programParticipation);
                programParticipationsToUpdateIds.add(programParticipation.Program__c);
            }
        }
        Map<ID,Program__c> programs = new Map<ID,Program__c> 
                                    ([select id, Name from Program__c where id=:programParticipationsToUpdateIds]);
        
        for(Program_Participation__c programParticipation : programParticipationsToUpdateList) {
            programParticipation.Name = programs.get(programParticipation.Program__c).Name + '-' + 
                                        programParticipation.SBU__c + '-' +
                                        programParticipation.Participation_Type__c;
        } 
    }
}