unpackaged/objects/Report_Package__c.object
<CustomObject>
  <label>Report Package</label>
  <nameField>
    <label>Report Package Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Report Packages</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Report_Package_Line__c.object
<CustomObject>
  <fields>
    <fullName>Report_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Report Package</label>
    <referenceTo>Report_Package__c</referenceTo>
    <relationshipLabel>Report Package Lines</relationshipLabel>
    <relationshipName>Report_Package_Lines</relationshipName>
    <type>Lookup</type>
  </fields>
  <label>Report Package Line</label>
  <nameField>
    <displayFormat>RPL-{000}</displayFormat>
    <label>Report Package Line Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Report Package Lines</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Report_Package__c</fullName>
    <defaultValue>'a2X0J0000006vavUAA'</defaultValue>
    <inlineHelpText>Please enter the ID of the report package that controls which reports that the user can see in the left column of the Home tab</inlineHelpText>
    <label>Report Package</label>
    <length>18</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>User_Country__c</fullName>
    <label>User Country</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Country_Code_full</valueSetName>
    </valueSet>
  </fields>
  <fields>
    <fullName>User_Type__c</fullName>
    <inlineHelpText>Sales Representative  = District Managers, Territory Managers, Account Managers

Sales Manager = Regional Sales Mgrs, Division Sales Mgrs, National Sales Mgrs</inlineHelpText>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <sorted>true</sorted>
        <value>
          <fullName>Account Maintenance Team Member</fullName>
        </value>
        <value>
          <fullName>Area Sales Manager</fullName>
        </value>
        <value>
          <fullName>Clinical Affairs</fullName>
        </value>
        <value>
          <fullName>Complaints Handling</fullName>
        </value>
        <value>
          <fullName>Customer Service</fullName>
        </value>
        <value>
          <fullName>Finance</fullName>
        </value>
        <value>
          <fullName>Inside Sales Representative</fullName>
        </value>
        <value>
          <fullName>Key Account Manager</fullName>
        </value>
        <value>
          <fullName>Managing Director</fullName>
        </value>
        <value>
          <fullName>Marketing</fullName>
        </value>
        <value>
          <fullName>National Admin</fullName>
        </value>
        <value>
          <fullName>Operations</fullName>
        </value>
        <value>
          <fullName>Other</fullName>
        </value>
        <value>
          <fullName>Product Manager</fullName>
        </value>
        <value>
          <fullName>Regional Sales Manager</fullName>
        </value>
        <value>
          <fullName>Sales Manager</fullName>
        </value>
        <value>
          <fullName>Sales Representative</fullName>
        </value>
        <value>
          <fullName>Training &amp; Event Management</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/UserToReportPackageTest.cls
@isTest
public with sharing class UserToReportPackageTest {    
    
@isTest
private static void UserToReportPackageTest(){

        Report_package__c pd1 = new Report_package__c ();
        insert pd1;
        
        Report_package__c pd2 = new Report_package__c ();
        insert pd2;
        
        User a = new User();
        a.FirstName = 'Test';
        a.LastName = 'User 1';
        a.UserName = 'richard.trum@dentsplysirona.com.123';
        a.Email = 'richard.trum@dentsplysirona.com';
        a.Alias = 'TestUs';
        a.ProfileId = '00e20000001Ygwu';
        a.User_country__c = 'Sweden';
        a.User_type__c = 'Sales Manager';
        a.CommunityNickname = 'TestUser';
        a.TimeZoneSidKey = 'GMT';
        a.LocaleSidKey = 'en_GB';
        a.LanguageLocaleKey= 'en_US';
        a.Emailencodingkey= 'ISO-8859-1';        
        a.Report_package__c = pd1.id;
        insert a;
        

          
        List<Report_package__c> opps = new List<Report_package__c> ();
        
        opps = [SELECT Id, Name FROM Report_package__c LIMIT 50]; 
                    
        ApexPages.currentPage().getParameters().put('id', a.id);     
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(a);   
        
        UserToReportPackage controller = new UserToReportPackage(stdController);
        
        controller.fetchRecords();
                
        system.assertNotEquals(null, controller.getRadioValue);
        
        system.assertEquals(2, controller.ReportList.size());
        
        controller.getRadioValue = pd2.Id;
        
        controller.saveReport();
                
    }
       
    
    @isTest
private static void ReportPackageControllerTest(){
                       
        Report_package__c pd = new Report_package__c ();
        insert pd;
        
        Report_package_line__c pd1 = new Report_package_line__c ();
        pd1.Report_package__c = pd.Id;
        insert pd1;
   
        Report_package_line__c pd2 = new Report_package_line__c ();
        pd2.Report_package__c = pd.Id;
        insert pd2;
        
        User a = new User();
        a.FirstName = 'Test';
        a.LastName = 'User 1';
        a.UserName = 'richard.trum@dentsplysirona.com.123';
        a.Email = 'richard.trum@dentsplysirona.com';
        a.Alias = 'TestUs';
        a.ProfileId = '00e20000001Ygwu';
        a.User_country__c = 'Sweden';
        a.User_type__c = 'Sales Manager';
        a.CommunityNickname = 'TestUser';
        a.TimeZoneSidKey = 'GMT';
        a.LocaleSidKey = 'en_GB';
        a.LanguageLocaleKey= 'en_US';
        a.Emailencodingkey= 'ISO-8859-1';        
        a.Report_package__c = pd.id;
        insert a;
  
        List<Report_package_line__c> opps = new List<Report_package_line__c> ();
        
        opps = [SELECT Id, Name FROM Report_package_Line__c LIMIT 50];
        
        PageReference pageRef = new PageReference('/apex/Custom_Links_VF');
        Test.setCurrentPage(pageRef);
        
        //ApexPages.currentPage().getParameters().put('id', pd.id);   
                
        System.runAs(a) {                                 
                    
        ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(opps);
                       
        ReportPackageController controller = new ReportPackageController(stdController);
                
        controller.fetchRecords();
                        
        system.assertEquals(2, controller.ReportList.size());
        
        }
                
    } 
     
    
    
    }