unpackaged/objects/Report_Package__c.object
<CustomObject>
  <fields>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
      <restricted>true</restricted>
      <valueSetName>Market</valueSetName>
    </valueSet>
  </fields>
  <label>Report Package</label>
  <nameField>
    <label>Report Package Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Report Packages</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Market__c</fullName>
    <description>&lt;ADMINISTRATION&gt; Keep the values of this field aligned with the Price Book Market field values.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
      <valueSetDefinition>
        <value>
          <fullName>Australia</fullName>
        </value>
        <value>
          <fullName>Austria</fullName>
        </value>
        <value>
          <fullName>Belarus</fullName>
        </value>
        <value>
          <fullName>BeNelux</fullName>
        </value>
        <value>
          <fullName>BEX</fullName>
        </value>
        <value>
          <fullName>Brazil</fullName>
        </value>
        <value>
          <fullName>CEE</fullName>
        </value>
        <value>
          <fullName>China</fullName>
        </value>
        <value>
          <fullName>DEX</fullName>
        </value>
        <value>
          <fullName>Finland</fullName>
        </value>
        <value>
          <fullName>France</fullName>
        </value>
        <value>
          <fullName>Germany</fullName>
        </value>
        <value>
          <fullName>Hong Kong</fullName>
        </value>
        <value>
          <fullName>HQ</fullName>
        </value>
        <value>
          <fullName>Iberia</fullName>
        </value>
        <value>
          <fullName>India</fullName>
        </value>
        <value>
          <fullName>Indonesia</fullName>
        </value>
        <value>
          <fullName>Italy</fullName>
        </value>
        <value>
          <fullName>Japan</fullName>
        </value>
        <value>
          <fullName>Kazakhstan</fullName>
        </value>
        <value>
          <fullName>Korea</fullName>
        </value>
        <value>
          <fullName>Malaysia</fullName>
        </value>
        <value>
          <fullName>MEA</fullName>
        </value>
        <value>
          <fullName>NA</fullName>
        </value>
        <value>
          <fullName>Nordics</fullName>
        </value>
        <value>
          <fullName>Poland</fullName>
        </value>
        <value>
          <fullName>Russia</fullName>
        </value>
        <value>
          <fullName>Singapore</fullName>
        </value>
        <value>
          <fullName>South Africa</fullName>
        </value>
        <value>
          <fullName>Switzerland</fullName>
        </value>
      </valueSetDefinition>
    </valueSet>
  </fields>
  <fields>
    <fullName>Report_Package__c</fullName>
    <defaultValue>'a2X0J0000006vavUAA'</defaultValue>
    <inlineHelpText>Please enter the ID of the report package that controls which reports that the user can see in the left column of the Home tab</inlineHelpText>
    <label>Report Package</label>
    <length>18</length>
    <type>Text</type>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/UserToReportPackage.cls
public with sharing class UserToReportPackage {

public User UsName {get; set;}
public Report_Package__c CurrentReportPackage {get; set;} 
public List<Report_Package__c> ReportList {get; set;}
Public String getRadioValue{get;set;}
public PageReference UserLink {get; set;}

public UserToReportPackage(ApexPages.StandardController stdController) {
}

public void fetchRecords(){
UsName = [Select Id, Name, Report_Package__c,Market__c FROM User WHERE Id =: apexPages.currentPage().getParameters().get('id')];

if (UsName.Report_Package__c<>null) {
CurrentReportPackage = [SELECT ID, Name FROM Report_Package__c WHERE Id =: UsName.Report_Package__c];
getRadioValue = CurrentReportPackage.Id;
}

ReportList = [Select Id, Name FROM Report_Package__c WHERE Market__c=:UsName.Market__c LIMIT 50];
this.getDealerOptions();

}

public List<SelectOption> getDealerOptions() {

List<SelectOption> options = new List<SelectOption>();

for (Report_package__c dealerSelect : ReportList) {
options.add(new SelectOption(dealerSelect.id, dealerSelect.Name));
}

return options;

}

public PageReference saveReport() {

for(Report_Package__c ReportSelect: ReportList) {

If (ReportSelect.id == getRadioValue){
UsName.Report_Package__c = ReportSelect.id; 
update UsName;
}
}

UserLink = new PageReference('/' + UsName.id + '?noredirect=1&isUserEntityOverride=1');
return UserLink;

}


         
}