unpackaged/objects/Report_Package__c.object
<CustomObject>
  <label>Report Package</label>
  <nameField>
    <label>Report Package Name</label>
    <type>Text</type>
  </nameField>
  <pluralLabel>Report Packages</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Report_Package_Line__c.object
<CustomObject>
  <fields>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
  </fields>
  <fields>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <type>Url</type>
  </fields>
  <fields>
    <fullName>Report_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Report Package</label>
    <referenceTo>Report_Package__c</referenceTo>
    <relationshipLabel>Report Package Lines</relationshipLabel>
    <relationshipName>Report_Package_Lines</relationshipName>
    <type>Lookup</type>
  </fields>
  <fields>
    <fullName>Sort_order__c</fullName>
    <label>Sort order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
  </fields>
  <label>Report Package Line</label>
  <nameField>
    <displayFormat>RPL-{000}</displayFormat>
    <label>Report Package Line Name</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Report Package Lines</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
  <fields>
    <fullName>Report_Package__c</fullName>
    <defaultValue>'a2X0J0000006vavUAA'</defaultValue>
    <inlineHelpText>Please enter the ID of the report package that controls which reports that the user can see in the left column of the Home tab</inlineHelpText>
    <label>Report Package</label>
    <length>18</length>
    <type>Text</type>
  </fields>
  <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/ReportPackageController.cls
public with sharing class ReportPackageController {

public ReportPackageController(ApexPages.StandardSetController stdController) {
}

public List<Report_Package__c> RepPac {get;set;}
public User UsName {get; set;}
public List<Report_Package_Line__c> ReportList {get; set;}

public void fetchRecords(){
UsName = [Select Id, Name, Report_Package__c FROM User WHERE Id =: UserInfo.getUserId()];
If (UsName.Report_Package__c != '') {
RepPac = [Select Id, Name From Report_Package__c WHERE Id =: UsName.Report_Package__c];
    if(!RepPac.IsEmpty()){
    	ReportList = [Select Id, Name, Link__c, Sort_order__c, Description__c FROM Report_Package_Line__c WHERE Report_Package__r.Id =: RepPac[0].Id ORDER BY Sort_order__c];
    }
}

}
         
}